Repository webdriverio/webdriverio, pull requests merged in 2018-12, with the labels that each got.

#3092 Fix: Removing wdio-cli duplicate peer dependency
  packages/wdio-browserstack-service/package.json
  packages/wdio-cli/package.json
Labels: Bug, wdio-browserstack-service

#3095 Update BoilerplateProjects.md
  docs/BoilerplateProjects.md
Labels: Appium, Docs

#3123 use lerna-changelog
  .gitignore
  CHANGELOG.md
  lerna.json
  package.json
Labels: PR: Internal :house:

#3124 simulate patch
  CHANGELOG.md
Labels: PR: Internal :house:

#3128 webdriverio: added custom error messages ability to wait commands
  packages/webdriverio/src/commands/element/waitForDisplayed.js
  packages/webdriverio/src/commands/element/waitForEnabled.js
  packages/webdriverio/src/commands/element/waitForExist.js
  packages/webdriverio/tests/commands/element/waitForDisplayed.test.js
  packages/webdriverio/tests/commands/element/waitForEnabled.test.js
Labels: PR: New Feature :rocket:

#3122 Update jsonwp.json
  packages/webdriver/protocol/jsonwp.json
Labels: PR: Spec Compliancy :eyeglasses:

#3118 wedbdriverio & webdriver: initial stale element handler work
  babel.config.js
  package.json
  packages/webdriver/src/request.js
  packages/webdriver/tests/request.test.js
  packages/webdriverio/src/middlewares.js
  packages/webdriverio/src/utils/refetchElement.js
  packages/webdriverio/tests/__mocks__/request.js
  packages/webdriverio/tests/commands/element/touchAction.test.js
  packages/webdriverio/tests/middleware.test.js
  packages/webdriverio/tests/utils/refetchElement.test.js
Labels: Enhancement, PR: Polish :nail_care:, webdriver, webdriverio

#3126 Update Changelog
  .github/ISSUE_TEMPLATE/--bug-report.md
  .github/ISSUE_TEMPLATE/--question.md
  CHANGELOG.md
  package.json
  packages/webdriver/protocol/appium.json
  scripts/changelog.js
Labels: PR: Docs :memo:

#3141 adding browserstack to readme
  README.md
Labels: PR: Docs :memo:

#3145 Update org team charter
  CONTRIBUTING.md
  GOVERNANCE.md
Labels: PR: Docs :memo:

#3149 Release blog post
  CHANGELOG.md
  CONTRIBUTING.md
  examples/wdio.conf.js
  website/blog/2018-08-04-WebdriverIO-v5.md
  website/blog/2018-12-19-webdriverio-v5-released.md
  website/i18n/en.json
  website/static/styles/index.scss
Labels: PR: Docs :memo:, work-in-progress

#3158 Update cloud job as failed if mocha.bail is set
  packages/wdio-browserstack-service/src/service.js
  packages/wdio-browserstack-service/tests/service.test.js
  packages/wdio-mocha-framework/package.json
  packages/wdio-sauce-service/src/service.js
  packages/wdio-sauce-service/tests/service.test.js
Labels: PR: Bug Fix :bug:

#3160 Sanitize caps before creating a session with the runner
  packages/wdio-config/src/index.js
  packages/wdio-config/tests/__mocks__/@wdio/config.js
  packages/wdio-runner/src/utils.js
  packages/wdio-runner/tests/utils.test.js
  packages/webdriver/src/constants.js
Labels: PR: Bug Fix :bug:

#3165 Ensure GITHUB_AUTH token is set to generate changelogs
  CHANGELOG.md
  scripts/changelog.js
Labels: PR: Internal :house:

#3171 Fix middleware regression and add smoke tests
  package.json
  packages/wdio-cli/src/interface.js
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/src/run.js
  packages/wdio-config/src/constants.js
  packages/wdio-interface/src/index.js
  packages/wdio-local-runner/src/run.js
  packages/wdio-runner/src/index.js
  packages/wdio-runner/src/utils.js
  packages/wdio-webdriver-mock-service/.npmignore
  packages/wdio-webdriver-mock-service/.npmrc
  packages/wdio-webdriver-mock-service/README.md
  packages/wdio-webdriver-mock-service/package.json
  packages/wdio-webdriver-mock-service/src/WebDriverMock.js
  packages/wdio-webdriver-mock-service/src/constants.js
  packages/wdio-webdriver-mock-service/src/index.js
  packages/wdio-webdriver-mock-service/src/mocks/newSession.js
  packages/webdriverio/src/middlewares.js
  packages/webdriverio/tests/commands/browser/waitUntil.test.js
  packages/webdriverio/tests/commands/element/touchAction.test.js
  packages/webdriverio/tests/middleware.test.js
  scripts/generate-sub-package.js
  tests/.eslintrc
  tests/smoke.conf.js
  tests/smoke.runner.js
  tests/smoke.test.js
Labels: PR: Bug Fix :bug:

#2874 Create SSL cert for website
  .github/SUPPORT.md
  README.md
  docs/ConfigurationFile.md
  docs/Frameworks.md
  docs/GettingStarted.md
  docs/Selectors.md
  docs/repl.md
  examples/cloudservices/browserstack.js
  examples/cloudservices/kobiton.js
  examples/cloudservices/saucelabs.js
  examples/cloudservices/testingbot.js
  examples/pageobject/wdio.conf.js
  examples/wdio.conf.js
  examples/wdio/jasmine/jasmine.spec.js
  examples/wdio/mocha/mocha.test.js
  packages/eslint-plugin-wdio/README.md
  packages/wdio-applitools-service/README.md
  packages/wdio-browserstack-service/README.md
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-concise-reporter/README.md
  packages/wdio-devtools-service/README.md
  packages/wdio-dot-reporter/README.md
  packages/wdio-firefox-profile-service/README.md
  packages/wdio-firefox-profile-service/tests/launcher.test.js
  packages/wdio-jasmine-framework/README.md
  packages/wdio-junit-reporter/README.md
  packages/wdio-mocha-framework/README.md
  packages/wdio-repl/src/index.js
  packages/wdio-reporter/src/constants.js
  packages/wdio-sauce-service/README.md
  packages/wdio-selenium-standalone-service/README.md
  packages/wdio-spec-reporter/README.md
  packages/wdio-sumologic-reporter/README.md
  packages/wdio-testingbot-service/README.md
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/browser/debug.js
  packages/webdriverio/src/commands/browser/deleteCookies.js
  packages/webdriverio/src/commands/browser/getCookies.js
  packages/webdriverio/src/commands/browser/newWindow.js
  packages/webdriverio/src/commands/browser/setCookies.js
  packages/webdriverio/src/commands/browser/switchWindow.js
  packages/webdriverio/src/commands/browser/url.js
  packages/webdriverio/src/commands/element/getText.js
  packages/webdriverio/src/constants.js
  packages/webdriverio/tests/commands/browser/deleteCookies.test.js
  packages/webdriverio/tests/commands/browser/getCookies.test.js
  packages/webdriverio/tests/commands/browser/setCookies.test.js
  website/static/styles/_utils/_fonts.scss
Labels: Docs

#3176 webdriver: Change getCurrentUrl to getUrl
  CHANGELOG.md
  packages/webdriver/protocol/jsonwp.json
  packages/webdriver/protocol/webdriver.json
  packages/webdriver/tests/index.test.js
  packages/webdriverio/src/commands/browser/switchWindow.js
  packages/webdriverio/src/commands/browser/url.js
  website/blog/2018-12-19-webdriverio-v5-released.md
Labels: PR: Polish :nail_care:

#3175 Garbage in npm wdio packages
  package.json
Labels: PR: Internal :house:

#3180 webdriverio: Correct deleteCookies example
  packages/webdriverio/src/commands/browser/deleteCookies.js
Labels: PR: Docs :memo:

#3178 Fix unknwon logFile issue + add documentation on logDir option
  docs/Frameworks.md
  docs/GettingStarted.md
  docs/Options.md
  examples/pageobject/wdio.conf.js
  examples/wdio.conf.js
  examples/wdio/custom-reporter/wdio.conf.js
  examples/wdio/jasmine/jasmine.spec.js
  examples/wdio/jasmine/wdio.conf.js
  examples/wdio/mocha/mocha.test.js
  examples/wdio/mocha/wdio.conf.js
  examples/wdio/multiremote/wdio.conf.js
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-config/src/constants.js
  packages/wdio-junit-reporter/tests/__fixtures__/runner.json
  packages/wdio-local-runner/src/worker.js
  packages/wdio-local-runner/tests/localRunner.test.js
  packages/wdio-reporter/README.md
  packages/wdio-reporter/src/index.js
  packages/wdio-reporter/tests/reporter.test.js
  packages/wdio-runner/src/index.js
  packages/wdio-runner/src/reporter.js
  packages/wdio-runner/tests/index.test.js
  packages/wdio-runner/tests/reporter.test.js
  packages/webdriverio/src/commands/browser/newWindow.js
  packages/webdriverio/src/constants.js
  packages/webdriverio/tests/__mocks__/request.js
  tests/smoke.conf.js
  website/blog/2018-12-19-webdriverio-v5-released.md
Labels: PR: Bug Fix :bug:, PR: Docs :memo:

#3184 webdriverio: getCssPropertry changed to getCSSProperty
  CHANGELOG.md
  packages/webdriverio/src/commands/element/getCSSProperty.js
  packages/webdriverio/src/commands/element/getProperty.js
Labels: PR: Docs :memo:

#3195 webdriverio: Update upgrade instructions
  website/blog/2018-12-19-webdriverio-v5-released.md
Labels: PR: Docs :memo:

#3190 Only set body if a body is required
  packages/webdriver/package.json
  packages/webdriver/src/request.js
  packages/webdriver/src/utils.js
  packages/webdriver/tests/request.test.js
  packages/webdriver/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#3197 Add support for .es6 file types
  packages/wdio-config/src/lib/ConfigParser.js
  packages/wdio-config/tests/__fixtures__/test.es6
  packages/wdio-config/tests/configparser.test.js
Labels: PR: Bug Fix :bug:

#3199 Disable unsupported cli wizard options
  packages/wdio-cli/src/config.js
Labels: PR: Docs :memo:

#3201 webdriverio: added error messages to the waitForExist call
  packages/webdriverio/src/commands/element/waitForDisplayed.js
  packages/webdriverio/src/commands/element/waitForEnabled.js
Labels: PR: Polish :nail_care:

#3202 fix: this PR fixes a bug on phones
  website/pages/en/index.js
  website/static/styles/_components/_content.scss
Labels: PR: Docs :memo:

#3206 Docs: fix Getting Started guide (part 2)
  docs/GettingStarted.md
Labels: PR: Docs :memo:

#3208 Fix bug where Geckodriver requires POST requests to have a valid JSON body
  packages/webdriver/src/request.js
  packages/webdriver/tests/request.test.js
Labels: PR: Bug Fix :bug:

#3211 fix hostname cli param
  packages/wdio-cli/src/config.js
Labels: PR: Bug Fix :bug:
