Repository webdriverio/webdriverio, pull requests merged in 2019-08, with the labels that each got.

#4290 Support multiple tables in scenario outline
  packages/wdio-cucumber-framework/src/utils.js
  packages/wdio-cucumber-framework/tests/utils.test.js
  tests/cucumber/step-definitions/given.js
  tests/cucumber/test.feature
Labels: PR: Bug Fix :bug:, wdio-cucumber-framework

#4308 Fix for async mode in wdio-sync
  packages/wdio-sync/src/index.js
Labels: PR: Bug Fix :bug:

#4300 TypeScript: add elementId as parameter to protocol commands with variable
  packages/webdriverio/webdriverio.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/webdriver-generate-typings.js
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Docs :memo:, TypeScript

#4302 Make dragAndDrop respect scroll position
  packages/webdriverio/src/commands/element/dragAndDrop.js
  packages/webdriverio/src/commands/element/moveTo.js
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/commands/element/dragAndDrop.test.js
  packages/webdriverio/tests/commands/element/moveTo.test.js
Labels: PR: Bug Fix :bug:

#4296 devtools-service: onFrameNavigated - do nothing if tracing is not started
  packages/wdio-devtools-service/src/gatherer/trace.js
  packages/wdio-devtools-service/tests/gatherer/trace.test.js
Labels: PR: Bug Fix :bug:

#4295 devtools-service: fix tracing
  packages/wdio-devtools-service/src/index.js
  packages/wdio-devtools-service/tests/service.test.js
Labels: PR: Bug Fix :bug:

#4299 Fix chrome getLogs and getLogTypes
  packages/webdriver/protocol/chromium.json
Labels: PR: Bug Fix :bug:

#4313 types: Add types for w3c capabilities of cloud services
  scripts/templates/webdriver.tpl.d.ts
Labels: PR: Docs :memo:

#4316 browserstack-service: fix 404 error for app test
  packages/wdio-browserstack-service/src/service.js
  packages/wdio-browserstack-service/tests/service.test.js
Labels: PR: Bug Fix :bug:

#4309 @wdio/allure-reporter: Skip reporting of passing hooks with option useCucumberStepReporter
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/__fixtures__/attachment.js
  packages/wdio-allure-reporter/tests/cucumber.suite.test.js
Labels: PR: Polish :nail_care:

#4334 Fix type generation for browser.uploadFile
  packages/webdriverio/src/commands/browser/uploadFile.js
Labels: PR: Docs :memo:

#4350 Devtools service: fix timeToFirstByte
  packages/wdio-devtools-service/src/auditor.js
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/time-to-first-byte.js
Labels: PR: Bug Fix :bug:

#4327 Add JS boilerplate with closure functions
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#4342 Fix getting scroll position in IE11
  packages/webdriverio/src/utils.js
Labels: PR: Bug Fix :bug:

#4356 Update minimum node version requirement to Node 10
  .nvmrc
  .travis.yml
  babel.config.js
  docs/Babel.md
  package.json
  packages/eslint-plugin-wdio/package.json
  packages/wdio-allure-reporter/package.json
  packages/wdio-applitools-service/package.json
  packages/wdio-browserstack-service/package.json
  packages/wdio-cli/package.json
  packages/wdio-concise-reporter/package.json
  packages/wdio-config/package.json
  packages/wdio-crossbrowsertesting-service/package.json
  packages/wdio-cucumber-framework/package.json
  packages/wdio-devtools-service/package.json
  packages/wdio-dot-reporter/package.json
  packages/wdio-firefox-profile-service/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-junit-reporter/package.json
  packages/wdio-lambda-runner/package.json
  packages/wdio-local-runner/package.json
  packages/wdio-logger/package.json
  packages/wdio-mocha-framework/package.json
  packages/wdio-repl/package.json
  packages/wdio-reporter/package.json
  packages/wdio-runner/package.json
  packages/wdio-sauce-service/package.json
  packages/wdio-selenium-standalone-service/package.json
  packages/wdio-smoke-test-service/package.json
  packages/wdio-spec-reporter/package.json
  packages/wdio-sumologic-reporter/package.json
  packages/wdio-sync/package.json
  packages/wdio-testingbot-service/package.json
  packages/wdio-utils/package.json
  packages/wdio-webdriver-mock-service/package.json
  packages/webdriver/package.json
  packages/webdriverio/package.json
  scripts/generateSubPackage.js
Labels: PR: Internal :house:

#4325 Fix stacktrace formatting
  packages/wdio-sync/src/constants.js
  packages/wdio-sync/src/utils.js
  packages/wdio-sync/src/wrapCommand.js
Labels: PR: Polish :nail_care:

#4359 add execute driver support
  packages/webdriver/protocol/appium.json
Labels: PR: Spec Compliancy :eyeglasses:

#4332 End process normally
  packages/wdio-cli/src/config.js
  packages/wdio-cli/src/interface.js
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/src/run.js
  packages/wdio-cli/src/setup.js
  packages/wdio-cli/tests/interface.test.js
  packages/wdio-cli/tests/launcher.test.js
  packages/wdio-cli/tests/run.test.js
  packages/wdio-local-runner/src/worker.js
  tests/helpers/launch.js
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#4288 Cucumber sync hooks
  docs/ConfigurationFile.md
  examples/pageobject/wdio.conf.js
  examples/wdio.conf.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-config/src/constants.js
  packages/wdio-cucumber-framework/cucumber-framework.d.ts
  packages/wdio-cucumber-framework/package.json
  packages/wdio-cucumber-framework/src/constants.js
  packages/wdio-cucumber-framework/src/hookRunner.js
  packages/wdio-cucumber-framework/src/index.js
  packages/wdio-cucumber-framework/src/utils.js
  packages/wdio-cucumber-framework/tests/__mocks__/cucumber.js
  packages/wdio-cucumber-framework/tests/adapter.test.js
  packages/wdio-cucumber-framework/tests/hookRunner.test.js
  packages/wdio-cucumber-framework/tests/utils.test.js
  packages/wdio-sync/package.json
  packages/wdio-sync/src/executeHooksWithArgs.js
  packages/wdio-sync/src/index.js
  packages/wdio-sync/src/runFnInFiberContextWithCallback.js
  packages/wdio-sync/tests/index.test.js
  packages/wdio-utils/src/index.js
  packages/wdio-utils/src/utils.js
  packages/wdio-utils/tests/__mocks__/@wdio/utils.js
  packages/wdio-utils/tests/utils.test.js
  packages/webdriverio/src/constants.js
  tests/cucumber/step-definitions/given.js
  tests/helpers/config.js
  tests/typings/sync-cucumber/cucumber.ts
Labels: PR: Bug Fix :bug:, wdio-cucumber-framework

#4358 Updated to add command to take region snapshot
  packages/wdio-applitools-service/README.md
  packages/wdio-applitools-service/package.json
  packages/wdio-applitools-service/src/index.js
  packages/wdio-applitools-service/tests/__mocks__/@applitools/eyes-webdriverio.js
  packages/wdio-applitools-service/tests/service.test.js
Labels: PR: New Feature :rocket:

#4363 wdio-crossbrowsertesting-service: Pass along `cbtTunnelOpts` to `cbtTunnels.start()`
  packages/wdio-crossbrowsertesting-service/README.md
  packages/wdio-crossbrowsertesting-service/src/launcher.js
  packages/wdio-crossbrowsertesting-service/tests/launcher.test.js
Labels: PR: Bug Fix :bug:

#4367 Fix user hooks in sync mode
  packages/wdio-cucumber-framework/src/index.js
  packages/wdio-cucumber-framework/src/utils.js
  packages/wdio-cucumber-framework/tests/adapter.test.js
  packages/wdio-cucumber-framework/tests/utils.test.js
  tests/cucumber/step-definitions/given.js
Labels: PR: Bug Fix :bug:

#4365 use `optionalDependencies` instead of `postinstall` for `fibers
  .travis.yml
  babel.config.js
  package.json
  packages/wdio-applitools-service/package.json
  packages/wdio-devtools-service/package.json
  packages/wdio-junit-reporter/package.json
  packages/wdio-sync/package.json
  packages/wdio-sync/postinstall.js
  packages/wdio-sync/src/executeHooksWithArgs.js
  packages/wdio-sync/src/fibers.js
  packages/wdio-sync/src/index.js
  packages/wdio-sync/src/runFnInFiberContext.js
  packages/wdio-sync/src/runFnInFiberContextWithCallback.js
  packages/wdio-sync/src/wrapCommand.js
  packages/wdio-sync/tests/__mocks__/fibers.js
  packages/wdio-sync/tests/__mocks__/fibers/future.js
  packages/wdio-sync/tests/fibers.test.js
  packages/wdio-sync/tests/wrapCommand.test.js
Labels: PR: Bug Fix :bug:

#4382 wdio-cli: configure allure reporter with wdio cli
  packages/wdio-cli/src/setup.js
  packages/wdio-cli/src/templates/afterTest.ejs
  packages/wdio-cli/src/templates/reporters.ejs
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
Labels: PR: Polish :nail_care:

#4389 webdriverio: bump resq version to 1.6
  packages/webdriverio/package.json
Labels: PR: Internal :house:

#4386 Fix process exit code
  packages/wdio-cli/src/interface.js
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/src/run.js
  packages/wdio-cli/tests/interface.test.js
  packages/wdio-cli/tests/launcher.test.js
  packages/wdio-cli/tests/run.test.js
  packages/wdio-local-runner/src/index.js
Labels: PR: Bug Fix :bug:

#4393 webdriverio: throw proper errors from selectByAttribute/VisibleText w…
  packages/webdriverio/src/commands/element/selectByAttribute.js
  packages/webdriverio/src/commands/element/selectByVisibleText.js
  packages/webdriverio/tests/commands/element/selectByAttribute.test.js
  packages/webdriverio/tests/commands/element/selectByVisibleText.test.js
Labels: PR: Polish :nail_care:

#4407 Sauce: Fix update cucumber feature name and job status in Sauce Labs
  packages/wdio-browserstack-service/src/service.js
  packages/wdio-browserstack-service/tests/service.test.js
  packages/wdio-crossbrowsertesting-service/src/service.js
  packages/wdio-crossbrowsertesting-service/tests/service.test.js
  packages/wdio-sauce-service/src/service.js
  packages/wdio-sauce-service/tests/service.test.js
  packages/wdio-testingbot-service/src/service.js
  packages/wdio-testingbot-service/tests/service.test.js
Labels: PR: Polish :nail_care:

#4412 Add example for custom service
  examples/wdio/custom-service/.eslintrc
  examples/wdio/custom-service/mocha.test.js
  examples/wdio/custom-service/my.custom.service.js
  examples/wdio/custom-service/wdio.conf.js
  examples/wdio/package.json
Labels: PR: Docs :memo:

#4414 Add 'documentation change' to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: Internal :house:

#4413 Add link to the browser `waitUntil` command
  packages/webdriverio/src/commands/element/waitUntil.js
Labels: PR: Docs :memo:

#4418 @wdio/allure-reporter: Handle test failures where 'error.name' and 'error.stack' are undefined
  packages/wdio-allure-reporter/src/utils.js
  packages/wdio-allure-reporter/tests/utils.test.js
Labels: PR: Polish :nail_care:

#4406 allure-reporter: fixed bug with mocha all hooks being treated as tests
  packages/wdio-allure-reporter/src/constants.js
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/src/utils.js
  packages/wdio-allure-reporter/tests/allureFeatures.test.js
  packages/wdio-allure-reporter/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#4420 @wdio/allure-reporter: Fix undefined/unknown step status
  packages/wdio-allure-reporter/src/constants.js
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/constants.test.js
  packages/wdio-allure-reporter/tests/cucumber.suite.test.js
  packages/wdio-allure-reporter/tests/runtime.test.js
Labels: PR: Bug Fix :bug:

#4419 [@wdio/devtools-service] Add command for mobile emulation
  packages/wdio-devtools-service/README.md
  packages/wdio-devtools-service/src/driver.js
  packages/wdio-devtools-service/src/index.js
  packages/wdio-devtools-service/tests/__mocks__/puppeteer-core.js
  packages/wdio-devtools-service/tests/__snapshots__/service.test.js.snap
  packages/wdio-devtools-service/tests/service.test.js
Labels: PR: New Feature :rocket:, wdio-devtools-service

#4234 @wdio/sync: throw if command is executed outside of a fiber context
  packages/wdio-runner/src/index.js
  packages/wdio-sync/src/fibers.js
  packages/wdio-sync/src/index.js
  packages/wdio-sync/src/runFnInFiberContext.js
  packages/wdio-sync/src/runFnInFiberContextWithCallback.js
  packages/wdio-sync/src/wrapCommand.js
Labels: PR: Internal :house:

#4416 Let auditors command fail if tracing failed
  packages/wdio-devtools-service/src/auditor.js
  packages/wdio-devtools-service/src/gatherer/trace.js
  packages/wdio-devtools-service/src/index.js
  packages/wdio-devtools-service/tests/gatherer/trace.test.js
  packages/wdio-devtools-service/tests/service.test.js
Labels: PR: Bug Fix :bug:

#4415 Add smoke tests for retries
  tests/jasmine/test.js
  tests/mocha/test.js
Labels: PR: Internal :house:

#4428 wdio-allure-reporter - Fix unknown status in allure report
  packages/wdio-allure-reporter/src/constants.js
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/__fixtures__/cucumber.js
  packages/wdio-allure-reporter/tests/constants.test.js
  packages/wdio-allure-reporter/tests/cucumber.suite.test.js
  packages/wdio-allure-reporter/tests/runtime.test.js
Labels: PR: Bug Fix :bug:

#4424 support direct connect functionality for load balanced session redirection
  packages/webdriver/src/constants.js
  packages/webdriver/src/index.js
  packages/webdriver/src/utils.js
  packages/webdriver/tests/utils.test.js
Labels: PR: New Feature :rocket:

#4429 Only print warning if user is running wdio testrunner
  packages/wdio-sync/src/wrapCommand.js
Labels: PR: Internal :house:

#4391 e2e tests for DevTools package
  .travis.yml
  e2e/.eslintrc
  e2e/element.test.js
  e2e/jest.config.js
  e2e/protocol.test.js
  package.json
  packages/devtools/README.md
  packages/devtools/src/commands/acceptAlert.js
  packages/devtools/src/commands/addCookie.js
  packages/devtools/src/commands/back.js
  packages/devtools/src/commands/closeWindow.js
  packages/devtools/src/commands/createWindow.js
  packages/devtools/src/commands/deleteAllCookies.js
  packages/devtools/src/commands/deleteCookie.js
  packages/devtools/src/commands/dismissAlert.js
  packages/devtools/src/commands/elementClear.js
  packages/devtools/src/commands/elementClick.js
  packages/devtools/src/commands/elementSendKeys.js
  packages/devtools/src/commands/executeAsyncScript.js
  packages/devtools/src/commands/executeScript.js
  packages/devtools/src/commands/findElement.js
  packages/devtools/src/commands/findElementFromElement.js
  packages/devtools/src/commands/findElements.js
  packages/devtools/src/commands/findElementsFromElement.js
  packages/devtools/src/commands/forward.js
  packages/devtools/src/commands/getActiveElement.js
  packages/devtools/src/commands/getAllCookies.js
  packages/devtools/src/commands/getElementAttribute.js
  packages/devtools/src/commands/getElementCSSValue.js
  packages/devtools/src/commands/getElementRect.js
  packages/devtools/src/commands/getElementTagName.js
  packages/devtools/src/commands/getElementText.js
  packages/devtools/src/commands/getNamedCookie.js
  packages/devtools/src/commands/getPageSource.js
  packages/devtools/src/commands/getTitle.js
  packages/devtools/src/commands/getUrl.js
  packages/devtools/src/commands/getWindowRect.js
  packages/devtools/src/commands/isElementEnabled.js
  packages/devtools/src/commands/navigateTo.js
  packages/devtools/src/commands/refresh.js
  packages/devtools/src/commands/setWindowRect.js
  packages/devtools/src/commands/switchToFrame.js
  packages/devtools/src/commands/switchToParentFrame.js
  packages/devtools/src/commands/switchToWindow.js
  packages/devtools/src/constants.js
  packages/devtools/src/devtoolsdriver.js
  packages/devtools/src/utils.js
  packages/devtools/tests/devtoolsdriver.test.js
  packages/devtools/tests/utils.test.js
  packages/wdio-sync/src/fibers.js
  packages/webdriver/README.md
  website/blog/2019-08-30-devtools.md
Labels: PR: Internal :house:
