Repository webdriverio/webdriverio, pull requests merged in 2019-12, with the labels that each got.

#4838 Fix typo in shared-store service doc
  packages/wdio-shared-store-service/README.md
Labels: PR: Docs :memo:

#4843 Add sessionId to normal capabilities for spec-reporter
  packages/wdio-runner/src/index.js
Labels: PR: Bug Fix :bug:

#4846 Docs: Add unbound function note on mocha rerun section.
  docs/Retry.md
Labels: PR: Docs :memo:

#4852 wdio-cli: add wdio-wiremock-service to cli wizard
  docs/CLI.md
  packages/wdio-cli/src/constants.js
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#4854 docs: change homepage link from course to book
  website/pages/en/index.js
Labels: PR: Docs :memo:

#4853 Sync vs Async test execution equality
  docs/Retry.md
  packages/wdio-sync/src/index.js
  packages/wdio-sync/tests/index.test.js
  packages/wdio-utils/src/shim.js
  packages/wdio-utils/tests/shim-async.test.js
  packages/wdio-utils/tests/shim-sync.test.js
  packages/wdio-utils/tests/shim.test.js
  tests/cucumber/step-definitions/then.js
  tests/jasmine/test.js
  tests/mocha/retry_and_fail.js
  tests/mocha/test.js
Labels: PR: Bug Fix :bug:

#4847 Docs: Update Debugging.md
  docs/Debugging.md
Labels: PR: Docs :memo:

#4857 add blog for newly added service
  website/blog/2019-12-05-wiremock.md
Labels: PR: Docs :memo:

#4858 Fix wrapCommand for async command execution
  packages/wdio-utils/src/shim.js
  packages/wdio-utils/tests/shim.test.js
  tests/helpers/async-config.js
  tests/mocha/test-async.js
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#4860 Run synchronous commands with standalone script
  docs/SetupTypes.md
  packages/wdio-sync/src/index.js
  tests/mocha/standalone.js
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#4862 Update boilerplete information
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#4861 Fix naming of retry variable
  docs/Retry.md
  docs/SetupTypes.md
  package-lock.json
  packages/wdio-cucumber-framework/package.json
  packages/wdio-local-runner/src/worker.js
  packages/wdio-local-runner/tests/localRunner.test.js
  packages/wdio-sync/src/index.js
  packages/wdio-sync/tests/index.test.js
  packages/wdio-utils/src/shim.js
  packages/wdio-utils/tests/shim-async.test.js
  packages/webdriverio/src/index.js
  tests/cucumber/step-definitions/then.js
  tests/helpers/async.config.js
  tests/helpers/command.hook.config.js
  tests/jasmine/test.js
  tests/mocha/retry_and_fail.js
  tests/mocha/standalone.js
  tests/mocha/test.js
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#4876 wdio-devtools-service: Readme update about emulateDevice and mobileEmulation
  packages/wdio-devtools-service/README.md
Labels: PR: Docs :memo:

#4875 Fix: #4856 condition never reached
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/allureFeatures.test.js
Labels: PR: Bug Fix :bug:

#4879 fixed typo on cucumber pckg info (2019-7-11 website blog)
  website/blog/2019-07-11-cucumberjs-v5-released.md
Labels: PR: Docs :memo:

#4883 Docs: Minor typo fixes to PROJECT_CHARTER.md
  PROJECT_CHARTER.md
Labels: PR: Internal :house:

#4881 Minor cleanup to avoid `getSpecs` call
  packages/wdio-cli/src/interface.js
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/tests/interface.test.js
Labels: PR: Polish :nail_care:

#4885 Add Fossa badge
  README.md
Labels: PR: Internal :house:

#4884 Remove sponsoring section from Governance.md
  GOVERNANCE.md
Labels: PR: Internal :house:

#4542 Drop Node v8 Support
  .travis.yml
  packages/devtools/package.json
  packages/eslint-plugin-wdio/package.json
  packages/wdio-allure-reporter/package.json
  packages/wdio-appium-service/package.json
  packages/wdio-applitools-service/package.json
  packages/wdio-browserstack-service/package.json
  packages/wdio-cli/package.json
  packages/wdio-cli/tests/launcher.test.js
  packages/wdio-concise-reporter/package.json
  packages/wdio-config/package.json
  packages/wdio-crossbrowsertesting-service/package.json
  packages/wdio-cucumber-framework/package.json
  packages/wdio-devtools-service/package.json
  packages/wdio-dot-reporter/package.json
  packages/wdio-firefox-profile-service/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-junit-reporter/package.json
  packages/wdio-lambda-runner/package.json
  packages/wdio-local-runner/package.json
  packages/wdio-logger/package.json
  packages/wdio-mocha-framework/package.json
  packages/wdio-protocols/package.json
  packages/wdio-repl/package.json
  packages/wdio-reporter/package.json
  packages/wdio-runner/package.json
  packages/wdio-sauce-service/package.json
  packages/wdio-selenium-standalone-service/package.json
  packages/wdio-shared-store-service/package.json
  packages/wdio-smoke-test-reporter/package.json
  packages/wdio-smoke-test-service/package.json
  packages/wdio-spec-reporter/package.json
  packages/wdio-static-server-service/package.json
  packages/wdio-sumologic-reporter/package.json
  packages/wdio-sync/package.json
  packages/wdio-sync/src/fibers.js
  packages/wdio-sync/tests/fibers.test.js
  packages/wdio-testingbot-service/package.json
  packages/wdio-utils/package.json
  packages/wdio-webdriver-mock-service/package.json
  packages/webdriver/package.json
  packages/webdriverio/package.json
  scripts/generateSubPackage.js
Labels: PR: Breaking Change :boom:

#4740 Update minimal TypeScript version to 3.7.2 or higher
  docs/TypeScript.md
  packages/devtools/package.json
  packages/wdio-shared-store-service/shared-store-service.d.ts
  packages/wdio-sync/package.json
  packages/webdriver/package.json
  packages/webdriverio/package.json
Labels: PR: Breaking Change :boom:, TypeScript

#4720 Remove WebdriverIOAsync namespace
  packages/wdio-applitools-service/applitools-service.d.ts
  packages/webdriverio/webdriverio-v6.d.ts
  packages/webdriverio/webdriverio.d.ts
  tests/typings/webdriverio/async.ts
  tests/typings/webdriverio/types/async.d.ts
Labels: PR: Breaking Change :boom:

#4890 Backporting Test PR
  README.md
Labels: backport-requested

#4891 Second backport test
  README.md
Labels: backport-requested

#4888 Document back-porting process for maintainers
  CONTRIBUTING.md
  package-lock.json
  package.json
  scripts/backport.js
Labels: Docs, PR: Internal :house:

#4802 Proposal to add element equals command
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/src/commands/element.js
  packages/webdriverio/src/commands/element/isEqual.js
  packages/webdriverio/tests/commands/element/isEqual.test.js
  packages/webdriverio/webdriverio-core-v5.d.ts
  packages/webdriverio/webdriverio-core.d.ts
Labels: PR: New Feature :rocket:, backport-requested

#4897 Prefer custom properties if detecting backend
  packages/wdio-config/src/utils.js
  packages/wdio-config/tests/detectBackend.test.js
Labels: PR: Bug Fix :bug:, backport-requested

#4873 Added flowcharts
  docs/Flowcharts.md
  docs/flowcharts/CreateLocalWorkerProcess.md
  docs/flowcharts/HighLevelOverview.md
  docs/flowcharts/TestExecution.md
  docs/flowcharts/WDIOCommands.md
  website/_sidebars.json
  website/static/js/flowchart.js
  website/static/styles/index.scss
Labels: PR: Docs :memo:, backport-requested

#4898 Minor styling fixes for flowchart
  docs/flowcharts/WDIOCommands.md
  website/i18n/en.json
  website/static/styles/_utils/_vars.scss
  website/static/styles/index.scss
Labels: PR: Docs :memo:, backport-requested

#4906 Feature/read timeout
  docs/BrowserObject.md
  docs/Options.md
  examples/pageobject/wdio.conf.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-config/src/constants.js
  packages/wdio-junit-reporter/tests/__fixtures__/runner.json
  packages/webdriver/README.md
  packages/webdriver/src/constants.js
  packages/webdriver/src/request.js
  packages/webdriver/tests/request.test.js
  packages/webdriver/webdriver.d.ts
  scripts/templates/webdriver.tpl.d.ts
Labels: PR: New Feature :rocket:, backport-requested

#4910 Add Slack Service to WDIO
  packages/wdio-cli/src/constants.js
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:, backport-requested

#4911 wdio-cli: allow for custom path for WDIO config
  docs/CLI.md
  packages/wdio-cli/src/commands/install.js
  packages/wdio-cli/tests/commands/install.test.js
Labels: PR: Polish :nail_care:, backport-requested

#4915 fix: fix spawning Appium on Windows
  packages/wdio-appium-service/src/launcher.js
  packages/wdio-appium-service/tests/launcher.test.js
Labels: PR: Bug Fix :bug:, backport-requested

#4918 Fix selection of h1 using tag name selector strategy
  packages/webdriverio/src/utils/findStrategy.js
  packages/webdriverio/tests/findStrategy.test.js
Labels: PR: Bug Fix :bug:, backport-requested

#4920 Add markdown Reporter
  packages/wdio-cli/src/constants.js
  scripts/docs-generation/3rd-party/reporters.json
Labels: PR: Docs :memo:, backport-requested

#4924 Remove ff dependency
  packages/devtools/package.json
Labels: PR: Polish :nail_care:, backport-requested

#4923 fix default configs being exported as a singleton
  packages/wdio-config/src/constants.js
  packages/wdio-config/src/lib/ConfigParser.js
  packages/wdio-config/tests/__mocks__/@wdio/config.js
Labels: PR: Bug Fix :bug:, backport-requested

#4878 💥🚀 Cucumber-style JUnit reports in @wdio/junit-reporter
  packages/wdio-junit-reporter/src/index.js
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-features-with-error-step-and-no-error-object.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-features-with-failed-then-skipped-steps.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-features-with-pending-step.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-features.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner.json
  packages/wdio-junit-reporter/tests/__fixtures__/mocha-runner.json
  packages/wdio-junit-reporter/tests/__fixtures__/suites-with-no-error-object.json
  packages/wdio-junit-reporter/tests/__fixtures__/wdio-0-0-junit-reporter-error-options-used.txt
  packages/wdio-junit-reporter/tests/__fixtures__/wdio-0-0-junit-reporter-hooks.txt
  packages/wdio-junit-reporter/tests/__fixtures__/wdio-0-0-junit-reporter-multiple-suites.txt
  packages/wdio-junit-reporter/tests/__fixtures__/wdio-0-0-junit-reporter.txt
  packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.js.snap
  packages/wdio-junit-reporter/tests/reporter.test.js
Labels: PR: Polish :nail_care:, backport-requested
