Repository webdriverio/webdriverio, pull requests merged in 2019-04, with the labels that each got.

#3794 Implement react$ and react$$ command
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/browser/$$.js
  packages/webdriverio/src/commands/browser/$.js
  packages/webdriverio/src/commands/browser/react$.js
  packages/webdriverio/src/commands/element/$$.js
  packages/webdriverio/src/commands/element/$.js
  packages/webdriverio/src/scripts/resq.js
  packages/webdriverio/src/utils/getElementObject.js
Labels: PR: New Feature :rocket:, work-in-progress

#3801 Update CustomReporter.md
  docs/CustomReporter.md
Labels: PR: Docs :memo:

#3811 webdriver: fix getAlertText typing for jsonwp
  packages/webdriver/protocol/jsonwp.json
Labels: PR: Spec Compliancy :eyeglasses:

#3812 webdriver: add missed return types for jsonwp
  packages/webdriver/protocol/jsonwp.json
Labels: PR: Spec Compliancy :eyeglasses:

#3814 Display link to EU platform of Sauce
  packages/wdio-spec-reporter/src/index.js
  packages/wdio-spec-reporter/tests/__fixtures__/testdata.js
  packages/wdio-spec-reporter/tests/index.test.js
Labels: PR: Bug Fix :bug:

#3638 Replace wdio-interface with logUpdate
  README.md
  packages/wdio-cli/package.json
  packages/wdio-cli/src/interface.js
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/src/run.js
  packages/wdio-cli/tests/__mocks__/chalk.js
  packages/wdio-cli/tests/__mocks__/log-update.js
  packages/wdio-cli/tests/interface.test.js
  packages/wdio-cli/tests/launcher.test.js
  packages/wdio-interface/.npmignore
  packages/wdio-interface/.npmrc
  packages/wdio-interface/README.md
  packages/wdio-interface/package.json
  packages/wdio-interface/src/index.js
  packages/wdio-interface/tests/.eslintrc
  packages/wdio-interface/tests/__mocks__/@wdio/interface.js
  packages/wdio-interface/tests/__mocks__/ansi-escapes.js
  packages/wdio-interface/tests/interface.test.js
  packages/wdio-local-runner/package.json
  packages/wdio-local-runner/src/constants.js
  packages/wdio-local-runner/src/index.js
  packages/wdio-local-runner/src/repl.js
  packages/wdio-local-runner/src/replQueue.js
  packages/wdio-local-runner/src/transformStream.js
  packages/wdio-local-runner/src/worker.js
  packages/wdio-local-runner/tests/repl.test.js
  packages/wdio-local-runner/tests/replQueue.test.js
  packages/wdio-local-runner/tests/worker.test.js
  packages/wdio-repl/.npmrc
Labels: PR: Bug Fix :bug:

#3804 wdio-appium-service: Wait for message from Appium instead of delay
  packages/wdio-appium-service/src/launcher.js
  packages/wdio-appium-service/tests/launcher.test.js
Labels: PR: Polish :nail_care:

#3816 Fix runFnInFiberContext to allow wrapped commands to run in try/catch
  packages/wdio-sync/src/runFnInFiberContext.js
  packages/wdio-sync/tests/__mocks__/fibers.js
  packages/wdio-sync/tests/runFnInFibersContext.test.js
Labels: PR: Bug Fix :bug:

#3053 Automatically deploy website if new version was released
  .travis.yml
  package.json
  scripts/generateDocs.js
  scripts/generateSubPackage.js
  scripts/updateDocs.js
  website/i18n/en.json
  website/package.json
Labels: Docs, PR: Docs :memo:

#3817 wdio-cli: Print reporters after stdout
  packages/wdio-cli/src/interface.js
Labels: PR: Polish :nail_care:

#3822 Add a couple features to boilerplate project
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#3821 allure-reporter: fix allure endStep and startStep
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/runtime.test.js
Labels: PR: Polish :nail_care:

#3818 Allow junit-reporter to work when a runner has multiple spec files per runner
  packages/wdio-junit-reporter/src/index.js
  packages/wdio-junit-reporter/tests/__fixtures__/runner-multiple-specs.json
  packages/wdio-junit-reporter/tests/__fixtures__/suites-multiple.json
  packages/wdio-junit-reporter/tests/__fixtures__/wdio-0-0-junit-reporter-multiple.txt
  packages/wdio-junit-reporter/tests/reporter.test.js
Labels: PR: Polish :nail_care:

#3746 Issue 3416: Support multiple errors in the Allure-reporter
  packages/wdio-allure-reporter/src/compoundError.js
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/src/utils.js
  packages/wdio-allure-reporter/tests/__fixtures__/testState.js
  packages/wdio-allure-reporter/tests/compoundError.test.js
  packages/wdio-allure-reporter/tests/suite.test.js
  packages/wdio-allure-reporter/tests/utils.test.js
Labels: PR: Polish :nail_care:

#3825 fix addCommand in multiremote
  packages/webdriver/src/monad.js
  packages/webdriver/tests/monad.test.js
  packages/webdriverio/src/index.js
  packages/webdriverio/src/multiremote.js
  packages/webdriverio/tests/multiremote.test.js
Labels: PR: Bug Fix :bug:

#3828 wdio-cli: fix typo
  packages/wdio-cli/src/interface.js
Labels: PR: Polish :nail_care:

#3832 Ensure ms edge runs on w3c on Sauce
  packages/webdriver/src/utils.js
  packages/webdriver/tests/__fixtures__/edgedriver.response.json
  packages/webdriver/tests/utils.test.js
  packages/webdriverio/tests/__mocks__/request.js
Labels: PR: Spec Compliancy :eyeglasses:

#3836 wdio-jasmine-framework: Fix xit logging code to the console
  packages/wdio-jasmine-framework/src/index.js
Labels: PR: Bug Fix :bug:

#3841 wdio-devtools-service: adding debuggerAddress parameter
  packages/wdio-devtools-service/README.md
  packages/wdio-devtools-service/src/index.js
  packages/wdio-devtools-service/src/utils.js
  packages/wdio-devtools-service/tests/service.test.js
  packages/wdio-devtools-service/tests/utils.test.js
Labels: PR: New Feature :rocket:

#3846 Boilerplate Page update
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#3833 wdio-browserstack-service: Add configuration to modify session url fo…
  packages/wdio-browserstack-service/src/service.js
  packages/wdio-browserstack-service/tests/service.test.js
Labels: PR: Polish :nail_care:

#3845 better sauce headless support
  packages/wdio-cli/src/config.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-config/src/utils.js
  packages/wdio-config/tests/detectBackend.test.js
  packages/wdio-spec-reporter/src/index.js
  packages/wdio-spec-reporter/tests/__fixtures__/testdata.js
  packages/wdio-spec-reporter/tests/index.test.js
Labels: PR: New Feature :rocket:

#3850 Fix imports according to package dependencies.
  packages/webdriverio/src/multiremote.js
Labels: PR: Bug Fix :bug:

#3849 webdriver: Fix link for setTimeouts
  packages/webdriver/protocol/webdriver.json
Labels: PR: Docs :memo:

#3856 [@wdio/mocha-framework] Upgrade mocha min version to v6.1.0 to avoid security issue
  packages/wdio-mocha-framework/package.json
Labels: PR: Internal :house:

#3858 fix path to image in debug API page
  packages/webdriverio/src/commands/browser/debug.js
Labels: PR: Docs :memo:

#3861 Returned object type to switchToFram under webdriver protocol
  packages/webdriver/protocol/webdriver.json
Labels: PR: Spec Compliancy :eyeglasses:

#3868 wdio-junit-reporter: Fix nested and multiple describes
  packages/wdio-junit-reporter/README.md
  packages/wdio-junit-reporter/src/index.js
  packages/wdio-junit-reporter/tests/__fixtures__/runner-multiple-specs.json
  packages/wdio-junit-reporter/tests/__fixtures__/suites-multiple.json
  packages/wdio-junit-reporter/tests/__fixtures__/wdio-0-0-junit-reporter-error-options-used.txt
  packages/wdio-junit-reporter/tests/__fixtures__/wdio-0-0-junit-reporter-multiple-suites.txt
  packages/wdio-junit-reporter/tests/reporter.test.js
Labels: PR: Bug Fix :bug:

#3870 wdio-runner: catch getLogTypes error
  packages/wdio-runner/src/index.js
  packages/wdio-runner/tests/index.test.js
Labels: PR: Polish :nail_care:

#3871 wdio-logger: fix setting log level for subloggers and docs
  docs/ConfigurationFile.md
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-logger/src/node.js
  packages/wdio-logger/tests/node.test.js
Labels: PR: Bug Fix :bug:

#3862 Fixes to react$ and react$$ scripts
  docs/Selectors.md
  package.json
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/browser/$$.js
  packages/webdriverio/src/commands/browser/$.js
  packages/webdriverio/src/commands/browser/react$$.js
  packages/webdriverio/src/commands/browser/react$.js
  packages/webdriverio/src/commands/element/$$.js
  packages/webdriverio/src/commands/element/$.js
  packages/webdriverio/src/scripts/resq.js
  packages/webdriverio/src/utils/getElementObject.js
  packages/webdriverio/tests/__mocks__/request.js
  packages/webdriverio/tests/commands/browser/reactElement.test.js
  packages/webdriverio/tests/commands/browser/reactElements.test.js
  packages/webdriverio/tests/module.test.js
  packages/webdriverio/tests/scripts/resq.test.js
Labels: PR: New Feature :rocket:

#3874 Don't fail element command in IE
  packages/webdriver/src/utils.js
  packages/webdriver/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#3876 Fix headless endpoint
  packages/wdio-config/src/utils.js
  packages/wdio-config/tests/detectBackend.test.js
  packages/wdio-spec-reporter/src/index.js
  packages/wdio-spec-reporter/tests/__fixtures__/testdata.js
Labels: PR: Bug Fix :bug:

#3872 apply wdioLogLevel before starting workers
  packages/wdio-cli/src/launcher.js
  packages/wdio-local-runner/src/worker.js
  packages/wdio-logger/src/node.js
  packages/wdio-logger/tests/node.test.js
  packages/wdio-runner/src/index.js
Labels: PR: Polish :nail_care:

#3882 wdio-local-runner: unpipe streams in the end
  packages/wdio-local-runner/src/transformStream.js
  packages/wdio-local-runner/tests/transformStream.test.js
Labels: PR: Polish :nail_care:

#3885 Update JenkinsIntegration.md
  docs/JenkinsIntegration.md
Labels: PR: Docs :memo:

#3886 webdriver: fix appium protocols
  packages/webdriver/protocol/appium.json
  packages/webdriver/protocol/jsonwp.json
  packages/webdriver/protocol/webdriver.json
Labels: PR: Spec Compliancy :eyeglasses:

#3891 Fix unit tests when contributing on Windows 10
  packages/wdio-appium-service/tests/utils/getFilePath.test.js
  packages/wdio-junit-reporter/tests/reporter.test.js
  packages/wdio-local-runner/tests/localRunner.test.js
  packages/wdio-runner/tests/index.test.js
  packages/wdio-runner/tests/reporter.test.js
  packages/wdio-selenium-standalone-service/tests/utils/getFilePath.test.js
Labels: PR: Internal :house:

#3892 junit-reporter: fix log file names
  packages/wdio-junit-reporter/README.md
  packages/wdio-runner/src/reporter.js
  packages/wdio-runner/tests/reporter.test.js
Labels: PR: Polish :nail_care:

#3898 wdio-sync: bump fibers version to 4
  packages/wdio-sync/package.json
Labels: PR: Internal :house:

#3900 blog: add blog for react selector command
  website/blog/2019-04-03-react-selectors.md
Labels: PR: Docs :memo:
