Repository webdriverio/webdriverio, pull requests merged in 2019-03, with the labels that each got.

#3657 Some grammatical and spelling fixes
  website/blog/2019-02-22-shadow-dom-support.md
Labels: PR: Docs :memo:

#3659 Add type mobileEmulationEnabled
  scripts/templates/webdriver.tpl.d.ts
Labels: PR: Docs :memo:

#3660 Fix optional tagging
  .gitignore
  packages/webdriverio/src/commands/browser/execute.js
  packages/webdriverio/src/commands/browser/executeAsync.js
  packages/webdriverio/src/commands/browser/setCookies.js
  scripts/templates/api.tpl.ejs
Labels: PR: Docs :memo:

#3661 webdriver: Add strictSSL option
  docs/Proxy.md
  packages/webdriver/src/request.js
  packages/webdriver/tests/request.test.js
Labels: PR: New Feature :rocket:

#3669 Issue 3416: pass all failed expectations through from wdio-jasmine-framework
  packages/wdio-jasmine-framework/src/index.js
  packages/wdio-jasmine-framework/src/reporter.js
  packages/wdio-jasmine-framework/tests/adapter.test.js
  packages/wdio-jasmine-framework/tests/reporter.test.js
Labels: PR: Polish :nail_care:

#3664 Fix for #3663: utils.js/getElementRect fallback
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#3647 Update governance model
  GOVERNANCE.md
Labels: PR: Internal :house:

#3674 mochaOpts.require after wrapping functions with Fibers
  packages/wdio-mocha-framework/src/index.js
  packages/webdriverio/src/constants.js
Labels: PR: Polish :nail_care:

#3672 Issue 3416: pass multiple errors through to test stats for reporting if available
  packages/wdio-reporter/src/index.js
  packages/wdio-reporter/src/stats/hook.js
  packages/wdio-reporter/src/stats/suite.js
  packages/wdio-reporter/src/stats/test.js
  packages/wdio-reporter/src/utils.js
  packages/wdio-reporter/tests/reporter.listeners.test.js
  packages/wdio-reporter/tests/stats/hook.test.js
  packages/wdio-reporter/tests/test.stats.test.js
Labels: PR: Polish :nail_care:

#3662 Fixing Refetch to handle slow rerenders
  packages/wdio-webdriver-mock-service/src/index.js
  packages/webdriverio/src/utils/refetchElement.js
  packages/webdriverio/tests/__mocks__/request.js
  packages/webdriverio/tests/utils/refetchElement.test.js
Labels: PR: Bug Fix :bug:, webdriverio

#3675 wdio-logger: fix webdriver log colors
  packages/wdio-logger/src/node.js
  packages/wdio-logger/tests/node.test.js
Labels: PR: Bug Fix :bug:

#3676 wdio-allure-reporter: start end step
  packages/wdio-allure-reporter/src/constants.js
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/allureFeatures.test.js
  packages/wdio-allure-reporter/tests/constants.test.js
  packages/wdio-allure-reporter/tests/runtime.test.js
  packages/wdio-allure-reporter/tests/suite.test.js
Labels: PR: Polish :nail_care:

#3381 Retries per specfile
  docs/ConfigurationFile.md
  docs/Options.md
  docs/Retry.md
  examples/wdio.conf.js
  packages/wdio-cli/src/interface.js
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/tests/interface.test.js
  packages/wdio-cli/tests/launcher.test.js
  packages/wdio-local-runner/src/worker.js
  packages/wdio-reporter/README.md
  packages/wdio-reporter/src/index.js
  packages/wdio-reporter/src/stats/runner.js
  packages/wdio-runner/src/index.js
  tests/mocha/retry_and_fail.js
  tests/mocha/retry_and_pass.js
  tests/smoke.runner.js
Labels: PR: New Feature :rocket:

#3679 Add smoke test for custom reporters
  docs/CustomReporter.md
  packages/wdio-runner/src/reporter.js
  packages/wdio-smoke-test-reporter/.npmignore
  packages/wdio-smoke-test-reporter/.npmrc
  packages/wdio-smoke-test-reporter/README.md
  packages/wdio-smoke-test-reporter/package.json
  packages/wdio-smoke-test-reporter/src/index.js
  packages/webdriverio/src/constants.js
  scripts/constants.js
  scripts/utils/helpers.js
  tests/helpers/fixtures.js
  tests/helpers/reporter.conf.js
  tests/mocha/reporter.js
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#3681 webdriverio: middleware refactor
  packages/wdio-webdriver-mock-service/src/index.js
  packages/webdriverio/src/middlewares.js
  packages/webdriverio/src/utils/implicitWait.js
  packages/webdriverio/src/utils/refetchElement.js
  packages/webdriverio/tests/commands/element/moveTo.test.js
  packages/webdriverio/tests/commands/element/shadow$$.test.js
  packages/webdriverio/tests/commands/element/shadow$.test.js
  packages/webdriverio/tests/utils/refetchElement.test.js
Labels: PR: Bug Fix :bug:, webdriverio

#3690 webdriver: Fix error matcher for edge 15-17
  packages/webdriver/src/utils.js
Labels: PR: Bug Fix :bug:, webdriver

#3688 update to absolute references to webdriver-io-core
  packages/wdio-sync/webdriverio.d.ts
  packages/webdriverio/webdriverio.d.ts
Labels: PR: Docs :memo:

#3692 wdio-firefox-profile: legacy handling
  packages/wdio-firefox-profile-service/README.md
  packages/wdio-firefox-profile-service/src/launcher.js
  packages/wdio-firefox-profile-service/tests/launcher.test.js
Labels: PR: Bug Fix :bug:, wdio-firefox-profile-service

#3678 Fixed typo signalStrength
  packages/webdriver/protocol/appium.json
Labels: PR: Spec Compliancy :eyeglasses:

#3601 webdriverio: isDisplayed() change for browsers without the endpoint
  packages/webdriverio/src/commands/element/isDisplayed.js
  packages/webdriverio/src/scripts/isElementDisplayed.js
  packages/webdriverio/tests/__mocks__/request.js
  packages/webdriverio/tests/commands/element/isDisplayed.test.js
  packages/webdriverio/tests/middleware.test.js
Labels: PR: Spec Compliancy :eyeglasses:, webdriver, webdriverio

#3680 webdriverio: fix control key w3c compliancy
  packages/webdriverio/src/constants.js
Labels: PR: Spec Compliancy :eyeglasses:

#3691 browserstack-service: fixes #3648 modifying name and reason
  packages/wdio-browserstack-service/src/service.js
  packages/wdio-browserstack-service/tests/service.test.js
Labels: PR: Polish :nail_care:

#3625 Create a `outputDir` logs folder if doesn't exist
  packages/wdio-cli/package.json
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/tests/launcher.test.js
  packages/wdio-config/tests/__mocks__/@wdio/config.js
  packages/wdio-reporter/tests/reporter.test.js
Labels: PR: Polish :nail_care:

#3697 webdriverio: fix options in multiremote
  packages/webdriverio/src/index.js
  packages/webdriverio/tests/module.test.js
Labels: PR: Bug Fix :bug:

#3695 Corrected config field for filtering cucumber scenarios by tag
  docs/ConfigurationFile.md
Labels: PR: Docs :memo:

#3696 [FEATURE] Add ability to set serverUrl
  packages/wdio-applitools-service/README.md
  packages/wdio-applitools-service/src/index.js
  packages/wdio-applitools-service/tests/__mocks__/@wdio/eyes.webdriverio.js
  packages/wdio-applitools-service/tests/service.test.js
Labels: PR: Polish :nail_care:

#3702 Issue 3416: Allow the spec reporter to expose multiple errors if present
  packages/wdio-spec-reporter/src/index.js
  packages/wdio-spec-reporter/tests/__fixtures__/testdata.js
  packages/wdio-spec-reporter/tests/index.test.js
Labels: PR: Polish :nail_care:

#3705 Also clear protocol if not set
  packages/wdio-config/src/lib/ConfigParser.js
  packages/wdio-config/tests/configparser.test.js
Labels: PR: Bug Fix :bug:

#3701 webdriverio: fix isDisplayed
  packages/webdriverio/src/commands/element/isDisplayed.js
  packages/webdriverio/src/middlewares.js
  packages/webdriverio/src/utils/implicitWait.js
  packages/webdriverio/tests/__mocks__/request.js
  packages/webdriverio/tests/commands/element/isDisplayed.test.js
  packages/webdriverio/tests/middleware.test.js
Labels: PR: Bug Fix :bug:, webdriverio

#3710 webdriverio: fix linter errors (fix failing build)
  packages/webdriverio/tests/commands/element/isDisplayed.test.js
  packages/webdriverio/tests/middleware.test.js
Labels: PR: Internal :house:

#3712 edits to mobile selectors section
  docs/Selectors.md
Labels: PR: Docs :memo:

#3716 webdriverio: Allow selectByVisibleText to work with newlines
  packages/webdriverio/src/commands/element/selectByVisibleText.js
  packages/webdriverio/tests/commands/element/selectByVisibleText.test.js
Labels: PR: Polish :nail_care:

#3723 docs: Update custom reporter example
  examples/wdio/custom-reporter/reporter/my.custom.reporter.js
Labels: PR: Docs :memo:

#3730 Fixed typo
  website/pages/en/index.js
Labels: PR: Docs :memo:

#3731 Typo fix
  docs/PageObjects.md
Labels: PR: Docs :memo:

#3733 Fixing press key code type to number
  packages/webdriver/protocol/appium.json
Labels: PR: Spec Compliancy :eyeglasses:

#3735 Add notice about modifier keys
  packages/webdriverio/src/commands/browser/keys.js
Labels: PR: Docs :memo:

#3698 webdriverio: added setWindowOuterSize command
  packages/webdriver/protocol/jsonwp.json
  packages/webdriverio/src/commands/browser/setWindowSize.js
  packages/webdriverio/tests/commands/browser/setWindowSize.test.js
Labels: PR: Spec Compliancy :eyeglasses:

#3739 'name' find strategy should be used if isMobile is used even when w3c is used
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#3742 Fix invalid urls
  .gitignore
  packages/webdriverio/src/commands/browser/url.js
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#3740 wdio-runner: Allow custom reporter options to be overridden
  packages/wdio-runner/src/reporter.js
  packages/wdio-runner/tests/reporter.test.js
Labels: PR: Polish :nail_care:

#3752 webdriverio: Remove commas from param doc block
  packages/webdriverio/src/commands/browser/setWindowSize.js
Labels: PR: Docs :memo:

#3750 wdio-sync: Cleanup stacktraces
  packages/wdio-sync/src/constants.js
Labels: PR: Polish :nail_care:

#3764 Fix main script path of testingbot service
  packages/wdio-testingbot-service/package.json
Labels: PR: Bug Fix :bug:

#3766 login.spec.js syntax error
  docs/PageObjects.md
Labels: PR: Docs :memo:

#3767 fix auth in testingbot service
  packages/wdio-testingbot-service/src/launcher.js
  packages/wdio-testingbot-service/tests/tb-launch-service.test.js
Labels: PR: Bug Fix :bug:

#3756 Fail test if sauce service is used but no credentials are provided
  packages/wdio-browserstack-service/src/service.js
  packages/wdio-browserstack-service/tests/service.test.js
  packages/wdio-config/src/utils.js
  packages/wdio-config/tests/detectBackend.test.js
  packages/wdio-sauce-service/src/service.js
  packages/wdio-sauce-service/tests/service.test.js
Labels: PR: Polish :nail_care:

#3757 Use new "saucelabs" NPM package to speak to Sauce API
  package.json
  packages/wdio-sauce-service/package.json
  packages/wdio-sauce-service/src/service.js
  packages/wdio-sauce-service/tests/service.test.js
  packages/webdriverio/src/scripts/isElementDisplayed.js
  tests/mocha/retry_and_pass.js
  tests/smoke.runner.js
Labels: PR: Polish :nail_care:, wdio-sauce-service

#3768 webdriverio: return promise-wrapped async elements from $/$$ in async mode
  packages/webdriverio/webdriverio.d.ts
Labels: PR: Docs :memo:

#3772 #3771 wdio-document:updated the set proxy documentation
  docs/Proxy.md
Labels: PR: Docs :memo:

#3773 Fix auth for RDC tests
  packages/wdio-sauce-service/src/service.js
  packages/wdio-sauce-service/tests/service.test.js
Labels: PR: Bug Fix :bug:

#3777 fix typing data for waitFor*
  packages/webdriverio/src/commands/element/waitForDisplayed.js
  packages/webdriverio/src/commands/element/waitForEnabled.js
  packages/webdriverio/src/commands/element/waitForExist.js
Labels: PR: Docs :memo:

#3717 Appium service
  packages/wdio-appium-service/.npmignore
  packages/wdio-appium-service/.npmrc
  packages/wdio-appium-service/README.md
  packages/wdio-appium-service/package.json
  packages/wdio-appium-service/src/index.js
  packages/wdio-appium-service/src/launcher.js
  packages/wdio-appium-service/src/utils/getFilePath.js
  packages/wdio-appium-service/tests/.eslintrc
  packages/wdio-appium-service/tests/launcher.test.js
  packages/wdio-appium-service/tests/utils/getFilePath.test.js
Labels: PR: Internal :house:

#3784 Fix parameter name of background app command
  packages/webdriver/protocol/appium.json
Labels: PR: Spec Compliancy :eyeglasses:

#3782 validate typings
  package.json
  scripts/type-generation/test/.gitignore
  scripts/type-generation/test/README.md
  scripts/type-generation/test/copy.js
  scripts/type-generation/test/sync/sync.ts
  scripts/type-generation/test/sync/tsconfig.json
  scripts/type-generation/test/webdriverio/async.ts
  scripts/type-generation/test/webdriverio/tsconfig.json
Labels: work-in-progress

#3786 [docs] typo fix
  docs/API.md
Labels: PR: Docs :memo:

#3785 Update documentation for junit-reporter to reflect v5 options
  packages/wdio-junit-reporter/README.md
Labels: PR: Docs :memo:

#3762 Add Espresso DataMatcher strategy
  CONTRIBUTING.md
  docs/Selectors.md
  packages/webdriverio/package.json
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/utils.test.js
Labels: PR: New Feature :rocket:

#3779 Docs: Note regarding Dot reporter test failure output in v5
  packages/wdio-dot-reporter/README.md
Labels: PR: Docs :memo:

#3788 Add pre-commit and pre-push hooks
  package.json
Labels: PR: Internal :house:

#3778 webdriverio: refactor find-strategy method
  packages/webdriverio/src/utils.js
  packages/webdriverio/src/utils/findStrategy.js
  packages/webdriverio/tests/findStrategy.test.js
  packages/webdriverio/tests/utils.test.js
Labels: PR: Internal :house:

#3789 Update supported service and reporter list in CLI
  README.md
  packages/wdio-cli/src/config.js
Labels: PR: Internal :house:

#3792 fix connectionRetryCount default
  packages/webdriver/src/constants.js
Labels: PR: Polish :nail_care:
