Repository webdriverio/webdriverio, pull requests merged in 2019-02, with the labels that each got.

#3481 Fix 3480
  packages/webdriverio/src/commands/browser/saveScreenshot.js
  packages/webdriverio/tests/commands/browser/saveScreenshot.test.js
Labels: PR: Polish :nail_care:

#3478 changed browser.close() to browser.closeWindow()
  packages/webdriverio/src/commands/browser/newWindow.js
Labels: PR: Docs :memo:

#3469 Update config.js
  packages/wdio-cli/src/config.js
Labels: PR: Polish :nail_care:

#3477 Extendable typings
  .gitignore
  docs/TypeScript.md
  packages/wdio-jasmine-framework/jasmine-framework.d.ts
  packages/wdio-jasmine-framework/package.json
  packages/wdio-mocha-framework/mocha-framework.d.ts
  packages/wdio-mocha-framework/package.json
  packages/wdio-selenium-standalone-service/package.json
  packages/wdio-selenium-standalone-service/selenium-standalone-service.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Docs :memo:

#3422 Fix handling of yarn-managed node_modules
  packages/wdio-cli/package.json
  packages/wdio-cli/src/setup.js
Labels: PR: Bug Fix :bug:

#3484 webdriverio: adding more addCommand UTs
  packages/webdriverio/tests/addCommand.test.js
Labels: PR: Internal :house:

#3485 Updating Browserstack to use SSL
  packages/wdio-browserstack-service/src/service.js
  packages/wdio-browserstack-service/tests/service.test.js
  packages/wdio-config/src/utils.js
  packages/wdio-config/tests/detectBackend.test.js
Labels: PR: Polish :nail_care:, wdio-browserstack-service

#3486 Fixing Regression for chrome stale elements
  packages/webdriver/src/utils.js
  packages/webdriver/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#3487 Fixing element not found for iPhone
  packages/webdriver/src/utils.js
  packages/webdriver/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#3500 Update contributing docs now that v5 is fully released
  CONTRIBUTING.md
  README.md
Labels: Docs, PR: Docs :memo:

#3506 Fix Appium reload session
  packages/wdio-runner/tests/reporter.test.js
  packages/webdriverio/src/commands/browser/reloadSession.js
  packages/webdriverio/tests/__mocks__/request.js
  packages/webdriverio/tests/commands/browser/reloadSession.test.js
  scripts/templates/webdriver.tpl.d.ts
Labels: PR: Bug Fix :bug:

#3508 Update GettingStarted.md
  docs/GettingStarted.md
Labels: PR: Docs :memo:

#3497 fix Suite and Test typings for #3495
  packages/wdio-jasmine-framework/jasmine-framework.d.ts
  packages/wdio-mocha-framework/mocha-framework.d.ts
  packages/wdio-selenium-standalone-service/selenium-standalone-service.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Docs :memo:

#3503 Update GettingStarted.md
  docs/GettingStarted.md
Labels: PR: Docs :memo:

#3496 Fix/3492 fix multi remote
  packages/wdio-config/src/lib/ConfigParser.js
  packages/wdio-config/tests/__fixtures__/wdio.conf.multiremote.rdc.js
  packages/wdio-config/tests/__fixtures__/wdio.conf.rdc.js
  packages/wdio-config/tests/configparser.test.js
Labels: PR: Bug Fix :bug:

#3510 wdio-reporter: create outputDir directory if does not exist
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-reporter/package.json
  packages/wdio-reporter/src/index.js
  packages/wdio-reporter/tests/reporter.test.js
Labels: PR: Polish :nail_care:

#3521 wdio-allure-reporter: fix test skip
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/suite.test.js
Labels: PR: Bug Fix :bug:

#3519 Webdriverio: fix Hooks interface
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Docs :memo:

#3524 Improve cookie commands documentation
  packages/webdriverio/src/commands/browser/deleteCookies.js
  packages/webdriverio/src/commands/browser/setCookies.js
Labels: PR: Docs :memo:

#3527 Webdriver add chromium typings
  packages/webdriver/protocol/chromium.json
Labels: PR: Docs :memo:

#3528 Remove obsolete config prop deprecationWarnings
  docs/BrowserObject.md
  examples/wdio.conf.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-config/src/constants.js
  packages/wdio-junit-reporter/tests/__fixtures__/runner.json
Labels: PR: Internal :house:

#3533 webdriver: Fix HTTP method for createWindow command
  packages/webdriver/protocol/webdriver.json
Labels: PR: Spec Compliancy :eyeglasses:

#3525 Streamline typings
  packages/webdriver/protocol/chromium.json
  scripts/constants.js
  scripts/generate-docs.js
  scripts/type-generation/webdriver-generate-typings.js
Labels: PR: Docs :memo:

#3549 docs: Remove reference to wdio-screenshot that is not compatible with v5
  packages/webdriverio/src/commands/browser/saveScreenshot.js
Labels: PR: Docs :memo:

#3559 webdriver: unhandled promise rejection
  packages/webdriver/src/monad.js
Labels: PR: Bug Fix :bug:

#3555 webdriver: Adding a standard header 'Content-Length' to the headers list
  packages/webdriver/src/request.js
  packages/webdriver/tests/request.test.js
Labels: PR: Polish :nail_care:

#3560 Fix error due to empty wd response
  packages/webdriver/src/utils.js
  packages/webdriver/tests/request.test.js
  packages/webdriver/tests/utils.test.js
  packages/webdriverio/tests/__mocks__/request.js
Labels: PR: Internal :house:

#3536 wdio-allure-reporter: capture before each and all hooks
  packages/wdio-allure-reporter/src/constants.js
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/src/utils.js
  packages/wdio-allure-reporter/tests/allureFeatures.test.js
  packages/wdio-allure-reporter/tests/utils.test.js
  packages/wdio-mocha-framework/src/index.js
  packages/wdio-mocha-framework/tests/adapter.test.js
Labels: PR: Polish :nail_care:

#3566 webdriverio: remove redundant Generic from Element
  scripts/templates/webdriver.tpl.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/generate-typings-utils.js
  scripts/type-generation/webdriver-generate-typings.js
Labels: PR: Docs :memo:

#3540 Fix selectByVisibleText when element has multiple textNodes
  packages/webdriverio/src/commands/element/selectByVisibleText.js
  packages/webdriverio/tests/commands/element/selectByVisibleText.test.js
Labels: PR: Polish :nail_care:

#3571 webdriverio: user friendly waitUntil messages
  packages/webdriverio/src/commands/browser/waitUntil.js
  packages/webdriverio/tests/commands/browser/waitUntil.test.js
Labels: PR: Polish :nail_care:

#3565 show better stack trace for commands
  packages/wdio-sync/.npmrc
  packages/wdio-sync/src/constants.js
  packages/wdio-sync/src/utils.js
  packages/wdio-sync/src/wrapCommand.js
  packages/wdio-sync/tests/.eslintrc
  packages/wdio-sync/tests/__mocks__/errors.js
  packages/wdio-sync/tests/utils.test.js
  packages/wdio-sync/tests/wrapCommand.test.js
Labels: PR: Polish :nail_care:

#3573 Add waitForX 'reverse' examples to docs
  packages/webdriverio/src/commands/element/waitForDisplayed.js
  packages/webdriverio/src/commands/element/waitForExist.js
Labels: PR: Docs :memo:

#3575 webdriverio: merge Coockie interface in .tpl.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Docs :memo:

#3576 Update getting started doc
  docs/GettingStarted.md
Labels: PR: Docs :memo:

#3581 Remove old logOutput option
  docs/Options.md
  packages/webdriver/README.md
  packages/webdriver/src/constants.js
  packages/webdriver/tests/constant.test.js
Labels: PR: Polish :nail_care:

#3582 Bump Jasmine to 3.3.0
  packages/wdio-jasmine-framework/package.json
Labels: PR: Internal :house:

#3585 Fix parameter definition for assertPerformance command
  packages/webdriver/protocol/saucelabs.json
Labels: PR: Spec Compliancy :eyeglasses:

#3586 webdriverio: shadow$ and shadow$$ commands
  packages/webdriverio/src/commands/element/shadow$$.js
  packages/webdriverio/src/commands/element/shadow$.js
  packages/webdriverio/src/scripts/shadowFnFactory.js
  packages/webdriverio/tests/commands/element/shadow$$.test.js
  packages/webdriverio/tests/commands/element/shadow$.test.js
Labels: PR: New Feature :rocket:

#3578 Move reporter directory creation up
  packages/wdio-reporter/src/index.js
Labels: PR: Bug Fix :bug:

#3587 Make metrics param in assertPerformance not required
  packages/webdriver/protocol/saucelabs.json
Labels: PR: Spec Compliancy :eyeglasses:

#3548 webdriverio: extend wait command prefixes
  docs/CustomCommands.md
  packages/webdriverio/src/middlewares.js
  packages/webdriverio/tests/middleware.test.js
Labels: PR: Polish :nail_care:

#3583 Adding outputDir to standalone
  docs/Options.md
  packages/webdriverio/src/index.js
  packages/webdriverio/tests/module.test.js
Labels: PR: Polish :nail_care:

#3577 typescript promise commands
  .gitignore
  docs/TypeScript.md
  packages/wdio-sync/package.json
  packages/wdio-sync/webdriverio.d.ts
  packages/webdriverio/webdriverio.d.ts
  scripts/templates/webdriver.tpl.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/webdriverio-generate-typings.js
Labels: PR: Docs :memo:

#3590 Update package list in readme
  README.md
  packages/wdio-repl/package.json
  packages/wdio-utils/package.json
Labels: PR: Internal :house:

#3591 webdriverio: handle null returned by function selectors
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/utils.test.js
Labels: PR: Polish :nail_care:

#3594 webdriverio: remove redundant [T] -> T
  scripts/templates/webdriver.tpl.d.ts
Labels: PR: Docs :memo:

#3597 webdriverio: IE11 support in fetchElementByJSFunction
  packages/webdriverio/src/utils.js
Labels: PR: Bug Fix :bug:

#3600 Fix #3460
  packages/webdriver/src/request.js
Labels: PR: Bug Fix :bug:

#3603 scrollIntoView uses a arrow function which breaks in IE
  packages/webdriverio/src/commands/element/scrollIntoView.js
Labels: PR: Bug Fix :bug:

#3595 add return type void for Browser and Element commands
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/generate-typings-utils.js
  scripts/type-generation/specific-types.json
  scripts/type-generation/webdriver-generate-typings.js
Labels: PR: Docs :memo:

#3609 Add Docker setup boilerplate.
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#3467 set logLevel per logger and disable driver logger
  docs/ConfigurationFile.md
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/tests/__mocks__/chalk.js
  packages/wdio-config/src/constants.js
  packages/wdio-devtools-service/src/lighthouse/tabTraces.js
  packages/wdio-devtools-service/src/lighthouse/tracingProcessor.js
  packages/wdio-logger/src/node.js
  packages/wdio-logger/src/web.js
  packages/wdio-logger/tests/__mocks__/@wdio/logger.js
  packages/wdio-logger/tests/node.test.js
  packages/wdio-runner/src/index.js
  packages/wdio-runner/src/utils.js
  packages/wdio-runner/tests/index-initSession.test.js
  packages/wdio-runner/tests/index.test.js
  packages/wdio-utils/tests/__mocks__/@wdio/utils.js
  packages/webdriver/src/index.js
  packages/webdriver/tests/index.test.js
Labels: PR: New Feature :rocket:

#3624 webdriverio: fix scrollIntoView
  packages/webdriverio/src/commands/element/scrollIntoView.js
  packages/webdriverio/tests/commands/element/scrollIntoView.test.js
Labels: PR: Bug Fix :bug:

#3606 webdriverio: fix appium getvalue
  packages/webdriverio/src/commands/element/getValue.js
  packages/webdriverio/tests/commands/element/getValue.test.js
Labels: PR: Bug Fix :bug:

#3612 Strip Element objects from execute and executeAsync arguments
  packages/webdriverio/src/commands/browser/execute.js
  packages/webdriverio/src/commands/browser/executeAsync.js
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/utils.test.js
Labels: PR: Polish :nail_care:

#3598 Add check for caps, add tests
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/tests/launcher.test.js
Labels: PR: Polish :nail_care:

#3622 webdriverio: 📝 Correct isDisplayedInViewport docs
  packages/webdriverio/src/commands/element/isDisplayedInViewport.js
Labels: PR: Docs :memo:

#3618 typings: fix promise return type
  packages/webdriverio/webdriverio.d.ts
  scripts/templates/webdriver.tpl.d.ts
Labels: PR: Docs :memo:

#3619 Rename logger component name to match NPM package name
  packages/wdio-applitools-service/src/index.js
  packages/wdio-browserstack-service/src/launcher.js
  packages/wdio-browserstack-service/src/service.js
  packages/wdio-cli/src/interface.js
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/src/run.js
  packages/wdio-cli/src/utils.js
  packages/wdio-cli/src/watcher.js
  packages/wdio-config/src/lib/ConfigParser.js
  packages/wdio-config/src/shim.js
  packages/wdio-devtools-service/src/commands.js
  packages/wdio-devtools-service/src/index.js
  packages/wdio-devtools-service/src/utils.js
  packages/wdio-jasmine-framework/src/index.js
  packages/wdio-lambda-runner/src/handler.js
  packages/wdio-lambda-runner/src/index.js
  packages/wdio-local-runner/src/index.js
  packages/wdio-local-runner/src/run.js
  packages/wdio-local-runner/src/worker.js
  packages/wdio-mocha-framework/src/index.js
  packages/wdio-runner/src/index.js
  packages/wdio-runner/src/reporter.js
  packages/wdio-runner/src/utils.js
  packages/wdio-sauce-service/src/service.js
  packages/wdio-sumologic-reporter/src/index.js
  packages/wdio-sync/src/executeHooksWithArgs.js
  packages/wdio-sync/src/index.js
  packages/wdio-utils/src/initialiseServices.js
Labels: PR: Polish :nail_care:

#3628 Update README.md with Sauce Labs region parameter
  packages/wdio-sauce-service/README.md
Labels: PR: Docs :memo:

#3629 Increase test coverage
  package.json
  packages/wdio-allure-reporter/tests/helper.js
  packages/wdio-cli/tests/launcher.test.js
  packages/wdio-runner/src/index.js
  packages/wdio-runner/tests/index.test.js
  packages/webdriverio/tests/__mocks__/webdriverio.js
Labels: PR: Internal :house:

#3615 Assume JsonWP if platform cap is given
  packages/webdriver/src/utils.js
  packages/webdriver/tests/__fixtures__/safaridriver.legacy.response.json
  packages/webdriver/tests/__fixtures__/safaridriver.response.json
  packages/webdriver/tests/utils.test.js
Labels: PR: Spec Compliancy :eyeglasses:

#3630 webdriver: fix setNetworkConnection
  packages/webdriver/protocol/mjsonwp.json
Labels: Appium, Bug🐛, PR: Spec Compliancy :eyeglasses:

#3633 selenium-standalone-service: Fix typings after new sync/async type split
  packages/wdio-selenium-standalone-service/selenium-standalone-service.d.ts
Labels: PR: Docs :memo:

#3610 webdriverio: workaround for Safari to moveTo, getLocation, dragAndDrop, getSize
  packages/webdriverio/src/commands/element/dragAndDrop.js
  packages/webdriverio/src/commands/element/getLocation.js
  packages/webdriverio/src/commands/element/getSize.js
  packages/webdriverio/src/commands/element/moveTo.js
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/commands/element/moveTo.test.js
Labels: PR: Bug Fix :bug:

#3636 Update code sample at Selectors.md
  docs/Selectors.md
Labels: PR: Docs :memo:

#3635 website: shadow dom blog post
  website/blog/2019-02-22-shadow-dom-support.md
Labels: PR: Docs :memo:

#3640 webdriverio: update minimum required nodejs version
  packages/eslint-plugin-wdio/package.json
  packages/wdio-allure-reporter/package.json
  packages/wdio-applitools-service/package.json
  packages/wdio-browserstack-service/package.json
  packages/wdio-cli/package.json
  packages/wdio-concise-reporter/package.json
  packages/wdio-config/package.json
  packages/wdio-devtools-service/package.json
  packages/wdio-dot-reporter/package.json
  packages/wdio-firefox-profile-service/package.json
  packages/wdio-interface/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-junit-reporter/package.json
  packages/wdio-lambda-runner/package.json
  packages/wdio-local-runner/package.json
  packages/wdio-logger/package.json
  packages/wdio-mocha-framework/package.json
  packages/wdio-repl/package.json
  packages/wdio-reporter/package.json
  packages/wdio-runner/package.json
  packages/wdio-sauce-service/package.json
  packages/wdio-selenium-standalone-service/package.json
  packages/wdio-smoke-test-service/package.json
  packages/wdio-spec-reporter/package.json
  packages/wdio-sumologic-reporter/package.json
  packages/wdio-sync/package.json
  packages/wdio-testingbot-service/package.json
  packages/wdio-utils/package.json
  packages/wdio-webdriver-mock-service/package.json
  packages/webdriver/package.json
  packages/webdriverio/package.json
Labels: PR: Internal :house:

#3643 TypeScript version in doc and package.json
  docs/TypeScript.md
  packages/wdio-sync/package.json
  packages/webdriver/package.json
  packages/webdriverio/package.json
Labels: PR: Bug Fix :bug:

#3650 Fix execute script undefined argument
  packages/webdriver/protocol/jsonwp.json
  packages/webdriver/protocol/webdriver.json
  packages/webdriverio/package.json
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/utils.test.js
Labels: PR: Spec Compliancy :eyeglasses:

#3651 Pass custom agent and headers in every request
  docs/Options.md
  packages/webdriver/src/constants.js
  packages/webdriver/src/request.js
  packages/webdriver/tests/request.test.js
Labels: PR: New Feature :rocket:

#3653 docs: Update 'watch' example in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: PR: Docs :memo:
