Repository webdriverio/webdriverio, pull requests merged in 2019-01, with the labels that each got.

#3220 webdriverio: Update changelog for cli array arguments
  CHANGELOG.md
Labels: PR: Docs :memo:

#3225 Improve command definitions for available protocols
  CHANGELOG.md
  packages/webdriver/protocol/chromium.json
  packages/webdriver/protocol/jsonwp.json
  packages/webdriver/protocol/webdriver.json
  packages/webdriverio/src/commands/element/isEnabled.js
Labels: PR: Polish :nail_care:

#3215 Properly implement 'setTimeout' function and /timeouts endpoints
  CHANGELOG.md
  packages/webdriver/protocol/jsonwp.json
  packages/webdriver/protocol/webdriver.json
  packages/webdriverio/src/commands/browser/setTimeout.js
  packages/webdriverio/tests/commands/browser/setTimeout.test.js
Labels: PR: New Feature :rocket:

#3219 wdio-runner: Fix custom reporter options not being used
  package.json
  packages/wdio-runner/src/index.js
  packages/wdio-runner/src/reporter.js
  packages/wdio-runner/tests/reporter.test.js
Labels: PR: Bug Fix :bug:

#3226 Updated findStrategy
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#3231 docs: Update custom service export
  docs/CustomServices.md
Labels: PR: Docs :memo:

#3236 updating blog post v5 release, thank you section
  website/blog/2018-12-19-webdriverio-v5-released.md
Labels: PR: Docs :memo:

#3237 Update ConfigurationFile to use goog:chromeOptions
  docs/ConfigurationFile.md
Labels: PR: Docs :memo:

#3245 docs: Fix element commnads referencing the browser object
  scripts/generate-docs.js
  scripts/templates/api.tpl.ejs
  scripts/utils/formatter.js
Labels: PR: Docs :memo:

#3248 Add missing @wdio/reporter dep to junit reporter
  packages/wdio-junit-reporter/package.json
Labels: PR: Bug Fix :bug:

#3243 Set google analytics script into footer of website
  website/siteConfig.js
Labels: PR: Docs :memo:

#3240 Don't let jasmine swallow errors by ignoring its expectationResultHandler
  packages/wdio-jasmine-framework/src/index.js
  packages/wdio-jasmine-framework/tests/adapter.test.js
Labels: PR: Bug Fix :bug:

#3242 set NODE_ENV to production to not compile source map for NPM code
  package.json
  packages/wdio-cli/package.json
Labels: PR: Internal :house:

#3227 Undefined CSS classes for optional command parameters
  scripts/templates/api.tpl.ejs
  scripts/utils/formatter.js
  website/static/styles/_components/_labels.scss
  website/static/styles/_utils/_vars.scss
  website/static/styles/index.scss
Labels: Docs, PR: Docs :memo:

#3250 Update other commands which allow/expect 'null' as value.
  packages/webdriver/protocol/appium.json
  packages/webdriver/protocol/jsonwp.json
Labels: PR: Spec Compliancy :eyeglasses:

#3254 Fix package name and fix typos
  CONTRIBUTING.md
  docs/CLI.md
  packages/wdio-config/src/shim.js
  scripts/generate-sub-package.js
  website/blog/2018-12-19-webdriverio-v5-released.md
Labels: PR: Docs :memo:

#3249 Jasmine Framework improperly configures test randomization
  packages/wdio-jasmine-framework/src/index.js
  packages/wdio-jasmine-framework/tests/adapter.test.js
Labels: PR: Bug Fix :bug:

#3260 Updating options docs
  docs/Options.md
Labels: Docs, PR: Docs :memo:

#3258 Missing install of @babel/core
  docs/Babel.md
Labels: PR: Docs :memo:

#3253 wdio-reporter: updating pending test uid if existing
  packages/wdio-reporter/src/index.js
  packages/wdio-reporter/tests/reporter.listeners.test.js
Labels: PR: Polish :nail_care:

#3251 webdriverio: updating screenshot call to handle backslash
  packages/webdriverio/src/commands/browser/saveScreenshot.js
  packages/webdriverio/tests/__mocks__/fs.js
  packages/webdriverio/tests/commands/browser/saveScreenshot.test.js
Labels: PR: Polish :nail_care:

#3244 webdriverio: isDisplayed fix to return false on non existing elements
  packages/wdio-webdriver-mock-service/src/index.js
  packages/webdriverio/src/commands/element/isDisplayed.js
  packages/webdriverio/src/middlewares.js
  tests/smoke.test.js
Labels: PR: Polish :nail_care:

#3272 Update TypeScript.md docs
  docs/TypeScript.md
Labels: PR: Docs :memo:

#3275 Fix config key naming host =>hostname
  docs/CLI.md
  docs/ConfigurationFile.md
  packages/wdio-cli/src/config.js
  packages/wdio-sauce-service/src/launcher.js
  packages/wdio-sauce-service/tests/launcher.test.js
  packages/wdio-testingbot-service/src/launcher.js
  packages/wdio-testingbot-service/tests/tb-launch-service.test.js
  packages/webdriver/README.md
Labels: PR: Bug Fix :bug:

#3276 webdriverio: waitForDisplayed() now inherits isDisplayed() logic
  packages/webdriverio/src/commands/element/waitForDisplayed.js
  packages/webdriverio/tests/commands/element/waitForDisplayed.test.js
Labels: PR: Polish :nail_care:

#3268 webdriverio: utils.js - using "name" in element locator cause an InvalidSelector Error to be …
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/utils.test.js
Labels: PR: Polish :nail_care:

#3281 Remove semicolon from Debugging.md
  docs/Debugging.md
Labels: PR: Docs :memo:

#3278 Typescript definition
  packages/webdriverio/src/commands/browser/newWindow.js
  packages/webdriverio/src/commands/element/dragAndDrop.js
  packages/webdriverio/src/commands/element/getSize.js
  packages/webdriverio/src/commands/element/moveTo.js
Labels: PR: Docs :memo:

#3271 Fix instance prototype and enable custom commands for elements
  docs/CustomCommands.md
  package.json
  packages/wdio-cli/src/utils.js
  packages/wdio-cli/tests/utils.test.js
  packages/wdio-webdriver-mock-service/src/WebDriverMock.js
  packages/wdio-webdriver-mock-service/src/index.js
  packages/webdriver/src/index.js
  packages/webdriver/src/monad.js
  packages/webdriver/src/utils.js
  packages/webdriver/tests/monad.test.js
  packages/webdriver/tests/utils.test.js
  packages/webdriverio/src/commands/browser/$$.js
  packages/webdriverio/src/commands/browser/$.js
  packages/webdriverio/src/commands/element/$$.js
  packages/webdriverio/src/commands/element/$.js
  packages/webdriverio/src/commands/element/getSize.js
  packages/webdriverio/tests/__mocks__/request.js
  packages/webdriverio/tests/addCommand.test.js
  packages/webdriverio/tests/commands/browser/$$.test.js
  packages/webdriverio/tests/commands/browser/$.test.js
  packages/webdriverio/tests/commands/browser/touchAction.test.js
  packages/webdriverio/tests/commands/element/$$.test.js
  packages/webdriverio/tests/commands/element/$.test.js
  packages/webdriverio/tests/commands/element/isDisplayed.test.js
  packages/webdriverio/tests/commands/element/touchAction.test.js
  packages/webdriverio/tests/commands/element/waitForDisplayed.test.js
  packages/webdriverio/tests/commands/element/waitForExist.test.js
  packages/webdriverio/tests/multiremote.test.js
  tests/smoke.test.js
Labels: PR: Bug Fix :bug:

#3286 Loglevel
  docs/CLI.md
  docs/Options.md
  packages/wdio-cli/src/config.js
  packages/wdio-config/tests/validateConfig.test.js
  packages/wdio-logger/src/web.js
  packages/webdriver/src/constants.js
Labels: PR: Docs :memo:

#3290 Do mobile detection in webdriver package
  packages/webdriver/src/index.js
  packages/webdriver/src/monad.js
  packages/webdriver/src/utils.js
  packages/webdriver/tests/monad.test.js
  packages/webdriver/tests/utils.test.js
  packages/webdriverio/src/commands/browser/newWindow.js
  packages/webdriverio/src/index.js
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/commands/browser/newWindow.test.js
  packages/webdriverio/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#3296 Fix HTTP method of getCurrentActivity
  packages/webdriver/protocol/appium.json
Labels: PR: Spec Compliancy :eyeglasses:

#3299 Vendor specific protocol commands for Sauce Labs
  packages/webdriver/protocol/saucelabs.json
  packages/webdriver/src/index.js
  packages/webdriver/src/utils.js
  packages/webdriver/tests/utils.test.js
  scripts/generate-docs.js
  scripts/templates/api.tpl.ejs
  website/_sidebars.json
  website/i18n/en.json
Labels: PR: Spec Compliancy :eyeglasses:, webdriver

#3302 Improve typings
  docs/Options.md
  scripts/templates/webdriver.tpl.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Docs :memo:

#3303 Don't log error if service only contains a launcher
  packages/wdio-runner/src/utils.js
  packages/wdio-runner/tests/__mocks__/wdio-launcher-only-service.js
  packages/wdio-runner/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#3292 webdriverio: TypeScript defintions of $ - fix #3282
  docs/Selectors.md
  packages/webdriverio/src/commands/browser/$$.js
  packages/webdriverio/src/commands/browser/$.js
  packages/webdriverio/src/commands/browser/execute.js
  packages/webdriverio/src/commands/browser/executeAsync.js
  packages/webdriverio/src/commands/element/$$.js
  packages/webdriverio/src/commands/element/$.js
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/webdriverio-generate-typings.js
Labels: PR: Docs :memo:

#3308 Added new TypeScript boilerplate for WebdriverIO
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#3312 Keep scope when calling custom command on browser
  packages/wdio-webdriver-mock-service/src/WebDriverMock.js
  packages/wdio-webdriver-mock-service/src/index.js
  packages/webdriver/src/monad.js
  tests/smoke.test.js
Labels: PR: Bug Fix :bug:

#3311 Fixes type generation for URL variables
  scripts/type-generation/webdriver-generate-typings.js
Labels: PR: Docs :memo:

#3315 Bugfix service scope
  packages/wdio-cli/src/utils.js
  packages/wdio-cli/tests/utils.test.js
  packages/wdio-repl/src/index.js
Labels: PR: Bug Fix :bug:

#3313 ability for addCommand to add to element scope
  docs/CustomCommands.md
  packages/webdriver/src/monad.js
  packages/webdriver/tests/monad.test.js
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/browser/$$.js
  packages/webdriverio/src/commands/browser/$.js
  packages/webdriverio/src/commands/element/$$.js
  packages/webdriverio/src/commands/element/$.js
  packages/webdriverio/src/index.js
  packages/webdriverio/tests/addCommand.test.js
Labels: PR: Polish :nail_care:

#3247 README fix: move addAttachment args into a correct place
  packages/wdio-allure-reporter/README.md
Labels: PR: Docs :memo:

#3320 Update ConfigurationFile.md
  docs/ConfigurationFile.md
Labels: PR: Docs :memo:

#3321 wdio-allure-reporter: make step attachments optional
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/runtime.test.js
Labels: PR: Polish :nail_care:

#3325 Don't do instanceof check for set cookie and rather look for type
  packages/webdriverio/src/commands/browser/setCookies.js
Labels: PR: Bug Fix :bug:

#3326 webdriverio: Changed setCookie => setCookies in examples
  packages/webdriverio/src/commands/browser/deleteCookies.js
  packages/webdriverio/src/commands/browser/getCookies.js
  packages/webdriverio/src/commands/browser/setCookies.js
Labels: PR: Docs :memo:

#3319 Add missing typings
  docs/ConfigurationFile.md
  docs/Options.md
  examples/wdio.conf.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-config/src/constants.js
  packages/wdio-junit-reporter/tests/__fixtures__/runner.json
  packages/webdriverio/src/constants.js
  scripts/templates/webdriver.tpl.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Docs :memo:

#3330 Mention isSelected for checkbox and radio inputs
  packages/webdriverio/src/commands/element/getValue.js
Labels: PR: Docs :memo:

#3329 Remove desiredCapabilities in docs
  docs/CloudServices.md
  docs/Multiremote.md
  docs/Options.md
  examples/appium/appium-draws-its-logo.js
  packages/wdio-firefox-profile-service/src/launcher.js
  packages/wdio-firefox-profile-service/tests/launcher.test.js
  packages/webdriver/protocol/jsonwp.json
  packages/webdriverio/src/constants.js
Labels: PR: Docs :memo:

#3331 webdriverio: Fixes webdriverio constants and adds tests for services, execArgv and capabilities
  packages/webdriverio/src/constants.js
  packages/webdriverio/tests/constants.test.js
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Spec Compliancy :eyeglasses:

#3334 fix hook bug - closes #3333
  packages/wdio-config/src/constants.js
Labels: PR: Bug Fix :bug:

#3335 More typings improvements
  packages/webdriverio/tests/commands/browser/call.test.js
  scripts/templates/webdriver.tpl.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/webdriverio-generate-typings.js
Labels: PR: Docs :memo:

#3336 Tiny fixes of docs
  packages/webdriverio/src/commands/browser/deleteCookies.js
  packages/webdriverio/src/commands/browser/getCookies.js
  packages/webdriverio/src/commands/browser/setCookies.js
Labels: PR: Docs :memo:

#3340 Fix error message in webdriverio constants
  packages/webdriverio/src/constants.js
Labels: PR: Spec Compliancy :eyeglasses:

#3338 Better error handling for webdriver responses
  packages/webdriver/src/request.js
  packages/webdriver/src/utils.js
  packages/webdriver/tests/request.test.js
  packages/webdriver/tests/utils.test.js
Labels: PR: Polish :nail_care:

#3343 Fix addCommand typings and docs
  docs/CustomCommands.md
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Docs :memo:

#3341 Fix VSCode debug mode marking tests as failed
  packages/wdio-local-runner/src/constants.js
  packages/wdio-local-runner/src/transformStream.js
  packages/wdio-local-runner/tests/transformStream.test.js
Labels: PR: Bug Fix :bug:

#3348 Fix multiremote with wdio testrunner
  packages/wdio-local-runner/src/worker.js
  packages/wdio-local-runner/tests/localRunner.test.js
  packages/wdio-runner/src/index.js
  packages/wdio-runner/src/utils.js
  packages/wdio-webdriver-mock-service/src/index.js
  packages/webdriverio/src/index.js
  packages/webdriverio/tests/module.test.js
  tests/helpers/config.js
  tests/helpers/launch.js
  tests/mocha/test.js
  tests/multiremote/test.js
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#3349 missing lodash in dependencies require('lodash') node_modules/webdriverio/build/commands/element/$$.js
  packages/webdriverio/src/commands/element/$$.js
Labels: PR: Bug Fix :bug:

#3352 wdio-browserstack-service: Remove erroneous call to resolve
  packages/wdio-browserstack-service/src/launcher.js
Labels: PR: Bug Fix :bug:

#3353 wdio-browserstack-service: correcting error message
  packages/wdio-browserstack-service/src/launcher.js
Labels: Bug🐛, PR: Polish :nail_care:

#3355 Fix some webdriver and webdriverio typings
  packages/webdriver/protocol/mjsonwp.json
  scripts/templates/webdriver.tpl.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/specific-types.json
  scripts/type-generation/webdriverio-generate-typings.js
Labels: PR: Docs :memo:

#3356 Multiple fixes in typings
  packages/webdriverio/tests/constants.test.js
  scripts/templates/webdriver.tpl.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Docs :memo:

#3368 Acknowledge responses with body as string
  packages/webdriver/src/utils.js
  packages/webdriver/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#3364 Webdriver truncate log screenshot
  packages/webdriver/protocol/jsonwp.json
  packages/webdriver/protocol/webdriver.json
  packages/webdriver/src/command.js
  packages/webdriver/tests/command.test.js
Labels: PR: Polish :nail_care:

#3369 Update TypeScript.md
  docs/TypeScript.md
Labels: PR: Docs :memo:

#3371 Update --question.md
  .github/ISSUE_TEMPLATE/--question.md
Labels: PR: Internal :house:

#3375 Webdriver: Fix endpoint for Appium sendSms
  packages/webdriver/protocol/appium.json
Labels: PR: Spec Compliancy :eyeglasses:

#3374 Webdriver: Fix support on touchId documentation
  packages/webdriver/protocol/appium.json
Labels: PR: Spec Compliancy :eyeglasses:

#3376 Added Accessibility Test to TypeScript boilerplate
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#3382 Removing flaky test - this should not be a UT
  packages/wdio-testingbot-service/tests/tb-launch-service.test.js
Labels: PR: Internal :house:

#3380 Fix allure docs
  packages/wdio-allure-reporter/README.md
Labels: Docs, PR: Docs :memo:

#3347 Fix for #3344
  packages/webdriverio/src/commands/element/addValue.js
Labels: PR: Bug Fix :bug:

#3394 wdio-mocha-framework: upgrading mocha version
  packages/wdio-mocha-framework/package.json
Labels: Bug🐛, Enhancement, PR: Internal :house:

#3383 Add command to open a new top-level browsing context
  packages/webdriver/protocol/webdriver.json
Labels: PR: Spec Compliancy :eyeglasses:

#3398 guard against bad console method access in web version of logger
  packages/wdio-logger/src/web.js
Labels: PR: Polish :nail_care:

#3391 Updated Boilerplate Projects
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#3402 Update TypeScript.md
  docs/TypeScript.md
Labels: PR: Docs :memo:

#3401 webdriverio: improve typing for remote() function
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Docs :memo:

#3409 Update typescript setup docs
  docs/TypeScript.md
Labels: PR: Docs :memo:

#3411 Better error handling when config file is corrupted
  packages/wdio-config/src/lib/ConfigParser.js
  packages/wdio-runner/src/index.js
  packages/wdio-runner/tests/index.test.js
Labels: PR: Polish :nail_care:

#3414 Ignore if logs can't be received
  packages/wdio-runner/src/index.js
  packages/wdio-runner/tests/index.test.js
Labels: PR: Polish :nail_care:

#3415 Fix waitForXXX calls
  packages/wdio-webdriver-mock-service/src/index.js
  packages/webdriverio/src/utils/Timer.js
  tests/helpers/config.js
  tests/mocha/test.js
Labels: PR: Bug Fix :bug:

#3417 Include link to job details page from Sauce Labs
  packages/wdio-reporter/src/stats/runner.js
  packages/wdio-spec-reporter/src/index.js
  packages/wdio-spec-reporter/tests/__fixtures__/testdata.js
  packages/wdio-spec-reporter/tests/index.test.js
Labels: PR: Polish :nail_care:

#3418 Allow custom services with options
  package.json
  packages/wdio-allure-reporter/package.json
  packages/wdio-runner/src/utils.js
  packages/wdio-runner/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#3419 use eyes.webdriverio fork version to support v5
  packages/wdio-applitools-service/package.json
  packages/wdio-applitools-service/src/index.js
  packages/wdio-applitools-service/tests/__mocks__/@wdio/eyes.webdriverio.js
Labels: PR: Internal :house:

#3420 Fix param for getRunnerName
  packages/wdio-cli/src/interface.js
Labels: PR: Polish :nail_care:

#3427 change logger imports/exports for optimized webpack bundling
  packages/wdio-logger/src/index.js
Labels: PR: Polish :nail_care:

#3430 Allow displaying logs in realtime
  packages/wdio-cli/src/interface.js
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/src/watcher.js
  packages/wdio-cli/tests/interface.test.js
  packages/wdio-cli/tests/watcher.test.js
  packages/wdio-interface/src/index.js
  packages/wdio-interface/tests/__mocks__/@wdio/interface.js
  packages/wdio-interface/tests/interface.test.js
  packages/webdriverio/tests/commands/browser/keys.test.js
Labels: PR: Polish :nail_care:, work-in-progress

#3435 Fix the findStrategy for querying elements by tagname and content
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/utils.test.js
Labels: PR: Polish :nail_care:

#3436 Improve regexp to support custom elements that contain multiple dashes
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/utils.test.js
Labels: PR: Polish :nail_care:

#3423 mocha-framework: add file property
  packages/wdio-mocha-framework/src/index.js
  packages/wdio-mocha-framework/tests/adapter.test.js
Labels: PR: Polish :nail_care:

#3428 Temporary workaround for addValue and setValue
  packages/webdriver/protocol/webdriver.json
  packages/webdriverio/src/commands/element/addValue.js
  packages/webdriverio/tests/commands/element/addValue.test.js
Labels: PR: Polish :nail_care:

#3444 Fix allure multiremote
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/allureFeatures.test.js
Labels: PR: Bug Fix :bug:

#3452 Update README.md
  packages/wdio-junit-reporter/README.md
Labels: PR: Docs :memo:

#3453 Fix jasmine logger name
  packages/wdio-jasmine-framework/src/index.js
Labels: PR: Polish :nail_care:

#3461 wdio-allure-reporter: generate typings
  package.json
  packages/wdio-allure-reporter/package.json
  packages/wdio-allure-reporter/src/index.js
  scripts/type-generation/allure-reporter-generate-typings.js
  scripts/type-generation/generate-all-typings.js
  scripts/type-generation/generate-typings-utils.js
  scripts/type-generation/webdriverio-generate-typings.js
Labels: PR: Docs :memo:

#3463 Fix image path for jenkins job
  packages/wdio-junit-reporter/README.md
  website/static/img/jenkins-postjob.png
Labels: PR: Docs :memo:

#3464 Exit program on next tick
  packages/wdio-cli/src/run.js
Labels: PR: Bug Fix :bug:

#3465 Fix type generation
  packages/webdriver/protocol/saucelabs.json
  scripts/type-generation/generate-all-typings.js
  scripts/type-generation/webdriver-generate-typings.js
Labels: PR: Bug Fix :bug:
