Repository webdriverio/webdriverio, pull requests merged in 2019-11, with the labels that each got.

#4603 custom locator strategy
  packages/wdio-cli/src/interface.js
  packages/wdio-cli/tests/interface.test.js
  packages/wdio-protocols/protocols/jsonwp.json
  packages/webdriverio/src/commands/browser.js
  packages/webdriverio/src/commands/browser/custom$$.js
  packages/webdriverio/src/commands/browser/custom$.js
  packages/webdriverio/src/commands/element.js
  packages/webdriverio/src/commands/element/custom$$.js
  packages/webdriverio/src/commands/element/custom$.js
  packages/webdriverio/src/index.js
  packages/webdriverio/src/utils.js
  packages/webdriverio/src/utils/getElementObject.js
  packages/webdriverio/tests/__mocks__/request.js
  packages/webdriverio/tests/__mocks__/webdriverio.js
  packages/webdriverio/tests/commands/browser.test.js
  packages/webdriverio/tests/commands/browser/customSelector.test.js
  packages/webdriverio/tests/commands/browser/customSelectors.test.js
  packages/webdriverio/tests/commands/element.test.js
  packages/webdriverio/tests/commands/element/customSelector.test.js
  packages/webdriverio/tests/commands/element/customSelectors.test.js
  packages/webdriverio/tests/module.test.js
Labels: PR: New Feature :rocket:

#4719 Looks for Browserstack style versions in capabilities
  packages/wdio-allure-reporter/src/index.js
Labels: PR: Polish :nail_care:

#4722 Add test retry attempts to after hooks
  docs/ConfigurationFile.md
  docs/Options.md
  examples/pageobject/wdio.conf.js
  examples/wdio.conf.js
  examples/wdio/custom-service/my.custom.service.js
  packages/wdio-cli/src/templates/afterTest.ejs
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-runner/src/index.js
  packages/wdio-sync/src/index.js
  packages/wdio-sync/tests/index.test.js
  packages/wdio-sync/webdriverio-core.d.ts
  packages/wdio-utils/src/test-framework/testFnWrapper.js
  packages/wdio-utils/src/test-framework/testInterfaceWrapper.js
  packages/wdio-utils/tests/test-framework/testFnWrapper-async.test.js
  packages/wdio-utils/tests/test-framework/testFnWrapper-sync.test.js
  packages/wdio-utils/tests/test-framework/testInterfaceWrapper.test.js
  packages/webdriver/webdriver.d.ts
  packages/webdriverio/src/commands/element/isClickable.js
  packages/webdriverio/webdriverio-core-v5.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: New Feature :rocket:

#4727 shared-store: add types
  packages/wdio-shared-store-service/shared-store-service.d.ts
  tests/typings/copy.js
  tests/typings/sync/sync.ts
  tests/typings/sync/tsconfig.json
Labels: PR: Docs :memo:

#4730 Pass empty capabilities if session failed to start
  packages/wdio-runner/src/index.js
  packages/webdriver/src/utils.js
Labels: PR: Polish :nail_care:

#4736 Add waitForClickable command
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/src/commands/browser/pause.js
  packages/webdriverio/src/commands/element.js
  packages/webdriverio/src/commands/element/isClickable.js
  packages/webdriverio/src/commands/element/waitForClickable.js
  packages/webdriverio/tests/commands/element/waitForClickable.test.js
  packages/webdriverio/webdriverio-core-v5.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/generate-typings-utils.js
Labels: PR: New Feature :rocket:

#4733 Add docs to describe difference between sync and async modes
  docs/SyncVsAsync.md
  website/_sidebars.json
  website/i18n/en.json
Labels: PR: Docs :memo:

#4739 Pass capabilities to reporter before session started
  packages/wdio-runner/src/index.js
  packages/wdio-runner/tests/index.test.js
Labels: PR: Bug Fix :bug:

#4696 [NEW FEATURE] Add the ability to provided Feature file with line number or numbers as --spec on CLI
  packages/wdio-cli/src/index.js
  packages/wdio-config/src/lib/ConfigParser.js
  packages/wdio-config/src/utils.js
  packages/wdio-config/tests/__fixtures__/test-a.feature
  packages/wdio-config/tests/__fixtures__/test-b.feature
  packages/wdio-config/tests/configparser.test.js
  packages/wdio-cucumber-framework/src/index.js
Labels: PR: New Feature :rocket:

#4745 Fix before hook args
  packages/wdio-runner/src/index.js
  packages/wdio-runner/tests/index.test.js
Labels: PR: Bug Fix :bug:

#4750 Fix removeLineNumbers
  packages/wdio-config/src/utils.js
  packages/wdio-config/tests/configparser.test.js
  packages/wdio-config/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#4752 Assertperf typings fix
  packages/wdio-protocols/protocols/saucelabs.json
  packages/webdriver/webdriver.d.ts
Labels: PR: Docs :memo:

#4753 Fix cucumber framework initialisation
  packages/wdio-cucumber-framework/src/index.js
  packages/wdio-cucumber-framework/tests/adapter.test.js
  tests/cucumber/step-definitions/given.js
Labels: PR: Bug Fix :bug:

#4756 website: build status of master branch
  website/pages/en/index.js
Labels: PR: Internal :house:

#4754 isClickable handles child elements
  packages/webdriverio/src/scripts/isElementClickable.js
  packages/webdriverio/tests/scripts/isElementClickable.test.js
Labels: PR: Bug Fix :bug:

#4755 webdriverio: update url doc
  packages/webdriverio/src/commands/browser/url.js
Labels: PR: Docs :memo:

#4760 wdio-cucumber-framework: test-run-started event
  packages/wdio-cucumber-framework/src/cucumberEventListener.js
  packages/wdio-cucumber-framework/tests/reporter.test.js
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/webdriverio-core-v5.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  tests/cucumber/reporter/reporter.config.js
  tests/cucumber/reporter/reporter.feature
  tests/cucumber/reporter/reporter.given.js
  tests/helpers/config.js
  tests/helpers/cucumber-hooks.conf.js
  tests/helpers/fixtures.js
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#4763 docs(template): Fix API parameters
  scripts/templates/api.tpl.ejs
Labels: PR: Docs :memo:

#4764 Fix watch mode
  packages/wdio-config/src/lib/ConfigParser.js
  packages/wdio-config/src/utils.js
  packages/wdio-cucumber-framework/src/index.js
Labels: PR: Bug Fix :bug:

#4762 wdio-applitools-service: add typings
  package.json
  packages/wdio-applitools-service/applitools-service.d.ts
  packages/wdio-applitools-service/package.json
  packages/wdio-applitools-service/src/index.js
  packages/wdio-applitools-service/tests/__mocks__/@applitools/eyes-webdriverio.js
  packages/wdio-applitools-service/tests/service.test.js
  tests/typings/copy.js
  tests/typings/sync-applitools/applitools.ts
  tests/typings/sync-applitools/tsconfig.json
  tests/typings/webdriverio-applitools/applitools.ts
  tests/typings/webdriverio-applitools/tsconfig.json
Labels: PR: Docs :memo:

#4772 Handle multiline text in isClickable
  packages/webdriverio/src/scripts/isElementClickable.js
  packages/webdriverio/tests/scripts/isElementClickable.test.js
Labels: PR: Bug Fix :bug:

#4775 Document behaviour of custom services added by name
  docs/CustomServices.md
Labels: PR: Docs :memo:

#4794 wdio-crossbrowsertesting-service: fix process killed prematurely
  packages/wdio-crossbrowsertesting-service/src/launcher.js
  packages/wdio-crossbrowsertesting-service/tests/launcher.test.js
Labels: PR: Polish :nail_care:

#4797 fix(webdriverio): broader return types for Element.getProperty
  package-lock.json
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/src/commands/element/getProperty.js
  packages/webdriverio/webdriverio-core-v5.d.ts
  packages/webdriverio/webdriverio-core.d.ts
Labels: PR: Docs :memo:

#4798 Fix scrollIntoView in isClickable for old browsers
  packages/webdriverio/src/scripts/isElementClickable.js
Labels: PR: Bug Fix :bug:

#4800 isClickable shadow root support
  packages/webdriverio/src/scripts/isElementClickable.js
  packages/webdriverio/tests/scripts/isElementClickable.test.js
Labels: PR: Bug Fix :bug:

#4808 Fix isClickable in Edge if element is in ShadowRoot polyfill
  packages/webdriverio/src/scripts/isElementClickable.js
  packages/webdriverio/tests/scripts/isElementClickable.test.js
Labels: PR: Bug Fix :bug:

#4809 webdriver: Add the `headers` option to the Options type
  packages/webdriver/webdriver.d.ts
Labels: PR: Docs :memo:

#4785 Fix bug where multiple copies of logger breaks logging errors
  package.json
  packages/wdio-logger/src/node.js
  packages/wdio-logger/tests/node.test.js
Labels: PR: Bug Fix :bug:

#4773 wdio-allure-reporter: add flag to ignore/allow mocha hooks to have stacktrace and screenshots when they fail
  packages/wdio-allure-reporter/README.md
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/allureFeatures.test.js
Labels: PR: Polish :nail_care:

#4811 Warn devs to not develop on generate d.ts files
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriver/webdriver.d.ts
  packages/webdriverio/webdriverio-core-v5.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/constants.js
  scripts/templates/webdriver.tpl.d.ts
  scripts/type-generation/webdriver-generate-typings.js
  scripts/type-generation/webdriverio-generate-typings.js
Labels: PR: Docs :memo:

#4814 document isSynchronised in custom reporter
  docs/CustomReporter.md
Labels: PR: Docs :memo:

#4812 Allow overwriting specs and exclude in capabilities
  packages/wdio-config/src/lib/ConfigParser.js
  packages/wdio-config/tests/configparser.test.js
Labels: PR: Bug Fix :bug:

#4813 Extend checklist for type definitions
  .github/PULL_REQUEST_TEMPLATE.md
  e2e/protocol.test.js
Labels: PR: Docs :memo:

#4659 devtools automationProtocol: getUrl does not include #hash
  e2e/protocol.test.js
  packages/devtools/src/commands/getUrl.js
  packages/devtools/src/scripts/getUrl.js
Labels: PR: Bug Fix :bug:, devtools

#4821 Add note that FF extensions need to be signed or flag has to be set
  packages/wdio-firefox-profile-service/README.md
Labels: PR: Docs :memo:

#4819 wdio-allure-reporter: add tags cucumber support for scenario
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/__fixtures__/cucumber.js
  packages/wdio-allure-reporter/tests/cucumber.suite.test.js
Labels: PR: Polish :nail_care:

#4823 Set first failed expectation as error for jasmine
  packages/wdio-utils/src/test-framework/testFnWrapper.js
  packages/wdio-utils/tests/test-framework/__snapshots__/testFnWrapper-sync.test.js.snap
  packages/wdio-utils/tests/test-framework/testFnWrapper-sync.test.js
Labels: PR: Bug Fix :bug:

#4766 Inconsistency between webdriver and devtools getElementText command
  e2e/protocol.test.js
  packages/devtools/src/scripts/getElementText.js
  packages/webdriverio/src/utils/Timer.js
Labels: PR: Bug Fix :bug:, devtools

#4831 Feature/add proxy support for applitools
  packages/wdio-applitools-service/README.md
  packages/wdio-applitools-service/applitools-service.d.ts
  packages/wdio-applitools-service/package.json
  packages/wdio-applitools-service/src/index.js
  packages/wdio-applitools-service/tests/__mocks__/@applitools/eyes-webdriverio.js
  packages/wdio-applitools-service/tests/service.test.js
  tests/typings/sync-applitools/applitools.ts
  tests/typings/webdriverio-applitools/applitools.ts
Labels: PR: Polish :nail_care:

#4822 Remove `connectionRetryTimeout` option
  docs/BrowserObject.md
  docs/Options.md
  examples/pageobject/wdio.conf.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-config/src/constants.js
  packages/wdio-junit-reporter/tests/__fixtures__/runner.json
  packages/webdriver/README.md
  packages/webdriver/src/constants.js
  packages/webdriver/webdriver.d.ts
  scripts/templates/webdriver.tpl.d.ts
Labels: PR: Docs :memo:

#4828 Emit before and after command events in devtools
  packages/devtools/src/devtoolsdriver.js
  packages/devtools/tests/__snapshots__/devtoolsdriver.test.js.snap
  packages/devtools/tests/devtoolsdriver.test.js
Labels: PR: Bug Fix :bug:

#4836 wdio-mocha-framework: translate test:fail for error in "before each"-hook into hook:end
  packages/wdio-mocha-framework/src/index.js
  packages/wdio-mocha-framework/tests/adapter.test.js
Labels: PR: Bug Fix :bug:

#4829 Better handle script evaluation in devtools protocol
  e2e/protocol.test.js
  packages/devtools/src/commands/executeAsyncScript.js
  packages/devtools/src/commands/executeScript.js
  packages/devtools/src/scripts/executeAsyncScript.js
  packages/devtools/src/scripts/executeScript.js
Labels: PR: Bug Fix :bug:

#4835 Add data to refetch elements
  packages/wdio-sync/webdriverio-core.d.ts
  packages/wdio-sync/webdriverio.d.ts
  packages/webdriver/webdriver.d.ts
  packages/webdriverio/src/commands/browser/$$.js
  packages/webdriverio/src/commands/browser/custom$$.js
  packages/webdriverio/src/commands/browser/react$$.js
  packages/webdriverio/src/commands/element/$$.js
  packages/webdriverio/src/commands/element/custom$$.js
  packages/webdriverio/src/commands/element/react$$.js
  packages/webdriverio/src/commands/element/shadow$$.js
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/commands/browser/$$.test.js
  packages/webdriverio/tests/commands/browser/customSelectors.test.js
  packages/webdriverio/tests/commands/browser/reactElements.test.js
  packages/webdriverio/tests/commands/element/customSelectors.test.js
  packages/webdriverio/tests/commands/element/reactElements.test.js
  packages/webdriverio/webdriverio-core-v5.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  packages/webdriverio/webdriverio-v6.d.ts
  packages/webdriverio/webdriverio.d.ts
  scripts/constants.js
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/generate-typings-utils.js
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: New Feature :rocket:

#4833 Show link to job details page for each multiremote instance - …
  packages/wdio-runner/src/index.js
  packages/wdio-spec-reporter/src/index.js
  packages/wdio-spec-reporter/tests/__fixtures__/testdata.js
  packages/wdio-spec-reporter/tests/__snapshots__/index.test.js.snap
  packages/wdio-spec-reporter/tests/index.test.js
Labels: PR: Bug Fix :bug:
