Repository webdriverio/webdriverio, pull requests merged in 2019-06, with the labels that each got.

#4010 introduce 'install' command to wdio-cli
  docs/CLI.md
  docs/GettingStarted.md
  packages/wdio-cli/src/commands/install.js
  packages/wdio-cli/src/config.js
  packages/wdio-cli/src/setup.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/utils.js
  packages/wdio-cli/tests/utils.test.js
Labels: PR: New Feature :rocket:

#4026 typings: Add appium capabilities.
  scripts/templates/webdriver.tpl.d.ts
Labels: PR: Docs :memo:

#4052 Rename CONDUCT.md to CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: PR: Internal :house:

#4050 Fix call, execute, executeAsync, remote, multiremote
  .gitignore
  docs/TypeScript.md
  package.json
  packages/wdio-sync/webdriverio.d.ts
  packages/webdriver/protocol/jsonwp.json
  packages/webdriver/protocol/webdriver.json
  packages/webdriverio/webdriverio.d.ts
  scripts/templates/webdriver.tpl.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  tests/typings/sync/sync.ts
  tests/typings/sync/tsconfig.json
  tests/typings/sync/types/sync.d.ts
  tests/typings/webdriverio/async.ts
  tests/typings/webdriverio/tsconfig.json
  tests/typings/webdriverio/types/async.d.ts
Labels: PR: Docs :memo:

#4049 Overwrite native commands
  docs/CustomCommands.md
  packages/wdio-webdriver-mock-service/src/index.js
  packages/webdriver/src/monad.js
  packages/webdriver/src/utils.js
  packages/webdriver/tests/monad.test.js
  packages/webdriver/tests/utils.test.js
  packages/webdriverio/src/index.js
  packages/webdriverio/src/multiremote.js
  packages/webdriverio/tests/__mocks__/request.js
  packages/webdriverio/tests/module.test.js
  packages/webdriverio/tests/multiremote.test.js
  packages/webdriverio/tests/overwriteCommand.test.js
  packages/webdriverio/webdriverio.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  tests/mocha/test.js
  tests/multiremote/test.js
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: New Feature :rocket:

#3959 Add CrossBrowserTesting Service
  README.md
  docs/CloudServices.md
  docs/Options.md
  examples/README.md
  examples/cloudservices/README.md
  examples/cloudservices/crossbrowsertesting.js
  packages/wdio-cli/src/config.js
  packages/wdio-crossbrowsertesting-service/README.md
  packages/wdio-crossbrowsertesting-service/package.json
  packages/wdio-crossbrowsertesting-service/src/index.js
  packages/wdio-crossbrowsertesting-service/src/launcher.js
  packages/wdio-crossbrowsertesting-service/src/service.js
  packages/wdio-crossbrowsertesting-service/tests/.eslintrc
  packages/wdio-crossbrowsertesting-service/tests/__mocks__/cbt_tunnels.js
  packages/wdio-crossbrowsertesting-service/tests/launcher.test.js
  packages/wdio-crossbrowsertesting-service/tests/service.test.js
Labels: PR: New Feature :rocket:

#4056 wdio-mocha-framework: fix pending test test:end
  packages/wdio-devtools-service/tests/gatherer/trace.test.js
  packages/wdio-mocha-framework/src/index.js
  packages/wdio-mocha-framework/tests/adapter.test.js
Labels: PR: Bug Fix :bug:

#4062 Types fix for users with noImplicitAny set to true
  packages/wdio-sync/webdriverio.d.ts
  packages/webdriverio/webdriverio.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  tests/typings/sync-jasmine/tsconfig.json
  tests/typings/sync-mocha/tsconfig.json
  tests/typings/sync/sync.ts
  tests/typings/sync/tsconfig.json
  tests/typings/sync/types/sync.d.ts
  tests/typings/webdriverio-jasmine/tsconfig.json
  tests/typings/webdriverio-mocha/tsconfig.json
  tests/typings/webdriverio/async.ts
  tests/typings/webdriverio/tsconfig.json
  tests/typings/webdriverio/types/async.d.ts
Labels: PR: Docs :memo:

#4064 webdriverio: change argument type for setValue and addValue commands
  packages/webdriverio/src/commands/element/addValue.js
  packages/webdriverio/src/commands/element/setValue.js
  packages/webdriverio/tests/commands/element/addValue.test.js
  packages/webdriverio/tests/commands/element/setValue.test.js
Labels: PR: Bug Fix :bug:

#4071 Move cbt tunnels to dependency block
  packages/wdio-crossbrowsertesting-service/package.json
  packages/wdio-crossbrowsertesting-service/src/launcher.js
  packages/wdio-crossbrowsertesting-service/tests/launcher.test.js
Labels: PR: Bug Fix :bug:

#4075 Fix Chromedriver install via config wizard
  packages/wdio-cli/src/setup.js
Labels: PR: Bug Fix :bug:

#4077 Update utils.js
  packages/webdriver/src/utils.js
Labels: PR: Bug Fix :bug:

#4094 Update readme for Allure reporter
  packages/wdio-allure-reporter/README.md
Labels: PR: Docs :memo:

#4092 Fixing broken link to Lerna homepage
  CONTRIBUTING.md
Labels: PR: Docs :memo:

#4095 webdriverio: fix doubleClick when using w3c
  packages/webdriverio/src/commands/element/doubleClick.js
  packages/webdriverio/tests/commands/element/doubleClick.test.js
Labels: PR: Bug Fix :bug:

#4089 update appium service
  packages/wdio-appium-service/README.md
  packages/wdio-appium-service/package.json
  packages/wdio-appium-service/src/launcher.js
  packages/wdio-appium-service/tests/launcher.test.js
  packages/wdio-cli/src/commands/install.js
  packages/wdio-cli/src/setup.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/utils.js
  packages/wdio-cli/tests/utils.test.js
  packages/webdriverio/tests/overwriteCommand.test.js
Labels: PR: Bug Fix :bug:

#4099 Docs: waitUntil 'waitForTimeout' default value incorrect
  packages/webdriverio/src/commands/browser/waitUntil.js
Labels: PR: Docs :memo:

#4102 wdio-appium-service: fix args array, print startup failure message
  packages/wdio-appium-service/src/launcher.js
  packages/wdio-appium-service/tests/launcher.test.js
  packages/wdio-local-runner/tests/localRunner.test.js
  packages/webdriver/tests/monad.test.js
  packages/webdriverio/tests/commands/browser/pause.test.js
  packages/webdriverio/tests/commands/element/reactElement.test.js
  packages/webdriverio/tests/commands/element/reactElements.test.js
  packages/webdriverio/tests/commands/element/waitUntil.test.js
Labels: PR: Bug Fix :bug:

#4107 typings: specFileRetries is missing in type dsl.
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Docs :memo:

#4111 typings: add Edge specific in type DSL.
  scripts/templates/webdriver.tpl.d.ts
Labels: PR: Docs :memo:

#4108 typings: specs and exclude in capabilities is missing in type dsl.
  scripts/templates/webdriver.tpl.d.ts
Labels: PR: Docs :memo:

#4114 types: fix hook array
  scripts/templates/webdriverio.tpl.d.ts
  tests/typings/sync/config.ts
Labels: PR: Docs :memo:

#4116 Fix bug where environment flags aren't attached to session
  packages/webdriver/src/index.js
  packages/webdriver/src/utils.js
  packages/webdriver/tests/index.test.js
Labels: PR: Bug Fix :bug:

#4057 Add roadmap document
  ROADMAP.md
Labels: PR: Internal :house:

#4127 wdio-mocha-framework: add mocha error in type DSL
  packages/wdio-mocha-framework/mocha-framework.d.ts
Labels: PR: Docs :memo:
