Repository webdriverio/webdriverio, pull requests merged in 2019-05, with the labels that each got.

#3907 Don't try to connect to localhost anymore
  docs/ConfigurationFile.md
  docs/Options.md
  examples/wdio.conf.js
  examples/wdio/cucumber/wdio.conf.js
  examples/wdio/custom-reporter/wdio.conf.js
  examples/wdio/jasmine/wdio.conf.js
  examples/wdio/mocha/wdio.conf.js
  examples/wdio/multiremote/wdio.conf.js
  packages/wdio-appium-service/tests/launcher.test.js
  packages/wdio-cli/src/config.js
  packages/wdio-config/tests/__mocks__/@wdio/config.js
  packages/wdio-config/tests/detectBackend.test.js
  packages/wdio-webdriver-mock-service/src/WebDriverMock.js
  packages/webdriver/README.md
  packages/webdriver/src/constants.js
  tests/helpers/config.js
Labels: PR: Bug Fix :bug:

#3908 Propagate given capabilities to reporter
  packages/wdio-runner/src/index.js
  packages/wdio-runner/tests/index.test.js
  packages/wdio-utils/tests/__mocks__/@wdio/utils.js
Labels: PR: Bug Fix :bug:

#3909 move cloud service documentation to the options page
  docs/Options.md
  packages/wdio-sauce-service/README.md
Labels: PR: Docs :memo:

#3910 Replace own fork with Applitools package
  packages/wdio-applitools-service/package.json
  packages/wdio-applitools-service/src/index.js
  packages/wdio-applitools-service/tests/__mocks__/@applitools/eyes-webdriverio.js
  packages/wdio-applitools-service/tests/service.test.js
Labels: PR: Internal :house:

#3918 webdriver: Add return values for some commands
  packages/webdriver/protocol/appium.json
  packages/webdriver/protocol/chromium.json
  packages/webdriver/protocol/mjsonwp.json
  packages/webdriver/protocol/webdriver.json
Labels: PR: Docs :memo:

#3922 webdriverio: throw INVALID_SELECTOR_ERROR in correct spot
  packages/webdriverio/src/utils.js
Labels: PR: Polish :nail_care:

#3930 Fix/is displayed chrome
  packages/webdriverio/src/commands/element/isDisplayed.js
  packages/webdriverio/tests/commands/element/isDisplayed.test.js
Labels: PR: Spec Compliancy :eyeglasses:

#3936 Fix determining w3c for browserstack
  packages/webdriver/src/utils.js
Labels: PR: Spec Compliancy :eyeglasses:

#3941 webdriverio: add attach method to TypeScript definitions file
  packages/webdriverio/webdriverio.d.ts
Labels: PR: Docs :memo:

#3944 Documentation update for react$ and react$$
  packages/webdriverio/src/commands/browser/react$$.js
  packages/webdriverio/src/commands/browser/react$.js
Labels: PR: Docs :memo:

#3947 wdio-appium-service: Better handling of exit code = 2
  packages/wdio-appium-service/src/launcher.js
  packages/wdio-appium-service/tests/launcher.test.js
Labels: PR: Polish :nail_care:

#3949 Fix 'specifiy' typo
  docs/Options.md
Labels: PR: Docs :memo:

#3953 webdriverio: Update types for attach and remote methods
  packages/webdriverio/webdriverio.d.ts
  scripts/templates/webdriver.tpl.d.ts
Labels: PR: Docs :memo:

#3963 Add wdio-json-reporter to supported reporters
  packages/wdio-cli/src/config.js
Labels: PR: Internal :house:

#3967 Update TypeScript.md file require
  docs/TypeScript.md
Labels: PR: Docs :memo:

#3970 wdio-selenium-standalone: fix watch mode
  packages/wdio-selenium-standalone-service/src/launcher.js
  packages/wdio-selenium-standalone-service/tests/launcher.test.js
Labels: PR: Bug Fix :bug:

#3968 Move `@types/jasmine` to devDependency
  packages/wdio-jasmine-framework/package.json
Labels: PR: Internal :house:

#3964 webdriverio: Modify findStrategy.js to work with Youi.tv selectors.
  docs/Selectors.md
  packages/webdriverio/src/utils/findStrategy.js
  packages/webdriverio/tests/findStrategy.test.js
Labels: PR: New Feature :rocket:

#3979 Add getWindowSize command
  packages/webdriver/protocol/jsonwp.json
  packages/webdriverio/src/commands/browser/getWindowSize.js
  packages/webdriverio/tests/commands/browser/getWindowSize.test.js
Labels: PR: Spec Compliancy :eyeglasses:

#3978 Fix attach to session w3c handling
  packages/webdriver/src/index.js
  packages/webdriver/tests/index.test.js
Labels: PR: Bug Fix :bug:

#3983 Fix xpath selector start
  packages/webdriverio/src/utils/findStrategy.js
  packages/webdriverio/tests/findStrategy.test.js
Labels: PR: Bug Fix :bug:

#3988 typings: add automationName desired capability
  scripts/templates/webdriver.tpl.d.ts
Labels: PR: Docs :memo:

#3977 Fix queryAppState protocol
  packages/webdriver/protocol/appium.json
Labels: PR: Spec Compliancy :eyeglasses:

#3990 Visual regression blog
  website/blog/2019-05-18-visual-regression-for-v5.md
  website/blog/assets/image-comparison.jpg
Labels: PR: Docs :memo:

#3958 fix multiremote instances spawning
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/tests/launcher.test.js
  packages/wdio-runner/src/index.js
  packages/wdio-runner/tests/index.test.js
  packages/wdio-webdriver-mock-service/src/index.js
Labels: PR: Bug Fix :bug:, multi remote

#3950 new logger - initial version
  docs/JenkinsIntegration.md
  packages/wdio-cli/src/interface.js
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/src/utils.js
  packages/wdio-cli/src/watcher.js
  packages/wdio-cli/tests/__mocks__/chalk.js
  packages/wdio-cli/tests/interface.test.js
  packages/wdio-cli/tests/launcher.test.js
  packages/wdio-cli/tests/utils.test.js
  packages/wdio-cli/tests/watcher.test.js
  packages/wdio-local-runner/src/worker.js
  packages/wdio-local-runner/tests/worker.test.js
  packages/wdio-logger/src/node.js
  packages/wdio-logger/src/web.js
  packages/wdio-logger/tests/__mocks__/@wdio/logger.js
  packages/wdio-logger/tests/node.test.js
Labels: PR: Bug Fix :bug:

#3996 Print error message on test and "before/after all" hooks failure
  packages/wdio-cli/src/interface.js
  packages/wdio-cli/tests/interface.test.js
  packages/wdio-runner/src/reporter.js
  packages/wdio-runner/src/utils.js
  packages/wdio-runner/tests/reporter.test.js
  packages/wdio-runner/tests/utils.test.js
Labels: PR: New Feature :rocket:

#3995 wdio-config: include and exclude at capability level
  packages/wdio-config/src/lib/ConfigParser.js
  packages/wdio-config/tests/configparser.test.js
Labels: PR: New Feature :rocket:

#3993 wdio-junit-reporter: include before and after all failures
  packages/wdio-junit-reporter/src/index.js
  packages/wdio-junit-reporter/tests/__fixtures__/suites-hooks.json
  packages/wdio-junit-reporter/tests/__fixtures__/wdio-0-0-junit-reporter-hooks.txt
  packages/wdio-junit-reporter/tests/reporter.test.js
Labels: PR: Bug Fix :bug:

#3997 Docs: grammar changes to chaining selectors docs
  docs/Selectors.md
Labels: PR: Docs :memo:

#4002 avoid sauce:contexts calls being made for Sauce RDC tests
  packages/wdio-sauce-service/src/service.js
  packages/wdio-sauce-service/tests/service.test.js
Labels: PR: Bug Fix :bug:

#4005 wdio-mocha-framework: remove @types from runtime dependencies
  packages/wdio-mocha-framework/package.json
Labels: PR: Polish :nail_care:

#4007 Move `npm init -y` up in docs to avoid global installation
  docs/GettingStarted.md
Labels: PR: Docs :memo:

#4009 Typings: wrap waitUntil condition function return type with Promise
  packages/wdio-sync/webdriverio.d.ts
  packages/webdriverio/webdriverio.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  tests/typings/webdriverio/async.ts
  tests/typings/webdriverio/tsconfig.json
Labels: PR: Docs :memo:

#4017 Remove obsolete info about Object.create
  docs/PageObjects.md
Labels: PR: Docs :memo:

#4014 Simplify getting started
  docs/DriverBinaries.md
  docs/GettingStarted.md
  docs/RunProgrammatically.md
  packages/wdio-cli/src/config.js
  packages/wdio-cli/src/setup.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-selenium-standalone-service/README.md
  website/_sidebars.json
Labels: PR: Docs :memo:

#4022 Fixed issue #4021 - Not able to run tests with Sauce Connect and W3C caps
  packages/wdio-sauce-service/src/launcher.js
  packages/wdio-sauce-service/tests/launcher.test.js
Labels: PR: Bug Fix :bug:

#4006 Update CLI.md
  docs/CLI.md
Labels: PR: Docs :memo:

#3992 Updates to Performance Features
  package.json
  packages/wdio-devtools-service/README.md
  packages/wdio-devtools-service/package.json
  packages/wdio-devtools-service/src/auditor.js
  packages/wdio-devtools-service/src/commands.js
  packages/wdio-devtools-service/src/constants.js
  packages/wdio-devtools-service/src/driver.js
  packages/wdio-devtools-service/src/gatherer/devtools.js
  packages/wdio-devtools-service/src/gatherer/trace.js
  packages/wdio-devtools-service/src/index.js
  packages/wdio-devtools-service/src/lighthouse/errors.js
  packages/wdio-devtools-service/src/lighthouse/firstInteractive.js
  packages/wdio-devtools-service/src/lighthouse/tabTraces.js
  packages/wdio-devtools-service/src/lighthouse/tracingProcessor.js
  packages/wdio-devtools-service/src/scripts/.eslintrc.js
  packages/wdio-devtools-service/src/scripts/checkTimeSinceLastLongTask.js
  packages/wdio-devtools-service/src/scripts/registerPerformanceObserverInPage.js
  packages/wdio-devtools-service/src/utils.js
  packages/wdio-devtools-service/tests/__fixtures__/events.json
  packages/wdio-devtools-service/tests/__fixtures__/mouse_click.json
  packages/wdio-devtools-service/tests/__fixtures__/tracelog.json
  packages/wdio-devtools-service/tests/__mocks__/chrome-remote-interface.js
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/diagnostics.js
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/mainthread-work-breakdown.js
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics.js
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/time-to-first-byte.js
  packages/wdio-devtools-service/tests/__mocks__/puppeteer-core.js
  packages/wdio-devtools-service/tests/__snapshots__/auditor.test.js.snap
  packages/wdio-devtools-service/tests/auditor.test.js
  packages/wdio-devtools-service/tests/commands.test.js
  packages/wdio-devtools-service/tests/driver.test.js
  packages/wdio-devtools-service/tests/gatherer/__snapshots__/trace.test.js.snap
  packages/wdio-devtools-service/tests/gatherer/devtools.test.js
  packages/wdio-devtools-service/tests/gatherer/trace.test.js
  packages/wdio-devtools-service/tests/handler/network.test.js
  packages/wdio-devtools-service/tests/service.test.js
  packages/wdio-testingbot-service/tests/service.test.js
  packages/webdriverio/tests/utils/Timer.test.js
Labels: PR: New Feature :rocket:

#4025 Implement issue#4024: jasmine-framework - introduce new jasmineOpts option: stopSpecOnExpectationFailure
  packages/wdio-jasmine-framework/README.md
  packages/wdio-jasmine-framework/src/index.js
  packages/wdio-jasmine-framework/tests/adapter.test.js
Labels: PR: Polish :nail_care:

#3987 Fix browser session close in watch mode
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/src/watcher.js
  packages/wdio-cli/tests/interface.test.js
  packages/wdio-cli/tests/launcher.test.js
  packages/wdio-cli/tests/watcher.test.js
  packages/wdio-local-runner/src/index.js
  packages/wdio-local-runner/src/worker.js
  packages/wdio-local-runner/tests/localRunner.test.js
  packages/wdio-local-runner/tests/worker.test.js
  packages/wdio-runner/src/index.js
  packages/wdio-runner/src/utils.js
  packages/wdio-runner/tests/index.test.js
  packages/wdio-runner/tests/utils.test.js
  packages/webdriver/src/index.js
  packages/webdriver/tests/index.test.js
  packages/webdriverio/tests/__mocks__/webdriverio.js
Labels: PR: Bug Fix :bug:

#4020 scripts: generate 3rd party reporters and services
  package.json
  scripts/docs-generation/3rd-party/reporters.json
  scripts/docs-generation/3rd-party/services.json
  scripts/docs-generation/3rdPartyDocs.js
  scripts/docs-generation/generateDocs.js
  scripts/docs-generation/packagesDocs.js
  scripts/docs-generation/protocolDocs.js
  scripts/docs-generation/wdioDocs.js
  scripts/generateDocs.js
  scripts/utils/helpers.js
  website/i18n/en.json
  website/siteConfig.js
Labels: PR: Docs :memo:

#4000 #3980 Support array of functions for onPrepare and onComplete hooks
  docs/ConfigurationFile.md
  examples/pageobject/wdio.conf.js
  examples/wdio.conf.js
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/utils.js
  packages/wdio-cli/tests/launcher.test.js
  packages/wdio-cli/tests/utils.test.js
  packages/wdio-config/src/constants.js
  packages/wdio-config/src/lib/ConfigParser.js
  packages/wdio-config/tests/configparser.test.js
  packages/webdriverio/src/constants.js
Labels: PR: Polish :nail_care:

#4031 Update retry documentation as per #4008
  docs/Retry.md
Labels: PR: Docs :memo:

#4034 Update executeAsync.js
  packages/webdriverio/src/commands/browser/executeAsync.js
Labels: PR: Docs :memo:

#4037 Fix build
  packages/webdriverio/webdriverio.d.ts
  scripts/templates/webdriver.tpl.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Bug Fix :bug:

#4041 @wdio/devtools-service: updating puppeteer.connect arguments
  packages/wdio-devtools-service/src/driver.js
  packages/wdio-devtools-service/tests/driver.test.js
Labels: PR: Bug Fix :bug:

#4048 fix runOnCompleteHook to respect async functions
  packages/wdio-cli/src/utils.js
  packages/wdio-cli/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#4047 Wrap addCommand function with Fibers in multiremote mode
  packages/wdio-devtools-service/tests/gatherer/trace.test.js
  packages/wdio-webdriver-mock-service/src/index.js
  packages/webdriverio/src/index.js
  tests/multiremote/test.js
Labels: PR: Bug Fix :bug:
