Repository webdriverio/webdriverio, pull requests merged in 2019-07, with the labels that each got.

#4130 Fixed text in 2019-04-03-react-selectors.md
  website/blog/2019-04-03-react-selectors.md
Labels: PR: Docs :memo:

#4131 typings: add touchaction's ms type dsl.
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Docs :memo:

#4132 wdio-allure-reporter: allure attachment content can use Buffer type.
  packages/wdio-allure-reporter/src/index.js
Labels: PR: Internal :house:

#4136 Fix spawn declaration on Windows
  packages/wdio-appium-service/src/launcher.js
  packages/wdio-appium-service/tests/launcher.test.js
Labels: PR: Bug Fix :bug:

#3632 Upload blog post
  packages/webdriver/protocol/chromium.json
  packages/webdriver/protocol/selenium.json
  packages/webdriver/src/command.js
  packages/webdriver/src/request.js
  packages/webdriver/src/utils.js
  packages/webdriver/tests/__fixtures__/chromedriver.response.json
  packages/webdriver/tests/__fixtures__/standaloneserver.response.json
  packages/webdriver/tests/request.test.js
  packages/webdriver/tests/utils.test.js
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/browser/uploadFile.js
  packages/webdriverio/tests/__mocks__/archiver.js
  packages/webdriverio/tests/__mocks__/request.js
  packages/webdriverio/tests/commands/browser/uploadFile.test.js
  scripts/constants.js
  website/blog/2019-06-25-file-upload.md
Labels: PR: New Feature :rocket:

#4140 Update affiliation from JSF to OpenJSF
  LICENSE-MIT
  website/core/Footer.js
  website/i18n/en.json
  website/siteConfig.js
  website/static/img/jsf-logo.png
  website/static/img/open-jsf-logo.svg
Labels: PR: Internal :house:

#4142 Port wdio-static-server-service
  packages/wdio-static-server-service/.npmignore
  packages/wdio-static-server-service/.npmrc
  packages/wdio-static-server-service/README.md
  packages/wdio-static-server-service/package.json
  packages/wdio-static-server-service/src/index.js
  packages/wdio-static-server-service/src/launcher.js
  packages/wdio-static-server-service/tests/.eslintrc
  packages/wdio-static-server-service/tests/__mocks__/express.js
  packages/wdio-static-server-service/tests/example.test.js
Labels: PR: New Feature :rocket:

#4146 Docs: Normalize terminal commands
  docs/CLI.md
  docs/Debugging.md
  docs/DriverBinaries.md
  docs/GettingStarted.md
  docs/OrganizingTestSuites.md
  docs/Proxy.md
  docs/RunProgrammatically.md
  docs/WatchFiles.md
  docs/repl.md
Labels: PR: Docs :memo:

#4128 webdriverio: fix isDisplayed script to work with shadow dom
  packages/webdriverio/src/scripts/isElementDisplayed.js
Labels: PR: Polish :nail_care:

#4150 cli: Add defaults when running programmatically
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/tests/launcher.test.js
Labels: PR: Polish :nail_care:

#4152 wdio-allure-reporter: add suite separator
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/allureFeatures.test.js
Labels: PR: Polish :nail_care:

#4156 wdio-spec-reporter: fix header in multiremote mode
  packages/wdio-spec-reporter/src/index.js
  packages/wdio-spec-reporter/tests/index.test.js
Labels: PR: Bug Fix :bug:

#4158 wdio-utils: Make safeRequire use require.resolve
  packages/wdio-utils/src/initialisePlugin.js
Labels: PR: Polish :nail_care:

#4159 Cucumber: TypeScript Setup doc, pass function to requireModule
  docs/TypeScript.md
  packages/wdio-cucumber-framework/README.md
  packages/wdio-cucumber-framework/src/constants.js
  packages/wdio-cucumber-framework/src/index.js
  packages/wdio-cucumber-framework/tests/adapter.test.js
Labels: PR: Docs :memo:

#4160 Fixed text in 2019-05-18-visual-regression-for-v5.md
  website/blog/2019-05-18-visual-regression-for-v5.md
Labels: PR: Docs :memo:

#4162 Add sauce-connect-launcher to logger of wdio-sauce-service
  packages/wdio-sauce-service/src/launcher.js
Labels: PR: Polish :nail_care:

#4167 Add selector and elementId to Element
  packages/webdriverio/webdriverio.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Docs :memo:

#4166 fix cucumber hook args
  packages/wdio-cucumber-framework/src/hookRunner.js
  packages/wdio-cucumber-framework/tests/hookRunner.test.js
Labels: PR: Bug Fix :bug:

#4169 Update Cucumber Babel setup doc
  docs/Babel.md
  examples/pageobject/wdio.conf.js
  examples/wdio.conf.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cucumber-framework/tests/adapter.test.js
  packages/wdio-cucumber-framework/tests/fixtures/customModule.js
  tests/helpers/config.js
  website/i18n/en.json
Labels: PR: Docs :memo:

#4173 Cucumber related minor update to frameworks doc
  docs/Frameworks.md
Labels: PR: Docs :memo:

#4174 Cucumber fix error message
  packages/wdio-cucumber-framework/src/reporter.js
  packages/wdio-cucumber-framework/src/utils.js
  packages/wdio-cucumber-framework/tests/reporter.test.js
  packages/wdio-cucumber-framework/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#4176 Chore/cucumber5 blogpost
  website/blog/2019-07-11-cucumberjs-v5-released.md
Labels: PR: Docs :memo:

#4181 wdio-cucumber-framework: fix hook handling
  packages/wdio-cucumber-framework/src/reporter.js
  packages/wdio-cucumber-framework/src/utils.js
  packages/wdio-cucumber-framework/tests/__snapshots__/utils.test.js.snap
  packages/wdio-cucumber-framework/tests/reporter.test.js
  packages/wdio-cucumber-framework/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#4153 Add Changelog and Roadmap links to README.md
  README.md
Labels: PR: Docs :memo:

#4179 Add EsLint check for dependencies
  package.json
  packages/wdio-appium-service/package.json
  packages/wdio-crossbrowsertesting-service/package.json
  packages/wdio-testingbot-service/package.json
Labels: PR: Bug Fix :bug:

#4194 isSauce should not depend on hostname
  packages/webdriver/src/utils.js
  packages/webdriver/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#4202 Fix overflow text is displayed
  packages/webdriverio/src/scripts/isElementDisplayed.js
Labels: PR: Bug Fix :bug:

#4201 Print data tables in spec reporter
  packages/wdio-cucumber-framework/src/utils.js
  packages/wdio-cucumber-framework/tests/__snapshots__/utils.test.js.snap
  packages/wdio-spec-reporter/package.json
  packages/wdio-spec-reporter/src/index.js
  packages/wdio-spec-reporter/tests/__fixtures__/testdata.js
  packages/wdio-spec-reporter/tests/__snapshots__/index.test.js.snap
  packages/wdio-spec-reporter/tests/index.test.js
Labels: PR: Polish :nail_care:

#4117 Updated selectors documentation for element ID
  docs/Selectors.md
Labels: PR: Docs :memo:

#4189 Fix type for webdriverio onPrepare parameter
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Docs :memo:

#4211 clean up setTimeout implementation
  packages/webdriverio/src/commands/browser/setTimeout.js
Labels: PR: Polish :nail_care:

#4204 Print link to Sauce Labs job details page when using Sauce Connect
  packages/wdio-spec-reporter/src/index.js
  packages/wdio-spec-reporter/tests/index.test.js
Labels: PR: Bug Fix :bug:

#4212 Remove safe-buffer dependency
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/browser/saveRecordingScreen.js
  packages/webdriverio/src/commands/browser/saveScreenshot.js
  packages/webdriverio/src/commands/element/saveScreenshot.js
Labels: PR: Internal :house:

#4213 Fixed text in 2019-07-11-cucumberjs-v5-released.md
  website/blog/2019-07-11-cucumberjs-v5-released.md
Labels: PR: Docs :memo:

#4226 Fix failing ci
  tests/multiremote/test.js
  tests/smoke.runner.js
Labels: PR: Internal :house:

#4223 Fix MaxListenersExceededWarning
  packages/wdio-local-runner/src/stdStream.js
  packages/wdio-local-runner/src/utils.js
  packages/wdio-local-runner/src/worker.js
  packages/wdio-local-runner/tests/stdStream.test.js
  packages/wdio-local-runner/tests/transformStream.test.js
  packages/wdio-local-runner/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#4046 Add throttleCPU command
  packages/webdriver/protocol/saucelabs.json
Labels: PR: Spec Compliancy :eyeglasses:

#4233 Add Cucumber and Mocha boilerplate
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#4229 Browser/element prototype performance improvements
  packages/webdriver/src/index.js
  packages/webdriver/src/request.js
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/browser.js
  packages/webdriverio/src/commands/element.js
  packages/webdriverio/src/multiremote.js
  packages/webdriverio/src/utils.js
  packages/webdriverio/src/utils/getElementObject.js
  packages/webdriverio/tests/commands/browser.test.js
  packages/webdriverio/tests/commands/browser/saveRecordingScreen.test.js
  packages/webdriverio/tests/commands/browser/saveScreenshot.test.js
  packages/webdriverio/tests/commands/browser/uploadFile.test.js
  packages/webdriverio/tests/commands/element.test.js
  packages/webdriverio/tests/commands/element/saveScreenshot.test.js
  tests/performance/sample.js
Labels: PR: Internal :house:

#4220 Add allure-reporter option useCucumberStepReporter
  packages/wdio-allure-reporter/README.md
  packages/wdio-allure-reporter/src/constants.js
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/__fixtures__/cucumber.js
  packages/wdio-allure-reporter/tests/constants.test.js
  packages/wdio-allure-reporter/tests/cucumber.suite.test.js
  packages/wdio-allure-reporter/tests/runtime.test.js
  packages/wdio-cucumber-framework/src/reporter.js
  packages/wdio-cucumber-framework/src/utils.js
  packages/wdio-cucumber-framework/tests/__snapshots__/utils.test.js.snap
  packages/wdio-cucumber-framework/tests/reporter.test.js
  packages/wdio-cucumber-framework/tests/utils.test.js
  packages/wdio-reporter/src/stats/suite.js
Labels: PR: Polish :nail_care:

#4221 Fix slow before/after command hook in sync mode
  packages/wdio-sync/src/wrapCommand.js
  packages/wdio-sync/tests/wrapCommand.test.js
  packages/webdriver/src/command.js
  packages/webdriverio/src/middlewares.js
  packages/webdriverio/src/utils/getElementObject.js
Labels: PR: Bug Fix :bug:

#4239 Cucumber: add result argument to afterScenario hook
  docs/ConfigurationFile.md
  examples/pageobject/wdio.conf.js
  examples/wdio.conf.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cucumber-framework/src/cucumberEventListener.js
  packages/wdio-cucumber-framework/src/reporter.js
  packages/wdio-cucumber-framework/tests/eventListener.test.js
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Polish :nail_care:

#4237 speedup build, clean, bootstrap
  package.json
Labels: PR: Internal :house:

#4243 Feat/add cucumberjs json
  packages/wdio-cli/src/config.js
  scripts/docs-generation/3rd-party/reporters.json
Labels: PR: Docs :memo:

#4247 webdriver: add prefs to ChromeOptions typings
  scripts/templates/webdriver.tpl.d.ts
Labels: PR: Docs :memo:

#4249 Fix commands error handling in sync mode
  packages/wdio-sync/src/wrapCommand.js
  packages/wdio-sync/tests/wrapCommand.test.js
  packages/wdio-webdriver-mock-service/src/index.js
  tests/mocha/test.js
Labels: PR: Bug Fix :bug:

#4252 webdriver: truncate screen recording log #4251
  packages/webdriver/src/command.js
  packages/webdriver/tests/command.test.js
Labels: PR: Bug Fix :bug:

#4250 introduce profileDirectory option in wdio-firefox-profile-service
  packages/wdio-firefox-profile-service/src/launcher.js
  packages/wdio-firefox-profile-service/tests/__mocks__/firefox-profile.js
  packages/wdio-firefox-profile-service/tests/launcher.test.js
Labels: PR: Polish :nail_care:

#4255 Fix debug command in async mode
  packages/wdio-sync/src/wrapCommand.js
  packages/wdio-sync/tests/wrapCommand.test.js
Labels: PR: Bug Fix :bug:

#4256 Fix element chaining in async mode
  packages/wdio-sync/src/wrapCommand.js
  packages/wdio-sync/tests/wrapCommand.test.js
  packages/wdio-webdriver-mock-service/src/index.js
  tests/mocha/test.js
Labels: PR: Bug Fix :bug:

#4260 Fix FirefoxOptions prefs type to optional
  scripts/templates/webdriver.tpl.d.ts
Labels: PR: Docs :memo:

#4261 typings: add isChrome's type dsl.
  scripts/templates/webdriver.tpl.d.ts
Labels: PR: Docs :memo:

#4269 Fix waitUntil first iteration is promise
  packages/wdio-sync/src/wrapCommand.js
  packages/wdio-sync/tests/wrapCommand.test.js
  tests/mocha/test.js
Labels: PR: Bug Fix :bug:

#4276 Use index when refetching element
  packages/webdriverio/src/utils/refetchElement.js
  packages/webdriverio/tests/utils/refetchElement.test.js
Labels: PR: Bug Fix :bug:

#4281 Speedup internal tests
  .eslintignore
  .gitignore
  babel.config.js
  package.json
  tests/smoke.runner.js
  tests/typings/sync-jasmine/tsconfig.json
  tests/typings/sync-mocha/tsconfig.json
  tests/typings/sync/tsconfig.json
  tests/typings/webdriverio-jasmine/tsconfig.json
  tests/typings/webdriverio-mocha/tsconfig.json
  tests/typings/webdriverio/tsconfig.json
Labels: PR: Internal :house:

#4283 Encode uri params
  packages/webdriver/src/command.js
  packages/webdriver/tests/command.test.js
Labels: PR: Bug Fix :bug:

#4285 Add types for Cucumber hooks
  docs/ConfigurationFile.md
  examples/wdio.conf.js
  package.json
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cucumber-framework/cucumber-framework.d.ts
  packages/wdio-cucumber-framework/package.json
  scripts/templates/webdriverio.tpl.d.ts
  tests/typings/copy.js
  tests/typings/sync-cucumber/cucumber.ts
  tests/typings/sync-cucumber/tsconfig.json
Labels: PR: Bug Fix :bug:
