Repository webdriverio/webdriverio, pull requests merged in 2020-11, with the labels that each got.

#6061 allure-reporter: fix mime type
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/runtime.test.js
Labels: PR: Bug Fix :bug:

#6062 browser.mock use utf8 by default
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/src/utils/interception/devtools.ts
  packages/webdriverio/tests/utils/interception/devtools.test.js
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Bug Fix :bug:

#6065 fix: Sauce EmuSim can't work with sauce:options for Sauce Connect
  packages/wdio-sauce-service/src/utils.js
  packages/wdio-sauce-service/tests/launcher.test.js
  packages/wdio-sauce-service/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#5961 retry if SC fails to start
  packages/wdio-sauce-service/src/launcher.js
  packages/wdio-sauce-service/tests/launcher.test.js
Labels: PR: Polish :nail_care:

#6067 Better typing for callback arguments in browser.execute
  packages/wdio-sync/webdriverio.d.ts
  packages/webdriverio/webdriverio.d.ts
Labels: PR: Polish :nail_care:

#6073 Fixes #6068
  packages/wdio-logger/src/node.ts
  packages/wdio-logger/src/web.ts
  packages/wdio-logger/tests/node.test.ts
  packages/webdriver/src/command.ts
Labels: PR: Bug Fix :bug:

#6078 feat(ui5-service): add UI5 support to wdio
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#6089 website: adjust landing page mobile view
  website/i18n/en.json
  website/pages/en/index.js
  website/static/styles/_modules/_headers.scss
  website/static/styles/_modules/_nav.scss
  website/static/styles/_utils/_vars.scss
Labels: PR: Internal :house:

#6104 Update Selectors.md
  docs/Selectors.md
Labels: PR: Docs :memo:

#6107 Fix Selenium-Standalone service overriding capabilities
  packages/wdio-appium-service/src/launcher.js
  packages/wdio-config/src/utils.js
  packages/wdio-config/tests/utils.test.js
  packages/wdio-selenium-standalone-service/src/launcher.ts
  packages/wdio-selenium-standalone-service/tests/launcher.test.ts
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Bug Fix :bug:

#6108 fix(5973): fix for mocha before all hook incorrectly taking the first…
  packages/wdio-mocha-framework/src/index.js
  packages/wdio-mocha-framework/tests/adapter.test.js
Labels: PR: Bug Fix :bug:

#6111 Fix environment detection
  packages/wdio-repl/src/index.ts
  packages/wdio-utils/tests/__mocks__/@wdio/utils.ts
  packages/webdriver/src/command.ts
  packages/webdriver/src/index.ts
  packages/webdriver/src/request.ts
  packages/webdriver/tests/__snapshots__/index.test.ts.snap
  packages/webdriver/tests/index.test.ts
Labels: PR: Bug Fix :bug:

#6094 Rewrite DevTools unit test section
  jest.config.js
  packages/devtools/src/commands/closeWindow.ts
  packages/devtools/src/commands/elementClear.ts
  packages/devtools/src/commands/getElementAttribute.ts
  packages/devtools/src/commands/getElementCSSValue.ts
  packages/devtools/src/commands/getElementRect.ts
  packages/devtools/src/commands/getElementTagName.ts
  packages/devtools/src/commands/getElementText.ts
  packages/devtools/src/devtoolsdriver.ts
  packages/devtools/src/index.ts
  packages/devtools/src/launcher.ts
  packages/devtools/tests/__mocks__/chrome-launcher.ts
  packages/devtools/tests/__mocks__/pptrDebug.ts
  packages/devtools/tests/__mocks__/puppeteer-core.ts
  packages/devtools/tests/__snapshots__/devtools.test.ts.snap
  packages/devtools/tests/__snapshots__/devtoolsdriver.test.ts.snap
  packages/devtools/tests/__snapshots__/launcher.test.ts.snap
  packages/devtools/tests/__snapshots__/utils.test.ts.snap
  packages/devtools/tests/devtools.test.ts
  packages/devtools/tests/devtoolsdriver.test.ts
  packages/devtools/tests/elementStore.test.ts
  packages/devtools/tests/finder/finder.test.ts
  packages/devtools/tests/launcher.test.ts
  packages/devtools/tests/utils.test.ts
  packages/devtools/tsconfig.json
Labels: Tracking 🗒, TypeScript, needs-review

#6102 feat: enable new printPage command via webdriver protocol binding
  packages/wdio-protocols/protocols/webdriver.json
Labels: PR: New Feature :rocket:

#6076 Another take on bug #4953
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/__fixtures__/testState.js
  packages/wdio-allure-reporter/tests/suite.test.js
  packages/wdio-reporter/src/stats/hook.ts
  packages/wdio-reporter/tests/stats/hook.test.ts
Labels: PR: Bug Fix :bug:

#6066 Fixes #6057
  packages/webdriverio/src/commands/browser/mock.ts
  packages/webdriverio/tests/__mocks__/got.js
  packages/webdriverio/tests/commands/browser/mock.test.js
Labels: PR: Bug Fix :bug:

#6117 Update examples with outdated waitForVisible method
  docs/Timeouts.md
  examples/pageobject/specs/form.spec.js
  packages/webdriverio/src/commands/element/waitForDisplayed.js
Labels: PR: Docs :memo:

#6122 Execute beforeSession hook before everything is initiated
  packages/wdio-runner/src/index.js
Labels: PR: Polish :nail_care:

#6125 Change debuggerAddress to optional
  packages/webdriver/src/types.ts
Labels: PR: Bug Fix :bug:

#6123 Rewrite utils.ts and constants.ts of wdio-config in typescript
  packages/devtools/src/constants.ts
  packages/devtools/src/index.ts
  packages/wdio-config/src/constants.ts
  packages/wdio-config/src/index.ts
  packages/wdio-config/src/types.ts
  packages/wdio-config/src/utils.ts
  packages/wdio-config/tests/__fixtures__/wdio.conf.js
  packages/wdio-config/tests/__fixtures__/wdio.conf.multiremote.rdc.js
  packages/wdio-config/tests/__fixtures__/wdio.conf.rdc.js
  packages/wdio-config/tests/configparser.test.js
  packages/wdio-config/tsconfig.json
  packages/wdio-config/tsconfig.prod.json
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriver/src/constants.ts
  packages/webdriver/src/index.ts
  packages/webdriver/src/types.ts
  packages/webdriver/webdriver.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Internal :house:, TypeScript, wdio-config

#6126 Save pdf
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriver/webdriver.d.ts
  packages/webdriverio/src/commands/browser.js
  packages/webdriverio/src/commands/browser/savePDF.ts
  packages/webdriverio/tests/__mocks__/got.js
  packages/webdriverio/tests/commands/browser/savePDF.test.js
  packages/webdriverio/webdriverio-core.d.ts
Labels: PR: New Feature :rocket:

#6127 Switch window query strings
  packages/webdriverio/src/commands/browser/switchWindow.ts
  packages/webdriverio/tests/commands/browser/switchWindow.test.js
Labels: PR: Bug Fix :bug:

#6133 Add Options to Save PDF
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/src/commands/browser/savePDF.ts
  packages/webdriverio/tests/commands/browser/savePDF.test.js
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/constants.js
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Polish :nail_care:

#6135 Rewrite ConfigParser.ts of wdio-config in typescript
  docs/Options.md
  packages/wdio-config/src/constants.ts
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-config/src/types.ts
  packages/wdio-config/src/utils.ts
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Internal :house:, TypeScript, wdio-config

#6141 Rewrite all unit tests of wdio-config in typescript
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-config/src/types.ts
  packages/wdio-config/tests/__fixtures__/wdio.conf.js
  packages/wdio-config/tests/__fixtures__/wdio.conf.multiremote.rdc.ts
  packages/wdio-config/tests/__fixtures__/wdio.conf.rdc.js
  packages/wdio-config/tests/__fixtures__/wdio.conf.rdc.ts
  packages/wdio-config/tests/__fixtures__/wdio.conf.ts
  packages/wdio-config/tests/__fixtures__/wdio.local.conf.js
  packages/wdio-config/tests/__fixtures__/wdio.local.conf.ts
  packages/wdio-config/tests/__mocks__/@wdio/config.ts
  packages/wdio-config/tests/configparser.test.ts
  packages/wdio-config/tests/detectBackend.test.ts
  packages/wdio-config/tests/utils.test.ts
  packages/wdio-config/tests/validateConfig.test.ts
Labels: PR: Internal :house:, TypeScript, wdio-config

#6131 Rewrite devtools service tests
  packages/wdio-devtools-service/src/commands.ts
  packages/wdio-devtools-service/src/gatherer/trace.ts
  packages/wdio-devtools-service/src/index.ts
  packages/wdio-devtools-service/tests/__mocks__/chrome-remote-interface.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/diagnostics.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/mainthread-work-breakdown.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/cumulative-layout-shift.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/first-contentful-paint.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/interactive.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/largest-contentful-paint.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/speed-index.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/total-blocking-time.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/server-response-time.ts
  packages/wdio-devtools-service/tests/__mocks__/speedline.ts
  packages/wdio-devtools-service/tests/__snapshots__/auditor.test.ts.snap
  packages/wdio-devtools-service/tests/__snapshots__/service.test.ts.snap
  packages/wdio-devtools-service/tests/auditor.test.ts
  packages/wdio-devtools-service/tests/commands.test.ts
  packages/wdio-devtools-service/tests/gatherer/__snapshots__/trace.test.ts.snap
  packages/wdio-devtools-service/tests/gatherer/devtools.test.js
  packages/wdio-devtools-service/tests/gatherer/devtools.test.ts
  packages/wdio-devtools-service/tests/gatherer/trace.test.ts
  packages/wdio-devtools-service/tests/handler/network.test.ts
  packages/wdio-devtools-service/tests/service.test.js
  packages/wdio-devtools-service/tests/service.test.ts
  packages/wdio-devtools-service/tests/utils.test.ts
  packages/wdio-devtools-service/tsconfig.json
  packages/wdio-devtools-service/tsconfig.prod.json
  packages/wdio-local-runner/src/replQueue.ts
  packages/wdio-local-runner/tests/replQueue.test.ts
  packages/wdio-sumologic-reporter/src/index.js
  packages/wdio-sync/src/wrapCommand.js
  packages/wdio-sync/tests/wrapCommand.test.js
Labels: TypeScript, needs-review

#5834 Tracking doc: rewrite `@wdio/devtools-service` package into TypeScript
  packages/wdio-devtools-service/package.json
  packages/wdio-devtools-service/src/@types/lighthouse.ts
  packages/wdio-devtools-service/src/auditor.ts
  packages/wdio-devtools-service/src/commands.js
  packages/wdio-devtools-service/src/commands.ts
  packages/wdio-devtools-service/src/constants.ts
  packages/wdio-devtools-service/src/gatherer/devtools.js
  packages/wdio-devtools-service/src/gatherer/devtools.ts
  packages/wdio-devtools-service/src/gatherer/trace.ts
  packages/wdio-devtools-service/src/handler/network.ts
  packages/wdio-devtools-service/src/index.js
  packages/wdio-devtools-service/src/index.ts
  packages/wdio-devtools-service/src/scripts/checkTimeSinceLastLongTask.ts
  packages/wdio-devtools-service/src/scripts/registerPerformanceObserverInPage.ts
  packages/wdio-devtools-service/src/utils.ts
  packages/wdio-devtools-service/tests/__mocks__/chrome-remote-interface.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/diagnostics.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/mainthread-work-breakdown.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/cumulative-layout-shift.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/first-contentful-paint.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/interactive.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/largest-contentful-paint.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/speed-index.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/total-blocking-time.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/server-response-time.ts
  packages/wdio-devtools-service/tests/__mocks__/speedline.ts
  packages/wdio-devtools-service/tests/__snapshots__/auditor.test.ts.snap
  packages/wdio-devtools-service/tests/__snapshots__/service.test.ts.snap
  packages/wdio-devtools-service/tests/auditor.test.ts
  packages/wdio-devtools-service/tests/commands.test.ts
  packages/wdio-devtools-service/tests/gatherer/__snapshots__/trace.test.ts.snap
  packages/wdio-devtools-service/tests/gatherer/devtools.test.js
  packages/wdio-devtools-service/tests/gatherer/devtools.test.ts
  packages/wdio-devtools-service/tests/gatherer/trace.test.ts
  packages/wdio-devtools-service/tests/handler/network.test.ts
  packages/wdio-devtools-service/tests/service.test.js
  packages/wdio-devtools-service/tests/service.test.ts
  packages/wdio-devtools-service/tests/utils.test.ts
  packages/wdio-devtools-service/tsconfig.json
  packages/wdio-devtools-service/tsconfig.prod.json
  packages/wdio-local-runner/src/replQueue.ts
  packages/wdio-local-runner/tests/replQueue.test.ts
  packages/wdio-sumologic-reporter/src/index.js
  packages/wdio-sync/src/wrapCommand.js
  packages/wdio-sync/tests/wrapCommand.test.js
  packages/webdriverio/webdriverio-core.d.ts
Labels: PR: Internal :house:, Tracking 🗒, TypeScript

#6152 Update selenium-standalone with comma consistency
  packages/wdio-selenium-standalone-service/README.md
Labels: PR: Docs :memo:

#6156 Add typings tests for SevereServiceError in sync mode
  docs/CustomServices.md
  docs/Options.md
  packages/webdriverio/webdriverio-core.d.ts
  tests/typings/sync/sync.ts
Labels: PR: Docs :memo:

#6158 Add getElementComputedRole and getElementComputedLabel commands
  packages/devtools/tests/__snapshots__/utils.test.ts.snap
  packages/wdio-protocols/protocols/webdriver.json
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriver/webdriver.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: New Feature :rocket:

#6143 Don't use global.browser in services
  docs/ConfigurationFile.md
  docs/CustomServices.md
  examples/pageobject/wdio.conf.js
  examples/wdio.conf.js
  packages/devtools/tests/elementStore.test.ts
  packages/devtools/tests/finder/finder.test.ts
  packages/wdio-applitools-service/src/index.ts
  packages/wdio-applitools-service/tests/service.test.ts
  packages/wdio-applitools-service/tsconfig.json
  packages/wdio-applitools-service/tsconfig.prod.json
  packages/wdio-browserstack-service/src/service.js
  packages/wdio-browserstack-service/src/util.js
  packages/wdio-browserstack-service/tests/service.test.js
  packages/wdio-browserstack-service/tests/util.test.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-config/src/index.ts
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-crossbrowsertesting-service/src/service.js
  packages/wdio-crossbrowsertesting-service/tests/launcher.test.js
  packages/wdio-crossbrowsertesting-service/tests/service.test.js
  packages/wdio-devtools-service/src/commands.ts
  packages/wdio-devtools-service/src/index.ts
  packages/wdio-devtools-service/src/utils.ts
  packages/wdio-devtools-service/tests/commands.test.ts
  packages/wdio-devtools-service/tests/service.test.ts
  packages/wdio-runner/src/index.js
  packages/wdio-runner/tests/index.test.js
  packages/wdio-sauce-service/src/service.js
  packages/wdio-sauce-service/tests/service.test.js
  packages/wdio-shared-store-service/src/service.ts
  packages/wdio-shared-store-service/tests/service.test.ts
  packages/wdio-sync/webdriverio-core.d.ts
  packages/wdio-testingbot-service/src/service.ts
  packages/wdio-testingbot-service/tests/launcher.test.ts
  packages/wdio-testingbot-service/tests/service.test.ts
  packages/wdio-webdriver-mock-service/src/index.ts
  packages/wdio-webdriver-mock-service/tsconfig.json
  packages/wdio-webdriver-mock-service/tsconfig.prod.json
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Polish :nail_care:, needs-review

#6160 Implement a11y protocol commands in puppeteer
  packages/devtools/src/commands/getElementComputedLabel.ts
  packages/devtools/src/commands/getElementComputedRole.ts
Labels: PR: New Feature :rocket:

#6159 Add get `getComputedLabel` and `getComputedRole` to element scope
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/src/commands/element.ts
  packages/webdriverio/src/commands/element/getComputedLabel.ts
  packages/webdriverio/src/commands/element/getComputedRole.ts
  packages/webdriverio/tests/commands/element.test.js
  packages/webdriverio/webdriverio-core.d.ts
Labels: PR: New Feature :rocket:

#6163 Improve behavior fetching CSS shorthand properties
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/element/getCSSProperty.ts
  packages/webdriverio/src/types/css-shorthand-properties.d.ts
  packages/webdriverio/tests/__mocks__/got.js
  packages/webdriverio/tests/commands/element/getCSSProperty.test.js
Labels: PR: Polish :nail_care:, needs-review

#6164 Trigger change event if selecting an option in devtools
  e2e/element.test.js
  packages/devtools/src/commands/elementClick.ts
  packages/devtools/src/scripts/selectOption.ts
Labels: PR: Bug Fix :bug:, needs-review

#6171 selenium-standalone: simplify config
  packages/wdio-selenium-standalone-service/README.md
  packages/wdio-selenium-standalone-service/package.json
  packages/wdio-selenium-standalone-service/selenium-standalone-service.d.ts
  packages/wdio-selenium-standalone-service/src/launcher.ts
  packages/wdio-selenium-standalone-service/tests/launcher.test.ts
Labels: PR: New Feature :rocket:

#6173 Add back promisify bind fix
  packages/wdio-static-server-service/src/launcher.ts
  packages/wdio-static-server-service/tests/__mocks__/express.ts
Labels: PR: Bug Fix :bug:

#6176 selenium-standalone: fix driver keys condition
  packages/wdio-selenium-standalone-service/src/launcher.ts
  packages/wdio-selenium-standalone-service/tests/launcher.test.ts
Labels: PR: Polish :nail_care:

#6177 add winappdriver and ywinappdriver service
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#6178 Fix uploadFile command
  packages/wdio-logger/tests/node.test.ts
  packages/webdriverio/src/commands/browser/uploadFile.ts
  packages/webdriverio/tests/commands/browser/uploadFile.test.js
Labels: PR: Bug Fix :bug:

#6183 Fix `isFocused` command
  packages/webdriverio/src/commands/element/isFocused.ts
  packages/webdriverio/src/scripts/isFocused.js
  packages/webdriverio/tests/__mocks__/got.js
  packages/webdriverio/tests/commands/element/isFocused.test.js
Labels: PR: Bug Fix :bug:
