Repository webdriverio/webdriverio, pull requests merged in 2020-08, with the labels that each got.

#5678 Update Expect API Docs to add two matchers
  docs/api/expect.md
Labels: PR: Docs :memo:

#5677 Improve Puppeteer integration
  docs/AutomationProtocols.md
  packages/devtools/README.md
  packages/devtools/src/index.js
  packages/devtools/tests/__mocks__/puppeteer-core.js
  packages/wdio-cli/tests/launcher.test.js
  packages/wdio-devtools-service/README.md
  packages/wdio-devtools-service/devtools-service.d.ts
  packages/wdio-devtools-service/package.json
  packages/wdio-devtools-service/src/commands.js
  packages/wdio-devtools-service/src/constants.js
  packages/wdio-devtools-service/src/driver.js
  packages/wdio-devtools-service/src/gatherer/trace.js
  packages/wdio-devtools-service/src/handler/network.js
  packages/wdio-devtools-service/src/index.js
  packages/wdio-devtools-service/src/utils.js
  packages/wdio-devtools-service/tests/commands.test.js
  packages/wdio-devtools-service/tests/driver.test.js
  packages/wdio-devtools-service/tests/gatherer/trace.test.js
  packages/wdio-devtools-service/tests/service.test.js
  packages/wdio-devtools-service/tests/utils.test.js
  packages/wdio-junit-reporter/src/index.js
  packages/wdio-sync/webdriverio-core.d.ts
  packages/wdio-utils/src/monad.js
  packages/webdriverio/src/commands/browser.js
  packages/webdriverio/src/commands/browser/getPuppeteer.js
  packages/webdriverio/src/commands/browser/mock.js
  packages/webdriverio/src/commands/browser/throttle.js
  packages/webdriverio/src/utils/index.js
  packages/webdriverio/tests/__snapshots__/utils.test.js.snap
  packages/webdriverio/tests/commands/browser/__snapshots__/getPuppeteer.test.js.snap
  packages/webdriverio/tests/commands/browser/getPuppeteer.test.js
  packages/webdriverio/tests/utils.test.js
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/devtools.tpl.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/constants.js
  tests/typings/sync-devtools-service/devtools-service.ts
  tests/typings/webdriverio-devtools-service/devtools-service.ts
Labels: PR: Polish :nail_care:

#5688 repaired mocha/multiremote example
  examples/wdio/multiremote/mocha.test.js
  examples/wdio/multiremote/wdio.conf.js
Labels: PR: Bug Fix :bug:

#5638 Update browser.throttle documentation
  packages/webdriverio/src/commands/browser/throttle.js
Labels: PR: Docs :memo:

#5698 TypeDefination fix for selenoid options
  packages/webdriver/webdriver.d.ts
  scripts/templates/webdriver.tpl.d.ts
  tests/typings/webdriverio/config.ts
Labels: PR: Docs :memo:

#5704 docs: typescript package dependency requirement
  docs/TypeScript.md
Labels: PR: Docs :memo:

#5702 Fix data argument must be string in shared-store-service
  packages/wdio-shared-store-service/src/launcher.js
  packages/wdio-shared-store-service/tests/launcher.test.js
Labels: PR: Bug Fix :bug:

#5705 Fix prototypes for items in getElements array.
  packages/webdriverio/src/utils/getElementObject.js
  packages/webdriverio/tests/commands/browser/$$.test.js
Labels: PR: Bug Fix :bug:

#5707 docs: add extension to required ts conf path
  docs/TypeScript.md
Labels: PR: Docs :memo:

#5710 devtools: Fix `ignoreDefaultArgs` capability option
  packages/devtools/src/constants.js
  packages/devtools/src/launcher.js
  packages/devtools/tests/__snapshots__/launcher.test.js.snap
Labels: PR: Polish :nail_care:

#5722 Fix typo in README.md
  packages/wdio-devtools-service/README.md
Labels: PR: Docs :memo:

#5712 fix(cli): backslash replacement on win32
  packages/wdio-cli/src/utils.js
Labels: PR: Bug Fix :bug:

#5709 docs: add import for typed configuration
  docs/TypeScript.md
Labels: PR: Docs :memo:

#5708 docs: folder structure for typescript docs
  docs/TypeScript.md
Labels: PR: Docs :memo:

#5750 @wdio/sauce-service Job Names are not sliced when using Jasmine #5728
  packages/wdio-sauce-service/src/service.js
  packages/wdio-sauce-service/tests/service.test.js
Labels: PR: Polish :nail_care:

#5653 Update expect.md
  docs/api/expect.md
Labels: PR: Docs :memo:

#5733 Make type definition for createWindow more precise
  packages/webdriver/webdriver.d.ts
  scripts/type-generation/devtools-generate-typings.js
  scripts/type-generation/webdriver-generate-typings.js
  scripts/type-generation/webdriver-param-types.json
  tests/typings/devtools/async.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Docs :memo:

#5740 Add wdio-rerun-service entries to Webdriver.IO
  packages/wdio-cli/src/constants.js
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#5753 Document setting download paths with browser.cdp()
  packages/wdio-devtools-service/README.md
Labels: PR: Docs :memo:

#5760 Propagate CDP events to the browser event listener
  packages/wdio-devtools-service/src/index.js
  packages/wdio-devtools-service/tests/service.test.js
Labels: PR: Polish :nail_care:

#5761 Add section on reporting and include OpenJS Foundation excalation path
  CODE_OF_CONDUCT.md
Labels: PR: Internal :house:

#5764 Update documentation for tagExpression usage
  docs/ConfigurationFile.md
  examples/wdio.conf.js
  packages/wdio-cucumber-framework/README.md
Labels: PR: Docs :memo:

#5768 Invalidate stalled elements in ElementStore
  packages/devtools/src/commands/elementClear.js
  packages/devtools/src/commands/elementClick.js
  packages/devtools/src/commands/elementSendKeys.js
  packages/devtools/src/commands/executeAsyncScript.js
  packages/devtools/src/commands/executeScript.js
  packages/devtools/src/commands/findElementFromElement.js
  packages/devtools/src/commands/findElementsFromElement.js
  packages/devtools/src/commands/getElementAttribute.js
  packages/devtools/src/commands/getElementCSSValue.js
  packages/devtools/src/commands/getElementProperty.js
  packages/devtools/src/commands/getElementRect.js
  packages/devtools/src/commands/getElementTagName.js
  packages/devtools/src/commands/getElementText.js
  packages/devtools/src/commands/switchToFrame.js
  packages/devtools/src/commands/takeElementScreenshot.js
  packages/devtools/src/elementstore.js
  packages/devtools/src/utils.js
  packages/devtools/tests/elementStore.test.js
  packages/devtools/tests/utils.test.js
Labels: PR: Bug Fix :bug:, devtools

#5769 Use proper Chrome version in headless mode
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/allureFeatures.test.js
Labels: PR: Bug Fix :bug:, devtools, wdio-allure-reporter

#5772 Add new Sauce Labs Unified Platform endpoint
  packages/wdio-config/src/utils.js
  packages/wdio-config/tests/configparser.test.js
  packages/wdio-config/tests/detectBackend.test.js
  packages/wdio-sauce-service/README.md
Labels: PR: Polish :nail_care:

#5777 Minor updates to dragAndDrop command docs
  packages/webdriverio/src/commands/element/dragAndDrop.js
Labels: PR: Docs :memo:

#5659 docs: Don't have types being linked to their own pages
  scripts/templates/api.tpl.ejs
  website/i18n/en.json
Labels: PR: Docs :memo:
