Repository webdriverio/webdriverio, pull requests merged in 2020-03, with the labels that each got.

#5067 browserstack-service: add typings
  package.json
  packages/wdio-browserstack-service/browserstack-service.d.ts
  packages/wdio-browserstack-service/package.json
  tests/typings/copy.js
  tests/typings/sync-browserstack/browserstack.ts
  tests/typings/sync-browserstack/tsconfig.json
  tests/typings/webdriverio-browserstack/browserstack.ts
  tests/typings/webdriverio-browserstack/tsconfig.json
Labels: PR: Docs :memo:, backport-requested

#5039 Implement `performActions` for devtools automation protocol
  e2e/element.test.js
  packages/devtools/src/commands/performActions.js
  packages/devtools/src/commands/releaseActions.js
  packages/devtools/src/devtoolsdriver.js
  packages/webdriverio/src/commands/browser/keys.js
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/utils.test.js
Labels: PR: New Feature :rocket:, needs-review, v6

#4626 Separate launcher from worker services
  packages/wdio-cli/src/launcher.js
  packages/wdio-config/src/constants.js
  packages/wdio-config/src/lib/ConfigParser.js
  packages/wdio-config/tests/configparser.test.js
  packages/wdio-runner/src/index.js
  packages/wdio-runner/src/reporter.js
  packages/wdio-runner/tests/index.test.js
  packages/wdio-utils/src/index.js
  packages/wdio-utils/src/initialisePlugin.js
  packages/wdio-utils/src/initialiseServices.js
  packages/wdio-utils/tests/__mocks__/@wdio/utils.js
  packages/wdio-utils/tests/initialisePlugin.test.js
  packages/wdio-utils/tests/initialiseServices.test.js
Labels: PR: Polish :nail_care:, needs-review, v6

#5007 Use "devtools" automation protocol as fallback
  .travis.yml
  e2e/.eslintrc
  e2e/jest.config.js
  e2e/jest.setup.js
  e2e/testrunner.test.js
  e2e/wdio/secondTest.e2e.js
  e2e/wdio/test.e2e.js
  e2e/wdio/wdio.conf.js
  package-lock.json
  package.json
  packages/devtools/package.json
  packages/devtools/src/constants.js
  packages/devtools/src/devtoolsdriver.js
  packages/devtools/src/finder/edge.js
  packages/devtools/src/finder/firefox.js
  packages/devtools/src/index.js
  packages/devtools/src/launcher.js
  packages/devtools/src/utils.js
  packages/devtools/tests/__mocks__/puppeteer-core.js
  packages/devtools/tests/__mocks__/puppeteer-firefox.js
  packages/devtools/tests/__snapshots__/launcher.test.js.snap
  packages/devtools/tests/launcher.test.js
  packages/devtools/tests/utils.test.js
  packages/wdio-appium-service/src/index.js
  packages/wdio-browserstack-service/src/index.js
  packages/wdio-config/src/constants.js
  packages/wdio-crossbrowsertesting-service/src/index.js
  packages/wdio-firefox-profile-service/src/index.js
  packages/wdio-logger/src/index.js
  packages/wdio-logger/src/web.js
  packages/wdio-selenium-standalone-service/src/index.js
  packages/wdio-static-server-service/src/index.js
  packages/wdio-testingbot-service/src/index.js
  packages/wdio-utils/src/index.js
  packages/wdio-webdriver-mock-service/src/index.js
  packages/webdriverio/package.json
  packages/webdriverio/src/constants.js
  packages/webdriverio/src/index.js
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/commands/element/waitForClickable.test.js
  packages/webdriverio/tests/module.test.js
  packages/webdriverio/tests/utils.test.js
  scripts/constants.js
  tests/mocha/standalone.js
Labels: PR: Breaking Change :boom:, needs-review

#4929 Updating LTS docs
  docs/Versions.md
  scripts/updateDocs.js
  website/i18n/en.json
  website/siteConfig.js
Labels: PR: Docs :memo:, backport-requested, v6

#5078 docs: add reference to boilerplate
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:, backport-requested

#5080 Fix docs for TS setup with Mocha
  docs/TypeScript.md
Labels: PR: Docs :memo:, backport-requested

#5076 feature(cucumber-framework): add skip tags support
  docs/Frameworks.md
  packages/wdio-cucumber-framework/src/index.js
  packages/wdio-cucumber-framework/tests/adapter.test.js
  tests/cucumber/step-definitions/then.js
  tests/cucumber/test.feature
Labels: PR: New Feature :rocket:, backport-requested

#5084 Update GettingStarted.md
  docs/GettingStarted.md
Labels: PR: Docs :memo:, backport-requested

#5064 Fix selector typing
  packages/wdio-sync/webdriverio-core.d.ts
  packages/wdio-sync/webdriverio.d.ts
  packages/webdriverio/src/commands/element/$$.js
  packages/webdriverio/src/commands/element/$.js
  packages/webdriverio/webdriverio-core.d.ts
  packages/webdriverio/webdriverio.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/constants.js
Labels: PR: Docs :memo:, backport-requested

#5089 webdriverIO - Experitest Cli - Simplify the flow
  packages/wdio-cli/src/constants.js
Labels: PR: Polish :nail_care:, backport-requested

#5091 Fix v5 tests for browserstack typings
  .eslintignore
  package.json
  packages/wdio-browserstack-service/browserstack-service.d.ts
  tests/typings/sync-applitools/applitools.ts
  tests/typings/sync-browserstack/browserstack.ts
  tests/typings/webdriverio-applitools/applitools.ts
  tests/typings/webdriverio-browserstack/browserstack.ts
Labels: PR: Docs :memo:

#5062 webdriver: Add interceptors for HTTP requests and responses [v5]
  docs/Options.md
  packages/webdriver/README.md
  packages/webdriver/package.json
  packages/webdriver/src/constants.js
  packages/webdriver/src/request.js
  packages/webdriver/tests/constants.test.js
  packages/webdriver/tests/request.test.js
  packages/webdriver/webdriver.d.ts
  scripts/templates/webdriver.tpl.d.ts
  tests/typings/copy.js
  tests/typings/sync/config.ts
Labels: PR: New Feature :rocket:

#5097 wdio-lambdatest-service: Updated docs for New service Lambdatest #5057
  README.md
  docs/CLI.md
  docs/CloudServices.md
  docs/ConfigurationFile.md
  docs/Options.md
  docs/flowcharts/HighLevelOverview.md
  packages/wdio-cli/src/constants.js
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:, backport-requested

#5099 Allure: add issue and tms links patterns
  packages/wdio-allure-reporter/README.md
  packages/wdio-allure-reporter/src/constants.js
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/src/utils.js
  packages/wdio-allure-reporter/tests/allureFeatures.test.js
  packages/wdio-allure-reporter/tests/utils.test.js
Labels: PR: New Feature :rocket:, backport-requested

#5100 checkUnicode should always return an array regardless of isDevTools
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#5101 TypeScript improvements
  .eslintignore
  docs/Options.md
  examples/wdio.conf.js
  package.json
  packages/wdio-applitools-service/applitools-service.d.ts
  packages/wdio-browserstack-service/README.md
  packages/wdio-browserstack-service/browserstack-service.d.ts
  packages/wdio-browserstack-service/src/launcher.js
  packages/wdio-browserstack-service/tests/launcher.test.js
  packages/wdio-sauce-service/package.json
  packages/wdio-sauce-service/sauce-service.d.ts
  packages/wdio-selenium-standalone-service/selenium-standalone-service.d.ts
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriver/README.md
  packages/webdriver/webdriver.d.ts
  packages/webdriverio/src/commands/browser/getCookies.js
  packages/webdriverio/src/commands/browser/setCookies.js
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriver.tpl.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/constants.js
  scripts/type-generation/webdriver-return-types.json
  tests/typings/copy.js
  tests/typings/sync-applitools/applitools.ts
  tests/typings/sync-browserstack/browserstack.ts
  tests/typings/sync-cucumber/cucumber.ts
  tests/typings/sync-saucelabs/saucelabs.ts
  tests/typings/sync-saucelabs/tsconfig.json
  tests/typings/sync/config.ts
  tests/typings/sync/sync.ts
  tests/typings/webdriverio-applitools/applitools.ts
  tests/typings/webdriverio-browserstack/browserstack.ts
  tests/typings/webdriverio-saucelabs/saucelabs.ts
  tests/typings/webdriverio-saucelabs/tsconfig.json
  tests/typings/webdriverio/async.ts
  tests/typings/webdriverio/config.ts
  website/blog/2020-02-22-webdriverio-v6-released.md
  website/static/img/puppeteer-example.png
Labels: PR: Breaking Change :boom:

#5106 fix(browserstack, sauce): update test title
  packages/wdio-browserstack-service/src/service.js
  packages/wdio-browserstack-service/tests/service.test.js
  packages/wdio-sauce-service/src/service.js
  packages/wdio-sauce-service/tests/service.test.js
Labels: PR: Bug Fix :bug:, backport-requested

#5108 fix the edit button on protocol docs again
  scripts/docs-generation/protocolDocs.js
Labels: PR: Bug Fix :bug:, backport-requested

#5093 Propagate connection data to detect backend properly
  packages/wdio-cli/src/interface.js
  packages/wdio-cli/tests/interface.test.js
  packages/wdio-config/src/utils.js
  packages/wdio-config/tests/configparser.test.js
  packages/wdio-config/tests/detectBackend.test.js
  packages/wdio-config/tests/validateConfig.test.js
  packages/wdio-spec-reporter/src/index.js
  packages/webdriverio/src/index.js
  packages/webdriverio/tests/module.test.js
Labels: PR: Bug Fix :bug:

#5109 update switchToFrame docs
  packages/wdio-protocols/protocols/webdriver.json
Labels: PR: Bug Fix :bug:, backport-requested

#5123 Add support for .cjs files
  packages/wdio-config/src/constants.js
  packages/wdio-config/src/lib/ConfigParser.js
  packages/wdio-config/tests/__fixtures__/test.cjs
  packages/wdio-config/tests/configparser.test.js
Labels: PR: Bug Fix :bug:, backport-requested

#5125 Don't incentivise user to ask for help on GitHub
  .github/ISSUE_TEMPLATE/--bug-report.md
  .github/ISSUE_TEMPLATE/--documentation.md
  .github/ISSUE_TEMPLATE/--feature-request.md
  .github/ISSUE_TEMPLATE/--question.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SUPPORT.md
Labels: PR: Docs :memo:

#4930 overwrite capabilities in config parser
  packages/wdio-config/src/lib/ConfigParser.js
  packages/wdio-config/src/utils.js
  packages/wdio-config/tests/configparser.test.js
  packages/wdio-config/tests/utils.test.js
  website/blog/2020-02-22-webdriverio-v6-released.md
Labels: PR: Breaking Change :boom:, v6

#5137 added write method to typings
  packages/wdio-reporter/reporter.d.ts
Labels: PR: Docs :memo:, backport-requested

#5138 Some more documentation improvements
  CONTRIBUTING.md
  docs/GettingStarted.md
  packages/wdio-sync/README.md
  website/pages/en/index.js
Labels: PR: Docs :memo:

#5142 docs: fix spellings and grammar
  docs/Assertion.md
  docs/AutomationProtocols.md
  docs/BoilerplateProjects.md
  docs/CLI.md
  docs/ConfigurationFile.md
  docs/Contribute.md
  docs/CustomReporter.md
  docs/Frameworks.md
  docs/Options.md
  docs/OrganizingTestSuites.md
  docs/Selectors.md
  docs/TypeScript.md
  docs/Versions.md
Labels: PR: Docs :memo:, backport-requested

#5143 Enable spec filtering as default functionality
  packages/wdio-config/src/constants.js
  packages/wdio-cucumber-framework/src/index.js
  packages/wdio-cucumber-framework/tests/adapter.test.js
  packages/wdio-jasmine-framework/src/index.js
  packages/wdio-jasmine-framework/tests/adapter.test.js
  packages/wdio-mocha-framework/src/index.js
  packages/wdio-mocha-framework/tests/adapter.test.js
  packages/wdio-runner/src/index.js
  packages/wdio-runner/tests/index.test.js
  packages/wdio-sauce-service/tests/service.test.js
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/tests/__mocks__/got.js
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  tests/smoke.runner.js
  website/blog/2020-02-22-webdriverio-v6-released.md
Labels: PR: Breaking Change :boom:

#5145 Forward service defined path (driver server endpoint) for Selenium server.
  packages/wdio-cli/src/launcher.js
Labels: PR: Polish :nail_care:

#5159 Add dependency check to test pipeline
  CONTRIBUTING.md
  package-lock.json
  package.json
  packages/devtools/src/commands/status.js
  packages/wdio-crossbrowsertesting-service/package.json
  packages/wdio-utils/src/shim.js
  scripts/depcheck.js
Labels: PR: Internal :house:

#5160 Fix typings for got and its tests
  packages/wdio-browserstack-service/package.json
  packages/wdio-sumologic-reporter/package.json
  packages/wdio-testingbot-service/package.json
  packages/webdriver/package.json
  packages/webdriver/webdriver.d.ts
  scripts/templates/webdriver.tpl.d.ts
  tests/typings/copy.js
  tests/typings/sync/config.ts
Labels: PR: Bug Fix :bug:

#5166 Fix usage of uuid package
  package.json
  packages/devtools/src/commands/closeWindow.js
  packages/devtools/src/commands/createWindow.js
  packages/devtools/src/commands/getWindowHandles.js
  packages/devtools/src/commands/newSession.js
  packages/devtools/src/devtoolsdriver.js
  packages/devtools/src/index.js
Labels: PR: Bug Fix :bug:

#5168 Allow API descriptions
  scripts/constants.js
  scripts/docs-generation/protocolDocs.js
  scripts/updateDocs.js
Labels: PR: Docs :memo:

#5173 Set connection details in selenium-standalone properly
  packages/wdio-config/src/lib/ConfigParser.js
  packages/wdio-selenium-standalone-service/README.md
  packages/wdio-selenium-standalone-service/src/launcher.js
  packages/wdio-selenium-standalone-service/tests/launcher.test.js
Labels: PR: Bug Fix :bug:

#5175 v6 release bug fixes
  docs/Babel.md
  packages/devtools/src/constants.js
  packages/devtools/src/index.js
  packages/devtools/src/utils.js
  packages/devtools/tests/__mocks__/pptrDebug.js
  packages/devtools/tests/utils.test.js
  packages/wdio-crossbrowsertesting-service/src/service.js
  packages/wdio-crossbrowsertesting-service/tests/service.test.js
  packages/wdio-sauce-service/src/service.js
  packages/wdio-sauce-service/tests/service.test.js
  packages/wdio-testingbot-service/src/service.js
  packages/wdio-testingbot-service/tests/service.test.js
Labels: PR: Bug Fix :bug:

#5182 Fix `onReload` bug
  packages/wdio-webdriver-mock-service/package.json
  packages/wdio-webdriver-mock-service/src/WebDriverMock.js
  packages/wdio-webdriver-mock-service/src/constants.js
  packages/wdio-webdriver-mock-service/src/index.js
  packages/webdriverio/src/index.js
  tests/mocha/test.js
Labels: PR: Bug Fix :bug:
