Repository webdriverio/webdriverio, pull requests merged in 2020-09, with the labels that each got.

#5783 [#5541] dragAndDrop to sleep for given duration in JsonWireProtocol
  packages/webdriverio/src/commands/element/dragAndDrop.js
  packages/webdriverio/tests/commands/element/__snapshots__/dragAndDrop.test.js.snap
  packages/webdriverio/tests/commands/element/dragAndDrop.test.js
Labels: PR: Polish :nail_care:

#5787 [DOCUMENTATION] Nested shadow roots plugin
  packages/webdriverio/src/commands/element/shadow$$.js
  packages/webdriverio/src/commands/element/shadow$.js
Labels: PR: Docs :memo:

#5771 Fix #5647 : add other check for app capability in browserstack-service
  packages/wdio-browserstack-service/src/service.js
  packages/wdio-browserstack-service/tests/service.test.js
Labels: PR: Bug Fix :bug:

#5792 Fix wdio-devtools-service README
  packages/wdio-devtools-service/README.md
Labels: PR: Docs :memo:

#5800 Fixed broken links for browser.call page
  docs/Frameworks.md
  docs/SyncVsAsync.md
Labels: PR: Docs :memo:

#5799 addCommand and overwriteCommand types
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Docs :memo:

#5806 Check array input parameter using Array.isArray
  packages/webdriverio/src/commands/browser/keys.js
Labels: PR: Bug Fix :bug:

#5774 Add names of mentors will to give 1:1 help to "help" page
  website/pages/en/help.js
Labels: PR: Docs :memo:

#5805 Fix Unified Platform and Sauce Connect bug
  packages/wdio-sauce-service/src/utils.js
  packages/wdio-sauce-service/tests/launcher.test.js
Labels: PR: Bug Fix :bug:

#5808 Update cucumber boilerplate to webdriverio v6
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#5809 Support ESM specs with Mocha
  packages/wdio-mocha-framework/src/index.js
  packages/wdio-mocha-framework/tests/__mocks__/mocha.js
  packages/wdio-mocha-framework/tests/adapter.test.js
Labels: PR: Bug Fix :bug:

#5794 Add script to push release tag
  package.json
  scripts/pushTags.js
Labels: PR: Internal :house:

#5814 Update BoilerplateProjects.md
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#5820 Fix network mock headers filter
  packages/webdriverio/src/utils/interception/devtools.js
  packages/webdriverio/tests/utils/interception/devtools.test.js
Labels: PR: Bug Fix :bug:

#5818 generate expect-webdriverio api doc
  .gitignore
  docs/Assertion.md
  docs/api/expect.md
  scripts/docs-generation/3rd-party/api.json
  scripts/docs-generation/3rdPartyDocs.js
  website/_sidebars.json
  website/i18n/en.json
  website/package-lock.json
  website/package.json
Labels: PR: Docs :memo:

#5819 Add optional delay between spec file retry attempts
  docs/ConfigurationFile.md
  docs/Options.md
  docs/Retry.md
  examples/wdio.conf.js
  packages/wdio-cli/src/interface.js
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/tests/interface.test.js
  packages/wdio-cli/tests/launcher.test.js
  packages/wdio-sync/webdriverio-core.d.ts
  packages/wdio-utils/src/index.js
  packages/wdio-utils/src/utils.js
  packages/wdio-utils/tests/__mocks__/@wdio/utils.js
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  tests/smoke.runner.js
Labels: PR: New Feature :rocket:

#5803 adding dialog handler to switchwindow so that we can handle alerts
  packages/devtools/src/commands/switchToWindow.js
Labels: PR: Bug Fix :bug:

#5790 log warning if jasmine tests have no root describe
  packages/wdio-jasmine-framework/src/reporter.js
  packages/wdio-jasmine-framework/tests/reporter.test.js
  tests/helpers/fixtures.js
Labels: PR: Polish :nail_care:

#5821 Filter postData, responseHeaders, statusCode
  packages/wdio-shared-store-service/shared-store-service.d.ts
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/src/commands/browser/mock.js
  packages/webdriverio/src/utils/interception/devtools.js
  packages/webdriverio/tests/utils/interception/devtools.test.js
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: New Feature :rocket:

#5823 scripts: ensure api doc dir
  scripts/docs-generation/protocolDocs.js
Labels: PR: Bug Fix :bug:

#5812 Fix missing mocha test hooks in a junit report
  packages/wdio-junit-reporter/src/index.js
  packages/wdio-junit-reporter/tests/__fixtures__/suites-with-failed-after-each-hook.json
  packages/wdio-junit-reporter/tests/__fixtures__/suites-with-failed-before-each-hook.json.json
  packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.js.snap
  packages/wdio-junit-reporter/tests/reporter.test.js
Labels: PR: Bug Fix :bug:

#5856 Update BoilerplateProjects.md
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#5858 Fix unbound commands in devtools-service
  packages/wdio-devtools-service/src/commands.js
Labels: PR: Bug Fix :bug:

#5857 Prepend hash only for h1 in 3rd party docs
  scripts/docs-generation/3rdPartyDocs.js
Labels: PR: Docs :memo:

#5870 Fixes the issue On V6, for android tests, where the incorrect deviceName is displayed in allure reports
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/allureFeatures.test.js
Labels: PR: Bug Fix :bug:

#5868 Add docs on how to deploy and run our docs page
  CONTRIBUTING.md
Labels: PR: Docs :memo:

#5871 Added Bamboo Documentation
  docs/BambooIntegration.md
  website/_sidebars.json
  website/i18n/en.json
  website/static/img/bamboo/defaultstage.png
  website/static/img/bamboo/failedandfixed.png
  website/static/img/bamboo/failedtest.png
  website/static/img/bamboo/junitparser.png
  website/static/img/bamboo/plancreation.png
  website/static/img/bamboo/successfulltest.png
  website/static/img/bamboo/testrun.png
Labels: PR: Docs :memo:

#5872 Assign w3c identifier to element scope after element re-found
  packages/webdriverio/src/middlewares.js
  packages/webdriverio/tests/commands/element/$.test.js
  packages/webdriverio/tests/middleware.test.js
Labels: PR: Bug Fix :bug:

#5879 Disable password manager prompt by default in devtools
  packages/devtools/src/constants.js
  packages/devtools/tests/__snapshots__/launcher.test.js.snap
Labels: PR: Polish :nail_care:, devtools

#5873 Adds mocha test retry hook to reporter
  examples/wdio/custom-reporter/reporter/my.custom.reporter.js
  packages/wdio-mocha-framework/src/constants.js
  packages/wdio-mocha-framework/src/index.js
  packages/wdio-reporter/README.md
  packages/wdio-reporter/src/index.js
  packages/wdio-reporter/src/stats/test.js
  packages/wdio-reporter/tests/reporter.listeners.test.js
  packages/wdio-reporter/tests/reporter.test.js
Labels: PR: Polish :nail_care:

#5886 fix devtools tracing for click transitions
  packages/wdio-devtools-service/src/constants.js
  packages/wdio-devtools-service/src/gatherer/trace.js
  packages/wdio-devtools-service/src/index.js
  packages/wdio-devtools-service/tests/gatherer/trace.test.js
Labels: PR: Bug Fix :bug:

#5891 Add documentation to overwrite and add commands
  packages/webdriverio/src/commands/browser/addCommand.js
  packages/webdriverio/src/commands/browser/overwriteCommand.js
  packages/webdriverio/tests/commands/browser.test.js
  website/i18n/en.json
Labels: PR: Docs :memo:

#5892 Update Mocha boilerplate to wdio v6
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#5888 Rewrite type generation script for `webdriver` package
  aa
  packages/webdriver/src/index.ts
  packages/webdriver/src/types.ts
  scripts/templates/webdriver.tpl.d.ts
  scripts/type-generation/webdriver-generate-typings.js
Labels: TypeScript

#5902 Update PageObjects.md
  docs/PageObjects.md
Labels: PR: Docs :memo:

#5903 Fix double click
  packages/webdriverio/src/commands/element/doubleClick.js
  scripts/type-generation/webdriverio-generate-typings.js
Labels: PR: Bug Fix :bug:
