Repository webdriverio/webdriverio, pull requests merged in 2020-05, with the labels that each got.

#5349 Add hint for modifiyng clicks
  packages/webdriverio/src/commands/browser/keys.js
Labels: PR: Docs :memo:

#5347 @devtools: Enable file uploads by changing input elements' value
  e2e/element.test.js
  packages/devtools/src/commands/elementSendKeys.js
Labels: PR: Bug Fix :bug:

#5344 ignore defaultChromeFlags / PptrDefaultArgs tags
  docs/ConfigurationFile.md
  packages/devtools/src/launcher.js
  packages/devtools/tests/__snapshots__/launcher.test.js.snap
  packages/devtools/tests/launcher.test.js
Labels: PR: Polish :nail_care:

#5360 Move docs deployment to GitHub workflow
  .editorconfig
  .github/workflows/deploy.yml
  .gitignore
  .travis.yml
  package-lock.json
  package.json
  scripts/updateDocs.js
  website/package.json
  website/static/styles/_components/_headings.scss
  website/static/styles/_utils/_reset.scss
  website/static/styles/index.scss
Labels: PR: Internal :house:

#5351 Make `requestedCapabilities` better accessible
  docs/BrowserObject.md
  packages/devtools/src/index.js
  packages/devtools/tests/__snapshots__/devtools.test.js.snap
  packages/wdio-sync/webdriverio-core.d.ts
  packages/wdio-utils/src/envDetector.js
  packages/wdio-utils/src/monad.js
  packages/wdio-utils/tests/envDetector.test.js
  packages/webdriver/src/index.js
  packages/webdriver/src/utils.js
  packages/webdriver/tests/index.test.js
  packages/webdriver/tests/utils.test.js
  packages/webdriver/webdriver.d.ts
  packages/webdriverio/tests/commands/browser/reloadSession.test.js
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriver.tpl.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/webdriver-generate-typings.js
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Polish :nail_care:

#5361 Add types for devtools service
  package.json
  packages/wdio-devtools-service/devtools-service.d.ts
  packages/wdio-devtools-service/package.json
  tests/typings/copy.js
  tests/typings/sync-devtools-service/devtools-service.ts
  tests/typings/sync-devtools-service/tsconfig.json
  tests/typings/webdriverio-devtools-service/devtools-service.ts
  tests/typings/webdriverio-devtools-service/tsconfig.json
Labels: PR: Polish :nail_care:

#5365 Fix types of reporters runner hooks
  packages/wdio-reporter/reporter.d.ts
  tests/typings/webdriverio-reporter/reporter.ts
Labels: PR: Docs :memo:

#5369 devtools: fix import of devices
  packages/devtools/src/launcher.js
Labels: PR: Bug Fix :bug:

#5350 devtools package: fix switchToFrame function
  e2e/protocol.test.js
  packages/devtools/src/commands/switchToFrame.js
Labels: PR: Bug Fix :bug:

#5271 Rework Browserstack service, improve Cucumber integration
  packages/wdio-browserstack-service/README.md
  packages/wdio-browserstack-service/browserstack-service.d.ts
  packages/wdio-browserstack-service/src/service.js
  packages/wdio-browserstack-service/tests/service.test.js
Labels: PR: Polish :nail_care:

#5375 Add docs to Tidelift subscription
  docs/Enterprise.md
  packages/wdio-devtools-service/tests/gatherer/trace.test.js
  website/core/Footer.js
  website/i18n/en.json
  website/package.json
  website/static/styles/_components/_content.scss
  website/static/styles/_modules/_nav.scss
  website/static/styles/index.scss
Labels: PR: Docs :memo:

#5377 wdio-protocolse: add api for appium image comparison features (#5372)
  packages/wdio-protocols/protocols/appium.json
Labels: PR: Spec Compliancy :eyeglasses:

#5391 Update README.md of wdio-allure-reporter
  packages/wdio-allure-reporter/README.md
Labels: PR: Docs :memo:

#5397 Update typescript configuration for jasmine
  docs/TypeScript.md
Labels: PR: Docs :memo:

#5402 Fix class syntax in CustomServices.md
  docs/CustomServices.md
Labels: PR: Docs :memo:

#5390 Fix browser version in spec reporter
  packages/wdio-spec-reporter/src/index.js
  packages/wdio-spec-reporter/tests/__snapshots__/index.test.js.snap
  packages/wdio-spec-reporter/tests/index.test.js
Labels: PR: Polish :nail_care:

#5420 add new boilerplate project
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#5421 Added subrountine shapes where applicable
  docs/flowcharts/CreateLocalWorkerProcess.md
  docs/flowcharts/HighLevelOverview.md
  docs/flowcharts/TestExecution.md
  docs/flowcharts/WDIOCommands.md
Labels: PR: Docs :memo:

#5417 Update SauceLabs package and remove sauce-connect-launcher
  packages/wdio-sauce-service/README.md
  packages/wdio-sauce-service/package.json
  packages/wdio-sauce-service/src/launcher.js
  packages/wdio-sauce-service/tests/__mocks__/sauce-connect-launcher-update.js
  packages/wdio-sauce-service/tests/launcher.test.js
Labels: PR: Polish :nail_care:

#5422 update cucumber version in readme
  packages/wdio-cucumber-framework/README.md
Labels: PR: Docs :memo:

#5431 Promote that WebdriverIO supports modern web frameworks
  website/package.json
  website/pages/en/index.js
  website/static/img/icons/angular.svg
  website/static/img/icons/polymer.svg
  website/static/img/icons/vue.png
  website/static/img/react-support.png
  website/static/styles/_components/_content.scss
  website/static/styles/_modules/_nav.scss
Labels: PR: Docs :memo:

#5435 Improve Mocha timeout message
  packages/wdio-jasmine-framework/src/index.js
  packages/wdio-mocha-framework/src/constants.js
  packages/wdio-mocha-framework/src/index.js
  packages/wdio-mocha-framework/tests/__snapshots__/adapter.test.js.snap
  packages/wdio-mocha-framework/tests/adapter.test.js
  packages/wdio-reporter/src/constants.js
  packages/wdio-reporter/src/index.js
Labels: PR: Bug Fix :bug:

#5438 Setup Babel and TypeScript if config files are found
  packages/wdio-cli/src/commands/config.js
  packages/wdio-cli/src/constants.js
  packages/wdio-cli/src/templates/reporters.ejs
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/utils.js
  packages/wdio-cli/tests/commands/__snapshots__/config.test.js.snap
  packages/wdio-cli/tests/commands/config.test.js
  packages/wdio-cli/tests/utils.test.js
Labels: PR: Polish :nail_care:

#5437 Add typing definition for last missing service options
  package-lock.json
  packages/wdio-appium-service/README.md
  packages/wdio-appium-service/appium-service.d.ts
  packages/wdio-appium-service/package.json
  packages/wdio-cli/src/commands/config.js
  packages/wdio-cli/src/constants.js
  packages/wdio-cli/src/templates/reporters.ejs
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/utils.js
  packages/wdio-cli/tests/commands/__snapshots__/config.test.js.snap
  packages/wdio-cli/tests/commands/config.test.js
  packages/wdio-cli/tests/utils.test.js
  packages/wdio-crossbrowsertesting-service/crossbrowsertesting-service.d.ts
  packages/wdio-crossbrowsertesting-service/package.json
  packages/wdio-firefox-profile-service/firefox-profile-service.d.ts
  packages/wdio-firefox-profile-service/package.json
  packages/wdio-static-server-service/package.json
  packages/wdio-static-server-service/static-server-service.d.ts
  packages/wdio-sync/webdriverio-core.d.ts
  packages/wdio-testingbot-service/package.json
  packages/wdio-testingbot-service/testingbot-service.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  tests/typings/copy.js
  tests/typings/sync/config.ts
  tests/typings/sync/tsconfig.json
  tests/typings/webdriverio/config.ts
  tests/typings/webdriverio/tsconfig.json
Labels: PR: Docs :memo:

#5440 adding missing await for printSessionURL for onReload in browserstack service
  packages/wdio-browserstack-service/src/service.js
Labels: PR: Bug Fix :bug:

#5443 Couldn't find plugin "" runner
  packages/wdio-cli/src/commands/config.js
Labels: PR: Bug Fix :bug:

#5442 Add support for Android viewtag selector
  docs/Selectors.md
  packages/webdriverio/src/utils/findStrategy.js
  packages/webdriverio/tests/findStrategy.test.js
Labels: PR: Polish :nail_care:
