Repository webdriverio/webdriverio, pull requests merged in 2020-07, with the labels that each got.

#5526 fixing wrong variable call in error of devtools' cdp
  packages/wdio-devtools-service/src/commands.js
  packages/wdio-devtools-service/tests/commands.test.js
Labels: PR: Bug Fix :bug:

#5544 Fix command reporting in reporters
  packages/wdio-reporter/src/index.js
  packages/wdio-reporter/tests/reporter.test.js
Labels: PR: Bug Fix :bug:

#5543 Better support for Allure reporter using DevTools protocol
  packages/devtools/src/devtoolsdriver.js
  packages/devtools/tests/__snapshots__/devtoolsdriver.test.js.snap
  packages/wdio-allure-reporter/README.md
  packages/wdio-allure-reporter/src/index.js
  packages/wdio-allure-reporter/tests/__fixtures__/command.js
  packages/wdio-allure-reporter/tests/allureFeatures.test.js
  packages/wdio-allure-reporter/tests/suite.test.js
Labels: PR: Bug Fix :bug:

#5562 Add blog post for open office hours
  website/blog/2020-07-01-office-hours.md
Labels: PR: Docs :memo:

#5565 Enable Ability to Stop Execution when Error Occurs in Service Hook
  .nvmrc
  docs/CustomServices.md
  packages/wdio-cli/src/utils.js
  packages/wdio-cli/tests/launcher.test.js
  packages/wdio-cli/tests/utils.test.js
  packages/webdriverio/src/index.js
  packages/webdriverio/src/utils/SevereServiceError.js
  packages/webdriverio/tests/__mocks__/webdriverio.js
  packages/webdriverio/tests/index.test.js
  packages/webdriverio/tests/utils/SevereServiceError.test.js
Labels: PR: New Feature :rocket:

#5564 Add missing typescript typings for getPuppeteer command
  packages/wdio-devtools-service/devtools-service.d.ts
  tests/typings/sync-devtools-service/devtools-service.ts
  tests/typings/webdriverio-devtools-service/devtools-service.ts
Labels: PR: Docs :memo:

#5570 Added Novus Visual Regression Service
  packages/wdio-cli/src/constants.js
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Polish :nail_care:

#5574 Add workshop video to contribute page
  docs/Contribute.md
Labels: PR: Docs :memo:

#5540 Better package names for Cucumber Junit reports
  packages/wdio-junit-reporter/src/index.js
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner-browserstack-android.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner-browserstack-ios.json
  packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.js.snap
  packages/wdio-junit-reporter/tests/reporter.test.js
Labels: PR: Polish :nail_care:

#5573 Added Documentation to devtools command
  packages/devtools/src/commands/acceptAlert.js
  packages/devtools/src/commands/addCookie.js
  packages/devtools/src/commands/back.js
  packages/devtools/src/commands/closeWindow.js
  packages/devtools/src/commands/createWindow.js
  packages/devtools/src/commands/deleteAllCookies.js
  packages/devtools/src/commands/deleteCookie.js
  packages/devtools/src/commands/deleteSession.js
  packages/devtools/src/commands/dismissAlert.js
  packages/devtools/src/commands/elementClear.js
  packages/devtools/src/commands/elementClick.js
  packages/devtools/src/commands/elementSendKeys.js
  packages/devtools/src/commands/executeAsyncScript.js
  packages/devtools/src/commands/executeScript.js
  packages/devtools/src/commands/findElement.js
  packages/devtools/src/commands/findElementFromElement.js
  packages/devtools/src/commands/findElements.js
  packages/devtools/src/commands/findElementsFromElement.js
  packages/devtools/src/commands/forward.js
  packages/devtools/src/commands/getActiveElement.js
  packages/devtools/src/commands/getAlertText.js
  packages/devtools/src/commands/getAllCookies.js
  packages/devtools/src/commands/getElementAttribute.js
  packages/devtools/src/commands/getElementCSSValue.js
  packages/devtools/src/commands/getElementProperty.js
  packages/devtools/src/commands/getElementRect.js
  packages/devtools/src/commands/getElementTagName.js
  packages/devtools/src/commands/getElementText.js
  packages/devtools/src/commands/getNamedCookie.js
  packages/devtools/src/commands/getPageSource.js
  packages/devtools/src/commands/getTimeouts.js
  packages/devtools/src/commands/getTitle.js
  packages/devtools/src/commands/getUrl.js
  packages/devtools/src/commands/getWindowHandle.js
  packages/devtools/src/commands/getWindowHandles.js
  packages/devtools/src/commands/getWindowRect.js
  packages/devtools/src/commands/isElementEnabled.js
  packages/devtools/src/commands/isElementSelected.js
  packages/devtools/src/commands/navigateTo.js
  packages/devtools/src/commands/newSession.js
  packages/devtools/src/commands/performActions.js
  packages/devtools/src/commands/refresh.js
  packages/devtools/src/commands/releaseActions.js
  packages/devtools/src/commands/sendAlertText.js
  packages/devtools/src/commands/setTimeouts.js
  packages/devtools/src/commands/setWindowRect.js
  packages/devtools/src/commands/status.js
  packages/devtools/src/commands/switchToFrame.js
  packages/devtools/src/commands/switchToParentFrame.js
  packages/devtools/src/commands/switchToWindow.js
  packages/devtools/src/commands/takeElementScreenshot.js
  packages/devtools/src/commands/takeScreenshot.js
  packages/wdio-protocols/protocols/webdriver.json
Labels: PR: Docs :memo:

#5572 Fix #5568
  packages/webdriverio/src/commands/element/moveTo.js
  packages/webdriverio/tests/commands/element/moveTo.test.js
Labels: PR: Bug Fix :bug:

#5592 webdriverio-mocha: add ui type mocha ts in mochaOpts
  packages/wdio-mocha-framework/mocha-framework.d.ts
  tests/typings/webdriverio-mocha/mocha.ts
Labels: PR: Bug Fix :bug:, TypeScript, wdio-mocha-framework

#5583 Update docs for Applitools
  packages/wdio-applitools-service/README.md
Labels: PR: Docs :memo:

#5598 doc: fix incorrect links in docs
  docs/SetupTypes.md
  docs/SyncVsAsync.md
  docs/repl.md
  packages/wdio-sync/README.md
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/src/commands/browser/uploadFile.js
  packages/webdriverio/webdriverio-core.d.ts
  tests/mocha/test.js
Labels: PR: Docs :memo:

#5599 Have `remote` and `multiremote` return a promise
  packages/webdriverio/webdriverio.d.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Bug Fix :bug:

#5590 Implement autogeneration of test files
  package-lock.json
  package.json
  packages/wdio-cli/package.json
  packages/wdio-cli/src/commands/config.js
  packages/wdio-cli/src/commands/install.js
  packages/wdio-cli/src/constants.js
  packages/wdio-cli/src/templates/exampleFiles/cucumber/features/login.feature
  packages/wdio-cli/src/templates/exampleFiles/cucumber/step_definitions/steps.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/mochaJasmine/example.e2e.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/pageobjects/login.page.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/pageobjects/page.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/pageobjects/secure.page.js.ejs
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/utils.js
  packages/wdio-cli/tests/__mocks__/ejs.js
  packages/wdio-cli/tests/__mocks__/recursive-readdir.js
  packages/wdio-cli/tests/commands/__snapshots__/config.test.js.snap
  packages/wdio-cli/tests/commands/config.test.js
  packages/wdio-cli/tests/commands/install.test.js
  packages/wdio-cli/tests/config.test.js
  packages/wdio-cli/tests/utils.test.js
  packages/wdio-utils/tests/utils.test.js
Labels: PR: New Feature :rocket:

#5617 feat: update Sauce Unified Platform (RDC on Sauce) with the JS-executor
  packages/wdio-sauce-service/src/service.js
  packages/wdio-sauce-service/src/utils.js
  packages/wdio-sauce-service/tests/service.test.js
  packages/wdio-sauce-service/tests/utils.spec.js
Labels: PR: Polish :nail_care:

#5618 Remove extra space introduced by prior PR https://github.com/webdriverio/webdriverio/pull/5483
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
Labels: PR: Polish :nail_care:

#5610 Fix issue #5585
  packages/wdio-sauce-service/package.json
  packages/wdio-sauce-service/src/launcher.js
  packages/wdio-sauce-service/src/utils.js
  packages/wdio-sauce-service/tests/launcher.test.js
  packages/wdio-utils/src/envDetector.js
  packages/wdio-utils/src/index.js
  packages/wdio-utils/tests/__mocks__/@wdio/utils.js
Labels: PR: Polish :nail_care:

#5619 chore: Bump puppeteer core 5.1.0
  packages/devtools/package.json
  packages/devtools/src/commands/performActions.js
  packages/devtools/src/launcher.js
  packages/devtools/tests/__snapshots__/launcher.test.js.snap
  packages/devtools/tests/launcher.test.js
  packages/wdio-devtools-service/package.json
Labels: PR: Internal :house:

#5612 Move `pageobject` folders outside specs and steps folder...
  packages/wdio-cli/src/commands/config.js
  packages/wdio-cli/src/constants.js
  packages/wdio-cli/src/templates/exampleFiles/cucumber/step_definitions/steps.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/mochaJasmine/example.e2e.js.ejs
  packages/wdio-cli/src/utils.js
  packages/wdio-cli/tests/config.test.js
  packages/wdio-cli/tests/utils.test.js
Labels: PR: Polish :nail_care:

#5623 Update $.js documentation
  packages/webdriverio/src/commands/element/$.js
Labels: PR: Docs :memo:

#5566 fix return type of getPuppeteer in typescript definitions
  packages/wdio-devtools-service/devtools-service.d.ts
  packages/wdio-devtools-service/package.json
Labels: PR: Polish :nail_care:

#5627 Fix dependency of @wdio/sauce-service on @wdio/utils
  packages/wdio-sauce-service/package.json
Labels: PR: Bug Fix :bug:

#5628 Add file attribute to testcase output
  packages/wdio-junit-reporter/README.md
  packages/wdio-junit-reporter/package.json
  packages/wdio-junit-reporter/src/index.js
  packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.js.snap
  packages/wdio-junit-reporter/tests/reporter.test.js
Labels: PR: New Feature :rocket:

#5632 Add `calls` property to mock typings.
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Bug Fix :bug:

#5633 Appium find by image support
  docs/Selectors.md
  packages/webdriverio/src/utils/findStrategy.js
  packages/webdriverio/tests/findStrategy.test.js
Labels: PR: New Feature :rocket:

#5635 Update devtools package.json homepage url
  packages/devtools/package.json
Labels: PR: Docs :memo:

#5637 Fix 5589
  packages/wdio-junit-reporter/src/index.js
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner-browserstack-android-missing-os.json
  packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.js.snap
  packages/wdio-junit-reporter/tests/reporter.test.js
Labels: PR: Bug Fix :bug:

#5641 Wdio JUnit Reporter - fix #5637
  packages/wdio-junit-reporter/src/index.js
Labels: PR: Bug Fix :bug:

#5649 Add TypeScript types for SevereServiceError
  packages/webdriverio/src/utils/SevereServiceError.js
  packages/webdriverio/tests/index.test.js
  packages/webdriverio/tests/utils/SevereServiceError.test.js
  packages/webdriverio/webdriverio.d.ts
  tests/typings/webdriverio/async.ts
  tests/typings/webdriverio/types/async.d.ts
Labels: PR: Bug Fix :bug:

#5651 Fix re-attach devtools service if `reloadSession` was called
  packages/wdio-devtools-service/src/index.js
  packages/wdio-devtools-service/tests/service.test.js
  packages/webdriver/src/index.js
Labels: PR: Bug Fix :bug:

#5646 Upgrade lighthouse and add new metrics
  packages/wdio-devtools-service/package.json
  packages/wdio-devtools-service/src/auditor.js
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics.js
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/server-response-time.js
  packages/wdio-devtools-service/tests/__snapshots__/auditor.test.js.snap
Labels: PR: Polish :nail_care:

#5667 Calculate performance score based on new weightage and metrics
  packages/wdio-devtools-service/package.json
  packages/wdio-devtools-service/src/auditor.js
  packages/wdio-devtools-service/src/utils.js
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/cumulative-layout-shift.js
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/first-contentful-paint.js
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/interactive.js
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/largest-contentful-paint.js
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/speed-index.js
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/metrics/total-blocking-time.js
  packages/wdio-devtools-service/tests/__snapshots__/auditor.test.js.snap
  packages/wdio-devtools-service/tests/auditor.test.js
Labels: PR: Polish :nail_care:, wdio-devtools-service

#5671 Fix issue with auto-genarated tests for Cucumber
  packages/wdio-cli/src/commands/config.js
  packages/wdio-cli/src/utils.js
  packages/wdio-cli/tests/commands/config.test.js
  packages/wdio-cli/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#5674 docs: add docs for github action integration
  docs/GithubActions.md
  website/_sidebars.json
  website/i18n/en.json
Labels: PR: Docs :memo:
