Repository webdriverio/webdriverio, pull requests merged in 2020-06, with the labels that each got.

#5464 Don't think XPath selector is a base64 screenshot
  packages/wdio-utils/src/utils.js
  packages/wdio-utils/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#5463 Fix depcrecated usage of rejectUnauthorized
  packages/webdriver/src/request.js
  packages/webdriver/tests/request.test.js
Labels: PR: Bug Fix :bug:

#5462 Allow to have 0 x and y values for dragAndDrop
  packages/webdriverio/src/commands/element/dragAndDrop.js
  packages/webdriverio/tests/commands/element/__snapshots__/dragAndDrop.test.js.snap
  packages/webdriverio/tests/commands/element/dragAndDrop.test.js
Labels: PR: Bug Fix :bug:

#5448 Fix data table variable values in Cucumber scenario outlines
  packages/wdio-cucumber-framework/src/utils.js
  packages/wdio-cucumber-framework/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#5485 Fix DocString support in cucumber framework
  packages/wdio-cucumber-framework/src/utils.js
  packages/wdio-cucumber-framework/tests/utils.test.js
  tests/cucumber/step-definitions/then.js
  tests/cucumber/test.feature
Labels: PR: Bug Fix :bug:

#5487 Update GettingStarted.md; remove unneeded line of code
  docs/GettingStarted.md
Labels: PR: Docs :memo:

#5506 Add mochaOpts.grep documentation
  docs/OrganizingTestSuites.md
Labels: PR: Docs :memo:

#5516 chore: add wdio-ng-apimock-service
  packages/wdio-cli/src/constants.js
  scripts/docs-generation/3rd-party/services.json
  website/i18n/en.json
Labels: PR: Docs :memo:

#5514 Fix repl.js platformVersion must be a string for appium
  packages/wdio-cli/src/commands/repl.js
Labels: PR: Bug Fix :bug:

#5512 Removing extra comma (,) from waitUntil docs
  packages/webdriverio/src/commands/element/waitUntil.js
Labels: PR: Docs :memo:

#5517 Update BoilerplateProjects.md
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#5515 Update Debugging and TypeScript documentation
  docs/Debugging.md
  docs/TypeScript.md
Labels: PR: Docs :memo:

#5525 Update BoilerplateProjects.md
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#5527 Issue# 5521 - unskipped mocha test re-ran it several times
  tests/mocha/test.js
Labels: PR: Internal :house:

#5539 Fix #5535
  packages/wdio-devtools-service/devtools-service.d.ts
  tests/typings/sync-devtools-service/devtools-service.ts
  tests/typings/webdriverio-devtools-service/devtools-service.ts
Labels: PR: Bug Fix :bug:

#5483 Add context to before/after scenario hooks issue 5394
  docs/ConfigurationFile.md
  examples/wdio/custom-service/my.custom.service.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cucumber-framework/cucumber-framework.d.ts
  packages/wdio-cucumber-framework/src/index.js
  packages/wdio-cucumber-framework/tests/adapter.test.js
  tests/typings/sync-cucumber/cucumber.ts
  tests/typings/webdriverio-cucumber/cucumber.ts
Labels: PR: Polish :nail_care:

#5536 DevTools Service: Accept 'chromium' as the browserName
  packages/wdio-devtools-service/README.md
  packages/wdio-devtools-service/src/index.js
  packages/wdio-devtools-service/src/utils.js
  packages/wdio-devtools-service/tests/service.test.js
  packages/wdio-devtools-service/tests/utils.test.js
Labels: PR: Bug Fix :bug:

#5547 #5538: Added types for missing grep and invertGrep
  packages/wdio-jasmine-framework/jasmine-framework.d.ts
Labels: PR: Docs :memo:

#5549 docs: Add "Migrating from Chai" section
  docs/Assertion.md
Labels: PR: Docs :memo:
