Repository webdriverio/webdriverio, pull requests merged in 2020-12, with the labels that each got.

#5836 Tracking doc: rewrite `@wdio/firefox-profile-service` package into TypeScript
  packages/wdio-firefox-profile-service/firefox-profile-service.d.ts
  packages/wdio-firefox-profile-service/src/index.ts
  packages/wdio-firefox-profile-service/src/launcher.ts
  packages/wdio-firefox-profile-service/src/types.ts
  packages/wdio-firefox-profile-service/tests/__mocks__/firefox-profile.ts
  packages/wdio-firefox-profile-service/tests/launcher.test.ts
  packages/wdio-firefox-profile-service/tsconfig.json
  packages/wdio-firefox-profile-service/tsconfig.prod.json
  packages/webdriver/src/types.ts
  packages/webdriver/webdriver.d.ts
Labels: PR: Internal :house:, Tracking 🗒, TypeScript, needs-review

#5848 Tracking doc: rewrite `@wdio/sumologic-reporter` package into TypeScript
  package-lock.json
  package.json
  packages/wdio-dot-reporter/src/index.ts
  packages/wdio-reporter/package.json
  packages/wdio-reporter/reporter.d.ts
  packages/wdio-reporter/src/index.ts
  packages/wdio-sumologic-reporter/package.json
  packages/wdio-sumologic-reporter/src/index.ts
  packages/wdio-sumologic-reporter/src/types.ts
  packages/wdio-sumologic-reporter/tests/reporter.test.js
  packages/wdio-sumologic-reporter/tests/reporter.test.ts
  packages/wdio-sumologic-reporter/tsconfig.json
  packages/wdio-sumologic-reporter/tsconfig.prod.json
  tests/typings/copy.js
  tests/typings/webdriverio-reporter/reporter.ts
  tests/typings/webdriverio-reporter/tsconfig.json
Labels: PR: Internal :house:, Tracking 🗒, TypeScript, needs-review

#6192 Cucumber boilerplate showcasing advanced page object structure, Cucum…
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#6194 Add Sauce Labs Visual capability types
  packages/webdriver/src/types.ts
  packages/webdriver/webdriver.d.ts
Labels: PR: Docs :memo:, TypeScript

#6195 feat(*): rewrited wdio-crossbrowser-service package into typescript
  packages/wdio-crossbrowsertesting-service/src/@types/cbt_tunnels.d.ts
  packages/wdio-crossbrowsertesting-service/src/index.ts
  packages/wdio-crossbrowsertesting-service/src/launcher.ts
  packages/wdio-crossbrowsertesting-service/src/service.js
  packages/wdio-crossbrowsertesting-service/src/service.ts
  packages/wdio-crossbrowsertesting-service/tests/launcher.test.js
  packages/wdio-crossbrowsertesting-service/tests/launcher.test.ts
  packages/wdio-crossbrowsertesting-service/tests/service.test.js
  packages/wdio-crossbrowsertesting-service/tests/service.test.ts
  packages/wdio-crossbrowsertesting-service/tsconfig.json
  packages/wdio-crossbrowsertesting-service/tsconfig.prod.json
Labels: PR: Internal :house:, TypeScript

#6209 fix: improve executeAsync typing
  packages/wdio-sync/webdriverio.d.ts
  packages/webdriverio/webdriverio.d.ts
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Polish :nail_care:

#6060 Fix 5577
  packages/wdio-reporter/src/index.ts
  packages/wdio-reporter/tests/reporter.test.ts
  packages/wdio-runner/src/index.js
  packages/wdio-runner/tests/index.test.js
Labels: PR: Polish :nail_care:

#5837 Tracking doc: rewrite `@wdio/jasmine-framework` package into TypeScript
  packages/wdio-crossbrowsertesting-service/tests/service.test.ts
  packages/wdio-jasmine-framework/package.json
  packages/wdio-jasmine-framework/src/index.ts
  packages/wdio-jasmine-framework/src/reporter.js
  packages/wdio-jasmine-framework/src/reporter.ts
  packages/wdio-jasmine-framework/src/types.ts
  packages/wdio-jasmine-framework/tests/__mocks__/jasmine.js
  packages/wdio-jasmine-framework/tests/__mocks__/jasmine.ts
  packages/wdio-jasmine-framework/tests/adapter.test.ts
  packages/wdio-jasmine-framework/tests/reporter.test.js
  packages/wdio-jasmine-framework/tests/reporter.test.ts
  packages/wdio-jasmine-framework/tsconfig.json
  packages/wdio-jasmine-framework/tsconfig.prod.json
  packages/wdio-local-runner/tests/repl.test.ts
  packages/wdio-utils/src/test-framework/testInterfaceWrapper.ts
  packages/wdio-utils/src/test-framework/types.ts
  packages/webdriverio/tests/commands/element/getComputedLabel.test.ts
  packages/webdriverio/tests/commands/element/getComputedRole.test.ts
Labels: Tracking 🗒, TypeScript, needs-review

#5829 Tracking doc: rewrite `@wdio/cli` package into TypeScript
  e2e/testrunner.test.js
  jest.config.js
  packages/wdio-cli/package.json
  packages/wdio-cli/src/@types/async-exit-hooks.d.ts
  packages/wdio-cli/src/@types/yarn-install.ts
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/commands/install.ts
  packages/wdio-cli/src/commands/repl.ts
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/index.ts
  packages/wdio-cli/src/interface.ts
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/src/types.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/src/watcher.ts
  packages/wdio-cli/tests/__mocks__/async-exit-hook.ts
  packages/wdio-cli/tests/__mocks__/chalk.ts
  packages/wdio-cli/tests/__mocks__/chokidar.ts
  packages/wdio-cli/tests/__mocks__/ejs.ts
  packages/wdio-cli/tests/__mocks__/inquirer.ts
  packages/wdio-cli/tests/__mocks__/log-update.ts
  packages/wdio-cli/tests/__mocks__/recursive-readdir.ts
  packages/wdio-cli/tests/__mocks__/yargs.ts
  packages/wdio-cli/tests/__mocks__/yarn-install.ts
  packages/wdio-cli/tests/__snapshots__/utils.test.ts.snap
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  packages/wdio-cli/tests/commands/config.test.ts
  packages/wdio-cli/tests/commands/install.test.ts
  packages/wdio-cli/tests/commands/repl.test.ts
  packages/wdio-cli/tests/commands/run.test.ts
  packages/wdio-cli/tests/config.test.ts
  packages/wdio-cli/tests/index.test.ts
  packages/wdio-cli/tests/interface.test.ts
  packages/wdio-cli/tests/launcher.test.ts
  packages/wdio-cli/tests/run.test.ts
  packages/wdio-cli/tests/utils.test.ts
  packages/wdio-cli/tests/watcher.test.ts
  packages/wdio-config/src/index.ts
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-config/src/types.ts
  packages/wdio-sync/webdriverio-core.d.ts
  packages/wdio-utils/src/initialisePlugin.ts
  packages/wdio-utils/src/initialiseServices.ts
  packages/wdio-utils/src/monad.ts
  packages/wdio-utils/src/utils.ts
  packages/webdriver/webdriver.d.ts
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/commands/browser/executeAsync.test.ts
  packages/webdriverio/tests/utils.test.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  tests/helpers/launch.js
Labels: Tracking 🗒, TypeScript, needs-review

#6215 webdriverio: respond params function support for headers and statusCode
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/src/commands/mock/respond.ts
  packages/webdriverio/src/utils/interception/devtools.ts
  packages/webdriverio/tests/utils/interception/__snapshots__/devtools.test.ts.snap
  packages/webdriverio/tests/utils/interception/devtools.test.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: New Feature :rocket:

#6219 Revert "fix: improve executeAsync typing (#6209)"
  packages/wdio-sync/webdriverio.d.ts
  packages/webdriverio/webdriverio.d.ts
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Bug Fix :bug:

#6220 Fix CLI arguments
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/commands/install.ts
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/src/index.ts
  packages/wdio-cli/tests/commands/config.test.ts
  packages/wdio-cli/tests/commands/install.test.ts
  packages/wdio-cli/tests/commands/run.test.ts
  packages/wdio-cli/tests/index.test.ts
Labels: PR: Bug Fix :bug:

#6221 Another set of bug fixes after last release
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/src/index.ts
  packages/wdio-cli/src/types.ts
  packages/wdio-cli/tests/commands/run.test.ts
  packages/wdio-cli/tests/index.test.ts
Labels: PR: Bug Fix :bug:

#6222 run tests for typescript 3.7
  docs/TypeScript.md
  package.json
  packages/devtools/package.json
  packages/wdio-logger/package.json
  packages/wdio-repl/package.json
  packages/wdio-sync/package.json
  packages/webdriver/package.json
  packages/webdriverio/package.json
  tests/typings/.gitignore
  tests/typings/@typescript/ts3.8/package-lock.json
  tests/typings/@typescript/ts3.8/package.json
  tests/typings/devtools/async.ts
  tests/typings/setup.js
  tests/typings/webdriverio/async.ts
Labels: PR: Internal :house:

#6227 wdio-cli: fix local runner in config
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/tests/commands/config.test.ts
  packages/webdriverio/package.json
Labels: PR: Bug Fix :bug:

#6198 Rewrite typescript issue5830
  packages/wdio-concise-reporter/src/index.ts
  packages/wdio-concise-reporter/tests/fixtures.ts
  packages/wdio-concise-reporter/tests/index.test.ts
  packages/webdriver/src/types.ts
  packages/webdriver/webdriver.d.ts
Labels: PR: Internal :house:

#6233 Log duration of hook execution
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/utils.test.ts
  packages/wdio-cucumber-framework/src/index.js
  packages/wdio-cucumber-framework/tests/adapter.test.js
  packages/wdio-jasmine-framework/src/index.ts
  packages/wdio-jasmine-framework/tests/adapter.test.ts
  packages/wdio-mocha-framework/src/index.ts
  packages/wdio-mocha-framework/tests/adapter.test.ts
  packages/wdio-runner/src/index.ts
  packages/wdio-runner/src/utils.ts
  packages/wdio-runner/tests/index.test.ts
  packages/wdio-runner/tests/utils.test.ts
  packages/wdio-sync/src/executeHooksWithArgs.js
  packages/wdio-sync/src/wrapCommand.js
  packages/wdio-sync/tests/executeHooksWithArgs.test.js
  packages/wdio-utils/src/shim.ts
  packages/wdio-utils/src/test-framework/testFnWrapper.ts
  packages/wdio-utils/tests/shim-async.test.ts
  packages/wdio-utils/tests/test-framework/__snapshots__/testFnWrapper-sync.test.js.snap
  packages/wdio-utils/tests/test-framework/testFnWrapper-async.test.js
Labels: PR: Internal :house:, needs-review

#6216 Tracking doc: rewrite `@wdio/runner` package into TypeScript
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/utils.test.ts
  packages/wdio-config/src/types.ts
  packages/wdio-cucumber-framework/src/index.js
  packages/wdio-cucumber-framework/tests/adapter.test.js
  packages/wdio-devtools-service/tests/service.test.ts
  packages/wdio-jasmine-framework/src/index.ts
  packages/wdio-jasmine-framework/tests/adapter.test.ts
  packages/wdio-mocha-framework/src/index.ts
  packages/wdio-mocha-framework/tests/adapter.test.ts
  packages/wdio-runner/src/index.ts
  packages/wdio-runner/src/reporter.ts
  packages/wdio-runner/src/utils.ts
  packages/wdio-runner/tests/__mocks__/@wdio/runner.js
  packages/wdio-runner/tests/__mocks__/@wdio/runner.ts
  packages/wdio-runner/tests/__mocks__/expect-webdriverio.ts
  packages/wdio-runner/tests/index-initSession.test.ts
  packages/wdio-runner/tests/index.test.ts
  packages/wdio-runner/tests/reporter.test.ts
  packages/wdio-runner/tests/utils.test.ts
  packages/wdio-sync/src/executeHooksWithArgs.js
  packages/wdio-sync/src/wrapCommand.js
  packages/wdio-sync/tests/executeHooksWithArgs.test.js
  packages/wdio-sync/webdriverio-core.d.ts
  packages/wdio-sync/webdriverio.d.ts
  packages/wdio-utils/src/shim.ts
  packages/wdio-utils/src/test-framework/testFnWrapper.ts
  packages/wdio-utils/tests/shim-async.test.ts
  packages/wdio-utils/tests/test-framework/__snapshots__/testFnWrapper-sync.test.js.snap
  packages/wdio-utils/tests/test-framework/testFnWrapper-async.test.js
  packages/webdriver/src/types.ts
  packages/webdriver/webdriver.d.ts
  packages/webdriverio/src/index.ts
  packages/webdriverio/webdriverio-core.d.ts
  packages/webdriverio/webdriverio.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Internal :house:, Tracking 🗒, TypeScript, needs-review

#6240 Fix checkPendingNavigations memory leak in devtools
  packages/devtools/src/devtoolsdriver.ts
  packages/devtools/tests/devtoolsdriver.test.ts
Labels: PR: Bug Fix :bug:

#6245 fix: Add config parameter for before session hook
  packages/wdio-runner/src/index.ts
  packages/wdio-runner/tests/index.test.ts
Labels: PR: Bug Fix :bug:

#6246 Fix `afterSession` parameters
  packages/wdio-runner/src/index.ts
  packages/wdio-runner/tests/index.test.ts
Labels: PR: Bug Fix :bug:

#6253 fix: Sauce EmuSim testname and tests context are not updated
  packages/wdio-sauce-service/src/service.js
  packages/wdio-sauce-service/src/utils.js
Labels: PR: Bug Fix :bug:

#6260 Add headless to testrunner config docs
  docs/ConfigurationFile.md
Labels: PR: Docs :memo:

#6262 feat: add support for Appium W3C caps
  packages/wdio-sauce-service/src/utils.js
  packages/wdio-sauce-service/tests/utils.test.js
Labels: PR: Polish :nail_care:

#6272 Update Debugging.md
  docs/Debugging.md
Labels: PR: Docs :memo:
