Repository webdriverio/webdriverio, pull requests merged in 2020-01, with the labels that each got.

#4935 Add storybook-wdio boilerplate to document
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:, backport-requested

#4938 Fix sanitization of capabilities object (due to DEFAULT_CONFIGS now being a function)
  packages/wdio-config/tests/__mocks__/@wdio/config.js
  packages/wdio-runner/src/utils.js
Labels: PR: Bug Fix :bug:, backport-requested

#4946 Added possibility to disable automatic strings to unicode translation
  packages/webdriverio/src/commands/element/addValue.js
  packages/webdriverio/src/commands/element/setValue.js
  packages/webdriverio/src/utils.js
  packages/webdriverio/tests/commands/element/addValue.test.js
  packages/webdriverio/tests/commands/element/setValue.test.js
  packages/webdriverio/tests/utils.test.js
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/generate-typings-utils.js
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Polish :nail_care:

#4939 Fix some wording issues in the selector docs
  docs/Selectors.md
Labels: PR: Docs :memo:, backport-requested

#4940 Performance improvements on element creation
  packages/webdriverio/src/utils/getElementObject.js
Labels: PR: Polish :nail_care:, Performance, backport-requested

#4606 Remove ability to set service configs on root level
  packages/wdio-appium-service/README.md
  packages/wdio-appium-service/src/launcher.js
  packages/wdio-appium-service/src/utils.js
  packages/wdio-appium-service/src/utils/getFilePath.js
  packages/wdio-appium-service/tests/launcher.test.js
  packages/wdio-appium-service/tests/utils.test.js
  packages/wdio-applitools-service/README.md
  packages/wdio-applitools-service/src/index.js
  packages/wdio-applitools-service/tests/service.test.js
  packages/wdio-browserstack-service/README.md
  packages/wdio-browserstack-service/src/launcher.js
  packages/wdio-browserstack-service/src/service.js
  packages/wdio-browserstack-service/tests/launcher.test.js
  packages/wdio-browserstack-service/tests/service.test.js
  packages/wdio-crossbrowsertesting-service/README.md
  packages/wdio-crossbrowsertesting-service/src/launcher.js
  packages/wdio-crossbrowsertesting-service/tests/launcher.test.js
  packages/wdio-devtools-service/README.md
  packages/wdio-devtools-service/src/index.js
  packages/wdio-devtools-service/tests/service.test.js
  packages/wdio-firefox-profile-service/README.md
  packages/wdio-firefox-profile-service/src/launcher.js
  packages/wdio-firefox-profile-service/tests/launcher.test.js
  packages/wdio-sauce-service/README.md
  packages/wdio-sauce-service/src/launcher.js
  packages/wdio-sauce-service/tests/launcher.test.js
  packages/wdio-selenium-standalone-service/README.md
  packages/wdio-selenium-standalone-service/src/launcher.js
  packages/wdio-selenium-standalone-service/src/utils.js
  packages/wdio-selenium-standalone-service/tests/launcher.test.js
  packages/wdio-selenium-standalone-service/tests/utils.test.js
  packages/wdio-shared-store-service/README.md
  packages/wdio-static-server-service/README.md
  packages/wdio-static-server-service/src/launcher.js
  packages/wdio-static-server-service/tests/__mocks__/express.js
  packages/wdio-static-server-service/tests/launcher.test.js
  packages/wdio-testingbot-service/README.md
  packages/wdio-testingbot-service/src/launcher.js
  packages/wdio-testingbot-service/tests/launcher.test.js
  packages/wdio-utils/package.json
  packages/wdio-utils/src/initialiseServices.js
  packages/wdio-utils/tests/initialiseServices.test.js
Labels: PR: Breaking Change :boom:, v6

#4948 Better document process how types are generated.
  CONTRIBUTING.md
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriver/webdriver.d.ts
  packages/webdriverio/webdriverio-core-v5.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/constants.js
  scripts/type-generation/constants.js
  scripts/type-generation/generate-typings-utils.js
Labels: Docs, PR: Docs :memo:

#4944 webdriver.d.ts colliding type definitions for launchApp between Appium and Chromium
  packages/wdio-protocols/protocols/chromium.json
  packages/webdriver/webdriver.d.ts
Labels: PR: Breaking Change :boom:, v6

#4960 Add docs for addLocatorStrategy
  docs/Selectors.md
  packages/wdio-reporter/README.md
  packages/wdio-runner/src/reporter.js
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/webdriverio-core-v5.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Docs :memo:, backport-requested

#4959 Support fully qualified paths to plugins
  docs/CustomReporter.md
  docs/CustomServices.md
  packages/wdio-utils/src/initialisePlugin.js
  packages/wdio-utils/tests/initialisePlugin.test.js
Labels: PR: Polish :nail_care:, backport-requested

#4928 Replace args with options object in some methods
  docs/Selectors.md
  packages/wdio-sync/webdriverio-core.d.ts
  packages/wdio-sync/webdriverio.d.ts
  packages/webdriverio/src/commands/browser/newWindow.js
  packages/webdriverio/src/commands/browser/react$$.js
  packages/webdriverio/src/commands/browser/react$.js
  packages/webdriverio/src/commands/browser/waitUntil.js
  packages/webdriverio/src/commands/element/dragAndDrop.js
  packages/webdriverio/src/commands/element/moveTo.js
  packages/webdriverio/src/commands/element/react$$.js
  packages/webdriverio/src/commands/element/react$.js
  packages/webdriverio/src/commands/element/scrollIntoView.js
  packages/webdriverio/src/commands/element/waitForClickable.js
  packages/webdriverio/src/commands/element/waitForDisplayed.js
  packages/webdriverio/src/commands/element/waitForEnabled.js
  packages/webdriverio/src/commands/element/waitForExist.js
  packages/webdriverio/src/commands/element/waitUntil.js
  packages/webdriverio/tests/commands/browser/newWindow.test.js
  packages/webdriverio/tests/commands/browser/reactElement.test.js
  packages/webdriverio/tests/commands/browser/reactElements.test.js
  packages/webdriverio/tests/commands/browser/waitUntil.test.js
  packages/webdriverio/tests/commands/element/__snapshots__/waitForClickable.test.js.snap
  packages/webdriverio/tests/commands/element/__snapshots__/waitForDisplayed.test.js.snap
  packages/webdriverio/tests/commands/element/__snapshots__/waitForEnabled.test.js.snap
  packages/webdriverio/tests/commands/element/__snapshots__/waitForExist.test.js.snap
  packages/webdriverio/tests/commands/element/moveTo.test.js
  packages/webdriverio/tests/commands/element/reactElement.test.js
  packages/webdriverio/tests/commands/element/reactElements.test.js
  packages/webdriverio/tests/commands/element/waitForClickable.test.js
  packages/webdriverio/tests/commands/element/waitForDisplayed.test.js
  packages/webdriverio/tests/commands/element/waitForEnabled.test.js
  packages/webdriverio/tests/commands/element/waitForExist.test.js
  packages/webdriverio/webdriverio-core-v5.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  scripts/type-generation/constants.js
  tests/mocha/test.js
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
  website/blog/2019-04-03-react-selectors.md
Labels: PR: Breaking Change :boom:, v6

#4895 Add documentation around smoke tests
  CONTRIBUTING.md
Labels: PR: Docs :memo:

#4965 WebDriverIO V5, Cucumber, Perfecto project example
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:, backport-requested

#4463 Retried specfiles are inserted at the start of the specs queue
  docs/ConfigurationFile.md
  docs/Options.md
  docs/Retry.md
  examples/wdio.conf.js
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/tests/launcher.test.js
Labels: PR: New Feature :rocket:, backport-requested

#4937 Remove compatibility helpers for hook args
  docs/ConfigurationFile.md
  examples/pageobject/wdio.conf.js
  examples/wdio.conf.js
  examples/wdio/custom-service/my.custom.service.js
  package.json
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cucumber-framework/cucumber-framework.d.ts
  packages/wdio-cucumber-framework/src/index.js
  packages/wdio-cucumber-framework/tests/adapter.test.js
  packages/wdio-utils/src/test-framework/testFnWrapper.js
  packages/wdio-utils/tests/test-framework/__snapshots__/testFnWrapper-sync.test.js.snap
  packages/wdio-utils/tests/test-framework/testFnWrapper-sync.test.js
  tests/cucumber/step-definitions/given.js
  tests/helpers/cucumber-hooks.conf.js
  tests/typings/sync-cucumber/cucumber.ts
Labels: PR: Breaking Change :boom:, v6

#4926 Add onWorkerStart hook to launch service
  docs/ConfigurationFile.md
  docs/CustomServices.md
  docs/Options.md
  examples/pageobject/wdio.conf.js
  examples/wdio.conf.js
  examples/wdio/custom-service/my.custom.service.js
  packages/wdio-cli/src/launcher.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/utils.js
  packages/wdio-cli/src/watcher.js
  packages/wdio-cli/tests/launcher.test.js
  packages/wdio-cli/tests/utils.test.js
  packages/wdio-cli/tests/watcher.test.js
  packages/wdio-config/src/constants.js
  packages/wdio-local-runner/src/index.js
  packages/wdio-local-runner/src/worker.js
  packages/wdio-local-runner/tests/__mocks__/@wdio/local-runner.js
  packages/wdio-local-runner/tests/localRunner.test.js
  packages/wdio-local-runner/tests/worker.test.js
  packages/wdio-runner/src/index.js
  packages/wdio-runner/src/utils.js
  packages/wdio-runner/tests/index.test.js
  packages/wdio-runner/tests/utils.test.js
  packages/wdio-smoke-test-service/src/index.js
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriver/src/utils.js
  packages/webdriver/tests/utils.test.js
  packages/webdriverio/src/constants.js
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  tests/helpers/fixtures.js
Labels: PR: New Feature :rocket:, v6

#4908 Embed `expect-webdriverio` as built in assertion API
  .gitignore
  docs/Assertion.md
  docs/Autocompletion.md
  docs/api/.gitkeep
  docs/api/expect.md
  examples/pageobject/specs/checkbox.spec.js
  examples/pageobject/specs/dynamic.spec.js
  examples/pageobject/specs/form.spec.js
  examples/wdio/cucumber/.eslintrc
  examples/wdio/cucumber/step-definitions.js
  examples/wdio/cucumber/wdio.conf.js
  examples/wdio/custom-service/.eslintrc
  examples/wdio/custom-service/mocha.test.js
  examples/wdio/jasmine/jasmine.spec.js
  examples/wdio/mocha/.eslintrc
  examples/wdio/mocha/mocha.test.js
  package-lock.json
  package.json
  packages/eslint-plugin-wdio/index.js
  packages/wdio-runner/package.json
  packages/wdio-runner/src/index.js
  packages/wdio-runner/tests/__mocks__/expect-webdriverio.js
  packages/wdio-runner/tests/index.test.js
  scripts/docs-generation/3rd-party/services.json
  scripts/docs-generation/protocolDocs.js
  scripts/docs-generation/wdioDocs.js
  website/_sidebars.json
  website/i18n/en.json
Labels: PR: New Feature :rocket:, v6

#4964 Better error messages for wrong path
  packages/webdriver/src/request.js
  packages/webdriver/src/utils.js
  packages/webdriver/tests/utils.test.js
  packages/webdriverio/tests/commands/browser/pause.test.js
Labels: PR: Bug Fix :bug:

#4967 wdio-browserstack-service: fix test session status
  packages/wdio-browserstack-service/src/service.js
  packages/wdio-browserstack-service/tests/service.test.js
Labels: PR: Bug Fix :bug:, backport-requested

#4976 Add intercept service to wdio
  packages/wdio-cli/src/constants.js
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:, backport-requested

#4977 webdriverio: Fix 'oject' typo in click command
  packages/webdriverio/src/commands/element/click.js
  packages/webdriverio/tests/commands/element/click.test.js
Labels: PR: Docs :memo:, backport-requested
