Repository webdriverio/webdriverio, pull requests merged in 2021-06, with the labels that each got.

#6941 Propagate better result object in `afterScenario`
  examples/pageobject/wdio.conf.js
  examples/wdio.conf.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-crossbrowsertesting-service/src/service.ts
  packages/wdio-crossbrowsertesting-service/tests/service.test.ts
  packages/wdio-cucumber-framework/src/index.ts
  packages/wdio-cucumber-framework/src/types.ts
  packages/wdio-cucumber-framework/tests/adapter.test.ts
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/tests/service.test.ts
  packages/wdio-testingbot-service/src/service.ts
  packages/wdio-testingbot-service/tests/service.test.ts
  packages/wdio-types/src/Frameworks.ts
  website/docs/ConfigurationFile.md
  website/docs/Options.md
Labels: PR: Polish :nail_care:, needs-review

#6920 Issue #6877: Exclude files from code coverage
  packages/wdio-devtools-service/src/gatherer/coverage.ts
  packages/wdio-devtools-service/src/types.ts
  packages/wdio-devtools-service/tests/gatherer/__snapshots__/coverage.test.ts.snap
  packages/wdio-devtools-service/tests/gatherer/coverage.test.ts
Labels: PR: Polish :nail_care:, needs-review

#6958 Fix for isW3C
  packages/wdio-utils/src/envDetector.ts
  packages/wdio-utils/tests/__fixtures__/safaridriverdockerNbV.response.json
  packages/wdio-utils/tests/__fixtures__/safaridriverdockerNpN.response.json
  packages/wdio-utils/tests/envDetector.test.ts
Labels: PR: Bug Fix :bug:

#6967 fix(mocha-framework): move @types/mocha and @types/node to devDepende…
  packages/wdio-mocha-framework/package.json
Labels: PR: Polish :nail_care:

#6965 fix: Remove scripts from log payload
  packages/wdio-utils/src/utils.ts
  packages/wdio-utils/tests/utils.test.ts
Labels: PR: Polish :nail_care:

#6964 support APAC region for Sauce Labs
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-sauce-service/README.md
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/tests/__snapshots__/index.test.ts.snap
  packages/wdio-spec-reporter/tests/index.test.ts
  packages/wdio-types/src/Options.ts
  packages/webdriverio/src/utils/detectBackend.ts
  packages/webdriverio/tests/utils/detectBackend.test.ts
Labels: PR: Polish :nail_care:

#6996 Add in Learn WebdriverIO course link to homepage masthead
  website/src/pages/index.js
Labels: PR: Docs :memo:

#7002 Issue #6977: Renamed 'reset' command in Appium to 'resetApp'
  packages/wdio-protocols/protocols/appium.json
Labels: PR: Spec Compliancy :eyeglasses:

#7027 Support Firefox 86+ in Devtools Service & Migrate from deprecated Console domain
  packages/wdio-devtools-service/README.md
  packages/wdio-devtools-service/src/constants.ts
  packages/wdio-devtools-service/src/index.ts
  packages/wdio-devtools-service/src/utils.ts
  packages/wdio-devtools-service/tests/service.test.ts
  packages/wdio-devtools-service/tests/utils.test.ts
Labels: PR: Polish :nail_care:

#7028 Enable updating job name for UP tests for Sauce Labs
  package-lock.json
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/tests/service.test.ts
Labels: PR: Polish :nail_care:

#7020 Wrap coverage transform into try/catch to avoid staleness
  packages/wdio-devtools-service/src/gatherer/coverage.ts
  packages/wdio-devtools-service/tests/gatherer/__snapshots__/coverage.test.ts.snap
  packages/wdio-devtools-service/tests/gatherer/coverage.test.ts
Labels: PR: Bug Fix :bug:

#7031 Update selenium-standalone-service to use v7
  packages/wdio-selenium-standalone-service/README.md
  packages/wdio-selenium-standalone-service/package.json
  packages/wdio-selenium-standalone-service/src/launcher.ts
  packages/wdio-selenium-standalone-service/tests/__mocks__/selenium-standalone.ts
Labels: PR: Polish :nail_care:

#7041 JW Player blog post
  website/blog/2021-06-22-jwplayer-case-study.md
Labels: PR: Docs :memo:

#7054 @wdio/junit-reporter - replace ansi chars in test.error.message
  packages/wdio-junit-reporter/src/index.ts
  packages/wdio-junit-reporter/src/utils.ts
  packages/wdio-junit-reporter/tests/__fixtures__/suites-error.json
  packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.ts.snap
  packages/wdio-junit-reporter/tests/reporter.test.ts
Labels: PR: Polish :nail_care:

#7045 Fix sample test for jasmine framework
  packages/wdio-cli/src/templates/exampleFiles/jasmine/example.e2e.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/mocha/example.e2e.js.ejs
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/utils.test.ts
Labels: PR: Polish :nail_care:
