Repository webdriverio/webdriverio, pull requests merged in 2021-05, with the labels that each got.

#6790 Corrected output stream handling (issue from 7.5.3)
  package-lock.json
  package.json
  packages/wdio-local-runner/package.json
  packages/wdio-local-runner/src/transformStream.ts
  packages/wdio-local-runner/src/worker.ts
  packages/wdio-local-runner/tests/transformStream.test.ts
Labels: PR: Polish :nail_care:

#6809 Fix newWindow example
  packages/webdriverio/src/commands/browser/newWindow.ts
Labels: PR: Docs :memo:

#6814 Properly scope deep selector calls
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/utils.test.ts
Labels: PR: Bug Fix :bug:, needs-review

#6810 Have a single implementation for $ command
  packages/webdriverio/src/commands/browser/$.ts
  packages/webdriverio/src/commands/element/$.ts
Labels: PR: Polish :nail_care:, needs-review

#6833 Setup Babel if not already
  jest.config.js
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/index.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  packages/wdio-cli/tests/commands/config.test.ts
  packages/wdio-cli/tests/utils.test.ts
  packages/wdio-reporter/package.json
Labels: PR: Polish :nail_care:, needs-review

#6832 Fix reloading devtools sessions
  packages/devtools/src/index.ts
  packages/devtools/tests/index.test.ts
  packages/wdio-devtools-service/src/index.ts
  packages/wdio-devtools-service/tests/service.test.ts
Labels: PR: Bug Fix :bug:, needs-review

#6846 Update typescript examples, documentation and release notes
  tests/typings/sync/tsconfig.json
  tests/typings/webdriverio/tsconfig.json
  website/blog/2021-02-09-webdriverio-v7-released.md
  website/docs/TypeScript.md
Labels: PR: Docs :memo:

#6753 chore: Docusaurus with webpack 5
  website/package-lock.json
  website/package.json
Labels: PR: Docs :memo:

#6852 Spec Reporter - Display only failures
  packages/wdio-spec-reporter/README.md
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/src/types.ts
  packages/wdio-spec-reporter/tests/__snapshots__/index.test.ts.snap
  packages/wdio-spec-reporter/tests/index.test.ts
Labels: PR: New Feature :rocket:

#6856 Rename uploadFile Doc Example File
  packages/webdriverio/src/commands/browser/uploadFile.ts
Labels: PR: Docs :memo:

#6860 removing Contributor Guide reference link
  README.md
Labels: PR: Docs :memo:

#6858 Fix `wdio-wait-for` install via cli
  packages/wdio-cli/src/constants.ts
Labels: PR: Bug Fix :bug:

#6661 Special characters not properly detected with Puppeteer
  e2e/element.test.js
  packages/devtools/src/commands/elementSendKeys.ts
  packages/wdio-utils/src/constants.ts
  packages/wdio-utils/src/index.ts
  packages/wdio-utils/tests/__mocks__/@wdio/utils.ts
  packages/webdriverio/src/commands/browser/keys.ts
  packages/webdriverio/src/constants.ts
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/utils.test.ts
  tsconfig.prod.json
Labels: PR: Polish :nail_care:

#6869 Upgrade `expect-webdriverio` to v3
  packages/wdio-cucumber-framework/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-mocha-framework/package.json
Labels: PR: Internal :house:

#6862 Adding wdio-eslinter-service to auto-detect missing require imports i…
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#6875 Add missing documentation on returned Cucumber afterStep 'results' object
  website/docs/ConfigurationFile.md
  website/docs/Options.md
Labels: PR: Docs :memo:

#6893 Add custom wdio-ms-teams-service
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#6836 Modifies the cucumberEventListener to emit before-feature and after-feature events differently when using spec grouping configurations
  packages/wdio-cli/src/interface.ts
  packages/wdio-cucumber-framework/src/cucumberEventListener.ts
  packages/wdio-spec-reporter/src/index.ts
Labels: PR: Polish :nail_care:

#6874 6859 - Fixes the issue where wdio before/after Step gets wrapped around a Cucumber Before/After Step
  packages/wdio-allure-reporter/README.md
  packages/wdio-cucumber-framework/src/index.ts
  packages/wdio-cucumber-framework/src/types.ts
  packages/wdio-cucumber-framework/tests/__mocks__/@cucumber/cucumber.ts
  packages/wdio-cucumber-framework/tests/adapter.test.ts
  tests/cucumber/step-definitions/given.js
  tests/helpers/cucumber-hooks.conf.js
  website/docs/ConfigurationFile.md
  website/docs/Options.md
Labels: PR: Bug Fix :bug:

#6896 Fixes #6786
  packages/webdriverio/src/commands/browser/getPuppeteer.ts
  packages/webdriverio/src/commands/browser/reloadSession.ts
  packages/webdriverio/tests/commands/browser/getPuppeteer.test.ts
  packages/webdriverio/tests/commands/browser/mock.test.ts
  packages/webdriverio/tests/commands/browser/reloadSession.test.ts
Labels: PR: Bug Fix :bug:

#6922 Fixes Types for cucumber-framework
  packages/wdio-cucumber-framework/src/types.ts
  website/docs/Options.md
Labels: PR: Docs :memo:

#6927 Fix double click in devtools
  e2e/element.test.js
  packages/devtools/src/commands/performActions.ts
Labels: PR: Bug Fix :bug:, needs-review

#6929 Use WebDriver if Appium capabilities are found
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/utils.test.ts
Labels: PR: Bug Fix :bug:, needs-review

#6930 Implement restore/clear all mocks
  packages/wdio-logger/tests/__mocks__/@wdio/logger.js
  packages/webdriverio/src/commands/browser.ts
  packages/webdriverio/src/commands/browser/mock.ts
  packages/webdriverio/src/commands/browser/mockClearAll.ts
  packages/webdriverio/src/commands/browser/mockRestoreAll.ts
  packages/webdriverio/src/utils/interception/index.ts
  packages/webdriverio/tests/commands/browser/mock.test.ts
  packages/webdriverio/tests/commands/browser/mockClearAll.test.ts
  packages/webdriverio/tests/commands/browser/mockRestoreAll.test.ts
  packages/webdriverio/tests/utils/interception/interception.test.ts
Labels: PR: New Feature :rocket:, needs-review

#6933 CLI : Update visual-regression-testing to image-comparison
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Bug Fix :bug:

#6934 Click x and y are actually counted from center of element
  packages/webdriverio/src/commands/element/click.ts
Labels: PR: Docs :memo:

#6662 Strip color ascii characters when uploading error message to Sauce Labs job
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/src/utils.ts
  packages/wdio-sauce-service/tests/service.test.ts
Labels: PR: Bug Fix :bug:, needs-review

#6915 keep original selector for custom locator strategy
  packages/webdriverio/src/commands/browser/custom$$.ts
  packages/webdriverio/src/commands/browser/custom$.ts
  packages/webdriverio/src/commands/element/custom$$.ts
  packages/webdriverio/tests/commands/browser/customSelector.test.ts
  packages/webdriverio/tests/commands/browser/customSelectors.test.ts
  packages/webdriverio/tests/commands/element/customSelectors.test.ts
Labels: PR: Bug Fix :bug:

#6926 Better allow for manual TS transpiling
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/tests/launcher.test.ts
  website/docs/TypeScript.md
Labels: PR: Bug Fix :bug:

#6935 Update Debugging.md
  website/docs/Debugging.md
Labels: PR: Docs :memo:
