Repository webdriverio/webdriverio, pull requests merged in 2021-03, with the labels that each got.

#6509 Fix a typo
  website/docs/AutoWait.md
Labels: PR: Docs :memo:

#6487 Fix shrinked viewport for devtools package
  packages/devtools/src/launcher.ts
  packages/devtools/tests/__snapshots__/launcher.test.ts.snap
  packages/webdriverio/src/commands/browser/getPuppeteer.ts
  packages/webdriverio/tests/commands/browser/__snapshots__/getPuppeteer.test.ts.snap
Labels: PR: Bug Fix :bug:

#6522 Minor typo in example in README.md
  website/docs/GettingStarted.md
Labels: PR: Docs :memo:

#6520 Fix TS return types for $ command
  packages/webdriverio/async.d.ts
  packages/webdriverio/sync.d.ts
Labels: PR: Bug Fix :bug:, needs-review

#6521 Expose ElementArray as type to the WebdriverIO namespace
  packages/webdriverio/async.d.ts
  packages/webdriverio/sync.d.ts
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Polish :nail_care:, needs-review

#6533 fix #6531 return correct test status in allure report
  packages/wdio-allure-reporter/src/utils.ts
  packages/wdio-allure-reporter/tests/__fixtures__/cucumber.ts
  packages/wdio-allure-reporter/tests/__fixtures__/testState.ts
  packages/wdio-allure-reporter/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#6480 make use of ARIA Sematics role to identify element(webdriverio#6363)
  package.json
  packages/webdriverio/package.json
  packages/webdriverio/src/utils/findStrategy.ts
  packages/webdriverio/tests/findStrategy.test.ts
  website/docs/Selectors.md
Labels: PR: New Feature :rocket:

#6541 Fix test status in allure when several steps are passed and other skipped
  packages/wdio-allure-reporter/src/index.ts
  packages/wdio-allure-reporter/tests/__fixtures__/cucumber.ts
  packages/wdio-allure-reporter/tests/cucumber.suite.test.ts
Labels: PR: Bug Fix :bug:

#6508 Support Selenium 4.0 Grid CDP for Devtools Service
  packages/wdio-types/src/Capabilities.ts
  packages/webdriverio/src/commands/browser/getPuppeteer.ts
  packages/webdriverio/tests/commands/browser/__snapshots__/getPuppeteer.test.ts.snap
  packages/webdriverio/tests/commands/browser/getPuppeteer.test.ts
Labels: PR: New Feature :rocket:

#6507 Fix unable to use nativeWebTap in capabilities
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Docs :memo:

#6558 docs(typings): #6549 improve typings using overloads - getLocation, getSize
  .eslintrc.js
  packages/wdio-jasmine-framework/package.json
  packages/webdriverio/src/commands/element/getLocation.ts
  packages/webdriverio/src/commands/element/getSize.ts
  packages/webdriverio/src/types.ts
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Polish :nail_care:

#6464 Junit cucumber reporting fix
  packages/wdio-junit-reporter/src/index.ts
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-features-with-error-step-and-no-error-object-unordered.json
  packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.ts.snap
  packages/wdio-junit-reporter/tests/reporter.test.ts
Labels: PR: Bug Fix :bug:

#6577 Update `expect-webdriverio`
  packages/wdio-cli/src/interface.ts
  packages/wdio-cucumber-framework/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-local-runner/src/run.ts
  packages/wdio-mocha-framework/package.json
Labels: PR: Bug Fix :bug:

#6580 Update BambooIntegration.md
  website/docs/BambooIntegration.md
Labels: PR: Docs :memo:

#6582 Only apply base url if not empty string
  packages/webdriverio/src/commands/browser/url.ts
  packages/webdriverio/tests/commands/browser/url.test.ts
Labels: PR: Bug Fix :bug:, needs-review

#6581 Support custom tsconfig-paths options
  examples/wdio.conf.js
  packages/wdio-config/package.json
  packages/wdio-config/src/utils.ts
  packages/wdio-config/tests/configparser.test.ts
  packages/wdio-types/src/Options.ts
  website/docs/ConfigurationFile.md
  website/docs/TypeScript.md
Labels: PR: New Feature :rocket:, needs-review

#6574 docs(typings): #6458 use a more suitable return type for waitUntil
  packages/webdriverio/src/commands/browser/waitUntil.ts
  packages/webdriverio/tests/commands/browser/waitUntil.test.ts
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Polish :nail_care:

#6099 Upload WDIO logs to Sauce Labs via Sauce Service
  packages/wdio-sauce-service/README.md
  packages/wdio-sauce-service/src/constants.ts
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/src/types.ts
  packages/wdio-sauce-service/tests/service.test.ts
Labels: PR: New Feature :rocket:

#6599 Use a flat namespace for selenium options for finding WebDriver Bidi endpoint
  packages/wdio-types/src/Capabilities.ts
  packages/webdriverio/src/commands/browser/getPuppeteer.ts
  packages/webdriverio/tests/commands/browser/getPuppeteer.test.ts
Labels: PR: Polish :nail_care:, needs-review

#6317 Make it easier to add commands that make WebDriver based requests
  .husky/.gitignore
  .husky/pre-commit
  .husky/pre-push
  package-lock.json
  package.json
  packages/webdriver/src/command.ts
  packages/webdriver/src/index.ts
  packages/webdriver/tests/index.test.ts
  website/docs/CustomCommands.md
Labels: PR: Docs :memo:, needs-review

#6597 Mitigate LGTM scan warnings
  examples/appium/appium-draws-its-logo.js
  packages/wdio-appium-service/src/utils.ts
  packages/wdio-applitools-service/src/index.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-devtools-service/src/commands.ts
  packages/wdio-jasmine-framework/src/index.ts
  scripts/utils/formatter.js
Labels: PR: Polish :nail_care:, needs-review

#6594 Better expose config handler
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  packages/wdio-cli/tests/commands/config.test.ts
Labels: PR: Polish :nail_care:, needs-review

#6598 Improve project contributing guidelines
  .gitignore
  CONTRIBUTING.md
  examples/wdio/cucumber/wdio.conf.js
  examples/wdio/custom-reporter/wdio.conf.js
  examples/wdio/custom-service/wdio.conf.js
  examples/wdio/jasmine/wdio.conf.js
  examples/wdio/mocha/wdio.conf.js
  examples/wdio/multiremote/wdio.conf.js
  scripts/docs-generation/copyContributingDocs.js
  scripts/docs-generation/generateDocs.js
  website/docs/Contribute.md
Labels: PR: Docs :memo:, needs-review

#6602 Fix typo in error message
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/utils.test.ts
Labels: PR: Polish :nail_care:

#6610 fix(typo): Minor typo fixes and #6553
  CONTRIBUTING.md
  packages/webdriverio/src/utils/findStrategy.ts
Labels: PR: Bug Fix :bug:

#6600 Fix drag and drop
  package-lock.json
  package.json
  packages/webdriverio/src/commands/element/dragAndDrop.ts
  packages/webdriverio/tests/commands/element/__snapshots__/dragAndDrop.test.ts.snap
  packages/webdriverio/tests/commands/element/dragAndDrop.test.ts
Labels: PR: Bug Fix :bug:

#6619 Make CucumberOpts properties optional
  packages/wdio-cucumber-framework/src/index.ts
  packages/wdio-cucumber-framework/src/types.ts
Labels: PR: Bug Fix :bug:, needs-review

#6628 Check caps in `@wdio/selenium-standalone-server` before modifying capabilities
  packages/wdio-selenium-standalone-service/src/launcher.ts
  packages/wdio-selenium-standalone-service/src/utils.ts
  packages/wdio-selenium-standalone-service/tests/launcher.test.ts
Labels: PR: Bug Fix :bug:, needs-review

#6629 Propagate connection details from capabilities
  packages/wdio-runner/src/utils.ts
  packages/wdio-runner/tests/utils.test.ts
Labels: PR: Bug Fix :bug:, needs-review

#6637 Implement`attachToSession` for devtools package
  e2e/jest.config.js
  e2e/wdio/attach.test.js
  packages/devtools/src/constants.ts
  packages/devtools/src/index.ts
  packages/devtools/src/launcher.ts
  packages/devtools/src/types.ts
  packages/devtools/tests/__snapshots__/devtools.test.ts.snap
  packages/devtools/tests/devtools.test.ts
  packages/devtools/tests/launcher.test.ts
  packages/webdriverio/src/index.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/__snapshots__/utils.test.ts.snap
  packages/webdriverio/tests/module.test.ts
Labels: PR: New Feature :rocket:, needs-review

#6512 Issue #6511 fix
  packages/wdio-utils/src/test-framework/testInterfaceWrapper.ts
  packages/wdio-utils/tests/test-framework/testInterfaceWrapper.test.js
Labels: PR: Bug Fix :bug:

#6641 Fix name typo
  website/community/Resources.md
Labels: PR: Docs :memo:

#6625 fix sync browser type for "call" method
  packages/webdriverio/src/types.ts
Labels: PR: Bug Fix :bug:
