Repository webdriverio/webdriverio, pull requests merged in 2021-04, with the labels that each got.

#6646 Fixed missing github icon on the Team page
  website/src/css/custom.css
  website/src/theme/card.jsx
Labels: PR: Docs :memo:

#6647 Fixed github logo color for dark mode
  website/src/css/custom.css
  website/src/theme/card.jsx
Labels: PR: Docs :memo:

#6668 feat: add wdio-ocr-service to the service menu and service cli
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#6673 webdriverio: Allow to use devtools features for Aerokube Selenoid\Moon sessions
  packages/wdio-types/src/Capabilities.ts
  packages/webdriverio/src/commands/browser/getPuppeteer.ts
  packages/webdriverio/tests/commands/browser/__snapshots__/getPuppeteer.test.ts.snap
  packages/webdriverio/tests/commands/browser/getPuppeteer.test.ts
Labels: PR: Polish :nail_care:

#6676 Fix devtools url for Aerokube Selenoid\Moon sessions
  packages/webdriverio/src/commands/browser/getPuppeteer.ts
  packages/webdriverio/tests/commands/browser/__snapshots__/getPuppeteer.test.ts.snap
Labels: PR: Bug Fix :bug:

#6658 Added ability to group specs in suites
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-config/tests/__fixtures__/wdio.array.conf.ts
  packages/wdio-config/tests/configparser.test.ts
  website/blog/2021-03-23-grouping-specs.md
  website/docs/OrganizingTestSuites.md
Labels: PR: Polish :nail_care:

#6683 [BUGFIX] wdio-browserstack-service using the wrong session url when w3c properties are enforced
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/tests/service.test.ts
Labels: PR: Bug Fix :bug:

#6687 Remove done callback in Jasmine
  packages/wdio-jasmine-framework/src/index.ts
  packages/wdio-jasmine-framework/tests/adapter.test.ts
Labels: PR: Bug Fix :bug:

#6698 Small typo
  packages/webdriverio/src/commands/element/click.ts
Labels: PR: Docs :memo:

#6681 Fix connection details setting for multiremote in selenium server
  packages/wdio-selenium-standalone-service/src/launcher.ts
  packages/wdio-selenium-standalone-service/tests/launcher.test.ts
Labels: PR: Bug Fix :bug:, needs-review

#6699 Properly type config file if TypeScript is being used
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  packages/wdio-cli/tests/utils.test.ts
Labels: PR: Polish :nail_care:, needs-review

#6700 Improve spec reporting for multiremote
  packages/wdio-reporter/src/index.ts
  packages/wdio-reporter/src/stats/runner.ts
  packages/wdio-reporter/tests/stats/runner.test.ts
  packages/wdio-runner/src/index.ts
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/src/types.ts
  packages/wdio-spec-reporter/tests/index.test.ts
  packages/wdio-types/src/Options.ts
Labels: PR: Bug Fix :bug:, needs-review

#6701 Fix `checkPWA` command
  e2e/wdio/headless/test.e2e.js
  e2e/wdio/wdio.conf.js
  packages/wdio-devtools-service/src/@types/lighthouse.ts
  packages/wdio-devtools-service/src/gatherer/pwa.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/fraggle-rock/gather/session.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/gather/gather-runner.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/gather/gatherers/installability-errors.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/gather/gatherers/web-app-manifest.ts
Labels: PR: Bug Fix :bug:

#6682 Enhance docs for custom locator strategy
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/index.ts
  tests/typings/sync/sync.ts
  website/docs/Selectors.md
Labels: PR: Docs :memo:, needs-review

#6684 Allow more options to connect to a remote devtools connection
  packages/devtools/src/launcher.ts
  packages/devtools/src/types.ts
  packages/devtools/tests/__snapshots__/launcher.test.ts.snap
  packages/devtools/tests/launcher.test.ts
  website/docs/AutomationProtocols.md
Labels: PR: New Feature :rocket:, needs-review

#6708 Update name and link to @wdio/browserstack-service
  website/docs/CloudServices.md
Labels: PR: Docs :memo:

#6606 webdriverio: fix setvalue typings
  packages/wdio-utils/src/shim.ts
  packages/webdriverio/src/commands/element/addValue.ts
  packages/webdriverio/src/commands/element/setValue.ts
  packages/webdriverio/tests/commands/element/addValue.test.ts
  packages/webdriverio/tests/commands/element/setValue.test.ts
Labels: PR: Polish :nail_care:

#6718 Remove `@wdio/sync` package from cli wizard
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/types.ts
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  packages/wdio-cli/tests/commands/config.test.ts
  packages/wdio-cli/tests/commands/repl.test.ts
  packages/wdio-cli/tests/config.test.ts
Labels: PR: Polish :nail_care:

#6720 fix: Only log when the entry is not a string or array
  packages/wdio-config/src/lib/ConfigParser.ts
Labels: PR: Polish :nail_care:

#6626 Update CustomServices.md
  website/docs/CustomServices.md
Labels: PR: Docs :memo:

#6722 Update broken links
  CONTRIBUTING.md
  README.md
Labels: PR: Docs :memo:

#6723 Remove repeated the
  docs/OrganizingTestSuites.md
Labels: PR: Docs :memo:

#6678 Document the transition from a Protractor to WebdriverIO framework
  website/_sidebars.json
  website/docs/ProtractorMigration.md
Labels: PR: Docs :memo:

#6725 Fix DevToolsDriver elements storing
  packages/devtools/src/devtoolsdriver.ts
  packages/devtools/src/elementstore.ts
  packages/devtools/tests/devtoolsdriver.test.ts
  packages/devtools/tests/elementStore.test.ts
Labels: PR: Bug Fix :bug:

#6709 Implement `>>>` (deep) selector for WebdriverIO
  @types/query-selector-shadow-dom.d.ts
  e2e/element.test.js
  packages/devtools/package.json
  packages/devtools/src/commands/findElement.ts
  packages/devtools/src/commands/findElementFromElement.ts
  packages/devtools/src/commands/findElements.ts
  packages/devtools/src/commands/findElementsFromElement.ts
  packages/devtools/src/constants.ts
  packages/devtools/src/launcher.ts
  packages/devtools/src/utils.ts
  packages/devtools/tests/__mocks__/puppeteer-core.ts
  packages/devtools/tests/launcher.test.ts
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/element/shadow$$.ts
  packages/webdriverio/src/commands/element/shadow$.ts
  packages/webdriverio/src/constants.ts
  packages/webdriverio/src/utils/findStrategy.ts
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/findStrategy.test.ts
  packages/webdriverio/tests/utils.test.ts
  website/docs/Selectors.md
Labels: PR: New Feature :rocket:, needs-review

#6732 add(service): waitFor external package
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#6664 Fix Devtools hang on Android
  packages/wdio-devtools-service/src/index.ts
Labels: PR: Bug Fix :bug:

#6737 Pin Cucumber package versions
  packages/wdio-cucumber-framework/package.json
Labels: PR: Bug Fix :bug:

#6736 `checkPWA` command is broken
  e2e/wdio/headless/test.e2e.js
  packages/wdio-devtools-service/src/index.ts
Labels: PR: Bug Fix :bug:

#6751 fix executeScript results transformation in devtools
  packages/devtools/src/scripts/executeAsyncScript.ts
  packages/devtools/src/scripts/executeScript.ts
  packages/devtools/src/utils.ts
  packages/devtools/tests/__snapshots__/utils.test.ts.snap
Labels: PR: Bug Fix :bug:

#6755 Add documentation for accessing browser instances via strings
  website/docs/Multiremote.md
Labels: PR: Docs :memo:

#6759 attach to session improvements
  packages/wdio-types/src/Options.ts
  packages/webdriver/src/constants.ts
  packages/webdriver/src/index.ts
  packages/webdriver/tests/index.test.ts
  packages/webdriverio/src/index.ts
  tests/mocha/standalone.js
Labels: PR: Bug Fix :bug:, needs-review

#6758 Print custom error message if installing deps fails with no stderr
  packages/wdio-cli/src/commands/config.ts
Labels: PR: Polish :nail_care:, needs-review

#6756 Retry connection refused errors
  packages/webdriver/src/request.ts
  packages/webdriver/tests/request.test.ts
  packages/webdriverio/tests/__mocks__/got.ts
Labels: PR: Polish :nail_care:, needs-review

#6762 Added wdio 7 with appium and cucumber boilerplate
  website/docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#6781 Add CID to every line printed to stdout
  package-lock.json
  package.json
  packages/wdio-local-runner/package.json
  packages/wdio-local-runner/src/transformStream.ts
  packages/wdio-local-runner/src/worker.ts
  packages/wdio-local-runner/tests/transformStream.test.ts
Labels: PR: Polish :nail_care:

#6782 Documentation fix: Removed $ sign in commands so it wont be copied
  website/docs/ProtractorMigration.md
Labels: PR: Docs :memo:
