Repository webdriverio/webdriverio, pull requests merged in 2021-12, with the labels that each got.

#7777 fix: update state for a skipped test
  packages/wdio-cucumber-framework/src/index.ts
  packages/wdio-cucumber-framework/src/reporter.ts
Labels: PR: Polish :nail_care:

#7779 feat: add cucumber step name in Sauce
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/tests/service.test.ts
  packages/wdio-types/src/Frameworks.ts
Labels: PR: Polish :nail_care:

#7795 Docs
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Docs :memo:

#7799 docs: port descriptions from Appium's official document
  packages/wdio-types/src/Capabilities.ts
  packages/webdriverio/src/index.ts
Labels: PR: Docs :memo:

#7802 Update Overwriting element commands example
  website/docs/CustomCommands.md
Labels: PR: Docs :memo:

#7818 Removed cucumberopts profile and format that has no support yet.
  examples/wdio.conf.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cucumber-framework/src/constants.ts
  packages/wdio-cucumber-framework/src/types.ts
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner-browserstack-android-missing-os.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner-browserstack-android.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner-browserstack-ios.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner.json
  website/docs/ConfigurationFile.md
Labels: PR: Docs :memo:

#7819 test(na): add missing unit test to getCSSProperty
  packages/webdriverio/tests/commands/element/getCSSProperty.test.ts
Labels: PR: Internal :house:

#7720 Fix for bug #7640 run is not working when project already has a misconfigured tsconfig.json
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/types.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  packages/wdio-cli/tests/commands/config.test.ts
Labels: PR: Bug Fix :bug:

#7823 Fix for Jasmine webdriverio exception not failing suite
  packages/wdio-reporter/src/stats/test.ts
  packages/wdio-reporter/tests/stats/test.test.ts
Labels: PR: Bug Fix :bug:

#7839 Sauce service before step RDC fix
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/tests/service.test.ts
Labels: PR: Bug Fix :bug:
