Repository webdriverio/webdriverio, pull requests merged in 2021-11, with the labels that each got.

#7618 Connect to target manually if going through remote server
  packages/wdio-devtools-service/src/index.ts
  packages/wdio-devtools-service/src/lighthouse/cri.ts
  packages/wdio-devtools-service/src/utils.ts
  packages/wdio-devtools-service/tests/__snapshots__/utils.test.ts.snap
  packages/wdio-devtools-service/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#7671 Stricter typing examples
  packages/wdio-cli/src/templates/exampleFiles/pageobjects/login.page.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/pageobjects/page.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/pageobjects/secure.page.js.ejs
Labels: PR: Polish :nail_care:

#7677 Explicitly wait for window handle to be picked up in DevTools
  .github/workflows/test.yml
  packages/webdriverio/src/commands/browser/newWindow.ts
  packages/webdriverio/tests/commands/browser/newWindow.test.ts
Labels: PR: Bug Fix :bug:

#7680 Adding ability to override Suite Name
  packages/wdio-junit-reporter/src/index.ts
  packages/wdio-junit-reporter/src/types.ts
  packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.ts.snap
  packages/wdio-junit-reporter/tests/reporter.test.ts
Labels: PR: Polish :nail_care:

#7682 Add WebDriver protocol commands to fetch shadow elements
  packages/devtools/tests/__snapshots__/utils.test.ts.snap
  packages/wdio-protocols/protocols/webdriver.json
Labels: PR: New Feature :rocket:

#7688 Don't escape characters in templates
  packages/wdio-cli/src/templates/exampleFiles/pageobjects/login.page.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/pageobjects/page.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/pageobjects/secure.page.js.ejs
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
Labels: PR: Bug Fix :bug:

#7689 Implement WebDriver shadow commands in DevTools bridge
  e2e/element.test.js
  packages/devtools/src/commands.ts
  packages/devtools/src/commands/findElementFromShadowRoot.ts
  packages/devtools/src/commands/findElementsFromShadowRoot.ts
  packages/devtools/src/commands/getElementShadowRoot.ts
  packages/devtools/src/constants.ts
  packages/devtools/tests/__snapshots__/utils.test.ts.snap
  packages/wdio-protocols/protocols/webdriver.json
Labels: PR: New Feature :rocket:

#7691 Fix for Console log note added to failed cucumber step
  packages/wdio-allure-reporter/src/index.ts
  packages/wdio-allure-reporter/tests/cucumber.suite.test.ts
Labels: PR: Polish :nail_care:

#7699 doc(README): replace broken logo
  README.md
Labels: PR: Internal :house:

#7672 Set the job name before a suite is run
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/tests/service.test.ts
Labels: PR: Polish :nail_care:

#7711 Use buffer instead of atob/btoa
  package-lock.json
  package.json
  packages/wdio-devtools-service/package.json
  packages/wdio-devtools-service/src/gatherer/coverage.ts
  packages/webdriver/src/request/browser.ts
  packages/webdriverio/package.json
  packages/webdriverio/src/utils/interception/devtools.ts
Labels: PR: Polish :nail_care:

#7707 Remove outdated double-await issue in docs
  website/docs/SyncVsAsync.md
Labels: PR: Docs :memo:

#7721 doc(README): add a community section
  README.md
Labels: PR: Docs :memo:

#7727 fix: fix 6357
  package-lock.json
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/tests/__snapshots__/index.test.ts.snap
  packages/wdio-spec-reporter/tests/index.test.ts
Labels: PR: Bug Fix :bug:

#7732 feat: properly update Multi Remote jobs on Sauce
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/src/utils.ts
  packages/wdio-sauce-service/tests/service.test.ts
  packages/wdio-sauce-service/tests/utils.test.ts
Labels: PR: Polish :nail_care:

#7746 fix(devtools): accepting a prompt preserves the default value. Closes #7744
  packages/devtools/src/commands/acceptAlert.ts
Labels: PR: Bug Fix :bug:

#7757 Make @wdio/cucumber-framework export World class
  packages/wdio-cucumber-framework/src/index.ts
  packages/wdio-cucumber-framework/tests/adapter.test.ts
Labels: PR: Polish :nail_care:
