Repository webdriverio/webdriverio, pull requests merged in 2021-02, with the labels that each got.

#6389 Documentation: update `CustomWorkerService` before hook method signature
  docs/CustomServices.md
Labels: backport-requested

#6392 Add sauce sharable report links
  packages/wdio-spec-reporter/README.md
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/src/types.ts
  packages/wdio-spec-reporter/src/utils.ts
  packages/wdio-spec-reporter/tests/__snapshots__/index.test.ts.snap
  packages/wdio-spec-reporter/tests/index.test.ts
Labels: PR: Polish :nail_care:

#6401 Export RemoteOptions type
  packages/webdriverio/src/index.ts
Labels: PR: Polish :nail_care:

#6402 Update peer dependencies
  packages/wdio-allure-reporter/package.json
  packages/wdio-appium-service/package.json
  packages/wdio-applitools-service/package.json
  packages/wdio-browserstack-service/package.json
  packages/wdio-concise-reporter/package.json
  packages/wdio-crossbrowsertesting-service/package.json
  packages/wdio-cucumber-framework/package.json
  packages/wdio-devtools-service/package.json
  packages/wdio-dot-reporter/package.json
  packages/wdio-firefox-profile-service/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-junit-reporter/package.json
  packages/wdio-local-runner/package.json
  packages/wdio-sauce-service/package.json
  packages/wdio-selenium-standalone-service/package.json
  packages/wdio-spec-reporter/package.json
  packages/wdio-sumologic-reporter/package.json
  packages/wdio-testingbot-service/package.json
Labels: PR: Internal :house:

#6408 Refactor `detectBackend` and move it to the `webdriverio` package
  examples/wdio/custom-service/mocha.test.js
  examples/wdio/jasmine/jasmine.spec.js
  examples/wdio/mocha/mocha.test.js
  examples/wdio/mocha/wdio.conf.js
  packages/wdio-config/src/index.ts
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-config/src/utils.ts
  packages/wdio-config/tests/__fixtures__/wdio.conf.multiremote.rdc.ts
  packages/wdio-config/tests/__fixtures__/wdio.conf.rdc.ts
  packages/wdio-config/tests/__fixtures__/wdio.conf.ts
  packages/wdio-config/tests/__mocks__/@wdio/config.ts
  packages/wdio-config/tests/configparser.test.ts
  packages/wdio-config/tests/lib/MockPathService.ts
  packages/wdio-runner/src/index.ts
  packages/wdio-sync/README.md
  packages/wdio-sync/webdriverio-core.d.ts
  packages/wdio-types/src/Options.ts
  packages/webdriver/src/constants.ts
  packages/webdriver/src/request.ts
  packages/webdriverio/src/commands/browser/addCommand.ts
  packages/webdriverio/src/constants.ts
  packages/webdriverio/src/index.ts
  packages/webdriverio/src/utils/detectBackend.ts
  packages/webdriverio/tests/__mocks__/got.ts
  packages/webdriverio/tests/module.test.ts
  packages/webdriverio/tests/utils/detectBackend.test.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/depcheck.js
  website/docs/Frameworks.md
  website/docs/Options.md
Labels: PR: Polish :nail_care:, backport-requested

#6415 Allow `ScrollIntoViewOptions` in `scrollIntoView`
  packages/webdriverio/src/commands/element/scrollIntoView.ts
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Bug Fix :bug:

#6416 Move user/key options back to `webdriver` package
  .github/workflows/test.yml
  e2e/wdio/cloud/test.e2e.js
  e2e/wdio/headless/secondTest.e2e.js
  e2e/wdio/headless/test.e2e.js
  e2e/wdio/wdio.conf.js
  e2e/wdio/wdio.sauce.conf.js
  examples/wdio/mocha/wdio.conf.js
  package.json
  packages/wdio-types/src/Options.ts
  packages/webdriver/src/constants.ts
  packages/webdriver/src/request.ts
  packages/webdriverio/src/constants.ts
  website/docs/Options.md
Labels: PR: Bug Fix :bug:

#6373 @wdio/cli: Ensure watch mode re-runs all specs when the --spec command line option is set and a filesToWatch file is added or changed
  packages/wdio-cli/src/interface.ts
  packages/wdio-cli/src/types.ts
  packages/wdio-cli/src/watcher.ts
  packages/wdio-cli/tests/watcher.test.ts
  packages/wdio-local-runner/src/index.ts
  packages/wdio-local-runner/src/run.ts
  packages/wdio-local-runner/src/types.ts
  packages/wdio-local-runner/src/worker.ts
  packages/wdio-types/src/Capabilities.ts
  packages/wdio-types/src/Workers.ts
  packages/wdio-types/src/index.ts
Labels: PR: Bug Fix :bug:

#6431 fix docs for cucumber hooks
  examples/pageobject/wdio.conf.js
  examples/wdio.conf.js
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cucumber-framework/src/types.ts
  packages/webdriverio/src/constants.ts
  website/docs/ConfigurationFile.md
  website/docs/Options.md
Labels: PR: Docs :memo:, needs-review

#6430 bump junit reporter builder
  packages/wdio-junit-reporter/package.json
Labels: PR: Internal :house:, needs-review

#6429 Improve typings for instance base
  packages/wdio-runner/src/index.ts
  packages/webdriverio/src/commands/browser/execute.ts
  packages/webdriverio/src/commands/browser/executeAsync.ts
  packages/webdriverio/src/types.ts
Labels: PR: Docs :memo:, needs-review

#6439 Removed _ from suite/test name in junit reporter
  packages/wdio-junit-reporter/src/index.ts
  packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.ts.snap
  packages/wdio-junit-reporter/tests/reporter.test.ts
Labels: PR: Polish :nail_care:

#6444 fixed typo in the wdio exec command
  website/docs/GettingStarted.md
Labels: PR: Docs :memo:

#6441 Ensure that 'title' property is passed down by cucumber framework to reporters
  packages/wdio-cucumber-framework/src/utils.ts
  packages/wdio-cucumber-framework/tests/__snapshots__/reporter.test.ts.snap
  packages/wdio-cucumber-framework/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#6419 fix typos and version doc link
  GOVERNANCE.md
  e2e/protocol.test.js
  e2e/testrunner.test.js
  examples/README.md
  examples/appium/helpers/drawHelper.js
  examples/devtools/service/metrics.test.js
  examples/pageobject/wdio.conf.js
  examples/wdio/README.md
  examples/wdio/cucumber/features/my-feature.feature
  examples/wdio/cucumber/step-definitions.js
  examples/wdio/custom-reporter/reporter/my.custom.reporter.js
  examples/wdio/custom-service/my.custom.service.js
  packages/devtools/src/commands/performActions.ts
  packages/devtools/src/commands/switchToFrame.ts
  packages/devtools/src/finder/edge.ts
  packages/devtools/src/finder/firefox.ts
  packages/devtools/src/scripts/executeAsyncScript.ts
  packages/devtools/src/scripts/executeScript.ts
  packages/devtools/src/utils.ts
  packages/devtools/tests/utils.test.ts
  packages/wdio-allure-reporter/README.md
  packages/wdio-allure-reporter/src/index.ts
  packages/wdio-allure-reporter/tests/compoundError.test.ts
  packages/wdio-allure-reporter/tests/cucumber.suite.test.ts
  website/blog/2018-12-19-webdriverio-v5-released.md
  website/blog/2019-06-25-file-upload.md
  website/blog/2019-07-11-cucumberjs-v5-released.md
  website/blog/2019-09-16-devtools.md
  website/blog/2020-03-26-webdriverio-v6-released.md
  website/blog/2020-07-01-office-hours.md
  website/blog/2020-07-10-network-primitives.md
  website/blog/2021-02-09-webdriverio-v7-released.md
  website/docs/Assertion.md
  website/docs/AutoWait.md
  website/docs/BambooIntegration.md
  website/docs/BoilerplateProjects.md
  website/docs/CustomServices.md
  website/docs/DriverBinaries.md
  website/docs/Multiremote.md
  website/docs/Options.md
  website/docs/Selectors.md
  website/docs/WhatIsWebdriverIO.md
  website/src/pages/versions.js
Labels: PR: Docs :memo:

#6447 chore: remove obsolete puppeteer types
  package-lock.json
  package.json
  packages/devtools/package.json
  packages/wdio-devtools-service/package.json
  packages/webdriverio/package.json
Labels: PR: Internal :house:

#6446 chore: fix link to contributor guide in README
  README.md
Labels: PR: Docs :memo:

#6162 Pdf print page with Chrome DevTools
  e2e/protocol.test.js
  packages/devtools/src/commands/printPage.ts
  packages/wdio-protocols/protocols/webdriver.json
Labels: PR: Polish :nail_care:

#6454 Fix/sauce service cucumber
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/tests/service.test.ts
Labels: PR: Bug Fix :bug:

#6455 Update autocompletion.md
  website/docs/Autocompletion.md
Labels: PR: Docs :memo:

#6453 Fix/add cucumber keyword
  packages/wdio-cucumber-framework/src/constants.ts
  packages/wdio-cucumber-framework/src/cucumberEventListener.ts
  packages/wdio-cucumber-framework/src/utils.ts
  packages/wdio-cucumber-framework/tests/__snapshots__/reporter.test.ts.snap
  packages/wdio-cucumber-framework/tests/__snapshots__/utils.test.ts.snap
  packages/wdio-cucumber-framework/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#6462 Update autocompletion
  website/docs/Autocompletion.md
Labels: PR: Docs :memo:

#6474 Improve type definition for Sauce Labs capabilities
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Docs :memo:

#6472 Rename `jasmineNodeOpts` into `jasmineOpts`
  examples/wdio.conf.js
  examples/wdio/jasmine/wdio.conf.js
  packages/wdio-cli/src/commands/repl.ts
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/types.ts
  packages/wdio-config/src/constants.ts
  packages/wdio-jasmine-framework/README.md
  packages/wdio-jasmine-framework/src/index.ts
  packages/wdio-jasmine-framework/src/types.ts
  packages/wdio-jasmine-framework/tests/adapter.test.ts
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner-browserstack-android-missing-os.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner-browserstack-android.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner-browserstack-ios.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner.json
  packages/wdio-junit-reporter/tests/__fixtures__/mocha-runner.json
  tests/helpers/config.js
  website/docs/CLI.md
  website/docs/ConfigurationFile.md
  website/docs/Debugging.md
  website/docs/Frameworks.md
  website/docs/Options.md
  website/docs/Timeouts.md
Labels: PR: Bug Fix :bug:

#6476 Cleanup cucumber-framework dependencies
  packages/wdio-cucumber-framework/package.json
Labels: PR: Internal :house:

#6473 better type and document `wdio:devtoolsOptions`
  packages/devtools/README.md
  packages/devtools/src/index.ts
  packages/devtools/src/types.ts
  packages/wdio-types/src/Capabilities.ts
  packages/wdio-types/src/index.ts
  tests/typings/webdriverio/config.ts
Labels: PR: Bug Fix :bug:, needs-review

#6475 Fix auto compile mechanism
  package-lock.json
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/src/types.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/launcher.test.ts
  packages/wdio-config/src/constants.ts
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-config/tests/__mocks__/@wdio/config.ts
  packages/wdio-config/tests/configparser.test.ts
  packages/wdio-runner/src/index.ts
  packages/wdio-runner/tests/index.test.ts
  packages/wdio-types/src/Services.ts
Labels: PR: Bug Fix :bug:, needs-review

#6371 Added goog:chromeOption for passing the debugging port to the devtools chrome launcher (Fix #6370)
  packages/devtools/src/launcher.ts
  packages/devtools/tests/__snapshots__/launcher.test.ts.snap
  packages/devtools/tests/launcher.test.ts
Labels: PR: New Feature :rocket:

#6484 Add og:image and twitter:image
  website/docusaurus.config.js
Labels: PR: Docs :memo:

#6485 change internal variable type to resolve build issue
  packages/wdio-sumologic-reporter/src/index.ts
Labels: PR: Bug Fix :bug:

#6493 docs: fix minor typo
  website/docs/ConfigurationFile.md
Labels: PR: Docs :memo:

#6497 add missing comma for code coverage snippet for devtools service
  packages/wdio-devtools-service/README.md
Labels: PR: Docs :memo:

#6498 add missing type property hex for ParsedColor
  packages/webdriverio/src/types.ts
Labels: PR: Docs :memo:

#6505 Remove unused constants
  packages/webdriverio/src/constants.ts
Labels: PR: Internal :house:

#6504 Fix failed test from conflicting node type definition
  package-lock.json
  package.json
Labels: PR: Internal :house:

#6513 change SC options link
  packages/wdio-sauce-service/README.md
Labels: PR: Docs :memo:
