Repository webdriverio/webdriverio, pull requests merged in 2021-01, with the labels that each got.

#6279 Update webdriverio @types/lodash (and a few other @types) deps to be devDeps
  packages/webdriver/package.json
  packages/webdriverio/package.json
Labels: PR: Internal :house:

#6236 Update fibers to v5 and drop Node.js support for v10
  .github/workflows/deploy.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  jest.config.js
  packages/devtools/package.json
  packages/eslint-plugin-wdio/package.json
  packages/wdio-allure-reporter/package.json
  packages/wdio-appium-service/package.json
  packages/wdio-applitools-service/package.json
  packages/wdio-browserstack-service/package.json
  packages/wdio-cli/package.json
  packages/wdio-concise-reporter/package.json
  packages/wdio-config/package.json
  packages/wdio-crossbrowsertesting-service/package.json
  packages/wdio-cucumber-framework/package.json
  packages/wdio-devtools-service/package.json
  packages/wdio-dot-reporter/package.json
  packages/wdio-firefox-profile-service/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-junit-reporter/package.json
  packages/wdio-local-runner/package.json
  packages/wdio-logger/package.json
  packages/wdio-mocha-framework/package.json
  packages/wdio-protocols/package.json
  packages/wdio-repl/package.json
  packages/wdio-reporter/package.json
  packages/wdio-runner/package.json
  packages/wdio-sauce-service/package.json
  packages/wdio-selenium-standalone-service/package.json
  packages/wdio-shared-store-service/package.json
  packages/wdio-smoke-test-reporter/package.json
  packages/wdio-smoke-test-service/package.json
  packages/wdio-spec-reporter/package.json
  packages/wdio-static-server-service/package.json
  packages/wdio-sumologic-reporter/package.json
  packages/wdio-sync/package.json
  packages/wdio-sync/src/fibers.js
  packages/wdio-testingbot-service/package.json
  packages/wdio-utils/package.json
  packages/wdio-webdriver-mock-service/package.json
  packages/webdriver/package.json
  packages/webdriverio/package.json
  scripts/generateSubPackage.js
Labels: PR: Breaking Change :boom:, needs-review

#6275 TypeScript auto compiling
  docs/TypeScript.md
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  packages/wdio-cli/tests/commands/config.test.ts
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-config/src/utils.ts
  packages/wdio-config/tests/configparser.test.ts
  scripts/depcheck.js
Labels: PR: New Feature :rocket:, needs-review

#6274 Rewrite wdio-sauce-service package to TS
  packages/wdio-sauce-service/src/index.ts
  packages/wdio-sauce-service/src/launcher.ts
  packages/wdio-sauce-service/src/service.js
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/src/types.ts
  packages/wdio-sauce-service/src/utils.ts
  packages/wdio-sauce-service/tests/launcher.test.ts
  packages/wdio-sauce-service/tests/service.test.ts
  packages/wdio-sauce-service/tests/utils.test.ts
  packages/wdio-sauce-service/tsconfig.json
  packages/wdio-sauce-service/tsconfig.prod.json
  packages/webdriver/src/types.ts
  packages/webdriver/webdriver.d.ts
Labels: PR: Internal :house:, needs-review

#6273 Rewrite wdio-sync package to TS
  packages/wdio-sync/package.json
  packages/wdio-sync/src/constants.ts
  packages/wdio-sync/src/executeHooksWithArgs.ts
  packages/wdio-sync/src/fibers.ts
  packages/wdio-sync/src/index.ts
  packages/wdio-sync/src/runFnInFiberContext.ts
  packages/wdio-sync/src/types.ts
  packages/wdio-sync/src/utils.ts
  packages/wdio-sync/src/wrapCommand.ts
  packages/wdio-sync/tests/__mocks__/errors.ts
  packages/wdio-sync/tests/__mocks__/fibers.ts
  packages/wdio-sync/tests/__mocks__/fibers/future.ts
  packages/wdio-sync/tests/executeHooksWithArgs.test.ts
  packages/wdio-sync/tests/fibers.test.ts
  packages/wdio-sync/tests/index.test.ts
  packages/wdio-sync/tests/runFnInFibersContext.test.ts
  packages/wdio-sync/tests/wrapCommand.test.ts
  packages/wdio-sync/tsconfig.json
  packages/wdio-sync/tsconfig.prod.json
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
Labels: PR: Internal :house:, TypeScript, needs-review

#6286 Further TypeScript CLI improvements
  docs/Frameworks.md
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  packages/wdio-cucumber-framework/README.md
  packages/wdio-cucumber-framework/cucumber-framework.d.ts
  packages/wdio-cucumber-framework/src/index.js
Labels: PR: Bug Fix :bug:

#6263 Rewrite CucumberJS Framework Adapter to v7 and TypeScript
  jest.config.js
  package-lock.json
  package.json
  packages/wdio-cucumber-framework/package.json
  packages/wdio-cucumber-framework/src/constants.ts
  packages/wdio-cucumber-framework/src/cucumberEventListener.js
  packages/wdio-cucumber-framework/src/cucumberEventListener.ts
  packages/wdio-cucumber-framework/src/index.js
  packages/wdio-cucumber-framework/src/index.ts
  packages/wdio-cucumber-framework/src/reporter.js
  packages/wdio-cucumber-framework/src/reporter.ts
  packages/wdio-cucumber-framework/src/types.ts
  packages/wdio-cucumber-framework/src/utils.js
  packages/wdio-cucumber-framework/src/utils.ts
  packages/wdio-cucumber-framework/tests/__mocks__/@cucumber/cucumber.ts
  packages/wdio-cucumber-framework/tests/__mocks__/@cucumber/gherkin.ts
  packages/wdio-cucumber-framework/tests/__mocks__/@cucumber/lib/formatter/helpers/event_data_collector.js
  packages/wdio-cucumber-framework/tests/__mocks__/mockery.ts
  packages/wdio-cucumber-framework/tests/__mocks__/moduleA.ts
  packages/wdio-cucumber-framework/tests/__mocks__/moduleB.ts
  packages/wdio-cucumber-framework/tests/__mocks__/moduleC.ts
  packages/wdio-cucumber-framework/tests/__snapshots__/adapter.test.ts.snap
  packages/wdio-cucumber-framework/tests/__snapshots__/reporter.test.ts.snap
  packages/wdio-cucumber-framework/tests/__snapshots__/utils.test.js.snap
  packages/wdio-cucumber-framework/tests/__snapshots__/utils.test.ts.snap
  packages/wdio-cucumber-framework/tests/adapter.test.js
  packages/wdio-cucumber-framework/tests/adapter.test.ts
  packages/wdio-cucumber-framework/tests/eventListener.test.js
  packages/wdio-cucumber-framework/tests/eventListener.test.ts
  packages/wdio-cucumber-framework/tests/fixtures/customModule.js
  packages/wdio-cucumber-framework/tests/fixtures/envelopes.ts
  packages/wdio-cucumber-framework/tests/fixtures/stepDefinitionStub.js
  packages/wdio-cucumber-framework/tests/reporter.test.js
  packages/wdio-cucumber-framework/tests/reporter.test.ts
  packages/wdio-cucumber-framework/tests/utils.test.js
  packages/wdio-cucumber-framework/tests/utils.test.ts
  packages/wdio-reporter/src/index.ts
  packages/wdio-spec-reporter/src/index.js
  packages/wdio-spec-reporter/tests/__fixtures__/testdata.js
  packages/wdio-spec-reporter/tests/index.test.js
  tests/cucumber/reporter/reporter.given.js
  tests/cucumber/step-definitions/given.js
  tests/cucumber/step-definitions/then.js
  tests/helpers/cucumber-hooks.conf.js
  tests/smoke.runner.js
Labels: PR: Breaking Change :boom:, needs-review

#6295 Remove added boilerplate example
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#6172 Start refactoring wdio-browserstack to TypeScript
  packages/wdio-browserstack-service/browserstack-service.d.ts
  packages/wdio-browserstack-service/src/constants.ts
  packages/wdio-browserstack-service/src/index.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/service.js
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/src/types.ts
  packages/wdio-browserstack-service/src/util.js
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/launcher.test.ts
  packages/wdio-browserstack-service/tests/service.test.ts
  packages/wdio-browserstack-service/tests/util.test.ts
  packages/wdio-browserstack-service/tsconfig.json
  packages/webdriver/src/types.ts
  packages/webdriver/webdriver.d.ts
Labels: PR: Internal :house:, TypeScript

#6289 Add new WebDriver extensions
  packages/devtools/tests/utils.test.ts
  packages/wdio-protocols/protocols/chromium.json
  packages/wdio-protocols/protocols/webdriver.json
Labels: PR: New Feature :rocket:

#6276 Lighthouse v7 update
  packages/devtools/tests/__mocks__/puppeteer-core.ts
  packages/wdio-devtools-service/README.md
  packages/wdio-devtools-service/devtools-service.d.ts
  packages/wdio-devtools-service/package.json
  packages/wdio-devtools-service/src/@types/lighthouse.ts
  packages/wdio-devtools-service/src/auditor.ts
  packages/wdio-devtools-service/src/constants.ts
  packages/wdio-devtools-service/src/gatherer/pwa.ts
  packages/wdio-devtools-service/src/gatherer/trace.ts
  packages/wdio-devtools-service/src/index.ts
  packages/wdio-devtools-service/src/scripts/collectMetaElements.ts
  packages/wdio-devtools-service/src/types.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/apple-touch-icon.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/content-width.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/installable-manifest.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/maskable-icon.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/service-worker.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/splash-screen.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/themed-omnibox.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/audits/viewport.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/gather/gather-runner.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/gather/gatherers/link-elements.ts
  packages/wdio-devtools-service/tests/__mocks__/lighthouse/lighthouse-core/gather/gatherers/viewport-dimensions.ts
  packages/wdio-devtools-service/tests/__snapshots__/auditor.test.ts.snap
  packages/wdio-devtools-service/tests/auditor.test.ts
  packages/wdio-devtools-service/tests/gatherer/__snapshots__/pwa.test.ts.snap
  packages/wdio-devtools-service/tests/gatherer/pwa.test.ts
  packages/wdio-devtools-service/tests/gatherer/trace.test.ts
  packages/wdio-devtools-service/tests/service.test.ts
  packages/wdio-sync/webdriverio-core.d.ts
  packages/webdriverio/src/utils/interception/devtools.ts
  packages/webdriverio/webdriverio-core.d.ts
  scripts/templates/webdriverio.tpl.d.ts
  tests/typings/webdriverio-devtools-service/devtools-service.ts
Labels: PR: Breaking Change :boom:, needs-review

#6310 Change sauce update jobname order
  packages/wdio-sauce-service/README.md
  packages/wdio-sauce-service/sauce-service.d.ts
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/src/types.ts
  packages/wdio-sauce-service/tests/service.test.ts
Labels: PR: Polish :nail_care:

#6314 docs: typos, grammar, etc.
  CONTRIBUTING.md
  docs/Contribute.md
  packages/webdriver/README.md
  packages/webdriverio/README.md
Labels: PR: Docs :memo:

#6318 docs: fix the default branch in uses
  docs/GithubActions.md
Labels: PR: Docs :memo:

#6319 Update BoilerplateProjects.md
  docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#6327 Sauce Service: Push error stack to Sauce
  packages/wdio-sauce-service/README.md
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/src/types.ts
  packages/wdio-sauce-service/tests/service.test.ts
Labels: PR: Polish :nail_care:

#6329 Update constants.ts
  packages/wdio-cli/src/constants.ts
Labels: PR: Polish :nail_care:

#6328 Update services.json
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#6330 Move cucumber-framework supporting types to private declaration in browserstack-service
  packages/wdio-browserstack-service/browserstack-service.d.ts
  packages/wdio-browserstack-service/src/@types/cucumber-framework.d.ts
Labels: PR: Bug Fix :bug:

#6326 Better integrate Sauce visual
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-config/src/utils.ts
  packages/wdio-config/tests/configparser.test.ts
  packages/wdio-config/tests/detectBackend.test.ts
Labels: PR: Polish :nail_care:

#6331 Add AWS Device Farm service to docs and CLI
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#6334 Edit pull-file return type
  packages/wdio-protocols/protocols/appium.json
  packages/webdriver/webdriver.d.ts
Labels: PR: Polish :nail_care:

#6355 Adding Delta Reporter to docs and CLI
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/reporters.json
Labels: PR: Docs :memo:, backport-requested

#6364 Better type definition for execute and executeAsync command
  package-lock.json
  packages/webdriverio/src/commands/browser/execute.ts
  packages/webdriverio/src/commands/browser/executeAsync.ts
  packages/webdriverio/src/commands/browser/react$$.ts
  packages/webdriverio/src/commands/browser/react$.ts
  packages/webdriverio/src/commands/element/custom$$.ts
  packages/webdriverio/src/commands/element/custom$.ts
  packages/webdriverio/src/commands/element/getHTML.ts
  packages/webdriverio/src/commands/element/getProperty.ts
  packages/webdriverio/src/commands/element/isClickable.ts
  packages/webdriverio/src/commands/element/isDisplayed.ts
  packages/webdriverio/src/commands/element/isDisplayedInViewport.ts
  packages/webdriverio/src/commands/element/isFocused.ts
  packages/webdriverio/src/commands/element/react$$.ts
  packages/webdriverio/src/commands/element/react$.ts
  packages/webdriverio/src/commands/element/scrollIntoView.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/index.ts
  tests/typings/sync/sync.ts
  tests/typings/webdriverio/async.ts
Labels: PR: New Feature :rocket:
