Repository webdriverio/webdriverio, pull requests merged in 2022-12, with the labels that each got.

#9282 @wdio/browserstack-service: update peer dependencies for v8
  packages/wdio-browserstack-service/package.json
Labels: PR: Bug Fix :bug:

#9283 [🐛 Bug]: grouping specs results in only a single test report
  packages/wdio-runner/src/browser.ts
Labels: PR: Bug Fix :bug:

#9284 [🐛 Bug]: Don't fetch for browser events if `debug` command is called
  packages/wdio-browser-runner/src/browser/commands/index.ts
  packages/wdio-browser-runner/src/browser/driver.ts
  packages/wdio-browser-runner/src/index.ts
  packages/wdio-browser-runner/src/vite/server.ts
  packages/wdio-browser-runner/tests/runner.test.ts
  packages/wdio-browser-runner/tests/vite/server.test.ts
  packages/wdio-local-runner/src/run.ts
  packages/wdio-local-runner/src/worker.ts
  packages/wdio-runner/src/browser.ts
  website/docs/ComponentTesting.md
Labels: PR: Polish :nail_care:

#9292 expect-webdriverio: update packages to use 4.0.1
  packages/wdio-browser-runner/package.json
  packages/wdio-globals/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-runner/package.json
Labels: PR: Internal :house:

#9295 DevX improvements for component testing
  packages/wdio-cli/src/templates/exampleFiles/mocha/example.e2e.js.ejs
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/__snapshots__/templates.test.ts.snap
  packages/wdio-cli/tests/templates.test.ts
  packages/wdio-runner/src/browser.ts
Labels: PR: Polish :nail_care:

#9293 @wdio/globals: use declare var
  packages/wdio-cli/src/commands/repl.ts
  packages/wdio-globals/package.json
  packages/wdio-globals/types.d.ts
  packages/wdio-runner/src/browser.ts
Labels: PR: Bug Fix :bug:

#9297 @wdio/types: add tsconfigs to .npmignore
  packages/wdio-types/.npmignore
Labels: PR: Internal :house:

#9300 Make browser runner work with cloud vendor
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
  packages/wdio-browser-runner/src/index.ts
  packages/wdio-browser-runner/src/vite/server.ts
  packages/wdio-browser-runner/tests/runner.test.ts
  packages/wdio-browser-runner/tests/vite/server.test.ts
  packages/wdio-local-runner/src/worker.ts
  packages/wdio-runner/src/browser.ts
  packages/wdio-runner/src/types.ts
  packages/wdio-sauce-service/package.json
  packages/wdio-sauce-service/src/launcher.ts
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/src/utils.ts
  packages/wdio-sauce-service/tests/launcher.test.ts
  packages/wdio-sauce-service/tests/service.test.ts
Labels: PR: Bug Fix :bug:

#9325 eslint-plugin-wdio: add cjs build
  .gitignore
  packages/eslint-plugin-wdio/.npmignore
  packages/eslint-plugin-wdio/cjs/package.json
  packages/eslint-plugin-wdio/package.json
  packages/eslint-plugin-wdio/tsconfig.cjs.json
  scripts/build.js
Labels: PR: Bug Fix :bug:

#9327 Fixed npm pkg set call for Windows - fixes #9289
  packages/wdio-cli/src/utils.ts
Labels: PR: Bug Fix :bug:

#9328 Firefox DevTools connection improvements
  packages/wdio-browser-runner/a.js
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/utils.test.ts
  packages/wdio-types/src/Capabilities.ts
  packages/webdriverio/src/commands/browser/getPuppeteer.ts
  packages/webdriverio/tests/commands/browser/__snapshots__/getPuppeteer.test.ts.snap
  packages/webdriverio/tests/commands/browser/getPuppeteer.test.ts
Labels: PR: Bug Fix :bug:

#9335 Modified wdio-cli -> utils.test.ts -> getProjectRoot to handle alternate names of clone directory
  packages/wdio-cli/tests/utils.test.ts
Labels: PR: Internal :house:

#9336 Modified globalSetup.ts to make reason and origin of throwBetterErrorMessage more clear
  scripts/test/globalSetup.ts
Labels: PR: Internal :house:

#9341 @wdio/cli: fix typo - finisedCommand
  packages/wdio-cli/src/interface.ts
  packages/wdio-local-runner/src/run.ts
  packages/wdio-local-runner/src/worker.ts
  packages/wdio-local-runner/tests/run.test.ts
  packages/wdio-local-runner/tests/worker.test.ts
Labels: PR: Internal :house:

#9340 @wdio/types: fix return type of hooks
  packages/wdio-types/src/Services.ts
Labels: PR: Polish :nail_care:

#9342 Improve path handling for Windows
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  packages/wdio-cli/tests/templates.test.ts
  packages/wdio-cli/tests/utils.test.ts
  tsconfig.prod.json
Labels: PR: Bug Fix :bug:

#9344 webdriverio: use v7 scrollIntoView implementation for mobile
  packages/webdriverio/src/commands/browser/scroll.ts
  packages/webdriverio/src/commands/element/scrollIntoView.ts
  packages/webdriverio/tests/commands/browser/__snapshots__/scroll.test.ts.snap
  packages/webdriverio/tests/commands/browser/scroll.test.ts
  packages/webdriverio/tests/commands/element/__snapshots__/scrollIntoView.test.ts.snap
  packages/webdriverio/tests/commands/element/scrollIntoView.test.ts
Labels: PR: Bug Fix :bug:

#9347 Add Vitaq service to the v8 documentation
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#9350 minor correction in Example
  packages/webdriverio/src/commands/browser/action.ts
Labels: PR: Docs :memo:

#9354 feat: ability to send headers when connect to browser using puppeteer
  packages/devtools/package.json
  packages/wdio-devtools-service/package.json
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/browser/getPuppeteer.ts
  packages/webdriverio/tests/commands/browser/__snapshots__/getPuppeteer.test.ts.snap
  packages/webdriverio/tests/commands/browser/getPuppeteer.test.ts
  website/docs/Configuration.md
Labels: PR: New Feature :rocket:

#9359 Switch to new Algolia bucket
  website/docusaurus.config.js
Labels: PR: Docs :memo:

#9353 Adding capability support for LambdaTest
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Polish :nail_care:

#9364 Fix launching Appium in service
  packages/wdio-appium-service/package.json
  packages/wdio-appium-service/src/launcher.ts
  packages/wdio-appium-service/tests/__snapshots__/launcher.test.ts.snap
  packages/wdio-appium-service/tests/launcher.test.ts
  packages/wdio-cli/src/utils.ts
Labels: PR: Bug Fix :bug:

#9349 [📖 Docs]: Better Document `Key` import
  packages/webdriverio/src/commands/browser/action.ts
  packages/webdriverio/src/commands/browser/actions.ts
Labels: PR: Docs :memo:

#9365 Explicitly fail if service initialisation fails
  __mocks__/@wdio/scoped-service.ts
  __mocks__/wdio-borked-framework.js
  __mocks__/wdio-launcher-only-service.js
  __mocks__/wdio-scoped-service.js
  packages/wdio-utils/src/initialiseServices.ts
  packages/wdio-utils/src/utils.ts
  packages/wdio-utils/tests/initialiseServices.test.ts
Labels: PR: Bug Fix :bug:

#9366 Improve key actions
  packages/webdriverio/src/commands/browser/keys.ts
  packages/webdriverio/src/utils/actions/key.ts
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/commands/browser/__snapshots__/action.test.ts.snap
  packages/webdriverio/tests/commands/browser/__snapshots__/actions.test.ts.snap
  packages/webdriverio/tests/commands/browser/action.test.ts
  packages/webdriverio/tests/commands/browser/actions.test.ts
  packages/webdriverio/tests/commands/browser/keys.test.ts
Labels: PR: Polish :nail_care:

#9368 Fix fetching shadow elements
  e2e/wdio/cloud/test.e2e.ts
  e2e/wdio/headless/test.e2e.ts
  packages/webdriverio/src/utils/thirdParty/querySelectorShadowDom.ts
Labels: PR: Bug Fix :bug:

#9369 Wait for worker to be ready to receive events
  packages/wdio-cli/src/interface.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-local-runner/src/run.ts
  packages/wdio-local-runner/src/worker.ts
  packages/wdio-local-runner/tests/localRunner.test.ts
  packages/wdio-local-runner/tests/worker.test.ts
Labels: PR: Bug Fix :bug:

#9397 Fix async iterators
  e2e/wdio/headless/test.e2e.ts
  packages/wdio-utils/src/shim.ts
Labels: PR: Bug Fix :bug:

#9398 Fix watch mode by better resolving worker readiness
  packages/wdio-local-runner/src/worker.ts
  packages/wdio-local-runner/tests/localRunner.test.ts
  packages/wdio-local-runner/tests/worker.test.ts
Labels: PR: Bug Fix :bug:

#9399 Kill worker process if parent shuts down
  packages/wdio-cli/package.json
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/tests/commands/run.test.ts
Labels: PR: Bug Fix :bug:

#9386 feat: ability to send headers when connect to browser using puppeteer
  e2e/element.test.js
  e2e/wdio/headless/test.e2e.js
  packages/devtools/package.json
  packages/devtools/src/commands/elementSendKeys.ts
  packages/devtools/src/commands/performActions.ts
  packages/devtools/src/commands/status.ts
  packages/devtools/src/commands/switchToFrame.ts
  packages/devtools/src/commands/switchToParentFrame.ts
  packages/devtools/src/devtoolsdriver.ts
  packages/devtools/src/elementstore.ts
  packages/devtools/src/index.ts
  packages/devtools/src/launcher.ts
  packages/devtools/src/utils.ts
  packages/devtools/tests/__mocks__/puppeteer-core.ts
  packages/devtools/tests/devtools.test.ts
  packages/devtools/tests/elementStore.test.ts
  packages/devtools/tests/launcher.test.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-devtools-service/package.json
  packages/wdio-devtools-service/src/commands.ts
  packages/wdio-devtools-service/src/gatherer/coverage.ts
  packages/wdio-devtools-service/src/gatherer/pwa.ts
  packages/wdio-devtools-service/src/gatherer/trace.ts
  packages/wdio-devtools-service/src/index.ts
  packages/wdio-devtools-service/tests/__mocks__/ws.ts
  packages/wdio-devtools-service/tests/commands.test.ts
  packages/wdio-devtools-service/tests/gatherer/coverage.test.ts
  packages/wdio-devtools-service/tests/gatherer/pwa.test.ts
  packages/wdio-devtools-service/tests/gatherer/trace.test.ts
  packages/wdio-devtools-service/tests/service.test.ts
  packages/wdio-runner/src/index.ts
  packages/wdio-runner/src/utils.ts
  packages/wdio-sync/src/wrapCommand.ts
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/browser/getPuppeteer.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/tests/commands/browser/__snapshots__/getPuppeteer.test.ts.snap
  packages/webdriverio/tests/commands/browser/getPuppeteer.test.ts
  tests/typings/cucumber/tsconfig.json
  tests/typings/devtools/tsconfig.json
  tests/typings/jasmine/tsconfig.json
  tests/typings/mocha/tsconfig.json
  tests/typings/sync/tsconfig.json
  tests/typings/webdriverio/tsconfig.json
  website/docs/Options.md
Labels: PR: Polish :nail_care:

#9403 fix: updated wdio execution command in proxy setup
  website/docs/Proxy.md
Labels: PR: Docs :memo:

#9435 Have fallback for `scrollIntoView` if actions command fails
  __mocks__/got.ts
  packages/webdriverio/src/commands/element/scrollIntoView.ts
  packages/webdriverio/tests/commands/element/scrollIntoView.test.ts
Labels: PR: Bug Fix :bug:

#9438 @wdio/cucumber-framework: add missing Promise.all in registerRequired…
  packages/wdio-cucumber-framework/src/constants.ts
  packages/wdio-cucumber-framework/src/cucumberEventListener.ts
  packages/wdio-cucumber-framework/src/index.ts
  packages/wdio-cucumber-framework/src/reporter.ts
  packages/wdio-cucumber-framework/src/types.ts
  packages/wdio-cucumber-framework/src/utils.ts
Labels: PR: Polish :nail_care:

#9448 docs: Fix a few typos
  examples/standalone/sample.js
  website/docs/ComponentTesting.md
Labels: PR: Docs :memo:

#9441 Add missing noProxy typing for Capabilities ProxyObject
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Polish :nail_care:

#9437 update: mark session as failed if no specs ran
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/tests/service.test.ts
Labels: PR: Polish :nail_care:

#9444 @wdio/types: node16 module resolution compatibility
  packages/wdio-types/src/Capabilities.ts
  packages/wdio-types/src/Clients.ts
  packages/wdio-types/src/Options.ts
  packages/wdio-types/src/Reporters.ts
  packages/wdio-types/src/Services.ts
  packages/wdio-types/src/Workers.ts
  packages/wdio-types/src/index.ts
Labels: PR: Internal :house:

#9471 update: mark session as failed if no specs ran v7
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/tests/service.test.ts
Labels: PR: Polish :nail_care:

#9472 Create CJS export for Allure Reporter
  e2e/interop/allure-reporter.e2e.js
  package-lock.json
  packages/wdio-allure-reporter/cjs/package.json
  packages/wdio-allure-reporter/package.json
  packages/wdio-allure-reporter/src/common/api.ts
  packages/wdio-allure-reporter/src/constants.ts
  packages/wdio-allure-reporter/src/index.ts
  packages/wdio-allure-reporter/src/reporter.ts
  packages/wdio-allure-reporter/src/types.ts
  packages/wdio-allure-reporter/src/utils.ts
  packages/wdio-allure-reporter/tests/allureFeatures.test.ts
  packages/wdio-allure-reporter/tests/api.test.ts
  packages/wdio-allure-reporter/tests/cucumber.suite.test.ts
  packages/wdio-allure-reporter/tests/suite.test.ts
  packages/wdio-allure-reporter/tests/utils.test.ts
  packages/wdio-allure-reporter/tsconfig.cjs.json
  scripts/build.js
Labels: PR: Bug Fix :bug:

#9474 Add extension to type imports for nodenext module resolution
  packages/devtools/src/index.ts
  packages/wdio-protocols/src/index.ts
  packages/webdriver/src/command.ts
  packages/webdriver/src/index.ts
  packages/webdriver/src/request/factory.ts
  packages/webdriver/src/utils.ts
  packages/webdriverio/src/commands/browser/$$.ts
  packages/webdriverio/src/commands/browser/$.ts
  packages/webdriverio/src/commands/browser/custom$$.ts
  packages/webdriverio/src/commands/browser/custom$.ts
  packages/webdriverio/src/commands/browser/mock.ts
  packages/webdriverio/src/commands/browser/newWindow.ts
  packages/webdriverio/src/commands/browser/react$$.ts
  packages/webdriverio/src/commands/browser/react$.ts
  packages/webdriverio/src/commands/browser/throttle.ts
  packages/webdriverio/src/commands/browser/touchAction.ts
  packages/webdriverio/src/commands/browser/waitUntil.ts
  packages/webdriverio/src/commands/element/click.ts
  packages/webdriverio/src/commands/element/custom$$.ts
  packages/webdriverio/src/commands/element/custom$.ts
  packages/webdriverio/src/commands/element/nextElement.ts
  packages/webdriverio/src/commands/element/parentElement.ts
  packages/webdriverio/src/commands/element/previousElement.ts
  packages/webdriverio/src/commands/element/react$$.ts
  packages/webdriverio/src/commands/element/react$.ts
  packages/webdriverio/src/commands/element/touchAction.ts
  packages/webdriverio/src/commands/element/waitForClickable.ts
  packages/webdriverio/src/commands/element/waitForDisplayed.ts
  packages/webdriverio/src/commands/element/waitForEnabled.ts
  packages/webdriverio/src/commands/element/waitForExist.ts
  packages/webdriverio/src/index.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/actions/pointer.ts
  packages/webdriverio/src/utils/actions/wheel.ts
  packages/webdriverio/src/utils/interception/devtools.ts
  packages/webdriverio/src/utils/interception/index.ts
  packages/webdriverio/src/utils/interception/types.ts
  scripts/type-generation/generate-all-typings.js
Labels: PR: Internal :house:

#9394 @wdio/cli: refactor
  packages/wdio-cli/package.json
  packages/wdio-cli/src/@types/async-exit-hooks.d.ts
  packages/wdio-cli/src/index.ts
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/src/run.ts
Labels: PR: Internal :house:

#9476 ci: install package devDependencies
  lerna.json
Labels: PR: Internal :house:

#9484 update lint-staged filter to check for js, ts, mjs, cjs, mts, cts
  .husky/pre-commit
Labels: PR: Internal :house:

#9483 typings setup: use native node.js fs utilities
  tests/typings/setup.js
Labels: PR: Internal :house:

#9482 webdriverio: cast bound function to original type
  packages/webdriverio/src/index.ts
Labels: PR: Polish :nail_care:

#9489 add missing @types/node dependencies
  packages/devtools/package.json
  packages/wdio-allure-reporter/package.json
  packages/wdio-browser-runner/package.json
  packages/wdio-browserstack-service/package.json
  packages/wdio-browserstack-service/tests/util.test.ts
  packages/wdio-cli/package.json
  packages/wdio-crossbrowsertesting-service/package.json
  packages/wdio-cucumber-framework/package.json
  packages/wdio-devtools-service/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-junit-reporter/package.json
  packages/wdio-local-runner/package.json
  packages/wdio-local-runner/src/@types/async-exit-hook.d.ts
  packages/wdio-mocha-framework/package.json
  packages/wdio-repl/package.json
  packages/wdio-reporter/package.json
  packages/wdio-runner/package.json
  packages/wdio-runner/tests/index.test.ts
  packages/wdio-runner/tests/utils.test.ts
  packages/wdio-sauce-service/package.json
  packages/wdio-selenium-standalone-service/package.json
  packages/wdio-smoke-test-cjs-service/package.json
  packages/wdio-smoke-test-service/package.json
  packages/wdio-static-server-service/package.json
  packages/wdio-sumologic-reporter/package.json
  packages/webdriver/package.json
  packages/webdriverio/package.json
Labels: PR: Internal :house:

#9493 pre-commit: only lint staged files
  .husky/pre-commit
Labels: PR: Internal :house:
