Repository webdriverio/webdriverio, pull requests merged in 2022-05, with the labels that each got.

#8300 Fix Jasmine in testrunner
  examples/wdio/jasmine/foo.spec.js
  packages/wdio-utils/src/shim.ts
  tests/jasmine/test-timeout.js
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#8303 Update yargs interface usage
  e2e/element.test.js
  e2e/protocol.test.ts
  jest.config.js
  package-lock.json
  package.json
  packages/wdio-appium-service/tests/launcher.test.ts
  packages/wdio-cli/src/index.ts
  packages/wdio-cli/tests/__mocks__/yargs/yargs.ts
  packages/wdio-cli/tests/commands/config.test.ts
  packages/wdio-cli/tests/commands/install.test.ts
  packages/wdio-cli/tests/commands/repl.test.ts
  packages/wdio-cli/tests/commands/run.test.ts
  packages/wdio-cli/tests/index.test.ts
  packages/wdio-devtools-service/tests/gatherer/coverage.test.ts
  packages/wdio-devtools-service/tests/gatherer/trace.test.ts
  packages/wdio-sumologic-reporter/tests/reporter.test.ts
  packages/webdriverio/tests/commands/browser/pause.test.ts
  tests/resolver.js
Labels: PR: Polish :nail_care:

#8327 update documentation and include example for cucumber
  packages/wdio-allure-reporter/README.md
Labels: PR: Docs :memo:

#8337 fix: browserstack service with local
  packages/wdio-browserstack-service/README.md
  packages/wdio-browserstack-service/src/launcher.ts
Labels: PR: Docs :memo:

#8353 include asnyc await to screenshot example [fix #8323]
  packages/wdio-allure-reporter/README.md
Labels: PR: Docs :memo:

#8349 fix for https://github.com/webdriverio/webdriverio/issues/8335
  packages/wdio-shared-store-service/src/launcher.ts
  packages/wdio-shared-store-service/tests/launcher.test.ts
Labels: PR: Bug Fix :bug:

#8361 add cucumber html reporter
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/reporters.json
Labels: PR: Docs :memo:
