Repository webdriverio/webdriverio, pull requests merged in 2022-08, with the labels that each got.

#8630 Issue 8592: Detailed message for missing config
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/tests/commands/run.test.ts
Labels: PR: Polish :nail_care:, backport-requested

#8633 Issue 8592: Detailed message for missing config - v7
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/tests/commands/run.test.ts
Labels: PR: Polish :nail_care:

#8649 Remove `browser.config` as it is a duplicate of `browser.options`
  packages/wdio-runner/src/index.ts
  tests/mocha/retry_and_pass.js
  website/docs/BrowserObject.md
Labels: PR: Breaking Change :boom:

#8657 reloadSession with DevTools breaks switchWindow command
  __mocks__/puppeteer-core.ts
  packages/devtools/src/devtoolsdriver.ts
  packages/devtools/src/index.ts
  packages/devtools/src/types.ts
  packages/devtools/tests/devtools.test.ts
Labels: PR: Bug Fix :bug:

#8694 fix: skipped tests not showing jasmine pending() reason in spec repor… [MAIN] branch
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/tests/index.test.ts
Labels: PR: Bug Fix :bug:

#8693 Support direct locators in Appium
  packages/webdriverio/src/utils/findStrategy.ts
  packages/webdriverio/tests/findStrategy.test.ts
Labels: PR: Bug Fix :bug:, backport-requested

#8692 Support detailed contexts in TypeScript
  packages/wdio-protocols/protocols/mjsonwp.json
  packages/wdio-protocols/src/types.ts
  packages/webdriverio/src/commands/element/isEqual.ts
  scripts/type-generation/constants.js
  tests/typings/webdriverio/async.ts
Labels: PR: Breaking Change :boom:, backport-requested

#8691 Support prefs when running devtools
  packages/devtools/src/launcher.ts
  packages/devtools/tests/__snapshots__/launcher.test.ts.snap
  packages/devtools/tests/launcher.test.ts
Labels: PR: Bug Fix :bug:, backport-requested

#8765 updated required version from 14 to 18
  CONTRIBUTING.md
Labels: PR: Internal :house:

#8791 (bug):fix missing capas for WinAPPDriver for v7
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Polish :nail_care:
