Repository webdriverio/webdriverio, pull requests merged in 2022-03, with the labels that each got.

#8097 fix: unit tests in windows (resolves file path and build issues in windows)
  .github/workflows/test.yml
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-config/tests/configparser.test.ts
  packages/wdio-shared-store-service/src/@types/shared-store-service.d.ts
Labels: PR: Internal :house:

#8099 Run user hooks before service hooks
  packages/wdio-cli/src/launcher.ts
  packages/wdio-shared-store-service/src/client.ts
Labels: PR: Bug Fix :bug:

#8100 user hook improvements
  examples/pageobject/wdio.conf.js
  examples/wdio.conf.js
  examples/wdio/custom-service/my.custom.service.js
  packages/wdio-cli/src/interface.ts
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/interface.test.ts
  packages/wdio-cli/tests/launcher.test.ts
  packages/wdio-cli/tests/utils.test.ts
  packages/wdio-config/src/constants.ts
  packages/wdio-smoke-test-service/src/index.ts
  packages/wdio-types/src/Services.ts
  packages/webdriverio/src/constants.ts
  tests/helpers/fixtures.js
  tests/smoke.runner.js
  tests/typings/webdriverio/config.ts
  website/docs/ConfigurationFile.md
  website/docs/CustomServices.md
  website/docs/Options.md
Labels: PR: New Feature :rocket:

#8104 replace rm -> rimraf
  package.json
Labels: PR: Internal :house:

#8131 Docs: Typescript updates for async/sync
  website/docs/TypeScript.md
Labels: PR: Docs :memo:

#8136 Fix getSize if prop is 0
  packages/webdriverio/src/commands/element/getSize.ts
  packages/webdriverio/tests/commands/element/getSize.test.ts
Labels: PR: Bug Fix :bug:

#8151 chore(wdio-types): remove implicit dependency on ts-node
  packages/wdio-types/package.json
  packages/wdio-types/src/Compiler.ts
  packages/wdio-types/src/Options.ts
Labels: PR: Polish :nail_care:

#8165 Sanitize script command logs
  packages/wdio-utils/src/utils.ts
  packages/wdio-utils/tests/utils.test.ts
Labels: PR: Polish :nail_care:

#8166 Import config types rather than using namespaces
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
Labels: PR: Polish :nail_care:

#8172 Set empty array as default for plugins when setting up a project
  packages/wdio-cli/src/constants.ts
Labels: PR: Bug Fix :bug:

#8175 Fix maximum call stack size exceeded in Jasmine
  packages/wdio-runner/src/reporter.ts
  packages/wdio-runner/tests/reporter.test.ts
  packages/wdio-utils/src/shim.ts
  tests/jasmine/test-timeout.js
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:
