Repository webdriverio/webdriverio, pull requests merged in 2022-06, with the labels that each got.

#8420 fix: Clear executeScript timeout in case of promise rejection
  e2e/protocol.test.ts
  packages/devtools/src/commands/executeScript.ts
Labels: PR: Bug Fix :bug:

#8434 fix refetch elements with index > 0
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/src/utils/refetchElement.ts
  packages/webdriverio/tests/__mocks__/got.ts
  packages/webdriverio/tests/commands/element/selectByIndex.test.ts
  packages/webdriverio/tests/utils/refetchElement.test.ts
Labels: PR: Bug Fix :bug:

#8456 Added ability to pass capability to repl through config file
  packages/wdio-cli/package.json
  packages/wdio-cli/src/commands/repl.ts
  packages/wdio-cli/src/types.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/__snapshots__/utils.test.ts.snap
  packages/wdio-cli/tests/utils.test.ts
  packages/wdio-protocols/src/index.ts
  packages/webdriver/src/constants.ts
  packages/webdriver/src/utils.ts
  website/docs/repl.md
Labels: PR: New Feature :rocket:

#8457 Improve error message for invalid selectors
  packages/webdriver/src/request/index.ts
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/__snapshots__/utils.test.ts.snap
  packages/webdriver/tests/utils.test.ts
Labels: PR: New Feature :rocket:

#7740 [Bug #7739] Fix preferScenarioName logic
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/tests/service.test.ts
Labels: PR: Bug Fix :bug:

#8464 fix refetch elements error in wdio expect
  packages/webdriverio/src/commands/browser/custom$$.ts
  packages/webdriverio/src/commands/element/custom$$.ts
  packages/webdriverio/tests/commands/browser/customSelectors.test.ts
  packages/webdriverio/tests/commands/element/customSelectors.test.ts
Labels: PR: Bug Fix :bug:

#8466 Add info for a roku-appium boilerplate project
  website/docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#8468 add `cucumber-viewport-logger` service
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#8465 Allow to skip calling `releaseAction` command for click
  packages/webdriverio/src/commands/element/click.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/tests/commands/element/click.test.ts
Labels: PR: New Feature :rocket:
