Repository webdriverio/webdriverio, pull requests merged in 2022-04, with the labels that each got.

#8186 Fix typo on selectors documentation page
  website/docs/Selectors.md
Labels: PR: Docs :memo:

#8196 Update reporters in docs and wizard
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/reporters.json
Labels: PR: Docs :memo:

#8211 Fix running Firefox
  packages/wdio-types/src/Capabilities.ts
  packages/webdriverio/package.json
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/__snapshots__/utils.test.ts.snap
  packages/webdriverio/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#8238 chore: Set permissions for GitHub actions
  .github/workflows/deploy.yml
Labels: PR: Internal :house:

#8241 chore: Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: PR: Internal :house:

#8254 Update repo examples to use async/await
  examples/pageobject/pageobjects/checkbox.page.js
  examples/pageobject/pageobjects/dynamic.page.js
  examples/pageobject/pageobjects/form.page.js
  examples/pageobject/pageobjects/page.js
  examples/pageobject/specs/checkbox.spec.js
  examples/pageobject/specs/dynamic.spec.js
  examples/pageobject/specs/form.spec.js
  examples/pageobject/wdio.conf.js
  examples/wdio/custom-service/mocha.test.js
  examples/wdio/jasmine/jasmine.spec.js
  examples/wdio/mocha/mocha.test.js
Labels: PR: Internal :house:

#8263 Wdio light reporter
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/reporters.json
Labels: PR: Docs :memo:

#8262 Fix #8007 Cucumber skipped steps not appearing in report
  packages/wdio-reporter/src/index.ts
  packages/wdio-reporter/src/stats/test.ts
  packages/wdio-reporter/tests/reporter.test.ts
Labels: PR: Bug Fix :bug:
