Repository webdriverio/webdriverio, pull requests merged in 2022-01, with the labels that each got.

#7853 Update README.md for BrowserStack service
  packages/wdio-browserstack-service/README.md
Labels: PR: Docs :memo:

#7924 Adding Tesults reporter to CLI and reporter list
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/reporters.json
Labels: PR: Docs :memo:

#7894 Fix directConnect
  packages/wdio-types/src/Capabilities.ts
  packages/wdio-types/src/Options.ts
  packages/webdriver/src/constants.ts
  packages/webdriver/src/index.ts
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/index.test.ts
  packages/webdriver/tests/utils.test.ts
  website/docs/Options.md
Labels: PR: Bug Fix :bug:

#7942 Ensure correct reporting when a thread runs more then 1 Cucumber feature (spec)
  packages/wdio-junit-reporter/src/index.ts
Labels: PR: Polish :nail_care:

#7878 Make npm install step optional in CLI wizard
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/types.ts
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  packages/wdio-cli/tests/commands/config.test.ts
Labels: PR: Polish :nail_care:
