Repository webdriverio/webdriverio, pull requests merged in 2022-11, with the labels that each got.

#9103 Fix exclude pattern when cli spec passed v7
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-config/tests/configparser.test.ts
  website/docs/OrganizingTestSuites.md
Labels: PR: Bug Fix :bug:

#9157 [v7] @wdio/types: Add type definition for reporter outputFileFormat
  packages/wdio-concise-reporter/src/index.ts
  packages/wdio-junit-reporter/src/types.ts
  packages/wdio-runner/src/reporter.ts
  packages/wdio-runner/tests/reporter.test.ts
  packages/wdio-types/src/Reporters.ts
Labels: PR: Bug Fix :bug:

#9159 Make spec location relative from config file path and add ability to define project root
  __mocks__/@wdio/config.ts
  examples/wdio/mocha/wdio.conf.js
  examples/wdio/package.json
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/launcher.test.ts
  packages/wdio-cli/tests/utils.test.ts
  packages/wdio-cli/tests/watcher.test.ts
  packages/wdio-config/src/constants.ts
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-config/src/lib/FileSystemPathService.ts
  packages/wdio-config/src/types.ts
  packages/wdio-config/src/utils.ts
  packages/wdio-config/tests/FileSystemPathService.test.ts
  packages/wdio-config/tests/__fixtures__/wdio.conf.ts
  packages/wdio-config/tests/configparser.test.ts
  packages/wdio-config/tests/lib/ConfigParserBuilder.ts
  packages/wdio-config/tests/lib/MockFileContentBuilder.ts
  packages/wdio-mocha-framework/tests/__snapshots__/adapter.test.ts.snap
  packages/wdio-runner/src/index.ts
  packages/wdio-runner/tests/index.test.ts
  packages/wdio-types/src/Options.ts
  packages/wdio-types/src/Workers.ts
  packages/webdriverio/src/constants.ts
  packages/webdriverio/src/index.ts
  tests/smoke.runner.js
  website/blog/2022-11-20-webdriverio-v8-released.md
  website/docs/Configuration.md
  website/docs/OrganizingTestSuites.md
Labels: PR: Breaking Change :boom:

#9177 Fix URLs for webauthn extension capabilities
  packages/wdio-protocols/protocols/webdriver.json
Labels: PR: Spec Compliancy :eyeglasses:

#9228 [v7] Add the Vitaq AI service to the list of services in the v7 WebdriverIO documentation
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#9168 [v7] @wdio/browserstack-service: Add session naming options
  packages/wdio-browserstack-service/README.md
  packages/wdio-browserstack-service/src/constants.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/src/types.ts
  packages/wdio-browserstack-service/tests/service.test.ts
Labels: PR: New Feature :rocket:
