Repository webdriverio/webdriverio, pull requests merged in 2023-07, with the labels that each got.

#10677 Update documentation for cdp network events
  packages/wdio-devtools-service/README.md
Labels: PR: Docs :memo:

#10676 Updating the Boilerplate name
  website/docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#10475 @wdio/allure-reporter cucumber step reporter adds blank steps before and after each scenario bug fixing
  packages/wdio-allure-reporter/src/reporter.ts
  packages/wdio-allure-reporter/tests/cucumber.suite.test.ts
Labels: PR: Bug Fix :bug:

#10684 (@wdio/junit-reporter): fix issue with junit reporter not working on windows
  packages/wdio-junit-reporter/src/index.ts
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-features-with-error-step-and-no-error-object-unordered.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-features-with-error-step-and-no-error-object.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-features-with-failed-then-skipped-steps.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-features-with-pending-step.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-features.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner-browserstack-android-missing-os.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner-browserstack-android.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner-browserstack-ios.json
  packages/wdio-junit-reporter/tests/__fixtures__/cucumber-runner.json
  packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.ts.snap
  packages/wdio-junit-reporter/tests/reporter.test.ts
Labels: PR: Bug Fix :bug:

#10685 (@wdio/jasmine-framework): support sync negative matchers
  packages/wdio-jasmine-framework/src/index.ts
  tests/jasmine/test.js
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#10686 (@wdio/jasmine-framework): support `addMatcher`
  packages/wdio-jasmine-framework/src/index.ts
  packages/wdio-jasmine-framework/tests/adapter.test.ts
  tests/jasmine/test.js
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#10687 (@wdio/cli): support loading of config files with mjs or mts extension
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/tests/commands/config.test.ts
  packages/wdio-cli/tests/commands/run.test.ts
Labels: PR: Polish :nail_care:

#10607 (@wdio/cli): fix CJS interface
  e2e/interop/__fixtures__/wdio.conf.js
  e2e/interop/wdio-cli.e2e.js
  packages/wdio-cli/src/cjs/index.ts
Labels: PR: Bug Fix :bug:

#10688 (docs): add docs on testing vscode extensions
  website/_sidebars.json
  website/docs/VSCodeExtensionTesting.md
  website/static/img/vscode.gif
Labels: PR: Docs :memo:

#10689 (@wdio/cli): improved setup wizard based on testing purpose
  packages/wdio-appium-service/src/launcher.ts
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/templates/exampleFiles/cucumber/step_definitions/steps.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/jasmine/example.e2e.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/mocha/example.e2e.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/mochaJasmine/test.e2e.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/pageobjects/login.page.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/pageobjects/page.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/pageobjects/secure.page.js.ejs
  packages/wdio-cli/src/templates/snippets/afterTest.ejs
  packages/wdio-cli/src/templates/snippets/capabilities.ejs
  packages/wdio-cli/src/templates/snippets/electronTest.js.ejs
  packages/wdio-cli/src/templates/snippets/macosTest.js.ejs
  packages/wdio-cli/src/templates/snippets/reporters.ejs
  packages/wdio-cli/src/templates/snippets/services.ejs
  packages/wdio-cli/src/templates/snippets/testWithPO.js.ejs
  packages/wdio-cli/src/templates/snippets/testWithoutPO.js.ejs
  packages/wdio-cli/src/templates/snippets/vscodeTest.js.ejs
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/types.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/__snapshots__/utils.test.ts.snap
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  packages/wdio-cli/tests/utils.test.ts
  website/_sidebars.json
  website/docs/desktop-testing/Electron.md
  website/docs/desktop-testing/MacOS.md
  website/docs/desktop-testing/Windows.md
  website/docs/extension-testing/VSCodeExtension.md
  website/docs/extension-testing/WebExtension.md
  website/docs/web-extension-testing/TipsAndTricks.md
Labels: PR: New Feature :rocket:

#10691 (@wdio/spec-reporter): recognise bundleId if existing
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/tests/index.test.ts
Labels: PR: Bug Fix :bug:

#9914 (@wdio/spec-reporter): propagate root suite hook errors
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/tests/index.test.ts
Labels: PR: Bug Fix :bug:

#10692 (@wdio/mocha-framework): propagate mocha hook/spec function body to reporter
  packages/wdio-mocha-framework/src/common.ts
  packages/wdio-mocha-framework/src/types.ts
  packages/wdio-mocha-framework/tests/__snapshots__/common.test.ts.snap
  packages/wdio-reporter/src/stats/hook.ts
  packages/wdio-reporter/src/stats/test.ts
  packages/wdio-utils/src/test-framework/testInterfaceWrapper.ts
  packages/wdio-utils/tests/test-framework/testInterfaceWrapper.test.ts
Labels: PR: Polish :nail_care:

#10693 (@wdio/cucumber-framework): count error if hook fails
  packages/wdio-cucumber-framework/src/reporter.ts
Labels: PR: Bug Fix :bug:

#10712 [v7] Fix tests
  packages/webdriverio/tests/findStrategy.test.ts
Labels: PR: Bug Fix :bug:

#10675 Allure report is missing steps, links data when the afterEach() hook is present is the suite #10185
  packages/wdio-allure-reporter/src/reporter.ts
  packages/wdio-allure-reporter/src/utils.ts
  packages/wdio-allure-reporter/tests/__fixtures__/testState.ts
  packages/wdio-allure-reporter/tests/suite.test.ts
  packages/wdio-allure-reporter/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#10727 (@wdio/jasmine-framework): fix matcher
  packages/wdio-jasmine-framework/src/index.ts
  packages/wdio-jasmine-framework/tests/adapter.test.ts
  tests/jasmine/test.js
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#10728 (@wdio/browser-runner): Further improvements to mocking in browser
  e2e/browser-runner/lit.test.js
  e2e/package-lock.json
  e2e/package.json
  packages/wdio-browser-runner/src/browser/setup.ts
  packages/wdio-browser-runner/src/browser/spy.ts
  packages/wdio-browser-runner/src/index.ts
  packages/wdio-browser-runner/src/vite/plugins/mockHoisting.ts
  packages/wdio-browser-runner/src/vite/utils.ts
  packages/wdio-browser-runner/tests/runner.test.ts
  packages/wdio-browser-runner/tests/vite/__snapshots__/utils.test.ts.snap
  packages/wdio-browser-runner/tests/vite/plugins/__fixtures__/test.js
  packages/wdio-browser-runner/tests/vite/plugins/__snapshots__/mockHoisting.test.ts.snap
  packages/wdio-browser-runner/tests/vite/plugins/mockHoisting.test.ts
  packages/wdio-cli/src/launcher.ts
  packages/wdio-local-runner/src/index.ts
  packages/wdio-local-runner/tests/localRunner.test.ts
  packages/wdio-runner/src/browser.ts
  packages/webdriver/tests/__snapshots__/bidi.test.ts.snap
  scripts/bidi/downloadSpec.ts
  scripts/bidi/index.ts
Labels: PR: Bug Fix :bug:

#10731 (webdriver): re-export command
  e2e/interop/webdriver.e2e.js
  packages/webdriver/src/cjs/index.ts
Labels: PR: Bug Fix :bug:

#10732 doc: Update WhyWebdriverIO.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/WhyWebdriverIO.md
Labels: PR: Docs :memo:

#10733 (@wdio/browser-runner): elevate errors happening during test setup
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
  packages/wdio-browser-runner/src/browser/setup.ts
  packages/wdio-concise-reporter/src/index.ts
  packages/wdio-concise-reporter/tests/fixtures.ts
  packages/wdio-concise-reporter/tests/index.test.ts
Labels: PR: Bug Fix :bug:

#10755 Update action.ts example
  packages/webdriverio/src/commands/browser/action.ts
Labels: PR: Docs :memo:

#10757 (@wdio/browser-runner): automatically open in devtools when in watch mode
  packages/wdio-browser-runner/src/index.ts
  packages/wdio-browser-runner/src/utils.ts
  packages/wdio-browser-runner/tests/utils.test.ts
Labels: PR: Polish :nail_care:

#10758 (@wdio/browser-runner): show loading animation
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
Labels: PR: Polish :nail_care:

#10753 (@wdio/browser-runner): more import optimizations
  e2e/browser-runner/lit.test.js
  packages/wdio-browser-runner/src/browser/spy.ts
  packages/wdio-browser-runner/src/constants.ts
  packages/wdio-browser-runner/src/vite/mock.ts
  packages/wdio-browser-runner/src/vite/plugins/mockHoisting.ts
  packages/wdio-browser-runner/src/vite/server.ts
  packages/wdio-browser-runner/src/vite/types.ts
  packages/wdio-browser-runner/tests/vite/plugins/__fixtures__/test.js
  packages/wdio-browser-runner/tests/vite/plugins/__snapshots__/mockHoisting.test.ts.snap
  packages/wdio-browser-runner/tests/vite/plugins/mockHoisting.test.ts
Labels: PR: Polish :nail_care:

#10762 (@wdio/cli): fix component test templates
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.css.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.lit.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.lit.test.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.preact.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.preact.test.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.react.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.react.test.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.solid.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.solid.test.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.svelte.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.svelte.test.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.vue.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.vue.test.ejs
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/__snapshots__/onboarding.test.ts.snap
  packages/wdio-cli/tests/__snapshots__/utils.test.ts.snap
Labels: PR: Bug Fix :bug:

#10751 Fix error in onHookEnd in reporter for Mocha
  packages/wdio-browserstack-service/src/reporter.ts
  packages/wdio-browserstack-service/tests/reporter.test.ts
Labels: PR: Polish :nail_care:

#10768 Fix WhyWebDriverIO.md typos
  website/docs/WhyWebdriverIO.md
Labels: PR: Docs :memo:

#10771 (docs): add a sponsors page
  website/docs/Sponsor.md
  website/docusaurus.config.js
  website/src/components/CreateProjectAnimation.js
  website/src/components/Feature.js
  website/src/components/Feature.module.css
  website/src/components/Features.js
  website/src/components/Highlight.js
  website/src/components/ImageSwitcher.js
  website/src/components/LogoCarousel.js
  website/src/components/LogoCarousel.module.css
  website/src/components/Robot.js
  website/src/components/Robot.module.css
  website/src/components/Section.js
  website/src/components/Section.module.css
  website/src/components/highlight.module.css
  website/src/pages/index.js
  website/src/theme/MDXComponents.js
  website/static/img/sponsors/lambdatest_black.svg
  website/static/img/sponsors/lambdatest_white.svg
Labels: PR: Docs :memo:

#10773 (@wdio/browser-runner): support Nuxt auto-import
  packages/wdio-browser-runner/src/vite/frameworks/index.ts
  packages/wdio-browser-runner/src/vite/frameworks/nuxt.ts
  packages/wdio-browser-runner/src/vite/frameworks/types.d.ts
  packages/wdio-browser-runner/src/vite/frameworks/utils.ts
  packages/wdio-browser-runner/src/vite/server.ts
  packages/wdio-browser-runner/tests/vite/frameworks/__fixtures__/composables/test.ts
  packages/wdio-browser-runner/tests/vite/frameworks/__fixtures__/nuxt.config.ts
  packages/wdio-browser-runner/tests/vite/frameworks/index.test.ts
  packages/wdio-browser-runner/tests/vite/frameworks/nuxt.test.ts
  scripts/depcheck.ts
  website/docs/component-testing/Vue.md
Labels: PR: Polish :nail_care:

#10772 Dev/issue 7735
  examples/wdio/cucumber/features/my-feature.feature
  examples/wdio/cucumber/step-definitions.js
  packages/wdio-cucumber-framework/src/cucumberEventListener.ts
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#10775 (@wdio/browser-runner): improve Nuxt optimization process
  packages/wdio-browser-runner/src/index.ts
  packages/wdio-browser-runner/src/vite/frameworks/index.ts
  packages/wdio-browser-runner/src/vite/frameworks/nuxt.ts
  packages/wdio-browser-runner/src/vite/frameworks/types.d.ts
  packages/wdio-browser-runner/src/vite/server.ts
  packages/wdio-browser-runner/tests/vite/frameworks/index.test.ts
  packages/wdio-browser-runner/tests/vite/frameworks/nuxt.test.ts
  scripts/depcheck.ts
Labels: PR: Bug Fix :bug:

#10776 Update mock.ts
  packages/webdriverio/src/commands/browser/mock.ts
Labels: PR: Docs :memo:

#10777 (@wdio/cli) add Nuxt service to wizard and docs
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/utils.ts
  scripts/docs-generation/3rd-party/services.json
  website/docs/component-testing/Vue.md
  website/src/pages/index.js
  website/static/img/icons/nuxt.svg
Labels: PR: Docs :memo:

#10792 add:v7 changes based on #10772
  examples/wdio/cucumber/features/my-feature.feature
  examples/wdio/cucumber/step-definitions.js
  packages/wdio-cucumber-framework/src/cucumberEventListener.ts
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#10793 (@wdio/browser-runner): support Nuxt alias and ensure plugin is loaded before WDIO related ones
  packages/wdio-browser-runner/src/vite/frameworks/nuxt.ts
  packages/wdio-browser-runner/src/vite/server.ts
  packages/wdio-browser-runner/tests/vite/frameworks/nuxt.test.ts
  website/docs/component-testing/Vue.md
  website/src/pages/index.js
Labels: PR: Polish :nail_care:

#10798 (webdriverio): fix Action types
  packages/webdriverio/src/types.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Bug Fix :bug:

#10799 Update OrganizingTestSuites.md --> added exclude specific test with m…
  website/i18n/ar/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
Labels: PR: Docs :memo:

#10801 Update OrganizingTestSuites.md
  website/docs/OrganizingTestSuites.md
Labels: PR: Docs :memo:

#10802 (@wdio/browser-runner): respect alias when it comes to mocking
  .gitignore
  e2e/__fixtures__/tailwind.config.js
  e2e/browser-runner/components/Component.vue
  e2e/browser-runner/vue.test.js
  e2e/package-lock.json
  e2e/package.json
  package-lock.json
  packages/wdio-browser-runner/src/index.ts
  packages/wdio-browser-runner/src/vite/frameworks/index.ts
  packages/wdio-browser-runner/src/vite/frameworks/nuxt.ts
  packages/wdio-browser-runner/src/vite/frameworks/tailwindcss.ts
  packages/wdio-browser-runner/src/vite/frameworks/types.d.ts
  packages/wdio-browser-runner/src/vite/frameworks/utils.ts
  packages/wdio-browser-runner/src/vite/plugins/mockHoisting.ts
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-browser-runner/src/vite/server.ts
  packages/wdio-browser-runner/src/vite/utils.ts
  packages/wdio-browser-runner/tests/vite/__snapshots__/utils.test.ts.snap
  packages/wdio-browser-runner/tests/vite/frameworks/__fixtures__/tailwind.config.mts
  packages/wdio-browser-runner/tests/vite/frameworks/index.test.ts
  packages/wdio-browser-runner/tests/vite/frameworks/nuxt.test.ts
  packages/wdio-browser-runner/tests/vite/frameworks/tailwindcss.test.ts
  packages/wdio-browser-runner/tests/vite/server.test.ts
  packages/wdio-runner/src/browser.ts
  packages/wdio-utils/package.json
  packages/wdio-utils/src/pIteration.ts
  packages/wdio-utils/src/shim.ts
  packages/wdio-utils/tests/pIteration.test.ts
  website/docs/ComponentTesting.md
  website/docs/SyncAsyncMigration.md
  website/docs/api/Element.md
  website/docs/component-testing/Vue.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/SyncAsyncMigration.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/api/Element.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/SyncAsyncMigration.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/api/Element.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/SyncAsyncMigration.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/SyncAsyncMigration.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/SyncAsyncMigration.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/SyncAsyncMigration.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/api/Element.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/SyncAsyncMigration.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/SyncAsyncMigration.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/SyncAsyncMigration.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/api/Element.md
Labels: PR: Polish :nail_care:

#10813 (@wdio/cli): only add nuxt service if it is a nuxt project
  packages/wdio-cli/src/constants.ts
Labels: PR: Bug Fix :bug:
