Repository webdriverio/webdriverio, pull requests merged in 2023-05, with the labels that each got.

#10297 Check for hostname before setting isMac to true
  packages/webdriverio/src/utils/actions/key.ts
  packages/webdriverio/tests/commands/browser/action.test.ts
Labels: PR: Bug Fix :bug:

#10317 Valid W3C Appium caps only
  packages/devtools/src/index.ts
  packages/devtools/tests/devtools.test.ts
  packages/wdio-allure-reporter/src/reporter.ts
  packages/wdio-allure-reporter/tests/allureFeatures.test.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/tests/launcher.test.ts
  packages/wdio-browserstack-service/tests/service.test.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/utils.test.ts
  packages/wdio-concise-reporter/src/index.ts
  packages/wdio-concise-reporter/tests/index.test.ts
  packages/wdio-reporter/src/utils.ts
  packages/wdio-reporter/tests/utils.test.ts
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/tests/index.test.ts
  packages/wdio-types/src/Capabilities.ts
  packages/wdio-utils/src/envDetector.ts
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/utils.test.ts
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#10327 (fix) wdio-cucumber-framework: fix error after #10134
  packages/wdio-cucumber-framework/src/utils.ts
  packages/wdio-cucumber-framework/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#10324 Update Browser.md
  website/docs/api/Browser.md
Labels: PR: Docs :memo:

#10355 sauce-service: only upload relevant logs for instance
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/tests/service.test.ts
Labels: PR: Bug Fix :bug:

#10359 Fix Appium Doc Links
  packages/wdio-appium-service/README.md
  packages/wdio-protocols/src/protocols/appium.ts
  packages/wdio-protocols/src/protocols/mjsonwp.ts
  packages/wdio-types/src/Capabilities.ts
  packages/webdriverio/src/commands/browser/saveRecordingScreen.ts
  website/docs/Capabilities.md
  website/docs/Configuration.md
  website/docs/api/Protocols.md
  website/i18n/de/docusaurus-plugin-content-docs/current/Capabilities.md
  website/i18n/de/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/de/docusaurus-plugin-content-docs/current/api/Protocols.md
  website/i18n/es/docusaurus-plugin-content-docs/current/Capabilities.md
  website/i18n/es/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/es/docusaurus-plugin-content-docs/current/api/Protocols.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/Capabilities.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/api/Protocols.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/Capabilities.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/api/Protocols.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/Capabilities.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/api/Protocols.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/Capabilities.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/api/Protocols.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/Capabilities.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/api/Protocols.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/Capabilities.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/api/Protocols.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/Capabilities.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/api/Protocols.md
Labels: PR: Docs :memo:

#10368 wdio-cucumber-framework: Don't attempt to filter empty specs
  packages/wdio-cucumber-framework/src/index.ts
  packages/wdio-cucumber-framework/tests/adapter.test.ts
Labels: PR: Bug Fix :bug:

#10415 fix: set sessionName in case of browser.reloadSession
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/tests/service.test.ts
Labels: PR: Bug Fix :bug:

#10417 (browser-runner): avoid responses on map requests
  e2e/wdio/headless/test.e2e.ts
  packages/devtools/src/scripts/executeAsyncScript.ts
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-browser-runner/tests/vite/plugins/testrunner.test.ts
Labels: PR: Bug Fix :bug:

#10413 fix: disable restored mocks
  packages/webdriverio/src/commands/browser/mock.ts
  packages/webdriverio/src/commands/browser/mockRestoreAll.ts
  packages/webdriverio/src/commands/mock/restore.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/src/utils/interception/devtools.ts
  packages/webdriverio/src/utils/interception/index.ts
  packages/webdriverio/src/utils/interception/webdriver.ts
  packages/webdriverio/tests/utils/interception/devtools.test.ts
  packages/webdriverio/tests/utils/interception/webdriver.test.ts
Labels: PR: Bug Fix :bug:

#10423 Corrected a typo
  website/src/pages/index.js
Labels: PR: Docs :memo:

#10421 Support for Jasmine sessions for BrowserStack Test Observability (v8)
  packages/wdio-browserstack-service/package.json
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/performance-tester.ts
  packages/wdio-browserstack-service/src/reporter.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/crash-reporter.test.ts
  packages/wdio-browserstack-service/tests/insights-handler.test.ts
  packages/wdio-browserstack-service/tests/performance-tester.test.ts
  packages/wdio-browserstack-service/tests/reporter.test.ts
  packages/wdio-jasmine-framework/src/reporter.ts
  packages/wdio-jasmine-framework/src/types.ts
Labels: PR: Polish :nail_care:

#10446 update code links for browser->waitUntil
  packages/webdriverio/src/commands/browser/waitUntil.ts
Labels: PR: Docs :memo:

#10454 added new service to services list is named 'wdio-robonut-service'
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#10477 @wdio/allure-reporter: Exporting the addTag method so it can be used
  packages/wdio-allure-reporter/src/common/api.ts
Labels: PR: Polish :nail_care:
