Repository webdriverio/webdriverio, pull requests merged in 2023-04, with the labels that each got.

#10037 added observability and session check in browserstack service
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/launcher.test.ts
  packages/wdio-browserstack-service/tests/service.test.ts
Labels: PR: Polish :nail_care:

#10038 added observability and session check in browserstack service (v7)
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/launcher.test.ts
Labels: PR: Polish :nail_care:

#10116 fix(footer): openjs-fondation logo
  website/docusaurus.config.js
  website/static/img/open-jsf-logo.svg
Labels: PR: Docs :memo:

#10113 Docs - Added Test Observability as a reporter
  README.md
Labels: PR: Docs :memo:

#10091 Fix ScrollIntoView - DeltaX and DeltaY should be rounded
  packages/webdriverio/src/commands/element/scrollIntoView.ts
Labels: PR: Bug Fix :bug:

#10053 Added histroy and testcaseid
  packages/wdio-allure-reporter/src/reporter.ts
Labels: PR: Bug Fix :bug:

#10013 Support for Jasmine sessions for BrowserStack Test Observability
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/insights-handler.test.ts
  packages/wdio-browserstack-service/tests/util.test.ts
Labels: PR: Polish :nail_care:

#10029 shared store resource pool #10010
  e2e/interop/shared-store.e2e.js
  packages/wdio-shared-store-service/README.md
  packages/wdio-shared-store-service/src/@types/polka-stub.d.ts
  packages/wdio-shared-store-service/src/cjs/index.ts
  packages/wdio-shared-store-service/src/client.ts
  packages/wdio-shared-store-service/src/index.ts
  packages/wdio-shared-store-service/src/server.ts
  packages/wdio-shared-store-service/src/service.ts
  packages/wdio-shared-store-service/tests/client.test.ts
  packages/wdio-shared-store-service/tests/server.test.ts
  packages/wdio-shared-store-service/tests/service.test.ts
  tests/helpers/shared-store.conf.js
  tests/mocha/shared-store-service.js
Labels: PR: New Feature :rocket:

#10121 Have better internal API for shared store
  packages/wdio-shared-store-service/src/client.ts
  packages/wdio-shared-store-service/src/index.ts
  packages/wdio-shared-store-service/src/server.ts
  packages/wdio-shared-store-service/src/service.ts
  packages/wdio-shared-store-service/src/types.ts
  packages/wdio-shared-store-service/tests/client.test.ts
  packages/wdio-shared-store-service/tests/server.test.ts
Labels: PR: Polish :nail_care:

#10047 [🐛 Bug]: Selecting Lit as framework when selecting browser runner does not create example files for Lit
  packages/wdio-cli/src/constants.ts
Labels: PR: Bug Fix :bug:

#10128 docs: fix localhost links
  packages/wdio-local-runner/README.md
  website/docs/api/Browser.md
  website/docs/api/Element.md
Labels: PR: Docs :memo:

#10130 Partial content selector improvements
  e2e/browser-runner/lit.test.js
  packages/webdriverio/src/utils/findStrategy.ts
  packages/webdriverio/tests/findStrategy.test.ts
Labels: PR: Bug Fix :bug:

#10132 Alphabetically sort specs file
  packages/wdio-config/src/lib/FileSystemPathService.ts
  packages/wdio-config/tests/FileSystemPathService.test.ts
  website/docs/OrganizingTestSuites.md
Labels: PR: Bug Fix :bug:

#10137 feat(mock): emit 'request', 'overwrite', 'fail', 'match', 'continue' events
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/interception/devtools.ts
  packages/webdriverio/src/utils/interception/index.ts
  packages/webdriverio/src/utils/interception/webdriver.ts
  packages/webdriverio/tests/utils/interception/devtools.test.ts
  website/docs/api/Mock.md
Labels: PR: New Feature :rocket:

#10134 (feature) wdio-cucumber-framework: support `@skip` annotation without `()` for skip tests
  packages/wdio-cucumber-framework/src/utils.ts
  packages/wdio-cucumber-framework/tests/utils.test.ts
  website/docs/Frameworks.md
Labels: PR: New Feature :rocket:

#10129 docs(mock): 'matches' -> 'calls' property
  website/docs/api/Mock.md
Labels: PR: Docs :memo:

#10171 added path.absolute check
  packages/wdio-cli/src/commands/config.ts
Labels: PR: Bug Fix :bug:

#10115 Fixed build issues in v7
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-config/package.json
  packages/wdio-cucumber-framework/package.json
Labels: PR: Bug Fix :bug:

#10176 #9993 Properly set allure history id
  packages/wdio-allure-reporter/src/reporter.ts
  packages/wdio-allure-reporter/src/utils.ts
  packages/wdio-allure-reporter/tests/allureFeatures.test.ts
  packages/wdio-allure-reporter/tests/suite.test.ts
Labels: PR: Bug Fix :bug:

#10179 Fix glob types missing in production env (v7)
  packages/wdio-config/package.json
  packages/wdio-cucumber-framework/package.json
Labels: PR: Bug Fix :bug:

#10172 [📖 Docs]: Add docs on testing Chrome and Firefox Extensions
  website/_sidebars.json
  website/docs/WebExtensionTesting.md
  website/docs/web-extension-testing/TipsAndTricks.md
Labels: Docs 📖, PR: Docs :memo:

#10187 OBS 807 Fix Filepath V7
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/reporter.ts
Labels: PR: Bug Fix :bug:

#10188 feat: export cjs interface for wdio-cli
  packages/wdio-cli/package.json
  packages/wdio-cli/src/cjs/index.ts
  packages/wdio-cli/src/cjs/package.json
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/tests/index.test.ts
  packages/wdio-cli/tests/launcher.test.ts
  packages/wdio-cli/tsconfig.json
  packages/wdio-cli/tsconfig.prod.json
  scripts/build.js
Labels: PR: Bug Fix :bug:

#10199 Update to correct exports for CJS
  packages/wdio-cli/src/cjs/index.ts
Labels: PR: Bug Fix :bug:

#10215 browser-runner: allow tdd UI
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
  packages/wdio-browser-runner/src/vite/utils.ts
  packages/wdio-browser-runner/tests/vite/__snapshots__/utils.test.ts.snap
Labels: PR: Bug Fix :bug:

#10216 browser-runner: support nesting suites
  packages/wdio-runner/src/browser.ts
  packages/wdio-spec-reporter/src/index.ts
Labels: PR: Bug Fix :bug:

#10221 browser-runner: support global fixture through set up scripts
  e2e/browser-runner/__fixtures__/setup.js
  e2e/browser-runner/lit.test.js
  e2e/browser-runner/wdio.conf.js
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
  packages/wdio-browser-runner/src/index.ts
  website/docs/ComponentTesting.md
Labels: PR: Bug Fix :bug:

#10224 Fix ScrollIntoView - correct position for the focus
  __mocks__/got.ts
  e2e/wdio/headless/test.e2e.ts
  packages/webdriverio/src/commands/element/scrollIntoView.ts
  packages/webdriverio/tests/commands/element/__snapshots__/scrollIntoView.test.ts.snap
  packages/webdriverio/tests/commands/element/scrollIntoView.test.ts
Labels: PR: Polish :nail_care:

#10236 networkLogsOptions & interactiveDebugging
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Docs :memo:

#10259 [browserstack-service] [v7] Sending skipped test details for beforeEach, beforeAll and afterEach hooks in mocha
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/insight-handler.test.ts
  packages/wdio-browserstack-service/tests/util.test.ts
Labels: PR: Polish :nail_care:

#10258 [browserstack-service] Sending skipped test details for beforeEach, beforeAll and afterEach hooks in mocha
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/util.test.ts
Labels: PR: Polish :nail_care:

#10282 Fix scrollIntoView for element out of the viewport
  packages/webdriverio/src/commands/element/scrollIntoView.ts
  packages/webdriverio/tests/commands/element/__snapshots__/scrollIntoView.test.ts.snap
  packages/webdriverio/tests/commands/element/scrollIntoView.test.ts
Labels: PR: Bug Fix :bug:

#10288 (feat): Enable mobile set-up through appium-installer
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/templates/reporters.ejs
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/types.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/commands/config.test.ts
  packages/wdio-cli/tests/utils.test.ts
  website/_sidebars.json
  website/docs/Appium.md
  website/docs/DriverBinaries.md
  website/package.json
Labels: PR: New Feature :rocket:
