Repository webdriverio/webdriverio, pull requests merged in 2023-11, with the labels that each got.

#11537 Fix name selector to allow other characters
  packages/webdriverio/src/utils/findStrategy.ts
  packages/webdriverio/tests/findStrategy.test.ts
Labels: PR: Bug Fix :bug:

#11584 (@wdio/protocols): deprecate JSONWireProtocol commands
  packages/wdio-protocols/src/protocols/appium.ts
  packages/wdio-protocols/src/protocols/jsonwp.ts
  packages/wdio-protocols/src/protocols/mjsonwp.ts
  packages/webdriver/src/command.ts
  packages/webdriver/tests/command.test.ts
Labels: PR: Spec Compliancy :eyeglasses:

#11587 (scripts): migrate AWS SDK for JavaScript v2 APIs to v3
  package-lock.json
  package.json
  scripts/updateDocs.js
Labels: PR: Internal :house:

#11589 (webdriverio): keep testrunner options
  packages/wdio-runner/src/utils.ts
  packages/webdriverio/src/index.ts
  tests/mocha/standalone.js
  tests/mocha/test.ts
Labels: PR: Bug Fix :bug:

#11590 (webdriverio): remove type exports
  packages/webdriverio/src/index.ts
Labels: PR: Bug Fix :bug:

#11591 (docs): add tested example snippet to custom selector strategy docs
  packages/webdriverio/src/commands/browser/custom$$.ts
  packages/webdriverio/src/commands/browser/custom$.ts
  packages/webdriverio/src/commands/element/custom$$.ts
  packages/webdriverio/src/commands/element/custom$.ts
  website/docs/Selectors.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/Selectors.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/Selectors.md
  website/i18n/de/docusaurus-plugin-content-docs/current/Selectors.md
  website/i18n/es/docusaurus-plugin-content-docs/current/Selectors.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/Selectors.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/Selectors.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/Selectors.md
  website/i18n/it/docusaurus-plugin-content-docs/current/Selectors.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/Selectors.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/Selectors.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/Selectors.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/Selectors.md
Labels: PR: Docs :memo:

#11611 JSONWP deprecated methods
  packages/wdio-protocols/src/protocols/jsonwp.ts
Labels: PR: Internal :house:

#11464 Fixes issue 9578
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/types.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  packages/wdio-cli/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#11623 (@wdio/json-reporter): add JSON reporter based of `wdio-json-reporter`
  .gitignore
  package-lock.json
  packages/wdio-cli/src/constants.ts
  packages/wdio-json-reporter/.npmignore
  packages/wdio-json-reporter/LICENSE-MIT
  packages/wdio-json-reporter/README.md
  packages/wdio-json-reporter/package.json
  packages/wdio-json-reporter/src/cjs/mergeResults.ts
  packages/wdio-json-reporter/src/cjs/package.json
  packages/wdio-json-reporter/src/index.ts
  packages/wdio-json-reporter/src/mergeResults.ts
  packages/wdio-json-reporter/src/types.ts
  packages/wdio-json-reporter/src/utils.ts
  packages/wdio-json-reporter/tests/__fixtures__/wdio-0-0-json-reporter.json
  packages/wdio-json-reporter/tests/__fixtures__/wdio-0-1-json-reporter.json
  packages/wdio-json-reporter/tests/__snapshots__/index.test.ts.snap
  packages/wdio-json-reporter/tests/index.test.ts
  packages/wdio-json-reporter/tests/mergeResults.test.ts
  packages/wdio-json-reporter/tsconfig.json
  packages/wdio-json-reporter/tsconfig.prod.json
  scripts/docs-generation/3rd-party/reporters.json
  website/src/components/CreateFlowcharts.tsx
Labels: PR: New Feature :rocket:

#11528 [v7][browserstack-service]: Add more CIs
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/launcher.test.ts
  packages/wdio-browserstack-service/tests/util.test.ts
Labels: PR: Polish :nail_care:

#11570 Adding ability to get pseudo-elements css value via getCSSProperty #7709
  packages/webdriverio/src/commands/element/getCSSProperty.ts
Labels: PR: New Feature :rocket:

#11628 Adding back cucumber before & after Hooks support
  packages/wdio-cucumber-framework/src/constants.ts
  packages/wdio-cucumber-framework/src/index.ts
  packages/wdio-cucumber-framework/src/types.ts
  packages/wdio-cucumber-framework/src/utils.ts
  packages/wdio-cucumber-framework/tests/__snapshots__/adapter.test.ts.snap
  packages/wdio-cucumber-framework/tests/adapter.test.ts
Labels: PR: Bug Fix :bug:

#11548 (webdriverio): add throttleCPU and throttleNetwork commands
  packages/wdio-protocols/src/protocols/saucelabs.ts
  packages/webdriverio/src/commands/browser.ts
  packages/webdriverio/src/commands/browser/throttle.ts
  packages/webdriverio/src/commands/browser/throttleCPU.ts
  packages/webdriverio/src/commands/browser/throttleNetwork.ts
  packages/webdriverio/tests/commands/browser/__snapshots__/throttleCPU.test.ts.snap
  packages/webdriverio/tests/commands/browser/__snapshots__/throttleNetwork.test.ts.snap
  packages/webdriverio/tests/commands/browser/throttleCPU.test.ts
  packages/webdriverio/tests/commands/browser/throttleNetwork.test.ts
  tests/typings/webdriverio/async.ts
  website/docs/Debugging.md
Labels: PR: New Feature :rocket:

#11592 (webdriverio): support emulating Web APIs for `geolocation`, `colorScheme`, `userAgent` and `onLine`
  __mocks__/@wdio/logger.ts
  packages/webdriverio/src/commands/browser.ts
  packages/webdriverio/src/commands/browser/emulate.ts
  packages/webdriverio/tests/commands/browser/emulate.test.ts
  website/_sidebars.json
  website/docs/Emulation.md
Labels: PR: New Feature :rocket:

#11446 Make custom$ return Element object when an element is not found
  packages/webdriverio/src/commands/browser/custom$.ts
  packages/webdriverio/src/commands/element/custom$.ts
Labels: PR: Bug Fix :bug:

#11586 (webdriverio): fix aria selector strategy
  e2e/browser-runner/lit.test.js
  packages/webdriverio/src/utils/findStrategy.ts
  packages/webdriverio/tests/__snapshots__/findStrategy.test.ts.snap
Labels: PR: Bug Fix :bug:

#11631 (@wdio/globals): support asymmetric matchers
  package-lock.json
  packages/wdio-browser-runner/package.json
  packages/wdio-globals/package.json
  packages/wdio-globals/src/index.ts
  packages/wdio-jasmine-framework/package.json
  packages/wdio-runner/package.json
  tests/mocha/test.ts
Labels: PR: New Feature :rocket:

#11636 (webdriverio): remove type support for browser commands on element in…
  packages/webdriverio/src/types.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Bug Fix :bug:

#11635 (@wdio/jasmine-framework): typing support for Jasmine matchers
  packages/wdio-jasmine-framework/src/index.ts
  tests/typings/jasmine/config.ts
Labels: PR: Bug Fix :bug:

#11633 (@wdio/protocols): update WebDriver Bidi primitives
  examples/bidi/README.md
  examples/bidi/scripting.js
  package-lock.json
  package.json
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  packages/wdio-cli/tests/commands/config.test.ts
  packages/wdio-protocols/src/protocols/webdriverBidi.ts
  packages/webdriver/src/bidi/core.ts
  packages/webdriver/src/bidi/handler.ts
  packages/webdriver/src/bidi/localTypes.ts
  packages/webdriver/src/bidi/remoteTypes.ts
  packages/webdriverio/src/commands/browser/emulate.ts
  packages/webdriverio/tests/commands/browser/emulate.test.ts
  scripts/bidi/downloadSpec.ts
  scripts/bidi/index.ts
  vitest.config.ts
Labels: PR: Spec Compliancy :eyeglasses:

#11638 (allure-reporter): Align default exports with functions export
  packages/wdio-allure-reporter/src/common/api.ts
Labels: PR: Bug Fix :bug:

#11639 (webdriver): improve WebDriver Bidi integration
  e2e/wdio/headless/bidi.e2e.ts
  e2e/wdio/headless/secondTest.e2e.ts
  e2e/wdio/wdio.local.conf.ts
  examples/bidi/README.md
  examples/bidi/logging.js
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-protocols/src/protocols/webdriverBidi.ts
  packages/wdio-protocols/src/types.ts
  packages/wdio-utils/src/monad.ts
  packages/wdio-utils/src/node/utils.ts
  packages/wdio-utils/tests/node/utils.test.ts
  packages/webdriver/README.md
  packages/webdriver/src/bidi/core.ts
  packages/webdriver/src/bidi/localTypes.ts
  packages/webdriver/src/command.ts
  packages/webdriver/src/index.ts
  packages/webdriver/src/types.ts
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/command.test.ts
  packages/webdriver/tests/index.test.ts
  packages/webdriverio/src/commands/browser/emulate.ts
  packages/webdriverio/src/multiremote.ts
  packages/webdriverio/src/types.ts
  scripts/bidi/index.ts
  vitest.config.ts
Labels: PR: Bug Fix :bug:

#11668 re-register devtools when switching windows
  packages/wdio-devtools-service/src/index.ts
  packages/wdio-devtools-service/tests/service.test.ts
Labels: PR: Bug Fix :bug:

#11644 added workaround scrollIntoView to center to moveTo and click with a…
  e2e/wdio/headless/test.e2e.ts
  packages/webdriverio/src/commands/element/click.ts
  packages/webdriverio/src/commands/element/moveTo.ts
  packages/webdriverio/tests/commands/element/__snapshots__/click.test.ts.snap
  packages/webdriverio/tests/commands/element/__snapshots__/moveTo.test.ts.snap
  packages/webdriverio/tests/commands/element/click.test.ts
  packages/webdriverio/tests/commands/element/moveTo.test.ts
Labels: PR: Bug Fix :bug:

#11667 (webdriver): retry on post requests
  e2e/vitest.config.ts
  packages/wdio-types/src/Options.ts
  packages/wdio-webdriver-mock-service/src/index.ts
  packages/webdriver/src/request/index.ts
  tests/helpers/config.js
Labels: PR: Bug Fix :bug:

#11671 (webdriverio): expose WebdriverIO.ElementArray properly
  packages/webdriverio/src/commands/browser/$$.ts
  packages/webdriverio/src/commands/browser/custom$$.ts
  packages/webdriverio/src/commands/browser/react$$.ts
  packages/webdriverio/src/commands/element/custom$$.ts
  packages/webdriverio/src/commands/element/shadow$$.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/getElementObject.ts
  packages/webdriverio/src/utils/index.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Docs :memo:

#11672 (internal): fix usage of `intialise` wording in variables, comments and elsewhere
  __mocks__/@wdio/local-runner.ts
  __mocks__/@wdio/utils.ts
  examples/wdio.conf.js
  examples/wdio/vite-vue-example/wdio.conf.ts
  packages/wdio-browser-runner/src/index.ts
  packages/wdio-browser-runner/tests/runner.test.ts
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/watcher.ts
  packages/wdio-cli/tests/launcher.test.ts
  packages/wdio-cli/tests/watcher.test.ts
  packages/wdio-config/src/node/ConfigParser.ts
  packages/wdio-jasmine-framework/src/index.ts
  packages/wdio-local-runner/src/index.ts
  packages/wdio-local-runner/tests/localRunner.test.ts
  packages/wdio-mocha-framework/src/index.ts
  packages/wdio-repl/src/index.ts
  packages/wdio-reporter/tests/stats/__snapshots__/suite.test.ts.snap
  packages/wdio-reporter/tests/stats/hook.test.ts
  packages/wdio-reporter/tests/stats/runner.test.ts
  packages/wdio-reporter/tests/stats/suite.test.ts
  packages/wdio-reporter/tests/stats/test.test.ts
  packages/wdio-runner/src/index.ts
  packages/wdio-runner/src/reporter.ts
  packages/wdio-runner/src/utils.ts
  packages/wdio-runner/tests/index-initSession.test.ts
  packages/wdio-runner/tests/utils.test.ts
  packages/wdio-types/src/Services.ts
  packages/wdio-utils/src/index.ts
  packages/wdio-utils/src/initializePlugin.ts
  packages/wdio-utils/src/initializeServices.ts
  packages/wdio-utils/src/utils.ts
  packages/wdio-utils/tests/initializePlugin.test.ts
  packages/wdio-utils/tests/initializeServices.test.ts
  packages/webdriverio/src/commands/browser/debug.ts
  scripts/link.ts
  website/docs/ComponentTesting.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/ComponentTesting.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/ComponentTesting.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/ComponentTesting.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/ComponentTesting.md
  website/i18n/it/docusaurus-plugin-content-docs/current/ComponentTesting.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/ComponentTesting.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/ComponentTesting.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/ComponentTesting.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/ComponentTesting.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/ComponentTesting.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/ComponentTesting.md
  website/src/components/CreateFlowcharts.tsx
Labels: PR: Internal :house:

#11674 Update Sharding Docs
  website/docs/Sharding.md
Labels: PR: Docs :memo:

#11677 Wrap cucumber steps with timeouts.
  packages/wdio-cucumber-framework/src/index.ts
  packages/wdio-cucumber-framework/tests/__snapshots__/adapter.test.ts.snap
  packages/wdio-cucumber-framework/tests/adapter.test.ts
  packages/wdio-utils/src/test-framework/testFnWrapper.ts
Labels: PR: Bug Fix :bug:

#11680 Screenshot data format BrowserStack 🐛
  packages/wdio-browserstack-service/src/insights-handler.ts
Labels: PR: Bug Fix :bug:

#11679 deleted BidiHandler and browser commands from Element type
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/index.ts
Labels: PR: Polish :nail_care:

#11681 (webdriverio): fix isDisplayed for Firefox, updated examples in docs
  packages/wdio-webdriver-mock-service/src/index.ts
  packages/webdriverio/src/commands/element/isDisplayed.ts
  packages/webdriverio/src/commands/element/isDisplayedInViewport.ts
  packages/webdriverio/tests/commands/element/isClickable.test.ts
  packages/webdriverio/tests/commands/element/isDisplayed.test.ts
  packages/webdriverio/tests/commands/element/isDisplayedInViewport.test.ts
  packages/webdriverio/tests/commands/element/waitForDisplayed.test.ts
Labels: PR: Bug Fix :bug:

#11706 fix: guard check for ShadowRoot using `'ShadowRoot' in window` (#11705)
  packages/webdriverio/src/scripts/isElementDisplayed.ts
Labels: PR: Bug Fix :bug:

#11707 (webdriverio): continue to use isElementDisplayed for mobile native tests
  packages/webdriverio/src/commands/element/isDisplayed.ts
  packages/webdriverio/tests/commands/element/isDisplayed.test.ts
Labels: PR: Bug Fix :bug:

#11712 fix: avoid script syntax to support IE11 again (#11711)
  packages/webdriverio/src/scripts/isElementDisplayed.ts
  packages/webdriverio/src/scripts/resq.ts
Labels: PR: Bug Fix :bug:

#11714 (@wdio/runner): support assertion hooks
  package-lock.json
  packages/wdio-browser-runner/package.json
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-config/src/constants.ts
  packages/wdio-globals/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-reporter/src/index.ts
  packages/wdio-runner/package.json
  packages/wdio-runner/src/index.ts
  packages/wdio-runner/tests/index.test.ts
  packages/wdio-smoke-test-cjs-service/src/service.ts
  packages/wdio-smoke-test-reporter/src/index.ts
  packages/wdio-smoke-test-service/src/index.ts
  packages/wdio-types/src/Services.ts
  tests/cucumber/reporter/reporter.given.js
  tests/helpers/fixtures.js
  tests/jasmine/reporter.js
  tests/mocha/reporter.js
  tests/mocha/service.js
  website/docs/Configuration.md
  website/docs/ConfigurationFile.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/de/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/de/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/es/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/es/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/it/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/it/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/Configuration.md
  website/src/css/custom.css
Labels: PR: New Feature :rocket:

#11726 (webdriver): no request retries for action commands
  e2e/vitest.config.ts
  packages/wdio-types/src/Options.ts
  packages/webdriver/src/request/index.ts
  packages/webdriver/tests/__snapshots__/request.test.ts.snap
  packages/webdriver/tests/request.test.ts
  tests/helpers/config.js
Labels: PR: Bug Fix :bug:

#11727 (@wdio/utils): don't throw if returning a chai assertion
  packages/wdio-utils/src/shim.ts
Labels: PR: Bug Fix :bug:

#11752 (@wdio/utils): don't throw if returning null
  packages/wdio-utils/src/shim.ts
Labels: PR: Bug Fix :bug:

#11755 (@webdriverio): add check of element size if subtree is hidden to isElementDisplayed
  packages/webdriverio/src/scripts/isElementDisplayed.ts
Labels: PR: Bug Fix :bug:

#11760 (@wdio/utils): detect sessions that have an app capability set as mobile session
  packages/wdio-utils/src/envDetector.ts
  packages/wdio-utils/tests/envDetector.test.ts
Labels: PR: Bug Fix :bug:

#11756 chore: Fix build and test timeouts
  packages/wdio-browserstack-service/src/cleanup.ts
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/request-handler.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/cleanup.test.ts
Labels: PR: Polish :nail_care:

#11718 removed unused library
  package-lock.json
  packages/wdio-utils/package.json
Labels: PR: Polish :nail_care:
