Repository webdriverio/webdriverio, pull requests merged in 2023-03, with the labels that each got.

#9865 Fix glob issue
  examples/wdio/cucumber/features/my-feature.feature
  examples/wdio/cucumber/step-definitions.js
  examples/wdio/cucumber/wdio.conf.js
  packages/wdio-config/src/lib/FileSystemPathService.ts
Labels: PR: Bug Fix :bug:

#9864 Make `__mocks__` dir optional
  packages/wdio-browser-runner/src/vite/utils.ts
  packages/wdio-browser-runner/tests/__fixtures__/__mocks__/@namespace/otherModule.js
  packages/wdio-browser-runner/tests/__fixtures__/__mocks__/someModule.ts
  packages/wdio-browser-runner/tests/vite/utils.test.ts
Labels: PR: Bug Fix :bug:

#9739 Transform CJS deps to ESM through Vite
  packages/wdio-browser-runner/src/vite/constants.ts
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-browser-runner/src/vite/utils.ts
  packages/wdio-browser-runner/tests/vite/__snapshots__/utils.test.ts.snap
  packages/wdio-runner/src/browser.ts
Labels: PR: Polish :nail_care:

#9867 Ignore file extension of mocked files
  packages/wdio-browser-runner/src/browser/spy.ts
  packages/wdio-browser-runner/src/vite/plugins/mockHoisting.ts
  packages/wdio-browser-runner/tests/vite/plugins/__snapshots__/mockHoisting.test.ts.snap
  packages/wdio-browser-runner/tests/vite/plugins/mockHoisting.test.ts
Labels: PR: Polish :nail_care:

#9872 Improve mocking of namespaced dependencies
  examples/wdio/browser-runner/lit.test.js
  packages/wdio-browser-runner/src/browser/spy.ts
Labels: PR: Bug Fix :bug:

#9880 Allow preset and ViteConfig at the same time
  packages/wdio-browser-runner/src/types.ts
  packages/wdio-browser-runner/src/vite/server.ts
  packages/wdio-browser-runner/tests/vite/__fixtures__/vite.conf.ts
  packages/wdio-browser-runner/tests/vite/server.test.ts
  website/docs/Runner.md
Labels: PR: Polish :nail_care:

#9878 Ignore path for browser tests
  packages/wdio-browser-runner/src/browser/driver.ts
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
  packages/wdio-browser-runner/src/vite/plugins/mockHoisting.ts
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-browser-runner/tests/vite/plugins/mockHoisting.test.ts
  packages/wdio-browser-runner/tests/vite/plugins/testrunner.test.ts
  packages/wdio-runner/src/browser.ts
Labels: PR: Polish :nail_care:

#9883 Aria selector improvements
  packages/webdriverio/src/utils/findStrategy.ts
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/__snapshots__/findStrategy.test.ts.snap
  packages/webdriverio/tests/utils/index.test.ts
Labels: PR: Bug Fix :bug:

#9879 fix: duplicated suite
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-config/tests/configparser.test.ts
Labels: PR: Bug Fix :bug:

#9884 [💡 Feature]: Receive spec and cid properties from browser session
  packages/wdio-browser-runner/src/browser/driver.ts
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
  packages/wdio-browser-runner/src/browser/utils.ts
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-browser-runner/tests/vite/plugins/testrunner.test.ts
  packages/wdio-protocols/src/protocols/webdriver.ts
  packages/wdio-runner/src/browser.ts
  packages/wdio-utils/src/test-framework/errorHandler.ts
  packages/webdriverio/src/types.ts
Labels: PR: Polish :nail_care:, Idea 💡

#9882 [💡 Feature]: Put Mocha setup into a web component
  examples/wdio/package-lock.json
  examples/wdio/package.json
  packages/wdio-browser-runner/src/browser/driver.ts
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
  packages/wdio-browser-runner/src/browser/setup.ts
  packages/wdio-browser-runner/src/constants.ts
  packages/wdio-browser-runner/src/vite/constants.ts
  packages/wdio-browser-runner/src/vite/server.ts
  packages/wdio-browser-runner/src/vite/utils.ts
  packages/wdio-browser-runner/tests/vite/__snapshots__/utils.test.ts.snap
  packages/wdio-browser-runner/tests/vite/utils.test.ts
Labels: PR: Polish :nail_care:, Idea 💡

#9910 [💡 Feature]: Make `ChainablePromiseArray` and `ElementArray` iterable
  packages/webdriverio/src/commands/browser/$$.ts
  packages/webdriverio/src/commands/browser/$.ts
  packages/webdriverio/src/commands/element/$$.ts
  packages/webdriverio/src/commands/element/$.ts
Labels: PR: Docs :memo:, Idea 💡

#9911 [💡 Feature]: Replace `shadowFnFactory` with WebDriver shadow command
  __mocks__/got.ts
  e2e/browser-runner/.env
  e2e/browser-runner/.eslintrc
  e2e/browser-runner/__mocks__/is-url.ts
  e2e/browser-runner/__mocks__/namespace/module.ts
  e2e/browser-runner/__mocks__/someModule.ts
  e2e/browser-runner/components/Component.svelte
  e2e/browser-runner/components/Component.vue
  e2e/browser-runner/components/LitComponent.ts
  e2e/browser-runner/components/PreactComponent.tsx
  e2e/browser-runner/components/ReactComponent.jsx
  e2e/browser-runner/components/constants.ts
  e2e/browser-runner/lit.test.js
  e2e/browser-runner/package.json
  e2e/browser-runner/pr-eact.test.tsx
  e2e/browser-runner/react.test.tsx
  e2e/browser-runner/svelte.test.js
  e2e/browser-runner/tsconfig.json
  e2e/browser-runner/vue.test.js
  e2e/browser-runner/wdio.conf.js
  e2e/package-lock.json
  e2e/package.json
  examples/README.md
  examples/wdio/README.md
  examples/wdio/package.json
  examples/wdio/vite-vue-example/package-lock.json
  examples/wdio/vite-vue-example/package.json
  examples/wdio/vite-vue-example/src/components/HelloWorld.test.ts
  examples/wdio/vite-vue-example/test/tsconfig.json
  examples/wdio/vite-vue-example/wdio.conf.ts
  package.json
  packages/wdio-browser-runner/src/vite/utils.ts
  packages/wdio-protocols/src/protocols/webdriver.ts
  packages/wdio-protocols/src/types.ts
  packages/webdriverio/src/commands/element/shadow$$.ts
  packages/webdriverio/src/commands/element/shadow$.ts
  packages/webdriverio/src/constants.ts
  packages/webdriverio/tests/commands/element/shadow$$.test.ts
  packages/webdriverio/tests/commands/element/shadow$.test.ts
  scripts/type-generation/constants.js
Labels: PR: Spec Compliancy :eyeglasses:, Idea 💡

#9915 chore(docs): fix broken anchor link pointing to localhost in runner doc
  website/docs/Runner.md
Labels: PR: Docs :memo:

#9917 check for mocha in hook
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/tests/insights-handler.test.ts
Labels: PR: Bug Fix :bug:

#9927 [🐛 Bug]: Improve typing for `switchToFrame` command
  packages/devtools/src/commands/switchToFrame.ts
Labels: PR: Polish :nail_care:

#9947 wdio-config: Add multi-run cli flag
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-config/tests/configparser.test.ts
  website/docs/Retry.md
  website/docs/Testrunner.md
Labels: PR: New Feature :rocket:

#9968 Watch mode improvements for browser runner
  .github/workflows/test.yml
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
  packages/wdio-browser-runner/src/browser/setup.ts
  packages/wdio-browser-runner/src/index.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/interface.ts
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/src/templates/exampleFiles/mocha/example.e2e.js.ejs
  packages/wdio-cli/src/watcher.ts
  packages/wdio-cli/tests/__snapshots__/templates.test.ts.snap
  packages/wdio-cli/tests/interface.test.ts
  packages/wdio-cli/tests/launcher.test.ts
  packages/wdio-local-runner/src/worker.ts
  packages/wdio-runner/src/utils.ts
Labels: PR: Polish :nail_care:

#9985 Improve stability of component tests for Safari
  .github/workflows/test.yml
  e2e/browser-runner/lit.test.js
  e2e/browser-runner/wdio.conf.js
  e2e/package-lock.json
  e2e/package.json
  packages/wdio-browser-runner/src/browser/mock.ts
  packages/wdio-browser-runner/src/vite/constants.ts
  packages/wdio-browser-runner/src/vite/plugins/esbuild.ts
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-runner/src/browser.ts
Labels: PR: Bug Fix :bug:

#9991 chore(): updating webdriverio/klassijs-boilerplate
  website/docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#9992 Improve selector for finding elements by tag and content
  e2e/browser-runner/lit.test.js
  e2e/browser-runner/wdio.conf.js
  packages/webdriverio/src/utils/findStrategy.ts
  packages/webdriverio/tests/findStrategy.test.ts
  website/docs/Selectors.md
Labels: PR: Bug Fix :bug:

#9967 [💡 Feature]: Improve onboarding experience for browser tests
  examples/wdio/vite-vue-example/src/components/HelloWorld.test.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.css.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.lit.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.lit.test.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.preact.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.preact.test.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.react.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.react.test.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.solid.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.solid.test.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.svelte.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.svelte.test.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.vue.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.vue.test.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/standalone.test.ejs
  packages/wdio-cli/src/templates/exampleFiles/mocha/example.e2e.js.ejs
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/__snapshots__/onboarding.test.ts.snap
  packages/wdio-cli/tests/__snapshots__/templates.test.ts.snap
  packages/wdio-cli/tests/onboarding.test.ts
  packages/wdio-cli/tests/templates.test.ts
  packages/wdio-cli/tests/utils.test.ts
Labels: help wanted, Idea 💡

#9874 fix(commands): successive scrollIntoView
  e2e/wdio/headless/test.e2e.ts
  packages/webdriverio/src/commands/element/scrollIntoView.ts
  packages/webdriverio/tests/commands/element/__snapshots__/scrollIntoView.test.ts.snap
  packages/webdriverio/tests/commands/element/scrollIntoView.test.ts
Labels: PR: Bug Fix :bug:

#10021 webdriverio: Add missing specFileRetries* to WDIO_DEFAULTS
  packages/webdriverio/src/constants.ts
Labels: PR: Bug Fix :bug:

#10032 Add missing information and fix allure global result for cucumber tests
  packages/wdio-allure-reporter/src/reporter.ts
  packages/wdio-allure-reporter/tests/cucumber.suite.test.ts
Labels: PR: Polish :nail_care:

#10035 Handle `file://` in specs of junit reporter - fixes #9352
  packages/wdio-junit-reporter/src/index.ts
  packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.ts.snap
  packages/wdio-junit-reporter/tests/reporter.test.ts
Labels: PR: Bug Fix :bug:

#10041 [Docs] Fixes to Lit component testing page
  website/docs/component-testing/Lit.md
Labels: PR: Docs :memo:

#10046 Allow selectors to further search for elements by text and tag name
  e2e/browser-runner/lit.test.js
  packages/webdriverio/src/utils/findStrategy.ts
  packages/webdriverio/tests/findStrategy.test.ts
Labels: PR: Bug Fix :bug:

#10048 [🐛 Bug]: browser runner - `alert` or `confirm` stales execution of runner
  .github/workflows/test.yml
  e2e/browser-runner/lit.test.js
  packages/wdio-browser-runner/src/browser/setup.ts
  packages/wdio-browser-runner/src/browser/utils.ts
  packages/wdio-browser-runner/tests/browser/utils.test.ts
  website/docs/Runner.md
Labels: PR: Polish :nail_care:

#10045 Fix handling existence checks for shadow elements
  e2e/browser-runner/lit.test.js
  packages/webdriverio/src/commands/browser/react$$.ts
  packages/webdriverio/src/commands/browser/react$.ts
  packages/webdriverio/src/commands/element/isExisting.ts
  packages/webdriverio/src/commands/element/react$$.ts
  packages/webdriverio/src/commands/element/react$.ts
  packages/webdriverio/src/commands/element/shadow$$.ts
  packages/webdriverio/src/commands/element/shadow$.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/getElementObject.ts
  packages/webdriverio/src/utils/index.ts
Labels: PR: Bug Fix :bug:

#10068 devtools: Attempt to rerun command before waiting for a page load (that might timeout)
  packages/devtools/src/devtoolsdriver.ts
  packages/devtools/tests/__snapshots__/devtoolsdriver.test.ts.snap
  packages/devtools/tests/devtoolsdriver.test.ts
Labels: PR: Polish :nail_care:
