Repository webdriverio/webdriverio, pull requests merged in 2023-08, with the labels that each got.

#10851 (@wdio/cli): improve configuration wizard
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/templates/exampleFiles/cucumber/step_definitions/steps.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/pageobjects/login.page.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/pageobjects/page.js.ejs
  packages/wdio-cli/src/templates/exampleFiles/pageobjects/secure.page.js.ejs
  packages/wdio-cli/src/templates/snippets/capabilities.ejs
  packages/wdio-cli/src/templates/snippets/services.ejs
  packages/wdio-cli/src/templates/snippets/testWithPO.js.ejs
  packages/wdio-cli/src/templates/snippets/testWithoutPO.js.ejs
  packages/wdio-cli/src/templates/snippets/vscodeTest.js.ejs
  packages/wdio-cli/src/types.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  packages/wdio-cli/tests/config.test.ts
  packages/wdio-cli/tests/launcher.test.ts
  packages/wdio-cli/tests/onboarding.test.ts
  packages/wdio-cli/tests/utils.test.ts
Labels: PR: Polish :nail_care:

#10858 [💡 Feature]: Make WebdriverIO load `.env` environments
  package-lock.json
  packages/wdio-cli/package.json
  packages/wdio-cli/src/index.ts
  packages/wdio-cli/tests/index.test.ts
Labels: PR: Polish :nail_care:

#10889 Boilerplate project added to MD
  website/docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#10883 Update launcher.ts to handle defaultViewport
  packages/devtools/src/launcher.ts
  packages/devtools/tests/launcher.test.ts
Labels: PR: Polish :nail_care:

#10902 (webdriver): find good known version when Chromedriver can't be installed with found `buildId`
  .github/workflows/test.yml
  e2e/package-lock.json
  e2e/package.json
  e2e/wdio/wdio.conf.ts
  e2e/wdio/wdio.local.conf.ts
  package-lock.json
  package.json
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-config/src/constants.ts
  packages/webdriver/src/driver/index.ts
  packages/webdriver/tests/driver/index.test.ts
  vitest.config.ts
Labels: PR: Bug Fix :bug:

#10914 [Bug]: Execution steps are missing in allure reports.
  packages/wdio-allure-reporter/src/reporter.ts
Labels: PR: Bug Fix :bug:

#10898 (bugfix): remove acceptInsecureCerts appearences
  examples/devtools/service/wdio.conf.js
  examples/multiremote/chat.js
  examples/multiremote/webrtc.js
  examples/wdio/jasmine/wdio.conf.js
  examples/wdio/mocha/wdio.conf.js
  examples/wdio/vite-vue-example/wdio.conf.ts
  packages/wdio-cli/tests/__snapshots__/utils.test.ts.snap
  packages/wdio-cli/tests/utils.test.ts
  packages/wdio-selenium-standalone-service/tests/launcher.test.ts
  packages/wdio-shared-store-service/tests/launcher.test.ts
  packages/wdio-shared-store-service/tests/service.test.ts
  website/docs/Docker.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/Docker.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/Docker.md
  website/i18n/de/docusaurus-plugin-content-docs/current/Docker.md
  website/i18n/es/docusaurus-plugin-content-docs/current/Docker.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/Docker.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/Docker.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/Docker.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/Docker.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/Docker.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/Docker.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/Docker.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/Docker.md
Labels: PR: Bug Fix :bug:

#10921 (@wdio/config): allow specifying a file name as spec parameter
  e2e/package.json
  packages/wdio-config/src/lib/FileSystemPathService.ts
  packages/wdio-config/src/utils.ts
  packages/wdio-config/tests/FileSystemPathService.test.ts
Labels: PR: Bug Fix :bug:

#10864 (@wdio/jasmine-framework): switch to addMatchingHelperFiles
  packages/wdio-jasmine-framework/src/index.ts
  packages/wdio-jasmine-framework/tests/adapter.test.ts
Labels: PR: Bug Fix :bug:

#10905 (@wdio/selenium-standalone-service): good bye 👋
  README.md
  package-lock.json
  packages/wdio-selenium-standalone-service/.npmignore
  packages/wdio-selenium-standalone-service/LICENSE-MIT
  packages/wdio-selenium-standalone-service/README.md
  packages/wdio-selenium-standalone-service/package.json
  packages/wdio-selenium-standalone-service/src/index.ts
  packages/wdio-selenium-standalone-service/src/launcher.ts
  packages/wdio-selenium-standalone-service/src/types.ts
  packages/wdio-selenium-standalone-service/src/utils.ts
  packages/wdio-selenium-standalone-service/tests/launcher.test.ts
  packages/wdio-selenium-standalone-service/tests/utils.test.ts
  packages/wdio-selenium-standalone-service/tsconfig.json
  packages/wdio-selenium-standalone-service/tsconfig.prod.json
  tests/typings/setup.js
  tests/typings/webdriverio/config.ts
  tests/typings/webdriverio/tsconfig.json
Labels: PR: Internal :house:

#10913 (@wdio/cli): make install command detect config file better
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/commands/install.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/types.ts
  packages/wdio-cli/tests/commands/config.test.ts
  packages/wdio-cli/tests/commands/run.test.ts
Labels: PR: Bug Fix :bug:

#10922 Bump @geckodriver from 4.1.3 to 4.2.0
  package-lock.json
  packages/webdriver/package.json
Labels: PR: Polish :nail_care:

#10923 (webdriverio): fix driver management when calling reloadSession
  e2e/wdio/headless/test.e2e.ts
  packages/wdio-protocols/src/protocols/jsonwp.ts
  packages/wdio-protocols/src/protocols/webdriver.ts
  packages/wdio-protocols/src/types.ts
  packages/webdriver/src/command.ts
  packages/webdriver/src/index.ts
  packages/webdriverio/src/commands/browser/reloadSession.ts
  scripts/type-generation/constants.ts
  scripts/type-generation/generate-all-typings.ts
  vitest.config.ts
Labels: PR: Bug Fix :bug:

#10906 Fix chrome browser name to lower case
  packages/webdriver/src/driver/index.ts
Labels: PR: Polish :nail_care:

#10927 (@wdio/browser-runner): add StencilJS component testing support
  .github/workflows/test.yml
  e2e/browser-runner/components/StencilComponent.tsx
  e2e/browser-runner/stencil.test.tsx
  e2e/browser-runner/tsconfig.json
  e2e/package-lock.json
  e2e/package.json
  e2e/vitest.config.ts
  e2e/wdio/headless/test.e2e.ts
  package-lock.json
  package.json
  packages/wdio-browser-runner/README.md
  packages/wdio-browser-runner/src/types.ts
  packages/wdio-browser-runner/src/vite/constants.ts
  packages/wdio-browser-runner/src/vite/frameworks/fixtures/stencil.ts
  packages/wdio-browser-runner/src/vite/frameworks/index.ts
  packages/wdio-browser-runner/src/vite/frameworks/stencil.ts
  packages/wdio-browser-runner/src/vite/frameworks/types.d.ts
  packages/wdio-browser-runner/stencil/index.d.ts
  packages/wdio-browser-runner/tests/vite/frameworks/stencil.test.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.stencil.ejs
  packages/wdio-cli/src/templates/exampleFiles/browser/Component.stencil.test.ejs
  packages/wdio-cli/src/utils.ts
  scripts/depcheck.ts
  website/_sidebars.json
  website/docs/Runner.md
  website/docs/component-testing/Solid.md
  website/docs/component-testing/Stencil.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/Runner.md
  website/i18n/de/docusaurus-plugin-content-docs/current/Runner.md
  website/i18n/es/docusaurus-plugin-content-docs/current/Runner.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/Runner.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/Runner.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/Runner.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/Runner.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/Runner.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/Runner.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/Runner.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/Runner.md
  website/src/pages/index.js
  website/static/img/icons/stencil.svg
Labels: PR: New Feature :rocket:

#10803 add parallel multiremote capability
  e2e/testrunner.test.ts
  e2e/wdio/headless/multiremoteTest.e2e.ts
  e2e/wdio/wdio-multiremote.conf.ts
  e2e/wdio/wdio.conf.ts
  packages/wdio-appium-service/src/launcher.ts
  packages/wdio-appium-service/tests/launcher.test.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/tests/launcher.test.ts
  packages/wdio-firefox-profile-service/src/launcher.ts
  packages/wdio-firefox-profile-service/tests/launcher.test.ts
  packages/wdio-runner/src/index.ts
  packages/wdio-sauce-service/src/launcher.ts
  packages/wdio-sauce-service/tests/launcher.test.ts
  packages/wdio-testingbot-service/src/launcher.ts
  packages/wdio-testingbot-service/tests/launcher.test.ts
  packages/wdio-types/src/Capabilities.ts
  tests/helpers/parallel-multiremote-config.js
  tests/multiremote/test.js
  tests/smoke.runner.js
  website/docs/Multiremote.md
Labels: PR: New Feature :rocket:

#10952 (webdriver): improvements to driver management
  __mocks__/@wdio/utils.ts
  e2e/wdio/wdio.conf.ts
  e2e/wdio/wdio.local.conf.ts
  package-lock.json
  packages/wdio-browser-runner/src/browser/mock.ts
  packages/wdio-cli/src/interface.ts
  packages/wdio-cli/src/launcher.ts
  packages/wdio-types/src/Capabilities.ts
  packages/wdio-types/src/index.ts
  packages/wdio-utils/package.json
  packages/wdio-utils/src/constants.ts
  packages/wdio-utils/src/driver/index.ts
  packages/wdio-utils/src/driver/manager.ts
  packages/wdio-utils/src/driver/utils.ts
  packages/wdio-utils/src/index.ts
  packages/wdio-utils/src/shim.ts
  packages/wdio-utils/src/utils.ts
  packages/wdio-utils/tests/driver/__snapshots__/utils.test.ts.snap
  packages/wdio-utils/tests/driver/index.test.ts
  packages/wdio-utils/tests/driver/manager.test.ts
  packages/wdio-utils/tests/driver/utils.test.ts
  packages/webdriver/package.json
  packages/webdriver/src/constants.ts
  packages/webdriver/src/driver/index.ts
  packages/webdriver/src/driver/utils.ts
  packages/webdriver/src/index.ts
  tests/typings/setup.js
  tests/typings/webdriverio/tsconfig.json
  tsconfig.prod.json
Labels: PR: Bug Fix :bug:

#10959 (@wdio/utils): detect as remote session when user and key is defined
  packages/wdio-utils/src/driver/utils.ts
  packages/wdio-utils/tests/driver/utils.test.ts
Labels: PR: Bug Fix :bug:

#10971 (@wdio/utils): set edge binary path in caps
  e2e/wdio/wdio.local.conf.ts
  package-lock.json
  packages/wdio-browser-runner/src/browser/mock.ts
  packages/wdio-utils/package.json
  packages/wdio-utils/src/driver/index.ts
  packages/wdio-utils/tests/driver/index.test.ts
  website/docs/DriverBinaries.md
Labels: PR: Bug Fix :bug:

#10975 Adding esmDecorator & unloadFiles
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-mocha-framework/src/index.ts
  packages/wdio-mocha-framework/tests/adapter.test.ts
Labels: PR: Polish :nail_care:

#10998 (@wdio/reporter): support CJS environments
  e2e/interop/wdio-reporter.e2e.js
  packages/wdio-reporter/package.json
  packages/wdio-reporter/tsconfig.cjs.json
  scripts/build.js
Labels: PR: Polish :nail_care:

#10997 Update runner index.ts due to a logs.map error is not a function
  packages/wdio-runner/src/index.ts
Labels: PR: Bug Fix :bug:

#10972 deprecating array of args support in appium service
  packages/wdio-appium-service/README.md
  packages/wdio-appium-service/src/launcher.ts
  packages/wdio-appium-service/src/types.ts
  packages/wdio-appium-service/src/utils.ts
  packages/wdio-appium-service/tests/__snapshots__/launcher.test.ts.snap
  packages/wdio-appium-service/tests/launcher.test.ts
  packages/wdio-appium-service/tests/utils.test.ts
Labels: PR: Polish :nail_care:

#11014 (@wdio/utils): respect custom binary paths in caps
  packages/wdio-types/src/index.ts
  packages/wdio-utils/src/driver/index.ts
  packages/wdio-utils/src/driver/utils.ts
  packages/wdio-utils/tests/driver/index.test.ts
  packages/wdio-utils/tests/driver/utils.test.ts
Labels: PR: Bug Fix :bug:

#11015 (@wdio/utils): have driver manager time out when trying to connect to driver
  packages/wdio-utils/src/driver/index.ts
  packages/wdio-utils/tests/driver/index.test.ts
Labels: PR: Polish :nail_care:

#10999 [📖 Docs]: Better document new driver options and `cacheDir`
  website/docs/Capabilities.md
Labels: PR: Docs :memo:

#11019 (@wdio/utils): ignore space before new line when detecting local Chrome version
  packages/wdio-utils/src/driver/utils.ts
  packages/wdio-utils/tests/driver/utils.test.ts
Labels: PR: Bug Fix :bug:

#11017 docs: AI copilot implementation
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
  website/src/theme/Footer/index.js
  website/static/img/mendable/robot-white.png
Labels: PR: Docs :memo:

#10995 (@wdio/utils): support setup of Firefox browser through @puppeteer/browser
  .github/workflows/test.yml
  e2e/wdio/wdio.local.conf.ts
  package-lock.json
  packages/wdio-browser-runner/src/browser/mock.ts
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-utils/package.json
  packages/wdio-utils/src/driver/index.ts
  packages/wdio-utils/src/driver/manager.ts
  packages/wdio-utils/src/driver/utils.ts
  packages/wdio-utils/tests/driver/__fixtures__/application.ini
  packages/wdio-utils/tests/driver/index.test.ts
  packages/wdio-utils/tests/driver/manager.test.ts
  packages/wdio-utils/tests/driver/utils.test.ts
  website/docs/Capabilities.md
Labels: PR: Polish :nail_care:

#10978 Fix junit reporter test duplication issue for WDIO v7
  packages/wdio-junit-reporter/src/index.ts
  packages/wdio-junit-reporter/tests/__fixtures__/mocha-runner-nested-array-specs.json
  packages/wdio-junit-reporter/tests/__fixtures__/nested-array-suites.json
  packages/wdio-junit-reporter/tests/__fixtures__/nested-suites.json
  packages/wdio-junit-reporter/tests/__fixtures__/suite-test-retry.json
  packages/wdio-junit-reporter/tests/__fixtures__/suites-error.json
  packages/wdio-junit-reporter/tests/__fixtures__/suites-hooks.json
  packages/wdio-junit-reporter/tests/__fixtures__/suites-multiple.json
  packages/wdio-junit-reporter/tests/__fixtures__/suites-with-failed-after-each-hook.json
  packages/wdio-junit-reporter/tests/__fixtures__/suites-with-failed-before-each-hook.json
  packages/wdio-junit-reporter/tests/__fixtures__/suites-with-no-error-object.json
  packages/wdio-junit-reporter/tests/__fixtures__/suites.json
  packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.ts.snap
  packages/wdio-junit-reporter/tests/reporter.test.ts
Labels: PR: Bug Fix :bug:

#11049 fix JSONWP api description typo
  scripts/protocols.ts
Labels: PR: Docs :memo:

#11047 fix footer wrapping
  website/src/theme/Footer/index.js
Labels: PR: Docs :memo:

#11025 Update Capabilities.ts
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Polish :nail_care:

#11053 (@wdio/browser-runner): fix detection of mocked module
  packages/wdio-browser-runner/src/vite/plugins/mockHoisting.ts
Labels: PR: Bug Fix :bug:

#11065 fix(@wdio/cucumber-framework): fix Cucumber types
  packages/wdio-cucumber-framework/src/index.ts
Labels: PR: Bug Fix :bug:

#11061 Fix found typos
  packages/webdriverio/src/constants.ts
  scripts/protocols.ts
  website/docs/desktop-testing/Windows.md
  website/docs/extension-testing/WebExtension.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/WebExtensionTesting.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/WebExtensionTesting.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/WebExtensionTesting.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/WebExtensionTesting.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/WebExtensionTesting.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/WebExtensionTesting.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/WhyWebdriverIO.md
Labels: PR: Docs :memo:

#11066 adding headspin boilerplate
  website/docs/BoilerplateProjects.md
Labels: PR: Docs :memo:
