Repository webdriverio/webdriverio, pull requests merged in 2023-02, with the labels that each got.

#9706 Provide mock primitives from `@vitest/spy`
  examples/wdio/browser-runner/components/LitComponent.ts
  examples/wdio/browser-runner/lit.test.js
  packages/wdio-browser-runner/package.json
  packages/wdio-browser-runner/src/browser/spy.ts
  packages/wdio-browser-runner/src/index.ts
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-browser-runner/tests/runner.test.ts
  packages/wdio-browser-runner/tests/vite/plugins/testrunner.test.ts
  tests/typings/setup.js
  tests/typings/webdriverio/globalImport.ts
  website/_sidebars.json
  website/docs/component-testing/MocksAndSpies.md
Labels: PR: New Feature :rocket:

#9727 Use available Cucumber tag `feature` for Allure label instead of Feature name
  packages/wdio-allure-reporter/README.md
  packages/wdio-allure-reporter/src/index.ts
  packages/wdio-allure-reporter/tests/__fixtures__/cucumber.ts
  packages/wdio-allure-reporter/tests/cucumber.suite.test.ts
Labels: PR: Polish :nail_care:

#9731 extend webdriverbidi command to protocolCommands
  packages/wdio-protocols/src/index.ts
Labels: PR: Bug Fix :bug:

#9733 Use 'modern-node-polyfills' to polyfill node modules
  packages/wdio-browser-runner/package.json
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-browser-runner/src/vite/utils.ts
  packages/wdio-browser-runner/tests/vite/__snapshots__/utils.test.ts.snap
  packages/wdio-browser-runner/tests/vite/plugins/testrunner.test.ts
  packages/webdriverio/src/constants.ts
Labels: PR: Polish :nail_care:

#9735 Transform CJS deps to ESM through Vite
  packages/wdio-browser-runner/src/vite/constants.ts
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-browser-runner/src/vite/utils.ts
  packages/wdio-browser-runner/tests/vite/__snapshots__/utils.test.ts.snap
  packages/wdio-browser-runner/tests/vite/utils.test.ts
Labels: PR: Polish :nail_care:

#9736 build: change module from NodeNext to ESNext, module resolution from Node16 to Node
  packages/devtools/src/cjs/index.ts
  packages/wdio-browser-runner/src/browser/driver.ts
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
  packages/wdio-browser-runner/src/vite/server.ts
  packages/wdio-sauce-service/src/launcher.ts
  packages/wdio-sauce-service/src/service.ts
  packages/webdriver/src/cjs/index.ts
  packages/webdriverio/src/cjs/index.ts
  tsconfig.prod.json
Labels: PR: Internal :house:

#9743 [sauce-service] Add RDC update job support
  packages/wdio-sauce-service/README.md
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/tests/service.test.ts
Labels: PR: Polish :nail_care:, backport-requested

#9767 Have the return type of waitUntil be the return type of the condition
  packages/webdriverio/src/commands/browser/waitUntil.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Bug Fix :bug:

#9768 Don't have users extend `ChainablePromiseElement`
  packages/webdriverio/src/types.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Polish :nail_care:

#9776 RIP Gitter, welcome to the Matrix
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  GOVERNANCE.md
  PROJECT_CHARTER.md
  README.md
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  website/blog/2018-12-19-webdriverio-v5-released.md
  website/blog/2019-05-18-visual-regression-for-v5.md
  website/blog/2019-07-11-cucumberjs-v5-released.md
  website/blog/2019-09-16-devtools.md
  website/blog/2019-12-05-wiremock.md
  website/blog/2020-07-01-office-hours.md
  website/blog/2021-02-09-webdriverio-v7-released.md
  website/blog/2021-07-28-sync-api-deprecation.md
  website/blog/2022-12-01-webdriverio-v8-released.md
  website/community/OpenOfficeHours.md
  website/community/Support.md
  website/docs/GettingStarted.md
  website/docs/WhyWebdriverIO.md
  website/docusaurus.config.js
  website/src/constants.js
Labels: PR: Docs :memo:

#9775 Have same exports for webdriverio cjs and esm module
  packages/webdriverio/src/cjs/index.ts
  packages/webdriverio/tests/module.test.ts
Labels: PR: Bug Fix :bug:

#9808 Reference command examples from recipe repo and allow user to interact with them
  packages/wdio-protocols/src/protocols/webdriver.ts
  packages/webdriverio/src/commands/browser/deleteCookies.ts
  scripts/docs-generation/protocolDocs.ts
  scripts/docs-generation/wdioDocs.js
  scripts/templates/api.tpl.ejs
  scripts/utils/formatter.js
  website/docs/Selectors.md
  website/docs/SetupTypes.md
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
  website/src/css/codeblock.css
  website/src/css/custom.css
Labels: PR: Docs :memo:

#9818 Updated Readme - added testObservability docs
  packages/wdio-browserstack-service/README.md
Labels: PR: Docs :memo:

#9817 Updated Readme - added testObservability docs
  packages/wdio-browserstack-service/README.md
Labels: PR: Docs :memo:

#9806 [Browserstack-service] Support for BuildIdentifier and Fix for LocalIdentifier not adding in BrowserStack Capabilities
  packages/wdio-browserstack-service/README.md
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/types.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/launcher.test.ts
  packages/wdio-types/src/Capabilities.ts
Labels: PR: New Feature :rocket:

#9807 [Browserstack-service] Support for BuildIdentifier and Fix for LocalIdentifier not adding in BrowserStack Capabilities
  packages/wdio-browserstack-service/README.md
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/types.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/launcher.test.ts
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Polish :nail_care:

#9848 fix capabilities link in component testing docs
  website/docs/ComponentTesting.md
Labels: PR: Docs :memo:

#9823 Adds a dev container to help get started with GitHub Codespaces
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/welcome-message.txt
  README.md
Labels: PR: Internal :house:

#9821 Component Testing: Support mocking of modules and external dependencies
  .github/workflows/test.yml
  examples/wdio/browser-runner/__mocks__/is-url.ts
  examples/wdio/browser-runner/__mocks__/namespace/module.ts
  examples/wdio/browser-runner/__mocks__/someModule.ts
  examples/wdio/browser-runner/components/LitComponent.ts
  examples/wdio/browser-runner/components/constants.ts
  examples/wdio/browser-runner/lit.test.js
  examples/wdio/browser-runner/wdio.conf.js
  examples/wdio/package-lock.json
  examples/wdio/package.json
  packages/wdio-browser-runner/package.json
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
  packages/wdio-browser-runner/src/browser/setup.ts
  packages/wdio-browser-runner/src/browser/spy.ts
  packages/wdio-browser-runner/src/constants.ts
  packages/wdio-browser-runner/src/types.ts
  packages/wdio-browser-runner/src/vite/mock.ts
  packages/wdio-browser-runner/src/vite/plugins/mockHoisting.ts
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-browser-runner/src/vite/server.ts
  packages/wdio-browser-runner/src/vite/types.ts
  packages/wdio-browser-runner/src/vite/utils.ts
  packages/wdio-browser-runner/tests/vite/__snapshots__/utils.test.ts.snap
  packages/wdio-browser-runner/tests/vite/plugins/__fixtures__/test.js
  packages/wdio-browser-runner/tests/vite/plugins/__snapshots__/mockHoisting.test.ts.snap
  packages/wdio-browser-runner/tests/vite/plugins/mockHoisting.test.ts
  packages/wdio-browser-runner/tests/vite/plugins/testrunner.test.ts
  packages/wdio-browser-runner/tests/vite/server.test.ts
  packages/wdio-browser-runner/tests/vite/utils.test.ts
  packages/wdio-runner/src/browser.ts
  packages/webdriverio/tests/commands/browser/$$.test.ts
  website/_sidebars.json
  website/docs/MocksAndSpies.md
  website/docs/api/Modules.md
  website/docs/component-testing/MocksAndSpies.md
  website/docs/component-testing/coverage.md
  website/docs/component-testing/mocking.md
Labels: PR: New Feature :rocket:

#9704 Allure2
  __mocks__/@wdio/utils.ts
  packages/wdio-allure-reporter/README.md
  packages/wdio-allure-reporter/package.json
  packages/wdio-allure-reporter/src/common/api.ts
  packages/wdio-allure-reporter/src/constants.ts
  packages/wdio-allure-reporter/src/reporter.ts
  packages/wdio-allure-reporter/src/state.ts
  packages/wdio-allure-reporter/src/types.ts
  packages/wdio-allure-reporter/src/utils.ts
  packages/wdio-allure-reporter/tests/__fixtures__/cucumber.ts
  packages/wdio-allure-reporter/tests/__fixtures__/suite.ts
  packages/wdio-allure-reporter/tests/allureFeatures.test.ts
  packages/wdio-allure-reporter/tests/allureSteps.test.ts
  packages/wdio-allure-reporter/tests/api.test.ts
  packages/wdio-allure-reporter/tests/constants.test.ts
  packages/wdio-allure-reporter/tests/cucumber.suite.test.ts
  packages/wdio-allure-reporter/tests/helpers/wdio-allure-helper.ts
  packages/wdio-allure-reporter/tests/state.test.ts
  packages/wdio-allure-reporter/tests/suite.test.ts
  packages/wdio-allure-reporter/tests/utils.test.ts
Labels: PR: New Feature :rocket:

#9741 Cope with missing requestData
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/tests/insight-handler.test.ts
Labels: PR: Bug Fix :bug:

#9857 Cope with missing command
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/tests/insights-handler.test.ts
Labels: PR: Bug Fix :bug:

#9853 Fixes for module mocking
  packages/wdio-browser-runner/src/browser/spy.ts
  packages/wdio-browser-runner/src/index.ts
  packages/wdio-browser-runner/src/types.ts
  packages/wdio-browser-runner/src/vite/plugins/mockHoisting.ts
  packages/wdio-browser-runner/tests/vite/plugins/__snapshots__/mockHoisting.test.ts.snap
  packages/wdio-browser-runner/tests/vite/plugins/mockHoisting.test.ts
  packages/wdio-browser-runner/tests/vite/utils.test.ts
  tests/typings/webdriverio/globalImport.ts
  vitest.config.mts
Labels: PR: Bug Fix :bug:
