Repository webdriverio/webdriverio, pull requests merged in 2023-01, with the labels that each got.

#9512 browserstack-service: fix reporter
  packages/wdio-browserstack-service/src/service.ts
Labels: PR: Bug Fix :bug:

#9523 fix @types
  .eslintrc.cjs
  .eslintrc.js
  @types/css-shorthand-properties.d.ts
  @types/css-value.d.ts
  @types/junit-report-builder.d.ts
  @types/query-selector-shadow-dom.d.ts
  package.json
  packages/webdriverio/src/utils/index.ts
Labels: PR: Internal :house:

#9522 Fix request retries by using `got` retry feature
  packages/wdio-types/src/Options.ts
  packages/webdriver/src/request/index.ts
  packages/webdriver/src/request/node.ts
Labels: PR: Bug Fix :bug:

#9525 Fix creation of reporter output directories if they don't exist.
  packages/wdio-reporter/src/index.ts
  packages/wdio-reporter/tests/reporter.test.ts
Labels: PR: Bug Fix :bug:

#9526 browserstack-service: fix reporter on v7
  packages/wdio-browserstack-service/src/service.ts
Labels: PR: Bug Fix :bug:

#9527 fix webdriverio version; fs/promises imports
  packages/wdio-appium-service/package.json
  packages/wdio-appium-service/tests/launcher.test.ts
  packages/wdio-browserstack-service/package.json
  packages/wdio-crossbrowsertesting-service/package.json
  packages/wdio-devtools-service/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-sauce-service/package.json
  packages/wdio-shared-store-service/package.json
  packages/wdio-testingbot-service/package.json
  packages/wdio-webdriver-mock-service/package.json
Labels: PR: Internal :house:

#9530 Don't fail wizard if npm pkg set scripts.wdio fails
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/utils.test.ts
Labels: PR: Polish :nail_care:

#9532 remove expect-webdriverio from root dependencies
  examples/wdio/vite-vue-example/package-lock.json
  examples/wdio/vite-vue-example/package.json
  package-lock.json
  package.json
Labels: PR: Internal :house:

#9535 Update wdio-browserstack-service logging for http status codes
  packages/wdio-browserstack-service/src/util.ts
Labels: PR: Polish :nail_care:

#9544 Better transform unicode keys to Puppeteer key map
  packages/devtools/src/commands/performActions.ts
  packages/devtools/src/constants.ts
Labels: PR: Bug Fix :bug:

#9496 fix workaround for Safari 12.0.3
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#9590 pre-commit: don't run eslint if no files to lint
  .husky/pre-commit
Labels: PR: Internal :house:

#9586 @wdio/junit-reporter: remove validator dependency
  packages/wdio-junit-reporter/package.json
  packages/wdio-junit-reporter/src/@types/validator.d.ts
  packages/wdio-junit-reporter/src/utils.ts
  packages/wdio-utils/src/utils.ts
Labels: PR: Bug Fix :bug:

#9615 Remove 'module: ESNext' from config wizard's tsconfig.json template
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/__snapshots__/utils.test.ts.snap
Labels: PR: Bug Fix :bug:

#9588 fix devtools-service browser.cdp events (#9348 #9545)
  packages/wdio-devtools-service/package.json
  packages/wdio-devtools-service/src/index.ts
  packages/wdio-devtools-service/tests/service.test.ts
Labels: PR: Bug Fix :bug:

#9587 Update BoilerplateProjects.md
  website/docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#9477 Make Browserstack service default when browserstack is selected in env
  packages/wdio-cli/src/constants.ts
Labels: PR: Polish :nail_care:

#9622 [v7] Bug fix: TypeError: Cannot read properties of undefined (reading 'uuid')
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/tests/insight-handler.test.ts
Labels: PR: Bug Fix :bug:

#9631 CI: Update reference of GH Action retrying steps due to ownership transfer
  .github/workflows/test.yml
Labels: PR: Internal :house:

#9632 CI: Bump chromedriver from `107` to `109`
  .github/workflows/test.yml
Labels: PR: Internal :house:

#9630 Map Cucumber tags with special names to Allure links
  packages/wdio-allure-reporter/README.md
  packages/wdio-allure-reporter/src/reporter.ts
  packages/wdio-allure-reporter/tests/__fixtures__/cucumber.ts
  packages/wdio-allure-reporter/tests/cucumber.suite.test.ts
Labels: PR: New Feature :rocket:

#9633 Map Cucumber tags with special names to Allure links
  packages/wdio-allure-reporter/README.md
  packages/wdio-allure-reporter/src/index.ts
  packages/wdio-allure-reporter/tests/__fixtures__/cucumber.ts
  packages/wdio-allure-reporter/tests/cucumber.suite.test.ts
Labels: PR: New Feature :rocket:

#9634 Fix failing unit test
  packages/wdio-browserstack-service/tests/insight-handler.test.ts
Labels: PR: Internal :house:

#9640 Export browser and element type primitives in webdriverio package
  packages/webdriverio/src/types.ts
Labels: PR: Bug Fix :bug:

#9641 Implement CJS export for shared-store service
  e2e/interop/shared-store.e2e.js
  package.json
  packages/wdio-shared-store-service/README.md
  packages/wdio-shared-store-service/package.json
  packages/wdio-shared-store-service/src/cjs/index.ts
  packages/wdio-shared-store-service/src/cjs/package.json
  packages/wdio-shared-store-service/tsconfig.json
  packages/wdio-shared-store-service/tsconfig.prod.json
Labels: PR: Bug Fix :bug:

#9638 docs: fix the name of the Stack Overflow tag
  website/community/Support.md
Labels: PR: Docs :memo:

#9664 Improve wdio logging on browser/element objects
  packages/wdio-utils/src/monad.ts
Labels: PR: Polish :nail_care:

#9663 Support Mocha Root Hook Plugins
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-config/tests/configparser.test.ts
  packages/wdio-mocha-framework/src/common.ts
  packages/wdio-mocha-framework/src/index.ts
  packages/wdio-mocha-framework/src/types.ts
  packages/wdio-mocha-framework/tests/__fixtures__/mochaHooks.js
  packages/wdio-mocha-framework/tests/adapter.test.ts
  packages/wdio-runner/src/index.ts
Labels: PR: Bug Fix :bug:

#9667 Fixes to browser runner
  .github/workflows/test.yml
  examples/wdio/browser-runner/package.json
  examples/wdio/browser-runner/wdio.conf.js
  examples/wdio/package-lock.json
  examples/wdio/package.json
  package-lock.json
  package.json
  packages/wdio-browser-runner/package.json
  packages/wdio-browser-runner/src/browser/mock.ts
  packages/wdio-browser-runner/src/vite/constants.ts
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-browser-runner/src/vite/utils.ts
  packages/wdio-browser-runner/tests/vite/__snapshots__/utils.test.ts.snap
  packages/wdio-cli/src/interface.ts
  packages/wdio-cli/tests/utils.test.ts
  packages/wdio-runner/src/browser.ts
  packages/webdriverio/src/constants.ts
Labels: PR: Bug Fix :bug:

#9670 Install Jasmine types if user picks Jasmine and TypeScript
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/__snapshots__/utils.test.ts.snap
  packages/wdio-cli/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#9673 Various browser runner improvements
  __mocks__/yargs.ts
  packages/wdio-browser-runner/src/browser/driver.ts
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-browser-runner/src/vite/server.ts
  packages/wdio-browser-runner/tests/vite/plugins/testrunner.test.ts
  packages/wdio-cli/src/run.ts
  packages/wdio-runner/src/browser.ts
  packages/webdriverio/src/commands/browser/$$.ts
  packages/webdriverio/src/utils/getElementObject.ts
  packages/webdriverio/src/utils/index.ts
Labels: PR: Bug Fix :bug:

#9676 Support test coverage reporting and assertion for browser runner
  __mocks__/@wdio/utils.ts
  examples/wdio/browser-runner/wdio.conf.js
  examples/wdio/package.json
  packages/wdio-browser-runner/package.json
  packages/wdio-browser-runner/src/constants.ts
  packages/wdio-browser-runner/src/index.ts
  packages/wdio-browser-runner/src/types.ts
  packages/wdio-browser-runner/src/utils.ts
  packages/wdio-browser-runner/src/vite/constants.ts
  packages/wdio-browser-runner/src/vite/server.ts
  packages/wdio-browser-runner/tests/__fixtures__/coverage-summary.json
  packages/wdio-browser-runner/tests/runner.test.ts
  packages/wdio-browser-runner/tests/utils.test.ts
  packages/wdio-cli/src/launcher.ts
  packages/wdio-local-runner/src/index.ts
  packages/wdio-runner/src/browser.ts
  packages/wdio-types/src/Services.ts
  website/docs/ComponentTesting.md
  website/docs/Runner.md
Labels: PR: New Feature :rocket:

#9677 [🐛 Bug]: Properly merge coverage reports within `@wdio/runner`
  examples/wdio/browser-runner/react2.test.tsx
  packages/wdio-browser-runner/src/index.ts
  packages/wdio-browser-runner/tests/runner.test.ts
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/src/interface.ts
  packages/wdio-cli/src/types.ts
  packages/wdio-config/src/lib/ConfigParser.ts
  packages/wdio-config/tests/__snapshots__/configparser.test.ts.snap
  packages/wdio-config/tests/configparser.test.ts
  packages/wdio-runner/src/browser.ts
  packages/wdio-runner/src/types.ts
Labels: Bug 🐛, PR: Bug Fix :bug:
