Repository webdriverio/webdriverio, pull requests merged in 2024-01, with the labels that each got.

#11963 Update README.md
  packages/wdio-browserstack-service/README.md
Labels: PR: Docs :memo:

#11966 (docs): add docs on custom matcher
  examples/wdio/vite-vue-example/package.json
  package-lock.json
  packages/wdio-browser-runner/package.json
  packages/wdio-globals/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-runner/package.json
  website/_sidebars.json
  website/docs/CustomMatchers.md
Labels: PR: Docs :memo:

#11981 feat: Implement reporting of test runs to Sauce Labs Insights
  package-lock.json
  packages/wdio-sauce-service/package.json
  packages/wdio-sauce-service/src/ci.ts
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/src/types.ts
  packages/wdio-sauce-service/tests/service.test.ts
Labels: PR: New Feature :rocket:

#11990 Webdriverio: Fix regression in 11711
  packages/webdriverio/src/scripts/isElementDisplayed.ts
Labels: PR: Bug Fix :bug:

#11982 Sauce us east 4
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-types/src/Options.ts
  packages/webdriverio/src/utils/detectBackend.ts
  packages/webdriverio/tests/utils/detectBackend.test.ts
Labels: PR: Polish :nail_care:

#11906 (docs): add documentation on visual testing
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
  website/_sidebars.json
  website/blog/2019-05-18-visual-regression-for-v5.md
  website/docs/VisualTesting.md
  website/docs/accessibility-testing/AxeCore.md
  website/docs/visual-testing/Considerations.md
  website/docs/visual-testing/compare-options.md
  website/docs/visual-testing/faq.md
  website/docs/visual-testing/img/tabbable-chrome-latest-1366x768.png
  website/docs/visual-testing/img/test-output/android.blockouts.png
  website/docs/visual-testing/img/test-output/button-check.png
  website/docs/visual-testing/img/test-output/examplePage-chrome-latest-1366x768.png
  website/docs/visual-testing/img/test-output/fullPage-EmulatorAndroidGoogleAPIPortraitChromeDriver14.0-384x640.png
  website/docs/visual-testing/img/test-output/fullPage-Iphone12Portrait16-390x844.png
  website/docs/visual-testing/img/test-output/fullPage-chrome-latest-1366x768.png
  website/docs/visual-testing/img/test-output/fullpage-check.png
  website/docs/visual-testing/img/test-output/ios.blockouts.png
  website/docs/visual-testing/img/test-output/screen-check.png
  website/docs/visual-testing/img/test-output/screenshot-EmulatorAndroidGoogleAPIPortraitChromeDriver14.0-384x640.png
  website/docs/visual-testing/img/test-output/screenshot-EmulatorAndroidGoogleAPIPortraitNativeWebScreenshot14.0-384x640.png
  website/docs/visual-testing/img/test-output/screenshot-Iphone12Portrait15-390x844.png
  website/docs/visual-testing/img/test-output/wdioLogo-EmulatorAndroidGoogleAPIPortraitNativeWebScreenshot14.0-384x640.png
  website/docs/visual-testing/img/test-output/wdioLogo-Iphone12Portrait16-390x844.png
  website/docs/visual-testing/img/test-output/wdioLogo-chrome-latest-1-1366x768.png
  website/docs/visual-testing/method-options.md
  website/docs/visual-testing/methods.md
  website/docs/visual-testing/service-options.md
  website/docs/visual-testing/test-output.md
  website/docs/visual-testing/writing-tests.md
Labels: PR: Docs :memo:

#11997 [browserstack-service] Add platform version integration data for skipped tests
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/reporter.ts
  packages/wdio-browserstack-service/src/types.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/insights-handler.test.ts
  packages/wdio-browserstack-service/tests/reporter.test.ts
Labels: PR: Polish :nail_care:

#12002 wdio-utils: Fitler invalidateCache from stacktraces
  packages/wdio-utils/src/test-framework/testFnWrapper.ts
  packages/wdio-utils/tests/test-framework/testFnWrapper-async.test.ts
Labels: PR: Polish :nail_care:

#12003 (docs): update electron docs
  .gitignore
  scripts/docs-generation/electronDocs.ts
  scripts/docs-generation/generateDocs.ts
  website/_sidebars.json
  website/docs/desktop-testing/Electron.md
Labels: PR: Docs :memo:

#12034 [browserstack-service] Fix integrations data
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/src/util.ts
Labels: PR: Bug Fix :bug:

#12041 (@wdio/browser-runner): improve performance by less pulling
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
  packages/wdio-browser-runner/src/browser/setup.ts
  packages/wdio-browser-runner/tests/runner.test.ts
  packages/wdio-browser-runner/tests/vite/communicator.test.ts
  packages/wdio-runner/src/browser.ts
  packages/wdio-types/src/Workers.ts
Labels: PR: Bug Fix :bug:

#11957 Fix #11684: Improve AfterTest() for Jasmine
  packages/wdio-jasmine-framework/src/index.ts
  packages/wdio-utils/src/constants.ts
  packages/wdio-utils/src/test-framework/testFnWrapper.ts
  tests/helpers/jasmine-after-hook-validation/expected-results/expectedTestFailed.json
  tests/helpers/jasmine-after-hook-validation/expected-results/expectedTestPassed.json
  tests/helpers/jasmine.after-hook-validation.conf.js
  tests/jasmine/test.after-hook-validation.ts
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#12046 Add QUnit service
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#12052 Update AUTHORS.md
  AUTHORS.md
Labels: PR: Docs :memo:

#12058 (@wdio/cli): add support for snapshot testing
  e2e/browser-runner/__snapshots__/lit.test.js.snap
  e2e/browser-runner/__snapshots__/react.test.tsx.snap
  e2e/browser-runner/lit.test.js
  e2e/browser-runner/react.test.tsx
  e2e/package.json
  e2e/wdio/headless/__snapshots__/test.e2e.ts.snap
  e2e/wdio/headless/test.e2e.ts
  e2e/wdio/wdio.local.conf.ts
  examples/wdio/vite-vue-example/package.json
  package-lock.json
  packages/wdio-browser-runner/package.json
  packages/wdio-browser-runner/src/browser/expect.ts
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
  packages/wdio-cli/package.json
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/interface.ts
  packages/wdio-cli/src/types.ts
  packages/wdio-globals/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-runner/package.json
  packages/wdio-runner/src/browser.ts
  packages/wdio-runner/src/index.ts
  packages/wdio-runner/src/types.ts
  packages/wdio-runner/tests/index.test.ts
  packages/wdio-types/src/Options.ts
  packages/wdio-types/src/Workers.ts
  website/_sidebars.json
  website/docs/Snapshot.md
Labels: PR: New Feature :rocket:

#12076 Added default name for tms link to be displayed in allure reports
  packages/wdio-allure-reporter/src/reporter.ts
Labels: PR: Bug Fix :bug:

#12080 (docs): add governance policies around using donation funds
  .github/workflows/labeler.yml
  BACKERS.md
  GOVERNANCE.md
  package-lock.json
  package.json
  scripts/expense.ts
  scripts/templates/expenseMail.tsx
  tsconfig.json
Labels: PR: Docs :memo:

#12072 chore(devtools):
  packages/devtools/README.md
  packages/wdio-types/src/Options.ts
  website/docs/AutomationProtocols.md
  website/docs/Configuration.md
Labels: PR: Docs :memo:

#12088 (@wdio/cli): use -s for updating snapshots as -u is used to provide a username
  packages/wdio-cli/src/commands/run.ts
  website/docs/Snapshot.md
Labels: PR: Bug Fix :bug:

#12089 (@wdio/cli): use proper package manager when asking if to install
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/install.ts
  packages/wdio-cli/src/types.ts
  packages/wdio-cli/src/utils.ts
Labels: PR: Bug Fix :bug:

#12036 blog post for "Enhanced Test Automation" book
  website/blog/2024-01-18-Enhanced Test Automation with WebdriverIO.md
  website/blog/assets/enhanced-test-automation-webdriverio/Cover.png
Labels: PR: Docs :memo:

#12098 Update allure report links
  packages/wdio-allure-reporter/README.md
Labels: PR: Docs :memo:

#12093 (@wdio/browser-runner): improved stencil test integration
  e2e/browser-runner/.eslintrc
  e2e/browser-runner/components/StencilComponent.tsx
  e2e/browser-runner/components/StencilComponentNested.tsx
  e2e/browser-runner/components/stencil.css
  e2e/browser-runner/stencil.test.tsx
  packages/wdio-browser-runner/package.json
  packages/wdio-browser-runner/src/vite/frameworks/fixtures/stencil.ts
  packages/wdio-browser-runner/src/vite/frameworks/stencil.ts
  packages/wdio-browser-runner/tests/vite/frameworks/stencil.test.ts
  packages/wdio-runner/src/browser.ts
Labels: PR: Polish :nail_care:

#12103 (webdriverio): make puppeteer a peer dependency
  package-lock.json
  packages/wdio-cucumber-framework/src/index.ts
  packages/wdio-cucumber-framework/src/types.ts
  packages/wdio-cucumber-framework/tests/adapter.test.ts
  packages/wdio-utils/src/index.ts
  packages/wdio-utils/src/utils.ts
  packages/wdio-utils/tests/utils.test.ts
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/browser/getPuppeteer.ts
  packages/webdriverio/src/commands/browser/mock.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/interception/devtools.ts
  packages/webdriverio/src/utils/interception/types.ts
  packages/webdriverio/tests/commands/browser/getPuppeteer.test.ts
  packages/webdriverio/tests/commands/browser/throttleCPU.test.ts
  packages/webdriverio/tests/commands/browser/throttleNetwork.test.ts
Labels: PR: Breaking Change :boom:, v9

#12124 (docs): partnership with BrowserStack
  BACKERS.md
  README.md
  packages/webdriverio/README.md
  website/blog/2024-01-29-browserstack-partnership.md
  website/docs/Sponsor.md
  website/docusaurus.config.ts
  website/src/components/Feature.module.css
  website/src/components/ImageSwitcher.tsx
  website/src/constants.tsx
  website/src/css/custom.css
  website/src/css/sponsors.css
  website/src/pages/index.tsx
  website/static/img/blog/wdio-plus-bs-black.png
  website/static/img/blog/wdio-plus-bs-white.png
  website/static/img/sponsors/browserstack_black.svg
  website/static/img/sponsors/browserstack_white.svg
Labels: PR: Docs :memo:

#12127 update ua-parser-js for ReDoS
  package-lock.json
  packages/devtools/package.json
Labels: PR: Polish :nail_care:

#12044 Issue 11996: Not skip duplicate steps
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/tests/__fixtures__/testdata.ts
  packages/wdio-spec-reporter/tests/__snapshots__/index.test.ts.snap
Labels: PR: Bug Fix :bug:

#12129 Fix problem with tests which had been finished before the parent suite finished
  packages/wdio-allure-reporter/src/reporter.ts
  packages/wdio-allure-reporter/tests/cucumber.suite.test.ts
Labels: PR: Bug Fix :bug:

#12131 Missing ' in $$ example
  packages/webdriverio/src/commands/browser/$$.ts
Labels: PR: Docs :memo:

#12077 Feat: Add free text search to '--exclude' param
  packages/wdio-config/src/node/ConfigParser.ts
  tests/smoke.runner.js
  tests/tests-cli-exclude-arg/general.test.js
  tests/tests-cli-exclude-arg/general2.test.js
  tests/tests-cli-exclude-arg/general3.test.js
  tests/tests-cli-exclude-arg/wdio.conf.js
  tests/tests-cli-exclude-arg/wdio.with-exclude-prop.conf.js
  website/docs/OrganizingTestSuites.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
  website/i18n/de/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
  website/i18n/es/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
  website/i18n/it/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
Labels: PR: New Feature :rocket:
