Repository webdriverio/webdriverio, pull requests merged in 2024-06, with the labels that each got.

#12980 fix(@wdio/browser-runner): sanitize objects to reduce performance bur…
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
  packages/wdio-browser-runner/src/browser/utils.ts
Labels: PR: Bug Fix :bug:

#12979 fix(@wdio/browser-runner): sanitize objects to reduce performance burden when stringifying
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
  packages/wdio-browser-runner/src/browser/utils.ts
Labels: PR: Bug Fix :bug:

#12986 feat: display command name for webdriver calls in allure reporter for v8
  packages/wdio-allure-reporter/src/reporter.ts
  packages/wdio-allure-reporter/tests/allureFeatures.test.ts
  packages/webdriver/src/command.ts
Labels: PR: Polish :nail_care:

#13007 Ws/update-visual-docs (#12984)
  pnpm-lock.yaml
  website/docs/VisualTesting.md
  website/docs/visual-testing/faq.md
Labels: PR: Docs :memo:

#13011 feat: new blogpost (#13008)
  website/blog/2024-06-11-snapshot-testing.md
Labels: PR: Docs :memo:

#13020 fix(docs): add await before mock.restore()
  packages/webdriverio/src/commands/mock/restore.ts
Labels: PR: Docs :memo:

#13019 Allows reloadSession to connect to remote driver
  packages/webdriver/src/index.ts
  packages/webdriver/tests/index.test.ts
  packages/webdriverio/src/commands/browser/reloadSession.ts
Labels: PR: Polish :nail_care:

#12957 Allows reloadSession to connect to remote driver
  packages/webdriver/src/index.ts
  packages/webdriver/tests/index.test.ts
  packages/webdriverio/src/commands/browser/reloadSession.ts
Labels: PR: Polish :nail_care:

#13047 Add maskCommands type for `bstack:options`
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Polish :nail_care:

#13048 Add maskCommands type for `bstack:options` for v8
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Polish :nail_care:

#13045 Add logFilters appium server args type
  packages/wdio-appium-service/src/types.ts
Labels: PR: Polish :nail_care:

#13046 Add logFilter appium server arguments type v8
  packages/wdio-appium-service/src/types.ts
Labels: PR: Polish :nail_care:

#13051 breaking(webdriverio): remove Promise<T> adjective from ChainablePromiseElement
  packages/wdio-browser-runner/src/browser/expect.ts
  packages/wdio-utils/src/shim.ts
  packages/webdriverio/src/commands/element/dragAndDrop.ts
  packages/webdriverio/src/commands/element/isExisting.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/actions/pointer.ts
  packages/webdriverio/src/utils/actions/wheel.ts
  packages/webdriverio/src/utils/implicitWait.ts
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/src/utils/refetchElement.ts
  packages/webdriverio/tests/commands/element/shadow$$.test.ts
  packages/webdriverio/tests/commands/element/shadow$.test.ts
  packages/webdriverio/tests/commands/element/waitForClickable.test.ts
  packages/webdriverio/tests/commands/element/waitForDisplayed.test.ts
  tests/typings/webdriverio/async.ts
  tests/typings/webdriverio/globalImport.ts
Labels: v9
