Repository webdriverio/webdriverio, pull requests merged in 2024-11, with the labels that each got.

#13842 chore(@wdio/spec-reporter): use base name of app path in prefix
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/tests/index.test.ts
Labels: PR: Polish :nail_care:

#13843 fix(@wdio/appium-service): don't transform chromedriver_autodownload arg
  packages/wdio-appium-service/src/utils.ts
  packages/wdio-appium-service/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#13844 Fixing typo during wdio config wizard
  packages/wdio-cli/src/constants.ts
Labels: PR: Polish :nail_care:

#13850 fix(@wdio/cli): improve detection when no capabilities are provided
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/tests/launcher.test.ts
Labels: PR: Bug Fix :bug:

#13854 fix(@wdio/cli): improve passing framework parameters
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/coerce.test.ts
  packages/wdio-cli/tests/parameteters.test.ts
  website/docs/Frameworks.md
Labels: PR: Polish :nail_care:

#13833 Build Unification - WDIO Mocha, Cucumber, Jasmine - Browserstack Test Observability, Accessibility & Percy
  packages/wdio-browserstack-service/src/Percy/Percy.ts
  packages/wdio-browserstack-service/src/Percy/PercySDK.ts
  packages/wdio-browserstack-service/src/accessibility-handler.ts
  packages/wdio-browserstack-service/src/cleanup.ts
  packages/wdio-browserstack-service/src/constants.ts
  packages/wdio-browserstack-service/src/crash-reporter.ts
  packages/wdio-browserstack-service/src/exitHandler.ts
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/instrumentation/funnelInstrumentation.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/reporter.ts
  packages/wdio-browserstack-service/src/scripts/accessibility-scripts.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/src/testHub/utils.ts
  packages/wdio-browserstack-service/src/testOps/listener.ts
  packages/wdio-browserstack-service/src/testOps/requestUtils.ts
  packages/wdio-browserstack-service/src/types.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/cleanup.test.ts
  packages/wdio-browserstack-service/tests/insights-handler.test.ts
  packages/wdio-browserstack-service/tests/instrumentation/funnelInstrumentation.test.ts
  packages/wdio-browserstack-service/tests/launcher.test.ts
  packages/wdio-browserstack-service/tests/reporter.test.ts
  packages/wdio-browserstack-service/tests/service.test.ts
  packages/wdio-browserstack-service/tests/testHub/utils.test.ts
  packages/wdio-browserstack-service/tests/testOps/requestUtils.test.ts
  packages/wdio-browserstack-service/tests/util.test.ts
Labels: PR: Bug Fix :bug:

#13857 fix(webdriverio): switchWindow supports exact window handle match
  packages/webdriverio/src/commands/browser/switchWindow.ts
  packages/webdriverio/tests/commands/browser/switchWindow.test.ts
Labels: PR: Bug Fix :bug:

#13864 Show complete error
  packages/wdio-browserstack-service/src/instrumentation/funnelInstrumentation.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/testOps/requestUtils.ts
  packages/wdio-browserstack-service/src/util.ts
Labels: PR: Polish :nail_care:

#13865 docs: various documentation fixes
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/tests/commands/repl.test.ts
  website/docs/Configuration.md
  website/docs/ConfigurationFile.md
  website/docs/Proxy.md
  website/docs/Testrunner.md
  website/docs/TypeScript.md
  website/docs/component-testing/coverage.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/component-testing/coverage.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/component-testing/coverage.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/it/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/it/docusaurus-plugin-content-docs/current/component-testing/coverage.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/component-testing/coverage.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/component-testing/coverage.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/component-testing/coverage.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/component-testing/coverage.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/Testrunner.md
Labels: PR: Docs :memo:

#13861 Fix stack testobservability v7
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/reporter.ts
  packages/wdio-browserstack-service/tests/insight-handler.test.ts
Labels: PR: Bug Fix :bug:

#13860 Fix stacktrace testobservability v8
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/reporter.ts
Labels: PR: Bug Fix :bug:

#13858 fix: stacktrace for testobservability
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/reporter.ts
Labels: PR: Bug Fix :bug:

#13866 docs(eslint-plugin-wdio): add example to use Eslint v9
  e2e/wdio/wdio.local.conf.ts
  packages/eslint-plugin-wdio/README.md
Labels: PR: Docs :memo:

#13863 fix(webdriverio): properly handle unresolved element on `switchFrame` input in non-BIDI scenario
  packages/webdriverio/src/commands/browser/switchFrame.ts
  packages/webdriverio/tests/commands/browser/switchFrame.test.ts
Labels: PR: Bug Fix :bug:

#13869 fix(webdriverio): null check for switchFrame
  packages/webdriverio/src/commands/browser/switchFrame.ts
  packages/webdriverio/tests/commands/browser/switchFrame.test.ts
Labels: PR: Bug Fix :bug:

#13872 fix(@wdio/sauce-service): don't rely on vulnerable ip package
  packages/wdio-sauce-service/src/launcher.ts
  packages/wdio-sauce-service/src/utils.ts
Labels: PR: Polish :nail_care:

#13874 fix(webdriverio): include documentElement when looking up elements without scope
  packages/webdriverio/src/scripts/customElement.ts
  packages/webdriverio/src/shadowRoot.ts
Labels: PR: Bug Fix :bug:

#13880 polish(@wdio/reporter): better display retried scenarios
  examples/wdio/package.json
  packages/wdio-cucumber-framework/src/cucumberFormatter.ts
  packages/wdio-reporter/README.md
  packages/wdio-reporter/src/index.ts
  packages/wdio-reporter/src/stats/suite.ts
  packages/wdio-reporter/tests/reporter.test.ts
  packages/wdio-reporter/tests/stats/__snapshots__/suite.test.ts.snap
  packages/wdio-reporter/tests/stats/suite.test.ts
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/src/types.ts
  packages/wdio-spec-reporter/tests/__fixtures__/testdata.ts
  packages/wdio-spec-reporter/tests/__snapshots__/index.test.ts.snap
  packages/wdio-spec-reporter/tests/index.test.ts
  pnpm-lock.yaml
Labels: PR: Polish :nail_care:

#13870 feat: enhance scrollIntoView to support native mobile
  __mocks__/fetch.ts
  packages/webdriverio/src/commands/element/scrollIntoView.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/implicitWait.ts
  packages/webdriverio/tests/commands/element/__snapshots__/scrollIntoView.test.ts.snap
  packages/webdriverio/tests/commands/element/getValue.test.ts
  packages/webdriverio/tests/commands/element/isClickable.test.ts
  packages/webdriverio/tests/commands/element/isDisplayed.test.ts
  packages/webdriverio/tests/commands/element/scrollIntoView.test.ts
  packages/webdriverio/tests/commands/element/touchAction.test.ts
  tests/typings/webdriverio/async.ts
Labels: PR: New Feature :rocket:

#13876 v8/@wdio-util: downgrade geckodriver version
  package-lock.json
  packages/wdio-utils/package.json
Labels: PR: Bug Fix :bug:

#13878 fix(@wdio/runner): Respect excludes in capabilities in multiremote case.
  packages/wdio-runner/src/index.ts
  tests/multiremote/test-filter1.js
  tests/multiremote/test-filter2.js
  tests/smoke.runner.js
Labels: PR: Polish :nail_care:

#13883 polish(webdriverio): improve error stack of waitUntil command
  packages/webdriverio/src/commands/browser/waitUntil.ts
  packages/webdriverio/src/utils/Timer.ts
  packages/webdriverio/tests/commands/browser/waitUntil.test.ts
Labels: PR: Polish :nail_care:

#13902 fix(@wdio/cli): fix typing when creating cucumber projects
  packages/wdio-cli/src/utils.ts
Labels: PR: Bug Fix :bug:

#13903 chore(docs): add info setting up maxInstances and specs in docs
  website/docs/ConfigurationFile.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/de/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/de/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/es/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/es/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/it/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/it/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/ConfigurationFile.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/ConfigurationFile.md
Labels: PR: Docs :memo:

#13896 fix(webdriver): make isBidi flag dependent on whether WebdriverIO can connect to the websocket url
  .github/workflows/test-cloud.yml
  e2e/launch/aws.test.ts
  e2e/standalone/attach.test.ts
  e2e/vitest.config.ts
  package.json
  packages/webdriver/src/bidi/core.ts
  packages/webdriver/src/utils.ts
  pnpm-lock.yaml
Labels: PR: Bug Fix :bug:

#13892 fix(webdriverio): better handle context when closing windows
  e2e/wdio/headless/test.e2e.ts
  packages/webdriverio/src/context.ts
Labels: PR: Bug Fix :bug:

#13838 fix(webdriverio): reconnect to bidi on reloadSession
  e2e/reloadSession.test.ts
  e2e/wdio/headless/puppeteer.e2e.ts
  e2e/wdio/headless/reloadSession.e2e.ts
  e2e/wdio/headless/source-maps.e2e.ts
  packages/webdriver/src/bidi/core.ts
  packages/webdriver/src/command.ts
  packages/webdriver/src/index.ts
  packages/webdriver/src/utils.ts
Labels: PR: Bug Fix :bug:

#13888 feat: add longpress logic
  packages/webdriverio/src/commands/element/click.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/tests/commands/element/__snapshots__/click.test.ts.snap
  packages/webdriverio/tests/commands/element/click.test.ts
Labels: PR: Polish :nail_care:

#13895 Add an element `longPress` command
  .gitignore
  packages/webdriverio/src/commands/element.ts
  packages/webdriverio/src/commands/mobile.ts
  packages/webdriverio/src/commands/mobile/longPress.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/tests/commands/device/longPress.test.ts
  packages/webdriverio/tests/commands/element.test.ts
  scripts/docs-generation/wdioDocs.ts
  website/docs/api/Mobile.md
Labels: PR: New Feature :rocket:

#13904 propagate addCommand to children for multiremote
  packages/webdriverio/src/index.ts
  packages/webdriverio/tests/addCommand.test.ts
  website/docs/CustomCommands.md
Labels: PR: Polish :nail_care:

#13910 chore(@wdio/cucumber-framework): better re-export all Cucumber primitives
  packages/wdio-cucumber-framework/src/index.ts
  packages/wdio-cucumber-framework/tests/adapter.test.ts
  website/docs/Frameworks.md
Labels: PR: Polish :nail_care:

#13914 feat: add pinch and zoom
  packages/webdriverio/src/commands/element.ts
  packages/webdriverio/src/commands/mobile.ts
  packages/webdriverio/src/commands/mobile/pinch.ts
  packages/webdriverio/src/commands/mobile/zoom.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/mobile.ts
  packages/webdriverio/tests/commands/mobile/__snapshots__/pinch.test.ts.snap
  packages/webdriverio/tests/commands/mobile/__snapshots__/zoom.test.ts.snap
  packages/webdriverio/tests/commands/mobile/longPress.test.ts
  packages/webdriverio/tests/commands/mobile/pinch.test.ts
  packages/webdriverio/tests/commands/mobile/zoom.test.ts
  packages/webdriverio/tests/utils/mobile.test.ts
Labels: PR: New Feature :rocket:

#13922 fix: Catch requests failure to trigger the `result` and `onAfterCommand` event
  packages/wdio-allure-reporter/src/reporter.ts
  packages/wdio-allure-reporter/tests/allureFeatures.test.ts
  packages/webdriver/src/command.ts
  packages/webdriver/tests/command.test.ts
Labels: PR: Bug Fix :bug:
