Repository webdriverio/webdriverio, pull requests merged in 2024-12, with the labels that each got.

#13944 fix(@wdio/cli): use require to import json file
  packages/wdio-cli/src/constants.ts
Labels: PR: Bug Fix :bug:

#13941 fix(webdriverio): add 'appium:options' when checking for native context
  packages/webdriverio/src/utils/mobile.ts
  packages/webdriverio/tests/utils/mobile.test.ts
Labels: PR: Bug Fix :bug:

#13952 Changes to send SDK instrumentation in capabilities v7
  packages/wdio-browserstack-service/src/instrumentation/funnelInstrumentation.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/tests/launcher.test.ts
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Polish :nail_care:

#13926 Changes to send SDK instrumentation in capabilities v8
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/tests/launcher.test.ts
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Polish :nail_care:

#13951 Changes to send SDK instrumentation in capabilities v9
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/tests/launcher.test.ts
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Polish :nail_care:

#13958 fix(@wdio/runner): Continue emitting event on the runner even when a reporter throws an error
  .vscode/settings.json
  packages/wdio-runner/src/reporter.ts
  packages/wdio-runner/tests/index.test.ts
  packages/wdio-runner/tests/reporter.test.ts
Labels: PR: Bug Fix :bug:

#13960 fix(webdriverio): support opening file urls
  e2e/wdio/headless/__fixtures__/test.html
  e2e/wdio/headless/test.e2e.ts
  packages/wdio-utils/src/envDetector.ts
  packages/webdriverio/src/networkManager.ts
Labels: PR: Bug Fix :bug:

#13963 Remove unused cli-spinners dependency
  .github/dependabot.yml
  packages/wdio-cli/package.json
  pnpm-lock.yaml
Labels: PR: Bug Fix :bug:

#13950 fix(webdriverio): don't fail if getContext is not supported
  packages/wdio-utils/src/envDetector.ts
  packages/webdriverio/src/context.ts
Labels: PR: Polish :nail_care:

#13970 fix(@wdio/cli): Serenity/JS supports WebdriverIO 9
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/templates/exampleFiles/serenity-js/jasmine/example.spec.ts.ejs
  packages/wdio-cli/src/templates/exampleFiles/serenity-js/mocha/example.spec.ts.ejs
  packages/wdio-cli/src/utils.ts
Labels: PR: Polish :nail_care:

#13983 fix(@wdio/utils): Unset geckodriver when stable is set as browserVersion
  packages/wdio-utils/src/node/manager.ts
Labels: PR: Polish :nail_care:

#13988 wdio-types: add `platformVersion` field for BrowserStackCapabilities
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Bug Fix :bug:

#13978 fix(webdriver): enable Bidi commands for Appium sessions
  packages/wdio-utils/src/envDetector.ts
  packages/wdio-utils/tests/envDetector.test.ts
  packages/webdriver/src/index.ts
Labels: PR: Bug Fix :bug:

#13962 fix(@wdio/cli): propagate node-options to worker env
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/commands/run.test.ts
  packages/wdio-config/package.json
  packages/wdio-config/src/node/ConfigParser.ts
  packages/wdio-config/src/node/utils.ts
  packages/wdio-config/src/utils.ts
  packages/wdio-config/tests/node/utils.test.ts
  packages/wdio-config/tests/utils.test.ts
  packages/wdio-local-runner/src/worker.ts
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/index.test.ts
  pnpm-lock.yaml
Labels: PR: Bug Fix :bug:

#13993 catch failures onAfterCommand
  packages/wdio-allure-reporter/src/reporter.ts
  packages/webdriver/src/command.ts
Labels: PR: Bug Fix :bug:, v8

#13995 fix: Fixes an error message.
  packages/webdriverio/src/scripts/isElementStable.ts
  packages/webdriverio/tests/commands/element/isStable.test.ts
  packages/webdriverio/tests/commands/element/waitForStable.test.ts
Labels: PR: Polish :nail_care:

#14001 fix(@wdio/cli): adjust default value for specFileRetriesDeferred
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/tests/launcher.test.ts
  packages/wdio-jasmine-framework/tests/adapter.test.ts
  packages/wdio-types/src/Options.ts
  website/i18n/ar/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/de/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/es/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/it/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/Configuration.md
Labels: PR: Bug Fix :bug:

#14012 Add mobile tap command
  __mocks__/fetch.ts
  packages/webdriverio/src/commands/browser.ts
  packages/webdriverio/src/commands/element.ts
  packages/webdriverio/src/commands/element/scrollIntoView.ts
  packages/webdriverio/src/commands/mobile.ts
  packages/webdriverio/src/commands/mobile/dragAndDrop.ts
  packages/webdriverio/src/commands/mobile/longPress.ts
  packages/webdriverio/src/commands/mobile/pinch.ts
  packages/webdriverio/src/commands/mobile/scrollIntoView.ts
  packages/webdriverio/src/commands/mobile/tap.ts
  packages/webdriverio/src/commands/mobile/zoom.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/implicitWait.ts
  packages/webdriverio/tests/commands/browser.test.ts
  packages/webdriverio/tests/commands/element.test.ts
  packages/webdriverio/tests/commands/element/__snapshots__/scrollIntoView.test.ts.snap
  packages/webdriverio/tests/commands/mobile/__snapshots__/tap.test.ts.snap
  packages/webdriverio/tests/commands/mobile/longPress.test.ts
  packages/webdriverio/tests/commands/mobile/tap.test.ts
  scripts/templates/template.eta
  scripts/utils/formatter.ts
Labels: PR: New Feature :rocket:

#14013 fix(@wdio/sauce-service): set unique values for noSslBumpDomains
  packages/wdio-sauce-service/src/launcher.ts
  packages/wdio-sauce-service/tests/launcher.test.ts
Labels: PR: Bug Fix :bug:

#14018 fix(webdriverio): support resolve references from internalId
  packages/webdriverio/src/commands/browser/addInitScript.ts
  packages/webdriverio/src/utils/bidi/index.ts
  packages/webdriverio/tests/utils/bidi/value.test.ts
Labels: PR: Bug Fix :bug:

#13913 chore(appium-service): filter out `Debugger attached` as errorMessage
  packages/wdio-appium-service/src/launcher.ts
  packages/wdio-appium-service/tests/launcher.test.ts
Labels: PR: Bug Fix :bug:
