Repository webdriverio/webdriverio, pull requests merged in 2024-10, with the labels that each got.

#13732 v8: fix(webdriverio): remove default params in actions
  packages/webdriverio/src/utils/actions/pointer.ts
  packages/webdriverio/tests/commands/browser/__snapshots__/action.test.ts.snap
  packages/webdriverio/tests/commands/element/__snapshots__/click.test.ts.snap
  packages/webdriverio/tests/commands/element/__snapshots__/doubleClick.test.ts.snap
  packages/webdriverio/tests/commands/element/__snapshots__/dragAndDrop.test.ts.snap
  packages/webdriverio/tests/commands/element/__snapshots__/moveTo.test.ts.snap
Labels: PR: Polish :nail_care:

#13734 Fix Percy instrumentation
  packages/wdio-browserstack-service/src/instrumentation/funnelInstrumentation.ts
Labels: PR: Polish :nail_care:

#13736 chore(webdriver): add exponential backoff to request retries
  packages/webdriver/src/request/index.ts
  packages/webdriver/tests/request.test.ts
Labels: PR: Polish :nail_care:

#13730 fix(webdriverio): remove default params in actions
  packages/webdriverio/src/utils/actions/pointer.ts
  packages/webdriverio/tests/commands/browser/__snapshots__/action.test.ts.snap
  packages/webdriverio/tests/commands/element/__snapshots__/click.test.ts.snap
  packages/webdriverio/tests/commands/element/__snapshots__/doubleClick.test.ts.snap
  packages/webdriverio/tests/commands/element/__snapshots__/dragAndDrop.test.ts.snap
  packages/webdriverio/tests/commands/element/__snapshots__/moveTo.test.ts.snap
Labels: PR: Bug Fix :bug:

#13744 chore(webdriverio): provide a better error message if no debuggerAddress is available
  packages/webdriverio/src/commands/browser/getPuppeteer.ts
Labels: PR: Polish :nail_care:

#13746 fix(webdriverio): make command more compatible with v8 behavior
  e2e/browser-runner/__snapshots__/react.test.tsx.snap
  e2e/browser-runner/lit.test.js
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-browser-runner/tests/vite/plugins/testrunner.test.ts
  packages/wdio-logger/package.json
  packages/webdriverio/src/commands/browser/url.ts
  packages/webdriverio/src/polyfill.ts
  packages/webdriverio/src/shadowRoot.ts
Labels: PR: Bug Fix :bug:

#13751 fix(webdriverio): make name polyfill compatible with old browsers
  packages/webdriverio/src/polyfill.ts
Labels: PR: Bug Fix :bug:

#13753 fix(webdriverio): selector engine improvements
  e2e/browser-runner/lit.test.js
  packages/webdriver/src/bidi/core.ts
  packages/webdriver/src/types.ts
  packages/webdriver/src/utils.ts
  packages/webdriverio/src/context.ts
  packages/webdriverio/src/shadowRoot.ts
  pnpm-lock.yaml
  website/docs/api/Browser.md
Labels: PR: Bug Fix :bug:

#13754 fix(@wdio/browser-runner): use expect v30 beta
  packages/wdio-browser-runner/package.json
  pnpm-lock.yaml
Labels: PR: Bug Fix :bug:

#13756 Remove unused gaze dependency
  packages/wdio-runner/package.json
  pnpm-lock.yaml
Labels: PR: Internal :house:

#13761 docs: correct links to flowcharts
  CONTRIBUTING.md
Labels: PR: Docs :memo:

#13760 Prevent switchWindow from switching on invalid window requested
  e2e/wdio/headless/test.e2e.ts
  packages/webdriverio/src/commands/browser/switchWindow.ts
  packages/webdriverio/tests/commands/browser/switchWindow.test.ts
Labels: PR: Bug Fix :bug:

#13758 docs: Updated examples guide to mention PNPM for setup instead of NPM
  examples/README.md
Labels: PR: Docs :memo:

#13768 Fix moduleLoaderFlag
  packages/wdio-cli/tests/commands/run.test.ts
Labels: PR: Bug Fix :bug:

#13772 fix(webdriverio): ensure BiDi browsingContext is updated after switchToWindow
  e2e/wdio/headless/test.e2e.ts
  packages/webdriverio/src/context.ts
Labels: PR: Bug Fix :bug:

#13777 fix(webdriverio): wait for request information to come in
  e2e/wdio/headless/test.e2e.ts
  packages/wdio-types/src/Network.ts
  packages/webdriverio/src/commands/browser/url.ts
  packages/webdriverio/src/networkManager.ts
  packages/webdriverio/src/utils/Timer.ts
Labels: PR: Bug Fix :bug:

#13792 add missing test:e2e script to package.json
  package.json
Labels: PR: Internal :house:

#13773 🐛 Bug Fix: TypeError: fetch failed
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/util.ts
Labels: PR: Bug Fix :bug:

#13797 docs(BACKERS.md): fix LambdaTest logo link
  BACKERS.md
Labels: PR: Docs :memo:

#13795 rename `attachSession` to `attachToSession`
  website/docs/api/Modules.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/api/Modules.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/api/Modules.md
  website/i18n/de/docusaurus-plugin-content-docs/current/api/Modules.md
  website/i18n/es/docusaurus-plugin-content-docs/current/api/Modules.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/api/Modules.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/api/Modules.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/api/Modules.md
  website/i18n/it/docusaurus-plugin-content-docs/current/api/Modules.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/api/Modules.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/api/Modules.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/api/Modules.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/api/Modules.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/api/Modules.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/api/Modules.md
Labels: PR: Docs :memo:

#13794 docs(browser.mock): remove outdated parameter comment
  packages/webdriverio/src/commands/browser/mock.ts
Labels: PR: Docs :memo:

#13793 feat: enhance newWindow function to support 'tab' or 'window' types
  package.json
  packages/webdriverio/src/commands/browser/newWindow.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/tests/commands/browser/newWindow.test.ts
Labels: PR: Polish :nail_care:

#13800 reorder shadowroot removal
  packages/webdriverio/src/shadowRoot.ts
  packages/webdriverio/tests/shadowRoot.test.ts
Labels: PR: Bug Fix :bug:

#13802 fix(webdriverio): typo in keys description
  packages/webdriverio/src/commands/browser/keys.ts
Labels: PR: Docs :memo:

#13798 fix(webdriverio): Misfound elements when using WebDriver BiDi
  packages/webdriverio/src/utils/index.ts
Labels: PR: Bug Fix :bug:

#13782 fix(@wdio/browser-runner): publish Mocha assets as part of package
  infra/compiler/src/index.ts
  infra/compiler/src/plugins.ts
  packages/wdio-browser-runner/package.json
  packages/wdio-browser-runner/src/vite/utils.ts
  packages/wdio-browser-runner/tests/vite/utils.test.ts
  packages/webdriver/src/request/constants.ts
  pnpm-lock.yaml
Labels: PR: Bug Fix :bug:

#13806 feat(wdio-protocols): extend BiDi type definitions
  packages/wdio-protocols/src/types.ts
Labels: PR: Polish :nail_care:

#13805 fix(webdriver): allow WebdriverIO to handle alerts
  e2e/wdio/headless/test.e2e.ts
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/__snapshots__/index.test.ts.snap
  packages/webdriver/tests/index.test.ts
Labels: PR: Bug Fix :bug:

#13804 chore(@wdio/appium-service): log to stdout if no log path is set
  packages/wdio-appium-service/src/launcher.ts
  packages/wdio-appium-service/tests/__snapshots__/launcher.test.ts.snap
  packages/wdio-appium-service/tests/launcher.test.ts
Labels: PR: Polish :nail_care:

#13781 fix(webdriverio): improve switchFrame behavior
  __mocks__/fetch.ts
  e2e/wdio/headless/test.e2e.ts
  packages/wdio-browser-runner/src/browser/driver.ts
  packages/wdio-browser-runner/tests/vite/utils.test.ts
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/src/run.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-config/src/node/utils.ts
  packages/wdio-local-runner/src/worker.ts
  packages/wdio-spec-reporter/src/index.ts
  packages/webdriver/src/bidi/core.ts
  packages/webdriver/src/command.ts
  packages/webdriver/src/index.ts
  packages/webdriver/tests/bidi.test.ts
  packages/webdriver/tests/index.test.ts
  packages/webdriverio/src/commands/browser/switchFrame.ts
  packages/webdriverio/src/context.ts
  packages/webdriverio/src/dialog.ts
  packages/webdriverio/src/networkManager.ts
  packages/webdriverio/src/polyfill.ts
  packages/webdriverio/src/shadowRoot.ts
  packages/webdriverio/tests/commands/browser/setViewport.test.ts
  packages/webdriverio/tests/commands/browser/switchFrame.test.ts
  packages/webdriverio/tests/shadowRoot.test.ts
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#13814 fix(webdriverio): enhance protocol stub to allow context initialization
  packages/webdriverio/src/protocol-stub.ts
Labels: PR: Bug Fix :bug:

#13837 fix(webdriverio): reset frame context if refresh command is called
  e2e/wdio/headless/test.e2e.ts
  packages/webdriverio/src/commands/browser/switchFrame.ts
  packages/webdriverio/src/context.ts
  packages/webdriverio/tests/commands/browser/switchFrame.test.ts
Labels: PR: Bug Fix :bug:
