Repository webdriverio/webdriverio, pull requests merged in 2024-05, with the labels that each got.

#12777 docs: fix typo
  scripts/templates/template.eta
Labels: PR: Docs :memo:

#12780 accessibility-testing-v8-bstack
  website/_sidebars.json
  website/docs/accessibility-testing/browserstack_accessibility_testing.md
Labels: PR: Docs :memo:

#12779 fix: convert npm to pnpm in gitpod
  .gitpod.yml
  pnpm-lock.yaml
Labels: PR: Internal :house:

#12752 feat: replace `ts-node` with `tsx`, remove autoCompileOpts
  examples/wdio.conf.js
  examples/wdio/vite-vue-example/wdio.conf.ts
  package.json
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/commands/repl.ts
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-cli/src/types.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/__snapshots__/utils.test.ts.snap
  packages/wdio-cli/tests/commands/__snapshots__/config.test.ts.snap
  packages/wdio-cli/tests/commands/config.test.ts
  packages/wdio-cli/tests/commands/run.test.ts
  packages/wdio-cli/tests/utils.test.ts
  packages/wdio-config/src/constants.ts
  packages/wdio-config/src/node/ConfigParser.ts
  packages/wdio-config/src/node/utils.ts
  packages/wdio-config/tests/__snapshots__/configparser.test.ts.snap
  packages/wdio-config/tests/lib/ConfigParserBuilder.ts
  packages/wdio-config/tests/lib/MockedModules.ts
  packages/wdio-config/tests/node/__snapshots__/configparser.test.ts.snap
  packages/wdio-config/tests/node/configparser.test.ts
  packages/wdio-config/tests/node/utils.test.ts
  packages/wdio-local-runner/src/worker.ts
  packages/wdio-runner/tests/index.test.ts
  packages/wdio-types/src/Options.ts
  packages/webdriverio/tests/commands/browser/action.test.ts
  pnpm-lock.yaml
  tests/helpers/config.js
  tests/smoke.runner.js
  website/docs/Babel.md
  website/docs/Configuration.md
  website/docs/ConfigurationFile.md
  website/docs/Testrunner.md
  website/docs/TypeScript.md
Labels: v9

#12802 Fix: Result and Context arguments for component tests
  packages/wdio-browser-runner/src/browser/frameworks/mocha.ts
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/tests/launcher.test.ts
Labels: PR: Polish :nail_care:

#12845 Add resignApp capability type
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Polish :nail_care:

#12851 Add resignApp capabilites v8
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Polish :nail_care:

#12850 Update the types for suites to fix the compile error
  packages/wdio-types/src/Options.ts
Labels: PR: Bug Fix :bug:

#12718 avoid calling googlechromelabs.github.io when offline and using ffx
  packages/wdio-utils/src/node/utils.ts
  packages/wdio-utils/tests/node/utils.test.ts
Labels: PR: Bug Fix :bug:

#12855 [#11473] Refactor wdio-allure-reporter package for better hooks handling [v8]
  packages/wdio-allure-reporter/src/constants.ts
  packages/wdio-allure-reporter/src/reporter.ts
  packages/wdio-allure-reporter/src/state.ts
  packages/wdio-allure-reporter/src/types.ts
  packages/wdio-allure-reporter/src/utils.ts
  packages/wdio-allure-reporter/tests/allureFeatures.test.ts
  packages/wdio-allure-reporter/tests/cucumber.suite.test.ts
  packages/wdio-allure-reporter/tests/state.test.ts
  packages/wdio-allure-reporter/tests/suite.test.ts
  packages/wdio-allure-reporter/tests/utils.test.ts
Labels: PR: Polish :nail_care:

#12852 [#11473] - Refactor wdio-allure-reporter package for better hooks handling
  packages/wdio-allure-reporter/src/constants.ts
  packages/wdio-allure-reporter/src/reporter.ts
  packages/wdio-allure-reporter/src/state.ts
  packages/wdio-allure-reporter/src/types.ts
  packages/wdio-allure-reporter/src/utils.ts
  packages/wdio-allure-reporter/tests/allureFeatures.test.ts
  packages/wdio-allure-reporter/tests/cucumber.suite.test.ts
  packages/wdio-allure-reporter/tests/state.test.ts
  packages/wdio-allure-reporter/tests/suite.test.ts
  packages/wdio-allure-reporter/tests/utils.test.ts
Labels: PR: Polish :nail_care:

#12889 [v8] Select proper input via ancestor label when multiple match
  e2e/browser-runner/lit.test.js
  packages/webdriverio/src/utils/findStrategy.ts
  packages/webdriverio/tests/__snapshots__/findStrategy.test.ts.snap
Labels: PR: Bug Fix :bug:

#12884 Select proper input via ancestor label when multiple match
  e2e/browser-runner/lit.test.js
  packages/webdriverio/src/utils/findStrategy.ts
  packages/webdriverio/tests/__snapshots__/findStrategy.test.ts.snap
Labels: PR: Bug Fix :bug:

#12921 [v8] fix(logger): reset cursor visibility on progress clear
  packages/wdio-logger/src/node.ts
Labels: PR: Bug Fix :bug:

#12920 fix(logger): reset cursor visibility on progress clear
  packages/wdio-logger/src/node.ts
Labels: PR: Bug Fix :bug:

#12916 [v8][browserstack-service]Add instrumentation for graceful kill builds
  packages/wdio-browserstack-service/src/cleanup.ts
  packages/wdio-browserstack-service/src/config.ts
  packages/wdio-browserstack-service/src/exitHandler.ts
  packages/wdio-browserstack-service/src/instrumentation/funnelInstrumentation.ts
  packages/wdio-browserstack-service/src/types.ts
  packages/wdio-browserstack-service/src/util.ts
Labels: PR: Bug Fix :bug:

#12922 Fix virtual authenticator
  packages/wdio-protocols/src/protocols/webdriver.ts
  packages/wdio-protocols/src/types.ts
  scripts/type-generation/constants.ts
Labels: PR: Bug Fix :bug:

#12923 Add Selenium downloadFile command
  packages/wdio-protocols/src/protocols/selenium.ts
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/browser.ts
  packages/webdriverio/src/commands/browser/downloadFile.ts
  packages/webdriverio/tests/commands/browser/downloadFile.test.ts
  pnpm-lock.yaml
Labels: PR: New Feature :rocket:

#12778 Add Selenium downloadFile command
  package-lock.json
  packages/wdio-protocols/src/protocols/selenium.ts
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/browser.ts
  packages/webdriverio/src/commands/browser/downloadFile.ts
  packages/webdriverio/tests/commands/browser/downloadFile.test.ts
Labels: PR: New Feature :rocket:

#12929 Ws/ocr-v9
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
  website/_sidebars.json
  website/docs/ocr-testing/cli-wizard.md
  website/docs/ocr-testing/getting-started.md
  website/docs/ocr-testing/more-test-optimization.md
  website/docs/ocr-testing/ocr-click-on-text.md
  website/docs/ocr-testing/ocr-faq.md
  website/docs/ocr-testing/ocr-get-element-position-by-text.md
  website/docs/ocr-testing/ocr-get-text.md
  website/docs/ocr-testing/ocr-set-value.md
  website/docs/ocr-testing/ocr-wait-for-text-displayed.md
  website/docs/ocr-testing/what-is-wdio-ocr-service.md
  website/package.json
  website/pnpm-lock.yaml
  website/static/img/ocr/increased-contrast.jpg
  website/static/img/ocr/ocr-click-on-text-target.jpg
  website/static/img/ocr/ocr-service-cli.mp4
  website/static/img/ocr/processing-steps.jpg
Labels: PR: Docs :memo:

#12953 SDK-694: Fix for showing reason for passed test (v7)
  packages/wdio-browserstack-service/src/service.ts
Labels: PR: Bug Fix :bug:

#12951 SDK-694: Fix for showing reason for passed test (main)
  packages/wdio-browserstack-service/src/service.ts
Labels: PR: Bug Fix :bug:
