Repository webdriverio/webdriverio, pull requests merged in 2024-02, with the labels that each got.

#12140 (@wdio/browser-runner): improved stencil test integration
  e2e/browser-runner/stencil.test.tsx
  packages/wdio-browser-runner/src/browser/fixtures/stencil.ts
  packages/wdio-browser-runner/src/vite/frameworks/stencil.ts
  packages/wdio-browser-runner/stencil/index.d.ts
  packages/wdio-browser-runner/tests/vite/frameworks/stencil.test.ts
  packages/wdio-runner/src/browser.ts
Labels: PR: Bug Fix :bug:

#12141 fix upload file in selenium 4
  packages/wdio-protocols/src/protocols/selenium.ts
Labels: PR: Bug Fix :bug:

#12006 V9 Remove JSONWireProtocol
  e2e/browser-runner/lit.test.js
  e2e/browser-runner/react.test.tsx
  e2e/wdio/headless/test.e2e.ts
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-browser-runner/tests/vite/plugins/testrunner.test.ts
  packages/wdio-protocols/README.md
  packages/wdio-protocols/src/index.ts
  packages/wdio-protocols/src/protocols/appium.ts
  packages/wdio-protocols/src/protocols/jsonwp.ts
  packages/wdio-webdriver-mock-service/src/WebDriverMock.ts
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/index.test.ts
  packages/webdriver/tests/utils.test.ts
  packages/webdriverio/src/commands/browser/getWindowSize.ts
  packages/webdriverio/src/commands/browser/keys.ts
  packages/webdriverio/src/commands/browser/setTimeout.ts
  packages/webdriverio/src/commands/browser/setWindowSize.ts
  packages/webdriverio/src/commands/element/addValue.ts
  packages/webdriverio/src/commands/element/click.ts
  packages/webdriverio/src/commands/element/doubleClick.ts
  packages/webdriverio/src/commands/element/dragAndDrop.ts
  packages/webdriverio/src/commands/element/getLocation.ts
  packages/webdriverio/src/commands/element/getProperty.ts
  packages/webdriverio/src/commands/element/getSize.ts
  packages/webdriverio/src/commands/element/moveTo.ts
  packages/webdriverio/tests/commands/browser/getWindowSize.test.ts
  packages/webdriverio/tests/commands/browser/keys.test.ts
  packages/webdriverio/tests/commands/browser/setTimeout.test.ts
  packages/webdriverio/tests/commands/browser/setWindowSize.test.ts
  packages/webdriverio/tests/commands/element/addValue.test.ts
  packages/webdriverio/tests/commands/element/click.test.ts
  packages/webdriverio/tests/commands/element/doubleClick.test.ts
  packages/webdriverio/tests/commands/element/dragAndDrop.test.ts
  packages/webdriverio/tests/commands/element/getLocation.test.ts
  packages/webdriverio/tests/commands/element/getProperty.test.ts
  packages/webdriverio/tests/commands/element/getSize.test.ts
  packages/webdriverio/tests/commands/element/moveTo.test.ts
  scripts/protocols.ts
Labels: PR: Breaking Change :boom:, v9

#12092 (@wdio/spec-reporter): introduce `color` option to disable colors for spec reporter
  __mocks__/@wdio/reporter.ts
  __mocks__/chalk.ts
  packages/wdio-cli/src/interface.ts
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/interface.test.ts
  packages/wdio-spec-reporter/README.md
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/src/types.ts
  packages/wdio-spec-reporter/tests/__snapshots__/index.test.ts.snap
  packages/wdio-spec-reporter/tests/index.test.ts
Labels: PR: New Feature :rocket:

#12145 (@wdio/browser-runner): document stencil component testing integration better
  e2e/browser-runner/components/StencilComponentNoShadow.tsx
  e2e/browser-runner/stencil.test.tsx
  packages/wdio-browser-runner/src/browser/driver.ts
  packages/wdio-browser-runner/src/browser/integrations/stencil.ts
  packages/wdio-browser-runner/src/browser/utils.ts
  packages/wdio-browser-runner/src/vite/frameworks/stencil.ts
  packages/wdio-browser-runner/stencil/index.d.ts
  packages/wdio-browser-runner/tests/browser/utils.test.ts
  packages/wdio-browser-runner/tests/vite/frameworks/stencil.test.ts
  packages/webdriverio/src/commands/browser/$$.ts
  packages/webdriverio/src/middlewares.ts
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/utils/index.test.ts
  website/docs/component-testing/Stencil.md
Labels: PR: Polish :nail_care:

#12146 (webdriver): have a more reliable way to shut down attached session driver
  e2e/attach.test.ts
  packages/wdio-types/src/Capabilities.ts
  packages/webdriver/src/command.ts
  packages/webdriver/src/index.ts
Labels: PR: Polish :nail_care:

#12148 feat: add native app compare docs
  website/blog/2024-02-06-visual-testing-enhancements.md
  website/docs/VisualTesting.md
  website/docs/visual-testing/method-options.md
  website/docs/visual-testing/methods.md
  website/docs/visual-testing/service-options.md
  website/docs/visual-testing/writing-tests.md
Labels: PR: Docs :memo:

#12184 (@wdio/browser-runner): allow services and other hooks to register custom matcher
  __mocks__/expect-webdriverio.ts
  e2e/browser-runner/lit.test.js
  e2e/browser-runner/wdio.conf.js
  examples/wdio/vite-vue-example/package.json
  package-lock.json
  packages/wdio-browser-runner/package.json
  packages/wdio-browser-runner/src/browser/expect.ts
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-browser-runner/tests/vite/communicator.test.ts
  packages/wdio-globals/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-jasmine-framework/src/index.ts
  packages/wdio-jasmine-framework/src/utils.ts
  packages/wdio-jasmine-framework/tests/adapter.test.ts
  packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.ts.snap
  packages/wdio-runner/package.json
  packages/wdio-runner/src/browser.ts
  packages/wdio-types/src/Workers.ts
Labels: PR: Bug Fix :bug:

#12147 (webdriverio): allow to define new capabilities when calling `reloadSession
  __mocks__/@wdio/utils/node.ts
  e2e/wdio/headless/test.e2e.ts
  e2e/wdio/wdio.conf.ts
  packages/devtools/src/cjs/index.ts
  packages/devtools/src/index.ts
  packages/devtools/src/types.ts
  packages/wdio-utils/src/startWebDriver.ts
  packages/webdriver/src/index.ts
  packages/webdriver/tests/index.test.ts
  packages/webdriverio/src/commands/browser/reloadSession.ts
Labels: PR: New Feature :rocket:

#11904 Wdio Percy Support v7
  jest.config.js
  package-lock.json
  package.json
  packages/wdio-browserstack-service/package.json
  packages/wdio-browserstack-service/src/@types/bstack-service-types.d.ts
  packages/wdio-browserstack-service/src/Percy/Percy-Handler.ts
  packages/wdio-browserstack-service/src/Percy/Percy.ts
  packages/wdio-browserstack-service/src/Percy/PercyBinary.ts
  packages/wdio-browserstack-service/src/Percy/PercyCaptureMap.ts
  packages/wdio-browserstack-service/src/Percy/PercyHelper.ts
  packages/wdio-browserstack-service/src/Percy/PercyLogger.ts
  packages/wdio-browserstack-service/src/Percy/PercySDK.ts
  packages/wdio-browserstack-service/src/constants.ts
  packages/wdio-browserstack-service/src/index.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/src/types.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/Percy-Handler.test.ts
  packages/wdio-browserstack-service/tests/Percy.test.ts
  packages/wdio-browserstack-service/tests/PercyBinary.test.ts
  packages/wdio-browserstack-service/tests/PercyCaptureMap.test.ts
  packages/wdio-browserstack-service/tests/PercyHelper.test.ts
  packages/wdio-browserstack-service/tests/PercyLogger.test.ts
  packages/wdio-browserstack-service/tests/launcher.test.ts
  packages/wdio-browserstack-service/tests/util.test.ts
Labels: PR: New Feature :rocket:

#12186 File Downloads Best Practices
  website/_sidebars.json
  website/docs/best-practices/FileDownloads.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/best-practices/FileDownloads.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/best-practices/FileDownloads.md
  website/i18n/de/docusaurus-plugin-content-docs/current/best-practices/FileDownloads.md
  website/i18n/es/docusaurus-plugin-content-docs/current/best-practices/FileDownloads.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/best-practices/FileDownloads.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/best-practices/FileDownloads.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/best-practices/FileDownloads.md
  website/i18n/it/docusaurus-plugin-content-docs/current/BestPractices.md
  website/i18n/it/docusaurus-plugin-content-docs/current/best-practices/FileDownloads.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/BestPractices.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/best-practices/FileDownloads.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/best-practices/FileDownloads.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/best-practices/FileDownloads.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/best-practices/FileDownloads.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/best-practices/FileDownloads.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/best-practices/FileDownloads.md
Labels: PR: Docs :memo:

#12199 (@wdio/cli): ensure ts-node is installed if tsconfig.json is found
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#12198 (@wdio/browser-runner): fix scope propagation for not found elements
  e2e/browser-runner/lit.test.js
  packages/wdio-browser-runner/src/browser/expect.ts
  packages/wdio-browser-runner/src/browser/utils.ts
  packages/wdio-browser-runner/tests/browser/utils.test.ts
Labels: PR: Bug Fix :bug:

#11992 feat(wdio-prefix): introduce `wdio:{maxInstances,specs,exclude}` to WebdriverIO.Capabilities
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/tests/launcher.test.ts
  packages/wdio-config/src/node/ConfigParser.ts
  packages/wdio-config/tests/__fixtures__/prefix-test-01.ts
  packages/wdio-config/tests/__fixtures__/prefix-test-02.ts
  packages/wdio-config/tests/__fixtures__/wdio.wdio-prefix.conf.ts
  packages/wdio-config/tests/node/configparser.test.ts
  packages/wdio-types/src/Capabilities.ts
  tests/typings/webdriverio/capabilityOptions.ts
  website/docs/Capabilities.md
Labels: PR: Polish :nail_care:

#12200 (webdriverio): don't fail getContext is not supported, e.g. using Tizen TV driver
  packages/webdriverio/src/commands/element/isClickable.ts
  packages/webdriverio/src/commands/element/isEqual.ts
  packages/webdriverio/tests/commands/element/isClickable.test.ts
Labels: PR: Bug Fix :bug:

#12226 [Docs] moveTo docs updated
  packages/webdriverio/src/commands/element/moveTo.ts
Labels: PR: Docs :memo:

#12228 chore: update default baseline for visual tests
  website/docs/visual-testing/service-options.md
Labels: PR: Docs :memo:

#12204 Added null check on fetching capabilities
  packages/wdio-browserstack-service/src/reporter.ts
Labels: PR: Bug Fix :bug:

#12232 (internal): replace expense workflow with custom action
  .github/dependabot.yml
  .github/workflows/expense.yml
  package-lock.json
  package.json
  scripts/docs-generation/3rdPartyDocs.ts
  scripts/expense.ts
  scripts/templates/expenseMail.tsx
Labels: PR: Internal :house:

#12207 update Frameworks.md and remove 's' from cucumber option 'names' to '…
  website/docs/Frameworks.md
Labels: PR: Docs :memo:

#12210 fix: WDIO Cucumber Test Tags
  packages/wdio-browserstack-service/src/accessibility-handler.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/util.test.ts
Labels: PR: Bug Fix :bug:

#12303 Bump @puppeteer/browsers from 1.9.1 to 2.0.1
  packages/wdio-utils/package.json
  pnpm-lock.yaml
Labels: PR: Bug Fix :bug:

#12305 Workaround for chromedriver domain name change
  packages/wdio-utils/src/node/utils.ts
Labels: PR: Bug Fix :bug:

#12302 Updating capabilities for Lamdatest & Browserstack
  e2e/package.json
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-types/src/Capabilities.ts
  packages/wdio-utils/src/envDetector.ts
  pnpm-lock.yaml
Labels: PR: Bug Fix :bug:, backported

#12306 Updating capabilities for Lamdatest & Browserstack
  package-lock.json
  package.json
  packages/wdio-allure-reporter/tests/helpers/wdio-allure-helper.ts
  packages/wdio-browser-runner/src/vite/plugins/esbuild.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-cli/package.json
  packages/wdio-types/src/Capabilities.ts
  packages/wdio-utils/src/envDetector.ts
Labels: PR: Bug Fix :bug:

#12307 [V8] Updated props to optional for getText and getLocation commands
  packages/webdriverio/src/commands/element/getLocation.ts
  packages/webdriverio/src/commands/element/getSize.ts
  tests/typings/webdriverio/commands.ts
Labels: PR: Bug Fix :bug:

#12308 Updated props to optional for getText and getLocation commands
  packages/webdriverio/src/commands/element/getLocation.ts
  packages/webdriverio/src/commands/element/getSize.ts
  tests/typings/webdriverio/commands.ts
Labels: PR: Bug Fix :bug:

#12327 fix(@wdio/utils): only apply baseUrl to Chromium based browser
  packages/wdio-utils/src/node/utils.ts
Labels: PR: Bug Fix :bug:

#12330 fix: added filename in file upload
  packages/wdio-browserstack-service/src/launcher.ts
Labels: PR: Bug Fix :bug:

#12335 (internal): remove dependency to devtools package
  packages/webdriverio/package.json
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/interception/devtools.ts
  packages/webdriverio/src/utils/interception/index.ts
  packages/webdriverio/src/utils/interception/types.ts
  pnpm-lock.yaml
Labels: PR: Polish :nail_care:

#12345 [V8] Add feature to specify os version for the emulated device
  packages/wdio-devtools-service/README.md
  packages/wdio-devtools-service/src/commands.ts
  packages/wdio-devtools-service/src/index.ts
  packages/wdio-devtools-service/src/types.ts
Labels: PR: Polish :nail_care:

#12344 Add feature to specify os version for the emulated device
  packages/wdio-devtools-service/README.md
  packages/wdio-devtools-service/src/commands.ts
  packages/wdio-devtools-service/src/index.ts
  packages/wdio-devtools-service/src/types.ts
Labels: PR: Polish :nail_care:

#12368 Browserstack observability reload session fix [v8]
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/tests/insights-handler.test.ts
Labels: PR: Bug Fix :bug:

#12369 Browserstack observability reload session fix [v7]
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/tests/insight-handler.test.ts
Labels: PR: Bug Fix :bug:

#12340 Browserstack observability reload session fix
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/tests/insights-handler.test.ts
Labels: PR: Bug Fix :bug:

#12378 (wdio-allure-reporter): CompoundError: Also print error message if present [v8]
  packages/wdio-allure-reporter/src/compoundError.ts
  packages/wdio-allure-reporter/tests/__fixtures__/testState.ts
  packages/wdio-allure-reporter/tests/compoundError.test.ts
  packages/wdio-allure-reporter/tests/suite.test.ts
Labels: PR: Polish :nail_care:

#12383 [v8] Add ability to click and moveTo outside the given element
  packages/webdriverio/src/commands/element/click.ts
  packages/webdriverio/src/commands/element/moveTo.ts
Labels: PR: Polish :nail_care:

#12370 (wdio-config): change order of the specs when using --multi-run
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-config/src/node/ConfigParser.ts
  packages/wdio-config/tests/node/configparser.test.ts
  website/docs/Retry.md
  website/docs/Testrunner.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/Retry.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/Retry.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/de/docusaurus-plugin-content-docs/current/Retry.md
  website/i18n/de/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/es/docusaurus-plugin-content-docs/current/Retry.md
  website/i18n/es/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/Retry.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/Retry.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/Retry.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/it/docusaurus-plugin-content-docs/current/Retry.md
  website/i18n/it/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/Retry.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/Retry.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/Retry.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/Retry.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/Retry.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/Testrunner.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/Retry.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/Testrunner.md
Labels: PR: Breaking Change :boom:
