Repository webdriverio/webdriverio, pull requests merged in 2024-07, with the labels that each got.

#13083 Reload session support
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/src/types.ts
Labels: PR: Bug Fix :bug:

#13085 chore: Reload session support
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/src/types.ts
Labels: PR: Bug Fix :bug:

#13122 Fix reloadSession subsequent commands
  packages/webdriver/src/index.ts
  packages/webdriver/tests/index.test.ts
Labels: PR: Polish :nail_care:

#13118 Support app inside appium options (v8)
  packages/wdio-browserstack-service/src/service.ts
Labels: PR: Bug Fix :bug:

#13113 Support app inside appium options (v9)
  packages/wdio-browserstack-service/src/service.ts
Labels: PR: Bug Fix :bug:

#13208 fix(@wdio/utils): Don't download chromedriver with CHROMEDRIVER_PATH (v8 backport)
  packages/wdio-utils/src/node/manager.ts
Labels: PR: Bug Fix :bug:

#13211 Dedupe Capabilities (main)
  packages/wdio-config/src/node/ConfigParser.ts
  packages/wdio-config/tests/node/configparser.test.ts
Labels: PR: Bug Fix :bug:

#12888 Dedupe Capabilities
  packages/wdio-config/src/node/ConfigParser.ts
  packages/wdio-config/tests/node/configparser.test.ts
Labels: PR: Bug Fix :bug:

#13179 fix-v8(@wdio/appium-service): add port to appium start command
  packages/wdio-appium-service/src/launcher.ts
  packages/wdio-appium-service/tests/__snapshots__/launcher.test.ts.snap
  packages/wdio-appium-service/tests/launcher.test.ts
Labels: PR: Bug Fix :bug:

#13180 fix(@wdio/appium-service): add port to appium start command
  packages/wdio-appium-service/src/launcher.ts
  packages/wdio-appium-service/tests/__snapshots__/launcher.test.ts.snap
  packages/wdio-appium-service/tests/launcher.test.ts
Labels: PR: Bug Fix :bug:

#13210 feat(webdriver): automatically opt-into WebDriver Bidi
  e2e/wdio/headless/multiremoteTest.e2e.ts
  e2e/wdio/headless/reloadSession.e2e.ts
  e2e/wdio/wdio.local.conf.ts
  packages/wdio-lighthouse-service/tests/__snapshots__/commands.test.ts.snap
  packages/wdio-types/src/Capabilities.ts
  packages/wdio-utils/src/node/utils.ts
  packages/webdriver/README.md
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/__snapshots__/index.test.ts.snap
  packages/webdriver/tests/index.test.ts
  packages/webdriver/tests/utils.test.ts
  website/docs/Capabilities.md
Labels: PR: New Feature :rocket:

#13212 feat(@wdio/browser-runner): allow to define custom hostname for component tests
  packages/wdio-browser-runner/src/index.ts
  packages/wdio-browser-runner/src/types.ts
  packages/wdio-browser-runner/src/vite/constants.ts
  packages/wdio-browser-runner/src/vite/server.ts
  packages/wdio-browser-runner/tests/vite/server.test.ts
  website/docs/ComponentTesting.md
Labels: PR: New Feature :rocket:

#13150 fix(webdriver): better error response detection for Safari and FF
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#13214 chore(webdriver): show stack trace for bidi errors
  packages/webdriver/src/bidi/core.ts
  packages/webdriver/tests/bidi.test.ts
Labels: PR: Polish :nail_care:

#13224 fix(wdio-browserstack-service): Fetching hostname in case of MultiRemote Browser
  packages/wdio-browserstack-service/src/util.ts
Labels: PR: Bug Fix :bug:

#13223 fix(webdriverio): don't support deep piercing in iframes
  e2e/attach.test.ts
  e2e/wdio/headless/test.e2e.ts
  packages/webdriver/src/bidi/core.ts
  packages/webdriver/src/types.ts
  packages/webdriverio/src/shadowRoot.ts
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/shadowRoot.test.ts
  packages/webdriverio/tsconfig.json
Labels: PR: Bug Fix :bug:

#13222 feat(webdriverio): new features for url command
  e2e/wdio/headless/test.e2e.ts
  package.json
  packages/wdio-types/src/Network.ts
  packages/wdio-types/src/index.ts
  packages/webdriverio/src/commands/browser/url.ts
  packages/webdriverio/src/index.ts
  packages/webdriverio/src/networkManager.ts
  packages/webdriverio/src/types.ts
  pnpm-lock.yaml
Labels: PR: New Feature :rocket:
