Repository webdriverio/webdriverio, pull requests merged in 2024-04, with the labels that each got.

#12620 Updating Sauce Labs specific capability type definitions - Backport v8
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Docs :memo:

#12598 Support mocking interface for Bidi
  __mocks__/fetch.ts
  e2e/browser-runner/lit.test.js
  e2e/browser-runner/mock.test.ts
  e2e/browser-runner/wdio.conf.js
  e2e/package.json
  e2e/vitest.config.ts
  packages/wdio-allure-reporter/package.json
  packages/wdio-appium-service/package.json
  packages/wdio-browser-runner/package.json
  packages/wdio-browser-runner/src/browser/driver.ts
  packages/wdio-browser-runner/src/vite/plugins/testrunner.ts
  packages/wdio-browserstack-service/package.json
  packages/wdio-cli/package.json
  packages/wdio-concise-reporter/package.json
  packages/wdio-config/package.json
  packages/wdio-cucumber-framework/package.json
  packages/wdio-devtools-service/package.json
  packages/wdio-dot-reporter/package.json
  packages/wdio-firefox-profile-service/package.json
  packages/wdio-globals/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-json-reporter/package.json
  packages/wdio-junit-reporter/package.json
  packages/wdio-local-runner/package.json
  packages/wdio-reporter/package.json
  packages/wdio-sauce-service/package.json
  packages/wdio-shared-store-service/package.json
  packages/wdio-smoke-test-reporter/package.json
  packages/wdio-spec-reporter/package.json
  packages/wdio-static-server-service/package.json
  packages/wdio-sumologic-reporter/package.json
  packages/wdio-testingbot-service/package.json
  packages/wdio-utils/src/monad.ts
  packages/wdio-webdriver-mock-service/package.json
  packages/webdriver/package.json
  packages/webdriver/src/bidi/core.ts
  packages/webdriver/src/bidi/socket.ts
  packages/webdriver/src/index.ts
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/browser/mock.ts
  packages/webdriverio/src/commands/browser/throttle.ts
  packages/webdriverio/src/commands/browser/throttleNetwork.ts
  packages/webdriverio/src/middlewares.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/getElementObject.ts
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/src/utils/interception/devtools.ts
  packages/webdriverio/src/utils/interception/index.ts
  packages/webdriverio/src/utils/interception/types.ts
  packages/webdriverio/src/utils/interception/utils.ts
  packages/webdriverio/src/utils/interception/webdriver.ts
  packages/webdriverio/tests/commands/browser/mock.test.ts
  packages/webdriverio/tests/commands/browser/reloadSession.test.ts
  packages/webdriverio/tests/utils/index.test.ts
  packages/webdriverio/tests/utils/interception/__snapshots__/devtools.test.ts.snap
  packages/webdriverio/tests/utils/interception/devtools.test.ts
  packages/webdriverio/tests/utils/interception/interception.test.ts
  packages/webdriverio/tests/utils/interception/utils.test.ts
  packages/webdriverio/tests/utils/interception/webdriver.test.ts
  pnpm-lock.yaml
Labels: PR: New Feature :rocket:, v9

#12627 docs: Remove link to Gitter
  .github/SUPPORT.md
Labels: PR: Docs :memo:

#12628 Use maintained `npm-run-all2`
  package.json
  pnpm-lock.yaml
Labels: PR: Internal :house:

#12593 (webdriverio): render shadow elements into proper declarative shadow doms
  e2e/browser-runner/__snapshots__/lit.test.js.snap
  e2e/browser-runner/__snapshots__/stencil.test.tsx.snap
  e2e/browser-runner/components/LitComponent.ts
  e2e/browser-runner/lit.test.js
  e2e/package.json
  packages/wdio-browser-runner/package.json
  packages/wdio-browser-runner/src/vite/frameworks/stencil.ts
  packages/wdio-cli/tests/commands/config.test.ts
  packages/wdio-cli/tests/commands/install.test.ts
  packages/wdio-cli/tests/commands/run.test.ts
  packages/wdio-cli/tests/config.test.ts
  packages/wdio-cli/tests/onboarding.test.ts
  packages/wdio-cucumber-framework/tests/adapter.test.ts
  packages/wdio-runner/tests/index.test.ts
  packages/webdriverio/package.json
  packages/webdriverio/src/commands/element/getHTML.ts
  packages/webdriverio/src/scripts/getHTMLShadow.ts
  packages/webdriverio/src/shadowRoot.ts
  packages/webdriverio/src/utils/getElementObject.ts
  packages/webdriverio/src/utils/refetchElement.ts
  pnpm-lock.yaml
  tests/helpers/fixtures.js
Labels: PR: Polish :nail_care:, v9

#12665 Fix error messages
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/testOps/listener.ts
  packages/wdio-browserstack-service/src/util.ts
Labels: PR: Bug Fix :bug:

#12677 update: error messages
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/testOps/listener.ts
  packages/wdio-browserstack-service/src/util.ts
Labels: PR: Bug Fix :bug:

#12675 Fix skip test filename
  packages/wdio-browserstack-service/src/reporter.ts
Labels: PR: Polish :nail_care:

#12708 fix: Fix skip test filename
  packages/wdio-browserstack-service/src/reporter.ts
Labels: PR: Polish :nail_care:

#12669 [webdriverio] Fix issue wdio log is missing in standalone mode
  __mocks__/@wdio/utils.ts
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/tests/launcher.test.ts
  packages/wdio-runner/src/utils.ts
  packages/wdio-runner/tests/utils.test.ts
  packages/wdio-utils/src/index.ts
  packages/wdio-utils/src/utils.ts
  packages/wdio-utils/tests/utils.test.ts
  packages/webdriverio/src/index.ts
Labels: PR: Bug Fix :bug:

#12703 [webdriverio-v8] Fix issue wdio log is missing in standalone mode
  __mocks__/@wdio/utils.ts
  packages/wdio-cli/src/launcher.ts
  packages/wdio-cli/tests/launcher.test.ts
  packages/wdio-runner/src/utils.ts
  packages/wdio-runner/tests/utils.test.ts
  packages/wdio-utils/src/index.ts
  packages/wdio-utils/src/utils.ts
  packages/wdio-utils/tests/utils.test.ts
  packages/webdriverio/src/index.ts
Labels: PR: Bug Fix :bug:

#12716 [webdriverio-v8] Flat ESLint support
  package-lock.json
  packages/eslint-plugin-wdio/docs/rules/no-debug.md
  packages/eslint-plugin-wdio/package.json
  packages/eslint-plugin-wdio/src/index.ts
Labels: PR: New Feature :rocket:

#12679 Flat ESLint support
  packages/eslint-plugin-wdio/docs/rules/no-debug.md
  packages/eslint-plugin-wdio/package.json
  packages/eslint-plugin-wdio/src/index.ts
  pnpm-lock.yaml
Labels: PR: New Feature :rocket:

#12723 fix: error counts in junit reporter
  packages/wdio-junit-reporter/README.md
  packages/wdio-junit-reporter/src/index.ts
  packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.ts.snap
Labels: PR: Bug Fix :bug:

#12751 [12428] [V8] CustomService is run twice
  packages/wdio-config/src/node/ConfigParser.ts
  packages/wdio-config/tests/node/configparser.test.ts
Labels: PR: Bug Fix :bug:

#12430 [12428] CustomService is run twice
  packages/wdio-config/src/node/ConfigParser.ts
  packages/wdio-config/tests/node/configparser.test.ts
Labels: PR: Bug Fix :bug:

#12720 feat(webdriverio): deep shadow root piercing
  .eslintrc.cjs
  e2e/browser-runner/__snapshots__/lit.test.js.snap
  e2e/browser-runner/components/LitComponent.ts
  e2e/browser-runner/lit.test.js
  e2e/browser-runner/wdio.conf.js
  packages/wdio-protocols/src/protocols/webdriverBidi.ts
  packages/wdio-utils/src/node/utils.ts
  packages/wdio-utils/tests/node/utils.test.ts
  packages/webdriver/src/bidi/handler.ts
  packages/webdriver/src/bidi/localTypes.ts
  packages/webdriver/src/bidi/remoteTypes.ts
  packages/webdriverio/src/commands/browser/$.ts
  packages/webdriverio/src/commands/element/getHTML.ts
  packages/webdriverio/src/scripts/customElement.ts
  packages/webdriverio/src/scripts/getHTMLShadow.ts
  packages/webdriverio/src/shadowRoot.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/getElementObject.ts
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/commands/browser/$$.test.ts
  packages/webdriverio/tests/commands/browser/$.test.ts
  packages/webdriverio/tests/commands/element/$$.test.ts
  packages/webdriverio/tests/commands/element/$.test.ts
  packages/webdriverio/tests/shadowRoot.test.ts
  packages/webdriverio/tests/utils/index.test.ts
  scripts/bidi/downloadSpec.ts
  scripts/bidi/index.ts
Labels: PR: New Feature :rocket:, v9
