Repository webdriverio/webdriverio, pull requests merged in 2024-09, with the labels that each got.

#13486 Fix `addInitScript` example in v9 blog post
  website/blog/2024-08-15-webdriverio-v9-release.md
Labels: PR: Docs :memo:

#13489 fix(@wdio/browser-runner): support Firefox using Bidi
  packages/wdio-browser-runner/package.json
  packages/wdio-browser-runner/src/index.ts
  packages/wdio-browser-runner/src/vite/server.ts
  packages/wdio-browser-runner/tests/runner.test.ts
  pnpm-lock.yaml
Labels: PR: Bug Fix :bug:

#13511 Add visual reporting option
  website/docs/visual-testing/service-options.md
Labels: Docs 📖

#13514 Added information on typescript types for wdio-shared-store-service
  packages/wdio-shared-store-service/README.md
Labels: PR: Docs :memo:

#13481 feat(webdriverio): set cookies via Bidi if supported
  packages/wdio-protocols/src/types.ts
  packages/webdriverio/src/commands/browser/deleteCookies.ts
  packages/webdriverio/src/commands/browser/getCookies.ts
  packages/webdriverio/src/commands/browser/setCookies.ts
  packages/webdriverio/src/commands/browser/setViewport.ts
  packages/webdriverio/tests/commands/browser/deleteCookies.test.ts
  packages/webdriverio/tests/commands/browser/getCookies.test.ts
  packages/webdriverio/tests/commands/browser/setCookies.test.ts
  packages/webdriverio/tests/commands/browser/setViewport.test.ts
  tests/multiremote/test.js
  tests/typings/webdriverio/async.ts
Labels: PR: New Feature :rocket:

#13482 fix(core): specify minimum node version to be 18.18.0 or higher
  .github/workflows/test-smoke.yml
  packages/eslint-plugin-wdio/package.json
  packages/wdio-allure-reporter/package.json
  packages/wdio-appium-service/package.json
  packages/wdio-browser-runner/package.json
  packages/wdio-browserstack-service/package.json
  packages/wdio-cli/package.json
  packages/wdio-concise-reporter/package.json
  packages/wdio-config/package.json
  packages/wdio-cucumber-framework/package.json
  packages/wdio-dot-reporter/package.json
  packages/wdio-firefox-profile-service/package.json
  packages/wdio-globals/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-junit-reporter/package.json
  packages/wdio-lighthouse-service/package.json
  packages/wdio-local-runner/package.json
  packages/wdio-logger/package.json
  packages/wdio-mocha-framework/package.json
  packages/wdio-repl/package.json
  packages/wdio-reporter/package.json
  packages/wdio-runner/package.json
  packages/wdio-sauce-service/package.json
  packages/wdio-shared-store-service/package.json
  packages/wdio-smoke-test-cjs-service/package.json
  packages/wdio-smoke-test-reporter/package.json
  packages/wdio-smoke-test-service/package.json
  packages/wdio-spec-reporter/package.json
  packages/wdio-static-server-service/package.json
  packages/wdio-sumologic-reporter/package.json
  packages/wdio-testingbot-service/package.json
  packages/wdio-types/package.json
  packages/wdio-utils/package.json
  packages/wdio-webdriver-mock-service/package.json
  packages/webdriver/package.json
  packages/webdriverio/package.json
  website/docs/GettingStarted.md
Labels: PR: Bug Fix :bug:

#13470 fix(webdriverio): fix script execution
  e2e/wdio/headless/bidi.e2e.ts
  e2e/wdio/headless/reloadSession.e2e.ts
  e2e/wdio/headless/test.e2e.ts
  examples/wdio/mocha/package.json
  examples/wdio/mocha/wdio.conf.js
  examples/wdio/mocha/wdio.conf.ts
  examples/wdio/package.json
  packages/webdriverio/src/commands/browser/execute.ts
  packages/webdriverio/src/commands/browser/executeAsync.ts
  packages/webdriverio/src/commands/constant.ts
  packages/webdriverio/src/commands/element/execute.ts
  packages/webdriverio/src/commands/element/executeAsync.ts
  packages/webdriverio/src/index.ts
  packages/webdriverio/src/polyfill.ts
  packages/webdriverio/src/utils/bidi/error.ts
  packages/webdriverio/src/utils/bidi/index.ts
  packages/webdriverio/tests/utils/bidi/index.test.ts
  pnpm-lock.yaml
Labels: PR: Bug Fix :bug:

#13520 fix the second deepselector call
  packages/webdriverio/src/utils/index.ts
Labels: PR: Bug Fix :bug:

#13439 Browserstack Turboscale Observability Integration
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/insight-handler.test.ts
Labels: PR: Polish :nail_care:

#13527 docs(watch-mode): update running instructions
  .devcontainer/devcontainer.json
  .gitpod.yml
  CONTRIBUTING.md
Labels: PR: Docs :memo:

#13549 docs: missing async in timeout docs
  website/docs/Timeouts.md
Labels: PR: Docs :memo:

#13557 fix(#11999): regression with Jasmine types
  packages/wdio-cli/src/utils.ts
Labels: PR: Bug Fix :bug:

#13567 fix(@wdio/types): make 'moz:debuggerAddress' a string or boolean
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Bug Fix :bug:

#13565 docs: fix bun create tab on gettingstarted
  website/docs/GettingStarted.md
Labels: PR: Docs :memo:

#13568 fix(@wdio/cli): package manager detection improvements
  packages/wdio-cli/src/utils.ts
  packages/wdio-cli/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#13566 fix(@wdio/cli): cucumber generated config spec path
  packages/wdio-cli/src/constants.ts
Labels: PR: Bug Fix :bug:

#13603 fix(@wdio/cli): fix type for config when generating a project
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
Labels: PR: Bug Fix :bug:

#13606 fix ci by removing unexpected ts-expect-error statements
  packages/wdio-cli/src/commands/config.ts
  packages/wdio-cli/src/utils.ts
Labels: PR: Bug Fix :bug:

#13523 Fix customElement wrapper for custom elements which don't define connectedCallback or disconnectedCallback
  e2e/browser-runner/lit.test.js
  packages/webdriverio/src/scripts/customElement.ts
Labels: PR: Bug Fix :bug:

#13605 fix(@wdio/cli): fix type for config when generating a project
  packages/wdio-browser-runner/package.json
  pnpm-lock.yaml
Labels: PR: Bug Fix :bug:

#13526 [junit-reporter] Add option to include nodejs console log in junit report
  packages/wdio-junit-reporter/README.md
  packages/wdio-junit-reporter/src/index.ts
  packages/wdio-junit-reporter/src/types.ts
  packages/wdio-junit-reporter/tests/reporter.test.ts
Labels: PR: New Feature :rocket:

#13564 fix(wdio-cucumber-framework): filter cucumberFeaturesWithLineNumbers
  infra/compiler/src/index.ts
  packages/wdio-cucumber-framework/src/index.ts
  tests/cucumber/features/features.given.js
  tests/cucumber/features/test1.feature
  tests/cucumber/features/test2.feature
  tests/cucumber/features/test3.feature
  tests/cucumber/reporter/reporter.given.js
  tests/cucumber/step-definitions/given.js
  tests/cucumber/step-definitions/then.js
  tests/helpers/cucumber-features.conf.js
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#13570 v7: Auto Enable App Percy for App Automate
  packages/wdio-browserstack-service/src/Percy/Percy.ts
  packages/wdio-browserstack-service/src/config.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/tests/Percy.test.ts
  packages/wdio-browserstack-service/tests/launcher.test.ts
Labels: PR: Polish :nail_care:

#13569 v8: Auto Enable App Percy for App Automate
  packages/wdio-browserstack-service/src/Percy/Percy.ts
  packages/wdio-browserstack-service/src/config.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/tests/launcher.test.ts
Labels: PR: Polish :nail_care:

#13604 [junit-reporter]: Add function to add additional properties to testcases
  packages/wdio-junit-reporter/README.md
  packages/wdio-junit-reporter/src/common/api.ts
  packages/wdio-junit-reporter/src/index.ts
  packages/wdio-junit-reporter/tests/reporter.test.ts
Labels: PR: New Feature :rocket:

#13613 feat(@wdio/junit-reporter): provide CJS export
  package.json
  packages/wdio-junit-reporter/package.json
  pnpm-lock.yaml
  tests/interop/junit-reporter.e2e.js
  tests/interop/package.json
Labels: PR: Polish :nail_care:

#13612 Removing us-east-1 region
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/tests/__snapshots__/index.test.ts.snap
  packages/wdio-spec-reporter/tests/index.test.ts
  packages/wdio-types/src/Options.ts
  packages/webdriverio/src/utils/detectBackend.ts
  packages/webdriverio/tests/utils/detectBackend.test.ts
Labels: PR: Polish :nail_care:

#13563 fix(wdio-cucumber-framework): filter cucumberFeaturesWithLineNumbers (v8)
  packages/wdio-cucumber-framework/src/index.ts
  tests/cucumber/features/features.given.js
  tests/cucumber/features/test1.feature
  tests/cucumber/features/test2.feature
  tests/cucumber/features/test3.feature
  tests/helpers/cucumber-features.conf.js
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#13616 Add file to cucumber options
  packages/wdio-cucumber-framework/src/constants.ts
  packages/wdio-cucumber-framework/src/index.ts
  packages/wdio-cucumber-framework/src/types.ts
  tests/cucumber/cucumber.js
  tests/smoke.runner.js
Labels: PR: New Feature :rocket:

#13625 Refetches element on bidi context change
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/utils/index.test.ts
Labels: PR: Bug Fix :bug:

#13622 fix(webdriverio): don't send `desiredCapabilities` anymore when initializing a session
  __mocks__/fetch.ts
  packages/wdio-appium-service/tests/launcher.test.ts
  packages/wdio-sauce-service/tests/launcher.test.ts
  packages/wdio-testingbot-service/tests/launcher.test.ts
  packages/wdio-utils/src/utils.ts
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/index.test.ts
  packages/webdriverio/tests/addCommand.test.ts
  packages/webdriverio/tests/commands/browser/$.test.ts
  packages/webdriverio/tests/commands/browser/newWindow.test.ts
  packages/webdriverio/tests/commands/browser/setTimeout.test.ts
  packages/webdriverio/tests/commands/element/$.test.ts
  packages/webdriverio/tests/commands/element/getValue.test.ts
  packages/webdriverio/tests/overwriteCommand.test.ts
Labels: PR: Polish :nail_care:

#13627 docs(integration): added selenium grid integration docs
  CONTRIBUTING.md
  website/_sidebars.json
  website/docs/SeleniumGrid.md
Labels: PR: Docs :memo:

#13648 fix(@wdio/utils): disable Bidi for Appium sessions
  packages/wdio-utils/src/envDetector.ts
  packages/wdio-utils/tests/envDetector.test.ts
  packages/webdriver/src/index.ts
Labels: PR: Polish :nail_care:

#13649 fix(webdriver): restore request retries
  packages/wdio-webdriver-mock-service/src/index.ts
  packages/webdriver/src/request/constants.ts
  packages/webdriver/src/request/index.ts
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/request.test.ts
  packages/webdriver/tests/utils.test.ts
  tests/mocha/test.ts
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:

#13653 fix(build): website build issue on windows
  scripts/docs-generation/electronDocs.ts
  scripts/docs-generation/eventDocs.ts
Labels: PR: Docs :memo:

#13655 chore: improve log formatting for args
  packages/wdio-local-runner/src/worker.ts
Labels: PR: Polish :nail_care:

#13650 [junit-reporter] compare files ignoring case on win32
  packages/wdio-junit-reporter/src/index.ts
  packages/wdio-junit-reporter/tests/reporter.test.ts
Labels: PR: Bug Fix :bug:

#13657 fix(webdriverio): recognise shadow tree after context reload
  e2e/wdio/headless/test.e2e.ts
  packages/webdriverio/src/shadowRoot.ts
  packages/webdriverio/tests/shadowRoot.test.ts
Labels: PR: Bug Fix :bug:

#13659 fix(webdriverio): better handle context switches
  e2e/wdio/headless/test.e2e.ts
  packages/webdriverio/src/commands/browser/newWindow.ts
  packages/webdriverio/src/commands/browser/switchWindow.ts
  packages/webdriverio/src/context.ts
Labels: PR: Bug Fix :bug:

#13660 fix(webdriver): also retry on various error codes
  packages/webdriver/src/request/constants.ts
  packages/webdriver/src/request/index.ts
Labels: PR: Bug Fix :bug:

#13666 Removing APAC region
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
  packages/wdio-sauce-service/README.md
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/tests/__snapshots__/index.test.ts.snap
  packages/wdio-spec-reporter/tests/index.test.ts
  packages/wdio-types/src/Options.ts
  packages/webdriverio/src/utils/detectBackend.ts
  packages/webdriverio/tests/utils/detectBackend.test.ts
Labels: PR: Polish :nail_care:

#13665 Reject promise if test is skipped via async method
  packages/wdio-utils/src/shim.ts
Labels: PR: Bug Fix :bug:

#13668 fix(webdriverio): fix mock filtering
  packages/webdriverio/src/utils/interception/index.ts
  packages/webdriverio/tests/utils/interception/index.test.ts
Labels: PR: Bug Fix :bug:

#13669 fix(webdriverio): fix execute command when passing in a string
  e2e/wdio/headless/bidi.e2e.ts
  packages/webdriverio/src/commands/browser/execute.ts
  packages/webdriverio/src/commands/browser/executeAsync.ts
Labels: PR: Bug Fix :bug:

#13667 chore(webdriver): refactor request/response error handling
  e2e/attach.test.ts
  e2e/browser-runner/lit.test.js
  packages/wdio-types/src/Options.ts
  packages/webdriver/src/command.ts
  packages/webdriver/src/constants.ts
  packages/webdriver/src/request/constants.ts
  packages/webdriver/src/request/error.ts
  packages/webdriver/src/request/index.ts
  packages/webdriver/src/request/request.ts
  packages/webdriver/src/request/types.ts
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/__snapshots__/utils.test.ts.snap
  packages/webdriver/tests/request.test.ts
  packages/webdriver/tests/request/error.test.ts
  packages/webdriver/tests/utils.test.ts
Labels: PR: Polish :nail_care:

#13717 fix(ci) group dependabot PRs by version type
  .github/dependabot.yml
Labels: PR: Internal :house:

#13701 fix(@wdio/sauce-service): fix setting annotations
  e2e/package.json
  e2e/wdio/wdio.sauce.conf.ts
  packages/wdio-sauce-service/src/service.ts
  packages/wdio-sauce-service/tests/service.test.ts
  packages/wdio-spec-reporter/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: PR: Bug Fix :bug:

#13694 Allow transformation from classic tag name selector to BiDi
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/utils/index.test.ts
Labels: PR: Bug Fix :bug:
