Repository webdriverio/webdriverio, pull requests merged in 2025-06, with the labels that each got.

#14523 fix(docs): update various Appium-related links
  packages/wdio-appium-service/README.md
  packages/wdio-cli/src/utils.ts
  packages/wdio-protocols/src/protocols/appium.ts
  packages/wdio-types/src/Capabilities.ts
  packages/webdriverio/src/commands/browser/action.ts
  website/docs/Appium.md
  website/docs/Capabilities.md
  website/docs/Configuration.md
  website/docs/Security.md
  website/docs/desktop-testing/MacOS.md
Labels: PR: Docs :memo:

#14522 fix(@wdio/protocols): Have `options` of appium terminateApp command optional
  packages/wdio-protocols/src/protocols/appium.ts
Labels: PR: Bug Fix :bug:

#14557 fix for accessibility build error [wdio-browsertstack-service]
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/util.test.ts
Labels: PR: Bug Fix :bug:

#14546 feat(wdio-runner): automatically include SoftAssertionService
  __mocks__/expect-webdriverio.ts
  e2e/browser-runner/react.test.tsx
  packages/wdio-config/src/constants.ts
  packages/wdio-runner/package.json
  packages/wdio-runner/src/index.ts
  packages/wdio-runner/tests/index.test.ts
  packages/wdio-types/src/Options.ts
  pnpm-lock.yaml
  website/docs/Assertion.md
  website/docs/Configuration.md
Labels: PR: New Feature :rocket:

#14565 fix(wdio-utils):fix to support windows path string
  packages/wdio-utils/src/initializePlugin.ts
  packages/wdio-utils/src/utils.ts
  packages/wdio-utils/tests/__fixtures__/plugins/bar-service.js
  packages/wdio-utils/tests/__fixtures__/plugins/foo-service.js
  packages/wdio-utils/tests/initializePlugin.test.ts
  packages/wdio-utils/tests/initializeServices.test.ts
  packages/wdio-utils/tests/utils.test.ts
Labels: PR: Bug Fix :bug:

#14572 Fix for isAndroid outside of test
  packages/wdio-utils/src/envDetector.ts
  packages/wdio-utils/tests/envDetector.test.ts
Labels: PR: Bug Fix :bug:

#14236 fix: Combines exclude and wdio:exclude.
  packages/wdio-config/src/node/ConfigParser.ts
  packages/wdio-config/tests/node/configparser.test.ts
Labels: PR: Bug Fix :bug:
