Repository webdriverio/webdriverio, pull requests merged in 2025-03, with the labels that each got.

#14242 fix(webdriverio): don't continue failing context request
  packages/webdriverio/src/session/context.ts
Labels: PR: Polish :nail_care:

#14234 feat(cucumber): Distinguish Cucumber PENDING status in reporters
  packages/wdio-cucumber-framework/src/cucumberFormatter.ts
  packages/wdio-cucumber-framework/src/utils.ts
  packages/wdio-cucumber-framework/tests/utils.test.ts
  packages/wdio-reporter/src/index.ts
  packages/wdio-reporter/src/stats/test.ts
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/src/types.ts
  packages/wdio-spec-reporter/tests/index.test.ts
  tests/cucumber/step-definitions/pending-steps.js
  tests/cucumber/test-pending.feature
  tests/smoke.runner.js
Labels: PR: New Feature :rocket:

#14244 fix(cli): bring back support for glob pattern in filesToWatch
  packages/wdio-cli/src/watcher.ts
  packages/wdio-cli/tests/watcher.test.ts
  packages/wdio-config/src/node/index.ts
Labels: PR: Bug Fix :bug:

#14245 fix(@wdio/utils): better detect functions in parameter
  packages/wdio-utils/src/utils.ts
  packages/wdio-utils/tests/utils.test.ts
Labels: PR: Polish :nail_care:

#14243 [WDIO9] added wildcards for cli
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-config/src/node/ConfigParser.ts
  packages/wdio-config/src/node/utils.ts
  tests/smoke.runner.js
  tests/tests-cli-spec-arg/mocha.test011.js
  tests/tests-cli-spec-arg/wdio-with-all-passed-wildcard.conf.js
  website/docs/Testrunner.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/OrganizingTestSuites.md
Labels: PR: Bug Fix :bug:

#14169 [WDIO8] added supporting wildcars for --spec and --exclude, added --group cli…
  packages/wdio-cli/src/commands/run.ts
  packages/wdio-config/src/node/ConfigParser.ts
  packages/wdio-config/src/node/utils.ts
  tests/smoke.runner.js
  tests/tests-cli-spec-arg/mocha.test011.js
  tests/tests-cli-spec-arg/wdio-with-all-passed-wildcard.conf.js
  website/docs/OrganizingTestSuites.md
  website/docs/Testrunner.md
Labels: PR: Bug Fix :bug:

#14235 feat(cucumber): Backport Distinguishing Cucumber PENDING status to v8
  packages/wdio-cucumber-framework/src/cucumberFormatter.ts
  packages/wdio-cucumber-framework/src/utils.ts
  packages/wdio-cucumber-framework/tests/utils.test.ts
  packages/wdio-reporter/src/index.ts
  packages/wdio-reporter/src/stats/test.ts
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/src/types.ts
  packages/wdio-spec-reporter/tests/index.test.ts
  tests/cucumber/step-definitions/pending-steps.js
  tests/cucumber/test-pending.feature
  tests/smoke.runner.js
Labels: PR: Polish :nail_care:

#14251 docs: improve typescript example with webdriverio namespace
  website/docs/TypeScript.md
Labels: PR: Docs :memo:

#14246 fix(webdriver): abort all operation when session closes
  packages/webdriver/src/bidi/core.ts
  packages/webdriver/src/command.ts
  packages/webdriver/src/request/polyfill.ts
  packages/webdriver/src/request/request.ts
  packages/webdriver/src/types.ts
  packages/webdriver/tests/command.test.ts
  packages/webdriver/tests/request.test.ts
  packages/webdriverio/src/commands/browser/waitUntil.ts
  packages/webdriverio/src/commands/element/waitForDisplayed.ts
  packages/webdriverio/src/utils/Timer.ts
  packages/webdriverio/tests/commands/browser/reloadSession.test.ts
  packages/webdriverio/tests/commands/element/waitForClickable.test.ts
  packages/webdriverio/tests/commands/element/waitForDisplayed.test.ts
  packages/webdriverio/tests/commands/element/waitForEnabled.test.ts
Labels: PR: Bug Fix :bug:

#14263 docs: mention that Chrome DevTools protocol is not installed by default and what package is required
  packages/webdriverio/src/commands/browser/getPuppeteer.ts
  packages/webdriverio/src/commands/browser/throttleCPU.ts
  packages/webdriverio/src/commands/browser/throttleNetwork.ts
Labels: PR: Docs :memo:

#14266 docs: fix waitforfontsloaded position in docs
  website/docs/visual-testing/service-options.md
Labels: PR: Docs :memo:

#14267 feat(webdriverio): allow more options for screenshot taking with Bidi
  packages/webdriverio/src/commands/browser/saveScreenshot.ts
  packages/webdriverio/src/node/saveScreenshot.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/tests/commands/browser/saveScreenshot.test.ts
  packages/webdriverio/tests/node/saveScreenshot.test.ts
  scripts/changelog.ts
Labels: PR: New Feature :rocket:

#14268 fix(webdriverio): fail implicitly when trying to use Puppeteer with the browser runner
  packages/webdriverio/src/commands/browser/getPuppeteer.ts
  packages/webdriverio/tests/commands/browser/getPuppeteer.test.ts
Labels: PR: Polish :nail_care:

#14269 docs: add compareoptions object for visual test docs
  website/docs/visual-testing/service-options.md
Labels: PR: Docs :memo:

#14270 fix(webdriverio): wait for element to exist before executing on it
  packages/webdriverio/src/commands/element/execute.ts
  packages/webdriverio/tests/commands/element/execute.test.ts
Labels: PR: Bug Fix :bug:

#14277 docs: update service-options broken links
  website/docs/visual-testing/service-options.md
Labels: PR: Docs :memo:

#14272 chore(webdriver): add unit tests for DNS patch
  packages/webdriver/src/bidi/core.ts
  packages/webdriver/src/browser.ts
  packages/webdriver/src/environment.ts
  packages/webdriver/src/index.ts
  packages/webdriver/src/node.ts
  packages/webdriver/src/node/bidi.ts
  packages/webdriver/tests/bidi.test.ts
  packages/webdriver/tests/node/bidi.test.ts
Labels: PR: Internal :house:

#14278 fix(webdriver): update the registration logic for abort listener
  packages/webdriver/src/command.ts
  packages/webdriver/tests/command.test.ts
Labels: PR: Polish :nail_care:

#14279 chore(cli): remove unnecessary definition of the variables
  packages/wdio-cli/src/commands/config.ts
Labels: PR: Polish :nail_care:

#14298 fix(webdriverio): update listener registration logic of SessionManager
  packages/webdriverio/src/session/session.ts
  packages/webdriverio/tests/session/session.test.ts
  packages/webdriverio/tests/shadowRoot.test.ts
Labels: PR: Bug Fix :bug:

#14294 Add Roku service to default services
  packages/wdio-cli/src/constants.ts
Labels: PR: Polish :nail_care:

#14287 fix: support windows/mac apps for isDisplayed
  __mocks__/fetch.ts
  packages/wdio-utils/src/envDetector.ts
  packages/wdio-utils/tests/envDetector.test.ts
  packages/webdriver/src/types.ts
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/command.test.ts
  packages/webdriver/tests/index.test.ts
  packages/webdriverio/src/commands/element/isDisplayed.ts
  packages/webdriverio/tests/commands/element/isDisplayed.test.ts
  packages/webdriverio/tests/module.test.ts
  packages/webdriverio/tests/protocol-stub.test.ts
  website/docs/api/Browser.md
Labels: PR: Bug Fix :bug:

#14288 Fix isClickable auto-scroll
  packages/webdriverio/src/scripts/isElementClickable.ts
  packages/webdriverio/tests/scripts/isElementClickable.test.ts
Labels: PR: Bug Fix :bug:

#14280 Bug Fix: missing Platform version on BrowserStack Observability
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/reporter.ts
  packages/wdio-browserstack-service/src/util.ts
Labels: PR: Bug Fix :bug:

#14304 feat(webdriver): support WebSocket options at the BiDi connection
  packages/webdriver/src/browser.ts
  packages/webdriver/src/environment.ts
  packages/webdriver/src/node/bidi.ts
  packages/webdriver/tests/node/bidi.test.ts
Labels: PR: New Feature :rocket:

#14311 Reduce wait port retry interval
  packages/wdio-utils/src/node/startWebDriver.ts
Labels: PR: Bug Fix :bug:

#14308 fix(docs): resolving broken github actions links
  website/docs/GithubActions.md
Labels: PR: Docs :memo:

#14306 updated spec reporter readme - sharable links value with valid sauce sharable link
  packages/wdio-spec-reporter/README.md
Labels: PR: Docs :memo:

#14312 Percy binary update
  packages/wdio-browserstack-service/package.json
  packages/wdio-browserstack-service/src/Percy/PercyBinary.ts
  pnpm-lock.yaml
Labels: PR: Polish :nail_care:

#14320 docs: update docker docs to use official puppeteer image
  website/docs/Docker.md
Labels: PR: Docs :memo:

#14318 docs: boilerplate project added to MD
  website/docs/BoilerplateProjects.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/BoilerplateProjects.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/BoilerplateProjects.md
  website/i18n/de/docusaurus-plugin-content-docs/current/BoilerplateProjects.md
  website/i18n/es/docusaurus-plugin-content-docs/current/BoilerplateProjects.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/BoilerplateProjects.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/BoilerplateProjects.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/BoilerplateProjects.md
  website/i18n/it/docusaurus-plugin-content-docs/current/BoilerplateProjects.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/BoilerplateProjects.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/BoilerplateProjects.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/BoilerplateProjects.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/BoilerplateProjects.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/BoilerplateProjects.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/BoilerplateProjects.md
Labels: PR: Docs :memo:

#14329 fix(docs): resolving broken sauce connect proxy link
  website/docs/Proxy.md
Labels: PR: Docs :memo:

#14327 docs: fix all references to Sauce Labs docs
  packages/wdio-cli/src/constants.ts
  packages/wdio-cli/src/templates/snippets/services.ejs
  packages/wdio-protocols/src/protocols/saucelabs.ts
  packages/wdio-sauce-service/README.md
  packages/wdio-spec-reporter/src/types.ts
  packages/wdio-types/src/Capabilities.ts
  scripts/protocols.ts
  website/docs/CloudServices.md
  website/docs/Configuration.md
  website/docs/Proxy.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/CloudServices.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/Proxy.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/CloudServices.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/Proxy.md
  website/i18n/de/docusaurus-plugin-content-docs/current/CloudServices.md
  website/i18n/de/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/de/docusaurus-plugin-content-docs/current/Proxy.md
  website/i18n/es/docusaurus-plugin-content-docs/current/CloudServices.md
  website/i18n/es/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/es/docusaurus-plugin-content-docs/current/Proxy.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/CloudServices.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/Proxy.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/CloudServices.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/Proxy.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/CloudServices.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/Proxy.md
  website/i18n/it/docusaurus-plugin-content-docs/current/CloudServices.md
  website/i18n/it/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/it/docusaurus-plugin-content-docs/current/Proxy.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/CloudServices.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/Proxy.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/CloudServices.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/Proxy.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/CloudServices.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/Proxy.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/CloudServices.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/Proxy.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/CloudServices.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/Proxy.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/CloudServices.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/Proxy.md
Labels: PR: Docs :memo:

#14321 fix: android deepLink using package instead of packageName
  packages/webdriverio/src/commands/mobile/deepLink.ts
  packages/webdriverio/tests/commands/mobile/deepLink.test.ts
Labels: PR: Bug Fix :bug:

#14335 fix: fix in docs formatter to accept new types
  scripts/utils/formatter.ts
Labels: PR: Docs :memo:

#14332 SDK-2064 A11y-Platform-Level-Support
  packages/wdio-browserstack-service/src/launcher.ts
Labels: PR: Polish :nail_care:

#14333 SDK-2064 fix: A11y-Platform-Level-Support for v8
  packages/wdio-browserstack-service/src/launcher.ts
Labels: PR: Polish :nail_care:

#14338 fix: Fixes isDisplayed to always use default params for checkVisibility.
  packages/webdriverio/src/commands/element/isDisplayed.ts
Labels: PR: Bug Fix :bug:

#14349 Fix isClickable auto-scroll (#14288)
  packages/webdriverio/src/scripts/isElementClickable.ts
  packages/webdriverio/tests/scripts/isElementClickable.test.ts
Labels: PR: Bug Fix :bug:

#14353 fix broken link in docs. Fixes #14348
  website/docs/Frameworks.md
  website/docs/api/Browser.md
  website/docs/api/Protocols.md
  website/docs/component-testing/Vue.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/Frameworks.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/Frameworks.md
  website/i18n/de/docusaurus-plugin-content-docs/current/Frameworks.md
  website/i18n/es/docusaurus-plugin-content-docs/current/Frameworks.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/Frameworks.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/Frameworks.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/Frameworks.md
  website/i18n/it/docusaurus-plugin-content-docs/current/Frameworks.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/Frameworks.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/Frameworks.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/Frameworks.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/Frameworks.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/Frameworks.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/Frameworks.md
Labels: PR: Docs :memo:
