Repository webdriverio/webdriverio, pull requests merged in 2025-05, with the labels that each got.

#14442 feature: contributor components in the index
  pnpm-lock.yaml
  website/src/components/Contributors/Contributors.tsx
  website/src/components/Contributors/contributors.css
  website/src/pages/index.tsx
Labels: PR: Docs :memo:

#14448 fix(bidi-dialog): only accept dialogs in active browsing context
  packages/webdriverio/src/session/dialog.ts
  packages/webdriverio/tests/commands/dialog/accept.test.ts
Labels: PR: Bug Fix :bug:

#14452 Fix: button alignment, update Twitter icon to X,. feat: add version dropdown
  website/docusaurus.config.ts
  website/docusaurusVersions.ts
  website/src/css/navbar.css
  website/src/pages/styles.module.css
  website/src/theme/card.tsx
Labels: PR: Docs :memo:

#14451 Update BoilerplateProjects.md
  website/docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#14454 feat(reporter): add browserName function and use where required
  __mocks__/@wdio/reporter.ts
  packages/wdio-allure-reporter/src/reporter.ts
  packages/wdio-concise-reporter/src/index.ts
  packages/wdio-reporter/src/index.ts
  packages/wdio-spec-reporter/src/index.ts
Labels: PR: Polish :nail_care:

#14463 fix(webdriver): stop cloning request so `await response.json()` can abort properly
  packages/webdriver/src/request/request.ts
Labels: PR: Bug Fix :bug:

#14472 chore(@wdio/spec-reporter): file name print format
  packages/wdio-spec-reporter/README.md
  packages/wdio-spec-reporter/src/index.ts
  packages/wdio-spec-reporter/tests/__snapshots__/index.test.ts.snap
Labels: PR: Bug Fix :bug:

#14478 feat(protocol): WebDriver Bidi Protocol update
  package.json
  packages/wdio-protocols/src/protocols/webdriverBidi.ts
  packages/webdriver/src/bidi/core.ts
  packages/webdriver/src/bidi/handler.ts
  packages/webdriver/src/bidi/localTypes.ts
  packages/webdriver/src/bidi/remoteTypes.ts
  packages/webdriverio/src/utils/bidi/index.ts
  pnpm-lock.yaml
Labels: PR: New Feature :rocket:

#14474 add browserstack camera-image-injection to wdio-types capabilities
  packages/wdio-types/src/Capabilities.ts
Labels: PR: Polish :nail_care:

#14481 feat: adding check in normalizeDoc function to make sure readmeArr is of string type
  packages/wdio-types/src/Capabilities.ts
  scripts/docs-generation/3rdPartyDocs.ts
Labels: PR: Internal :house:

#14488 docs: improve browser.keys documentation
  packages/webdriverio/src/commands/browser/keys.ts
Labels: PR: Docs :memo:

#14491 fix(webdriver): handle large images on screenshot (fix for 14489 bug)
  packages/webdriver/src/bidi/core.ts
  packages/webdriver/src/bidi/utils.ts
  packages/webdriver/src/constants.ts
  packages/webdriver/tests/bidi-utils.test.ts
Labels: PR: Bug Fix :bug:

#14465 fix(webdriverio): improve typing for execute and executeAsync
  packages/webdriverio/src/commands/browser/execute.ts
  packages/webdriverio/src/commands/browser/executeAsync.ts
  packages/webdriverio/src/commands/element/execute.ts
  packages/webdriverio/src/commands/element/executeAsync.ts
  packages/webdriverio/src/commands/element/getHTML.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/tests/commands/browser/execute.test-d.ts
  packages/webdriverio/tests/commands/browser/executeAsync.test-d.ts
  packages/webdriverio/tests/commands/element/execute.test-d.ts
  packages/webdriverio/tests/commands/element/executeAsync.test-d.ts
Labels: PR: Bug Fix :bug:

#14462 feat(protocol): add Chromium log commands to Appium protocol
  packages/wdio-protocols/src/protocols/appium.ts
Labels: PR: New Feature :rocket:

#14493 Cache the wd request dispatcher
  packages/webdriver/src/request/node.ts
  packages/webdriver/tests/request.test.ts
Labels: PR: Polish :nail_care:

#14507 feat(protocol): extend Appium protocol
  packages/wdio-protocols/src/protocols/appium.ts
Labels: PR: New Feature :rocket:

#13938 feat(runner+browserstack): Mask sensitive data for Reporters (and more)
  __mocks__/@wdio/logger.ts
  e2e/wdio/headless/test.e2e.ts
  e2e/wdio/wdio.conf.ts
  packages/wdio-logger/README.md
  packages/wdio-logger/src/browser.ts
  packages/wdio-logger/src/index.ts
  packages/wdio-logger/src/utils.ts
  packages/wdio-logger/tests/node.test.ts
  packages/wdio-logger/tests/utils.test.ts
  packages/wdio-runner/src/index.ts
  packages/wdio-types/src/Options.ts
  packages/webdriver/src/command.ts
  packages/webdriver/src/constants.ts
  packages/webdriver/src/request/request.ts
  packages/webdriver/src/request/types.ts
  packages/webdriver/src/types.ts
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/command.test.ts
  packages/webdriverio/src/commands/element/addValue.ts
  packages/webdriverio/src/commands/element/setValue.ts
  packages/webdriverio/src/types.ts
  website/_sidebars.json
  website/docs/Configuration.md
  website/docs/Security.md
Labels: PR: New Feature :rocket:, Expensable $100 💸
