Repository webdriverio/webdriverio, pull requests merged in 2025-04, with the labels that each got.

#14357 fix(docs): resolving broken sumologic reporter link
  website/docs/CustomReporter.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/CustomReporter.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/CustomReporter.md
  website/i18n/de/docusaurus-plugin-content-docs/current/CustomReporter.md
  website/i18n/es/docusaurus-plugin-content-docs/current/CustomReporter.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/CustomReporter.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/CustomReporter.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/CustomReporter.md
  website/i18n/it/docusaurus-plugin-content-docs/current/CustomReporter.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/CustomReporter.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/CustomReporter.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/CustomReporter.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/CustomReporter.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/CustomReporter.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/CustomReporter.md
Labels: PR: Docs :memo:

#14360 fix(interception): Properly handle binary response data in WebDriverInterception
  packages/webdriverio/src/utils/interception/index.ts
  packages/webdriverio/src/utils/interception/utils.ts
  packages/webdriverio/tests/utils/interception/index.test.ts
Labels: PR: Bug Fix :bug:

#14366 [docs]: fix reference links
  website/docs/Sharding.md
  website/docs/extension-testing/VSCodeExtension.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/VSCodeExtensionTesting.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/extension-testing/VSCodeExtension.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/VSCodeExtensionTesting.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/extension-testing/VSCodeExtension.md
  website/i18n/de/docusaurus-plugin-content-docs/current/VSCodeExtensionTesting.md
  website/i18n/de/docusaurus-plugin-content-docs/current/extension-testing/VSCodeExtension.md
  website/i18n/es/docusaurus-plugin-content-docs/current/VSCodeExtensionTesting.md
  website/i18n/es/docusaurus-plugin-content-docs/current/extension-testing/VSCodeExtension.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/VSCodeExtensionTesting.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/extension-testing/VSCodeExtension.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/VSCodeExtensionTesting.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/extension-testing/VSCodeExtension.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/VSCodeExtensionTesting.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/extension-testing/VSCodeExtension.md
  website/i18n/it/docusaurus-plugin-content-docs/current/VSCodeExtensionTesting.md
  website/i18n/it/docusaurus-plugin-content-docs/current/extension-testing/VSCodeExtension.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/extension-testing/VSCodeExtension.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/VSCodeExtensionTesting.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/extension-testing/VSCodeExtension.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/VSCodeExtensionTesting.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/extension-testing/VSCodeExtension.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/VSCodeExtensionTesting.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/extension-testing/VSCodeExtension.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/VSCodeExtensionTesting.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/extension-testing/VSCodeExtension.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/VSCodeExtensionTesting.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/extension-testing/VSCodeExtension.md
Labels: PR: Docs :memo:

#14361 fix(webdriverio): fix order of execution in session polyfill
  packages/webdriverio/src/session/polyfill.ts
Labels: PR: Internal :house:

#14369 Migrate documentation parsing to comment-parser
  package.json
  packages/webdriverio/src/commands/browser/getWindowSize.ts
  packages/webdriverio/src/commands/browser/newWindow.ts
  packages/webdriverio/src/commands/browser/react$$.ts
  packages/webdriverio/src/commands/browser/react$.ts
  packages/webdriverio/src/commands/browser/reloadSession.ts
  packages/webdriverio/src/commands/browser/setCookies.ts
  packages/webdriverio/src/commands/browser/setViewport.ts
  packages/webdriverio/src/commands/browser/setWindowSize.ts
  packages/webdriverio/src/commands/browser/switchFrame.ts
  packages/webdriverio/src/commands/browser/url.ts
  packages/webdriverio/src/commands/clock/restore.ts
  packages/webdriverio/src/commands/clock/setSystemTime.ts
  packages/webdriverio/src/commands/clock/tick.ts
  packages/webdriverio/src/commands/element/addValue.ts
  packages/webdriverio/src/commands/element/click.ts
  packages/webdriverio/src/commands/element/getLocation.ts
  packages/webdriverio/src/commands/element/react$$.ts
  packages/webdriverio/src/commands/element/react$.ts
  packages/webdriverio/src/commands/element/setValue.ts
  packages/webdriverio/src/commands/element/waitUntil.ts
  packages/webdriverio/src/commands/mock/request.ts
  packages/webdriverio/src/commands/mock/requestOnce.ts
  pnpm-lock.yaml
  scripts/docs-generation/wdioDocs.ts
  scripts/templates/template.eta
  scripts/utils/formatter.ts
Labels: PR: Docs :memo:

#14376 fix(webdriver): add timeout-related configurable options to ProxyAgent
  packages/webdriver/src/request/node.ts
Labels: PR: Bug Fix :bug:

#14379 feat(@wdio/protocols): Add "options" parameter to "terminateApp" command
  packages/wdio-protocols/src/protocols/appium.ts
Labels: PR: Spec Compliancy :eyeglasses:

#14380 feat(@wdio/protocols): Add "options" parameter to "terminateApp" command (v8)
  packages/wdio-protocols/src/protocols/appium.ts
Labels: PR: Spec Compliancy :eyeglasses:

#14383 chore: ignore error handling for command wrapping
  packages/wdio-browserstack-service/src/util.ts
Labels: PR: Polish :nail_care:

#14387 docs: fixing deprecated tag display and returns
  packages/webdriverio/src/commands/browser/$$.ts
  packages/webdriverio/src/commands/browser/$.ts
  packages/webdriverio/src/commands/browser/custom$.ts
  packages/webdriverio/src/commands/browser/react$$.ts
  packages/webdriverio/src/commands/browser/react$.ts
  packages/webdriverio/src/commands/browser/scroll.ts
  packages/webdriverio/src/commands/element/$$.ts
  packages/webdriverio/src/commands/element/$.ts
  packages/webdriverio/src/commands/element/custom$$.ts
  packages/webdriverio/src/commands/element/custom$.ts
  packages/webdriverio/src/commands/element/getElement.ts
  packages/webdriverio/src/commands/element/getElements.ts
  packages/webdriverio/src/commands/element/nextElement.ts
  packages/webdriverio/src/commands/element/parentElement.ts
  packages/webdriverio/src/commands/element/previousElement.ts
  packages/webdriverio/src/commands/element/react$$.ts
  packages/webdriverio/src/commands/element/react$.ts
  packages/webdriverio/src/commands/element/shadow$$.ts
  packages/webdriverio/src/commands/element/shadow$.ts
  scripts/templates/template.eta
  scripts/utils/formatter.ts
Labels: PR: Docs :memo:

#14393 fix: Failed hook reporting on observability
  packages/wdio-browserstack-service/src/insights-handler.ts
Labels: PR: Bug Fix :bug:

#14392 fix(utils): fix not to judged as screenshot the arg of switch*
  packages/wdio-utils/src/utils.ts
  packages/wdio-utils/tests/utils.test.ts
Labels: PR: Polish :nail_care:

#14403 fix(element): improve checkVisibility fallback handling in element.isDisplayed
  packages/webdriverio/src/commands/element/isDisplayed.ts
Labels: PR: Bug Fix :bug:

#14402 fix: unexpected token '?' on older browsers
  packages/webdriverio/src/scripts/isElementClickable.ts
Labels: PR: Bug Fix :bug:

#14401 fix(#14368): desync puppeteer-core peer-dep version
  packages/webdriverio/package.json
Labels: PR: Bug Fix :bug:

#14406 fix(interception): Return raw non-binary responses without metadata wrapper
  packages/webdriverio/src/utils/interception/index.ts
  packages/webdriverio/src/utils/interception/utils.ts
  packages/webdriverio/tests/utils/interception/index.test.ts
Labels: PR: Bug Fix :bug:

#14404 fix: unexpected token '?' on older browsers
  packages/webdriverio/src/scripts/isElementClickable.ts
Labels: PR: Bug Fix :bug:

#14410 fix(@wdio/browserstack-service): node fetch() failure over HTTPS_PROXY=<proxy_url> setup
  packages/wdio-browserstack-service/package.json
  packages/wdio-browserstack-service/src/Percy/PercyBinary.ts
  packages/wdio-browserstack-service/src/crash-reporter.ts
  packages/wdio-browserstack-service/src/fetchWrapper.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/src/util.ts
  pnpm-lock.yaml
Labels: PR: Polish :nail_care:

#14412 Address skipping tests for mocha and jasmine in aftertest
  packages/wdio-utils/src/test-framework/testFnWrapper.ts
  packages/wdio-utils/tests/test-framework/testFnWrapper-async.test.ts
Labels: PR: Bug Fix :bug:

#14398 catching error from addPreloadScript
  packages/webdriverio/src/session/polyfill.ts
  packages/webdriverio/tests/session/polyfill.test.ts
Labels: PR: Polish :nail_care:

#14417 Fix Windows Automation on WebDriverIO V9
  packages/wdio-utils/src/envDetector.ts
  packages/wdio-utils/tests/envDetector.test.ts
Labels: PR: Bug Fix :bug:

#14416 fix: failed test reporting on observability
  packages/wdio-browserstack-service/src/service.ts
Labels: PR: Bug Fix :bug:

#14413 Returns full body for mock response
  packages/webdriverio/src/utils/interception/index.ts
  packages/webdriverio/tests/utils/interception/index.test.ts
Labels: PR: Bug Fix :bug:

#14422 Add suite and test field of skipped test to xml report
  packages/wdio-junit-reporter/src/index.ts
  packages/wdio-junit-reporter/tests/__fixtures__/suite-empty.json
  packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.ts.snap
  packages/wdio-junit-reporter/tests/reporter.test.ts
Labels: PR: Bug Fix :bug:

#14427 fix: disable Chrome's password manager leak detection as it can block test execution
  packages/wdio-utils/src/node/startWebDriver.ts
  packages/wdio-utils/tests/node/index.test.ts
Labels: PR: Bug Fix :bug:

#14428 fix: disable Chrome's password manager leak detection as it can block test execution (v8 backport)
  packages/wdio-utils/src/node/startWebDriver.ts
  packages/wdio-utils/tests/node/index.test.ts
Labels: PR: Bug Fix :bug:

#14431 change gridProxyDetails request from GET to POST method
  packages/wdio-protocols/src/protocols/selenium.ts
Labels: PR: Spec Compliancy :eyeglasses:

#14435 docs: fix typo
  CONTRIBUTING.md
  ROADMAP.md
  packages/wdio-types/src/Options.ts
  website/docs/ComponentTesting.md
  website/docs/Configuration.md
  website/docs/Docker.md
  website/docs/api/Modules.md
  website/docs/api/Protocols.md
Labels: PR: Docs :memo:

#14438 Auto enable accessibility [v9]
  packages/wdio-browserstack-service/src/config.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/testHub/utils.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/util.test.ts
Labels: PR: Polish :nail_care:

#14437 Fix avoid misleading BiDi connection failure message
  packages/webdriver/src/node/bidi.ts
Labels: PR: Bug Fix :bug:
