Repository webdriverio/webdriverio, pull requests merged in 2025-07, with the labels that each got.

#14607 chore: replace asset to with at import statement
  __mocks__/lighthouse/lighthouse-core/gather/driver.ts
  infra/compiler/src/index.ts
  packages/wdio-browserstack-service/src/constants.ts
  packages/wdio-lighthouse-service/tests/gatherer/trace.test.ts
  packages/wdio-lighthouse-service/tests/handler/network.test.ts
  packages/wdio-utils/tests/envDetector.test.ts
  scripts/docs-generation/3rdPartyDocs.ts
  scripts/pushTags.ts
  scripts/updateDocs.ts
Labels: PR: Internal :house:

#14599 Update BoilerplateProjects.md
  website/docs/BoilerplateProjects.md
Labels: PR: Docs :memo:

#14612 docs: add note about WebDriver Bidi support in browser.url command
  packages/webdriverio/src/commands/browser/url.ts
Labels: PR: Docs :memo:

#14614 Add URLs to Browserstack WebDriverIO services
  packages/wdio-browserstack-service/README.md
Labels: PR: Docs :memo:

#14615 fix(docs): correct typos and improve clarity in Best Practices guide
  website/docs/BestPractices.md
Labels: PR: Docs :memo:

#14592 fix(@wdio/jasmine-framework): become independant from expect-webdriverio
  .github/workflows/test-unit.yml
  .vscode/settings.json
  __mocks__/jasmine.ts
  e2e/browser-runner/lit.test.js
  e2e/package.json
  e2e/wdio/headless/test.e2e.ts
  examples/wdio/package.json
  examples/wdio/vite-vue-example/package.json
  package.json
  packages/wdio-browser-runner/package.json
  packages/wdio-cli/src/interface.ts
  packages/wdio-globals/package.json
  packages/wdio-jasmine-framework/package.json
  packages/wdio-jasmine-framework/src/index.ts
  packages/wdio-jasmine-framework/tests/adapter.test.ts
  packages/wdio-local-runner/package.json
  packages/wdio-runner/package.json
  packages/wdio-runner/src/index.ts
  packages/wdio-runner/src/types.ts
  packages/wdio-utils/package.json
  packages/wdio-utils/src/monad.ts
  packages/webdriver/src/command.ts
  packages/webdriver/src/environment.ts
  packages/webdriver/src/index.ts
  packages/webdriver/src/node.ts
  packages/webdriver/src/request/request.ts
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/bidi-utils.test.ts
  packages/webdriver/tests/request.test.ts
  packages/webdriverio/src/commands/browser/debug.ts
  packages/webdriverio/src/commands/browser/switchFrame.ts
  packages/webdriverio/src/environment.ts
  packages/webdriverio/src/index.ts
  packages/webdriverio/src/middlewares.ts
  packages/webdriverio/src/node.ts
  packages/webdriverio/src/session/context.ts
  packages/webdriverio/src/session/session.ts
  packages/webdriverio/src/utils/interception/utils.ts
  pnpm-lock.yaml
  tests/package.json
  tests/typings/jasmine/package.json
Labels: PR: Bug Fix :bug:

#14581 fix: Emit browser custom command `beforeCommand` to fix broken reports
  packages/wdio-allure-reporter/src/reporter.ts
  packages/wdio-allure-reporter/tests/allureFeatures.test.ts
  packages/wdio-allure-reporter/tests/api.test.ts
  packages/wdio-allure-reporter/tests/suite.test.ts
  packages/wdio-reporter/src/types.ts
  packages/wdio-utils/src/monad.ts
  packages/wdio-utils/tests/monad.test.ts
  packages/webdriverio/tests/addCommand.test.ts
Labels: PR: Bug Fix :bug:

#14623 fix(webdriver): re-enable undici global dispatcher
  packages/webdriver/src/request/node.ts
  packages/webdriver/tests/request.test.ts
  website/docs/Proxy.md
Labels: PR: Bug Fix :bug:

#14625 fix(webdriver): #14622 added ability to proxy websocket connections
  packages/webdriver/package.json
  packages/webdriver/src/node/bidi.ts
  packages/webdriver/tests/node/bidi.test.ts
  pnpm-lock.yaml
Labels: PR: Bug Fix :bug:

#14631 chore: Update services.json to add TV Labs service
  packages/create-wdio/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#14633 ci: skip test suite for pushes that change only markdown files
  .github/workflows/test.yml
Labels: PR: Internal :house:

#14640 fix(webdriverio): properly toggle DISABLE_WEBDRIVERIO_DEPRECATION_WARNINGS
  packages/webdriver/src/command.ts
  packages/webdriver/src/environment.ts
  packages/webdriver/src/node.ts
  packages/webdriverio/src/commands/browser/switchFrame.ts
  packages/webdriverio/src/environment.ts
Labels: PR: Bug Fix :bug:

#14635 feat: do not attach prefs when debuggerAddress is specified (v8)
  packages/wdio-utils/src/node/startWebDriver.ts
  packages/wdio-utils/src/node/utils.ts
  packages/wdio-utils/tests/node/index.test.ts
Labels: PR: Polish :nail_care:

#14642 fix: avoid starting a timeout if the timer was resolved immediately
  packages/webdriverio/src/utils/Timer.ts
Labels: PR: Bug Fix :bug:

#14570 fix(security): address multiple security vulnerabilities across codebase
  infra/compiler/src/plugins.ts
  packages/create-wdio/src/constants.ts
  packages/wdio-browserstack-service/src/ai-handler.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-cucumber-framework/src/utils.ts
  packages/wdio-json-reporter/package.json
  packages/wdio-json-reporter/src/mergeResults.ts
  packages/wdio-json-reporter/tsconfig.json
  packages/wdio-logger/package.json
  packages/wdio-logger/src/utils.ts
  packages/wdio-logger/tests/utils.test.ts
  packages/wdio-logger/tsconfig.json
  packages/wdio-mocha-framework/src/common.ts
  packages/wdio-utils/package.json
  packages/wdio-utils/src/node/utils.ts
  packages/wdio-utils/src/utils.ts
  packages/wdio-utils/tests/node/utils.test.ts
  packages/webdriver/src/utils.ts
  packages/webdriverio/src/commands/element.ts
  packages/webdriverio/src/commands/element/getHTML.ts
  packages/webdriverio/src/utils/findStrategy.ts
  packages/webdriverio/tests/commands/element/getHTML.test.ts
  pnpm-lock.yaml
  scripts/bidi/downloadSpec.ts
Labels: PR: Bug Fix :bug:

#14659 polish(webdriverio): expose contentVisibilityAuto, opacityProperty and visibilityProperty to waitForDisplayed
  packages/webdriverio/src/commands/element/waitForDisplayed.ts
  packages/webdriverio/tests/commands/element/waitForDisplayed.test.ts
Labels: PR: Polish :nail_care:

#14660 core: update visual docs with `@wdio/image-comparison-core`
  website/docs/VisualTesting.md
  website/docs/visual-testing/service-options.md
Labels: PR: Docs :memo:

#14672 feat(cucumber): Fix skipping tests with skip tag
  packages/wdio-cucumber-framework/src/utils.ts
  packages/wdio-cucumber-framework/tests/fixtures/test_skip.feature
  tests/cucumber/test.feature
  tests/smoke.runner.js
Labels: PR: Bug Fix :bug:
