Repository webdriverio/webdriverio, pull requests merged in 2025-01, with the labels that each got.

#14020 fix(webdriver): allow BiDiCore to send declared headers
  packages/webdriver/src/index.ts
  packages/webdriver/src/utils.ts
  packages/webdriver/tests/bidi.test.ts
Labels: PR: Polish :nail_care:

#14026 update pnpm-lock.yaml
  pnpm-lock.yaml
Labels: PR: Internal :house:

#14032 fix(@wdio/appium-service): start Appium server with multiremote capabilities
  packages/wdio-appium-service/src/launcher.ts
  packages/wdio-appium-service/tests/launcher.test.ts
Labels: PR: Bug Fix :bug:

#14040 docs: document how to retrive browser logs
  website/_sidebars.json
  website/docs/best-practices/BrowserLogs.md
Labels: PR: Docs :memo:

#14025 fix(webdriverio): better handle window switching in webdriver classic
  e2e/wdio/headless/classic.e2e.ts
  packages/webdriverio/src/commands/browser/switchWindow.ts
  packages/webdriverio/src/context.ts
  packages/webdriverio/tests/module.test.ts
Labels: PR: Bug Fix :bug:

#13906 fix(webdriverio): consolidate session manager
  e2e/.eslintrc.json
  e2e/launch/aws.test.ts
  e2e/launch/reloadSession.test.ts
  packages/webdriver/src/index.ts
  packages/webdriverio/src/commands/browser/execute.ts
  packages/webdriverio/src/commands/browser/executeAsync.ts
  packages/webdriverio/src/commands/browser/mock.ts
  packages/webdriverio/src/commands/browser/newWindow.ts
  packages/webdriverio/src/commands/browser/reloadSession.ts
  packages/webdriverio/src/commands/browser/saveScreenshot.ts
  packages/webdriverio/src/commands/browser/setViewport.ts
  packages/webdriverio/src/commands/browser/switchFrame.ts
  packages/webdriverio/src/commands/browser/switchWindow.ts
  packages/webdriverio/src/commands/browser/url.ts
  packages/webdriverio/src/commands/element/getHTML.ts
  packages/webdriverio/src/index.ts
  packages/webdriverio/src/session/context.ts
  packages/webdriverio/src/session/dialog.ts
  packages/webdriverio/src/session/index.ts
  packages/webdriverio/src/session/networkManager.ts
  packages/webdriverio/src/session/polyfill.ts
  packages/webdriverio/src/session/session.ts
  packages/webdriverio/src/session/shadowRoot.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/commands/browser/switchFrame.test.ts
  packages/webdriverio/tests/shadowRoot.test.ts
  packages/webdriverio/tests/utils.test.ts
  packages/webdriverio/tests/utils/index.test.ts
Labels: PR: Bug Fix :bug:

#14056 fix(webdriverio): resolve target element in d&d command
  packages/webdriverio/src/commands/element/dragAndDrop.ts
  packages/webdriverio/tests/commands/element/__snapshots__/dragAndDrop.test.ts.snap
  packages/webdriverio/tests/commands/element/dragAndDrop.test.ts
Labels: PR: Bug Fix :bug:

#14049 chore(webdriver): remove dependency to Node.js in webdriver package
  packages/webdriver/src/command.ts
  packages/webdriver/src/request/index.ts
  packages/webdriver/src/request/request.ts
  packages/webdriver/src/request/types.ts
  packages/webdriver/src/types.ts
  packages/webdriver/tests/command.test.ts
  packages/webdriver/tests/request.test.ts
  website/docs/api/Browser.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/api/Browser.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/api/Browser.md
  website/i18n/de/docusaurus-plugin-content-docs/current/api/Browser.md
  website/i18n/es/docusaurus-plugin-content-docs/current/api/Browser.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/api/Browser.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/api/Browser.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/api/Browser.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/api/Browser.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/api/Browser.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/api/Browser.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/api/Browser.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/api/Browser.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/api/Browser.md
Labels: PR: Polish :nail_care:

#14061 fix(webdriverio): register polyfill on all windows
  packages/webdriverio/src/session/polyfill.ts
  packages/webdriverio/src/session/session.ts
  packages/webdriverio/tests/session/polyfill.test.ts
Labels: PR: Bug Fix :bug:

#14063 fix(webdriverio): further polyfill improvements
  packages/webdriverio/src/session/polyfill.ts
  packages/webdriverio/tests/session/polyfill.test.ts
Labels: PR: Bug Fix :bug:

#14050 fix(webdriverio): handle `closeWindow` for WDIO classic when no window is open
  packages/webdriverio/src/session/context.ts
Labels: PR: Polish :nail_care:

#14079 fix(webdriverio): allow it to visit chrome pages
  e2e/wdio/headless/test.e2e.ts
  packages/webdriverio/src/commands/browser/url.ts
Labels: PR: Bug Fix :bug:

#14085 fix(webdriverio): don't initialize session manager for stub
  e2e/launch/aws.test.ts
  e2e/launch/reloadSession.test.ts
  e2e/standalone/attach.test.ts
  e2e/wdio/headless/bidi.e2e.ts
  e2e/wdio/headless/classic.e2e.ts
  e2e/wdio/headless/launch.e2e.ts
  e2e/wdio/headless/mocking.e2e.ts
  e2e/wdio/headless/test.e2e.ts
  e2e/wdio/wdio.conf.ts
  packages/webdriver/src/utils.ts
  packages/webdriverio/src/commands/browser/mockClearAll.ts
  packages/webdriverio/src/session/index.ts
  packages/webdriverio/tests/module.test.ts
  packages/webdriverio/tests/session/index.test.ts
  website/docs/Emulation.md
  website/docs/Snapshot.md
  website/docs/VisualTesting.md
  website/docs/visual-testing/test-output.md
Labels: PR: Bug Fix :bug:

#14070 fix(webdriverio): properly switch context using switchToParentFrame()
  .gitignore
  __mocks__/fetch.ts
  e2e/wdio/headless/test.e2e.ts
  package.json
  packages/webdriverio/src/commands/browser/switchFrame.ts
  packages/webdriverio/src/node/saveScreenshot.ts
  packages/webdriverio/src/session/context.ts
  packages/webdriverio/tests/commands/browser/switchFrame.test.ts
  pnpm-lock.yaml
Labels: PR: Bug Fix :bug:

#14075 feat(webdriverio): use checkVisibility for display checks
  __mocks__/fetch.ts
  packages/webdriver/src/bidi/core.ts
  packages/webdriver/tests/bidi.test.ts
  packages/webdriverio/src/commands/browser/addInitScript.ts
  packages/webdriverio/src/commands/browser/execute.ts
  packages/webdriverio/src/commands/browser/executeAsync.ts
  packages/webdriverio/src/commands/element/isDisplayed.ts
  packages/webdriverio/src/session/polyfill.ts
  packages/webdriverio/src/utils/index.ts
  packages/webdriverio/tests/utils/index.test.ts
Labels: PR: New Feature :rocket:

#14087 docs(eslint-plugin-wdio): fix typo in readme
  packages/eslint-plugin-wdio/README.md
Labels: PR: Docs :memo:

#14092 docs(website): fix multiremote link
  website/docs/Configuration.md
Labels: PR: Docs :memo:

#14069 Accessibility Support for Browserstack app automate sessions
  packages/wdio-browserstack-service/src/accessibility-handler.ts
  packages/wdio-browserstack-service/src/constants.ts
  packages/wdio-browserstack-service/src/instrumentation/funnelInstrumentation.ts
  packages/wdio-browserstack-service/src/types.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/accessibility-handler.test.ts
  packages/wdio-browserstack-service/tests/app-accessibility-handler.test.ts
  packages/wdio-browserstack-service/tests/util.test.ts
Labels: PR: New Feature :rocket:

#14097 fix(webdriverio): remove obsolete export
  packages/webdriverio/package.json
Labels: PR: Bug Fix :bug:

#14100 fix: typos on readme
  packages/webdriver/README.md
Labels: PR: Docs :memo:

#14101 fix(webdriverio): enable arbitrary automation protocol packages
  packages/wdio-cli/tests/watcher.test.ts
  packages/wdio-types/src/Options.ts
  packages/webdriverio/src/constants.ts
  packages/webdriverio/src/index.ts
  packages/webdriverio/src/session/index.ts
  packages/webdriverio/src/session/session.ts
  packages/webdriverio/src/utils/driver.ts
  packages/webdriverio/tests/constants.test.ts
  packages/webdriverio/tests/module.test.ts
  packages/webdriverio/tests/session/index.test.ts
  packages/webdriverio/tests/shadowRoot.test.ts
  website/docs/Configuration.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/AutomationProtocols.md
  website/i18n/ar/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/AutomationProtocols.md
  website/i18n/bg/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/de/docusaurus-plugin-content-docs/current/AutomationProtocols.md
  website/i18n/de/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/es/docusaurus-plugin-content-docs/current/AutomationProtocols.md
  website/i18n/es/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/fa/docusaurus-plugin-content-docs/current/AutomationProtocols.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/AutomationProtocols.md
  website/i18n/fr/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/hi/docusaurus-plugin-content-docs/current/AutomationProtocols.md
  website/i18n/it/docusaurus-plugin-content-docs/current/AutomationProtocols.md
  website/i18n/it/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/AutomationProtocols.md
  website/i18n/ja/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/AutomationProtocols.md
  website/i18n/pl/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/AutomationProtocols.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/AutomationProtocols.md
  website/i18n/ta/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/AutomationProtocols.md
  website/i18n/uk/docusaurus-plugin-content-docs/current/Configuration.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/AutomationProtocols.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/Configuration.md
Labels: PR: Bug Fix :bug:

#14103 fix(webdriverio): double check elements that have a display: contents
  __mocks__/fetch.ts
  packages/wdio-webdriver-mock-service/src/index.ts
  packages/webdriverio/src/commands/element/isDisplayed.ts
  packages/webdriverio/tests/commands/element/isDisplayed.test.ts
Labels: PR: Bug Fix :bug:

#14104 fix(@wdio/browser-runner): export mocha source map
  packages/wdio-browser-runner/package.json
Labels: PR: Bug Fix :bug:

#14106 chore(@wdio/utils): allow to set spawnOpts for Chromedriver as well
  packages/wdio-utils/src/node/startWebDriver.ts
  website/docs/Capabilities.md
Labels: PR: Polish :nail_care:

#14110 fix(webdriverio): have the cjs export use the Node environment
  packages/webdriverio/src/index.cts
Labels: PR: Bug Fix :bug:

#14060 feat: enrich Appium context methods
  infra/compiler/src/type-generation/constants.ts
  packages/wdio-protocols/src/protocols/appium.ts
  packages/wdio-protocols/src/types.ts
  packages/webdriverio/src/commands/browser.ts
  packages/webdriverio/src/commands/element/isClickable.ts
  packages/webdriverio/src/commands/mobile.ts
  packages/webdriverio/src/commands/mobile/getContext.ts
  packages/webdriverio/src/commands/mobile/getContexts.ts
  packages/webdriverio/src/commands/mobile/switchContext.ts
  packages/webdriverio/src/session/context.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/tests/commands/element/isClickable.test.ts
  packages/webdriverio/tests/commands/mobile/__snapshots__/getContexts.test.ts.snap
  packages/webdriverio/tests/commands/mobile/__snapshots__/switchContext.test.ts.snap
  packages/webdriverio/tests/commands/mobile/getContext.test.ts
  packages/webdriverio/tests/commands/mobile/getContexts.test.ts
  packages/webdriverio/tests/commands/mobile/switchContext.test.ts
  website/docs/api/Mobile.md
Labels: PR: Polish :nail_care:

#14113 fix(webdriverio): fix isDisplayed call if element is non existant
  packages/webdriverio/src/commands/element/isDisplayed.ts
  packages/webdriverio/tests/commands/element/isDisplayed.test.ts
Labels: PR: Bug Fix :bug:

#14111 updating constants and services lists with wdio-roku-service refs
  packages/wdio-cli/src/constants.ts
  scripts/docs-generation/3rd-party/services.json
Labels: PR: Docs :memo:

#14024 wdio: implement `.entries()` for `ChainablePromiseArray`
  packages/wdio-utils/src/shim.ts
  packages/webdriverio/src/types.ts
  packages/webdriverio/tests/commands/element/$$.test.ts
  tests/typings/webdriverio/async.ts
Labels: PR: Polish :nail_care:

#14122 fixes in packages/wdio-browserstack-service to support wdio-v9
  packages/wdio-browserstack-service/package.json
  packages/wdio-browserstack-service/src/Percy/Percy.ts
  packages/wdio-browserstack-service/src/Percy/PercySDK.ts
  packages/wdio-browserstack-service/src/accessibility-handler.ts
  packages/wdio-browserstack-service/src/insights-handler.ts
  packages/wdio-browserstack-service/src/launcher.ts
  packages/wdio-browserstack-service/src/service.ts
  packages/wdio-browserstack-service/src/util.ts
  packages/wdio-browserstack-service/tests/service.test.ts
  packages/wdio-browserstack-service/tests/util.test.ts
Labels: PR: Bug Fix :bug:

#14054 fix: Handle paths for accessibility
  packages/wdio-browserstack-service/src/scripts/accessibility-scripts.ts
  packages/wdio-browserstack-service/tests/accessibility-scripts.test.ts
Labels: PR: Bug Fix :bug:

#14121 chore: update visual docs
  website/docs/VisualTesting.md
  website/docs/visual-testing/service-options.md
Labels: PR: Docs :memo:
